import {createHash,randomUUID} from 'node:crypto'
import {existsSync,readFileSync,lstatSync,unlinkSync} from 'node:fs'
const now=()=>new Date().toISOString(),hash=buffer=>createHash('sha256').update(buffer).digest('hex')
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status})}
export function artifactServices({ctx,pathOf,ensure,get,read,all,guards,serial}){
 const protect=async(user,file,operation)=>{for(const guard of guards.values()){const verdict=await guard.check(user,file,operation);if(verdict?.allowed===false)fail(verdict.reason||'This artifact is retained by another plugin.',409)}}
 const inspect=(user,file)=>{const path=pathOf(user,file.sha256);if(file.disposedAt)return{state:'disposed',bytes:0};try{if(!existsSync(path))return{state:'missing',bytes:0};const info=lstatSync(path);if(!info.isFile()||info.isSymbolicLink())return{state:'unavailable',bytes:null,reason:'The artifact is not a regular stored file.'};if(info.size!==file.size)return{state:'corrupt',bytes:info.size,reason:'Stored byte length differs from recorded size.'};return{state:hash(readFileSync(path))===file.sha256?'available':'corrupt',bytes:info.size}}catch(error){return{state:'unavailable',bytes:null,reason:error.message}}}
 const stat=(user,id)=>{ensure(user);const file=get(user,id,{includeDeleted:true,includeDisposed:true});return{...file,storage:inspect(user,file)}}
 const summary=user=>{ensure(user);const rows=all(user),blobs=new Map(),counts={records:rows.length,live:0,archived:0,disposed:0,missing:0,corrupt:0,unavailable:0},maximum=500;for(const file of rows){if(file.disposedAt)counts.disposed++;else if(file.deletedAt||file.archivedAt)counts.archived++;else counts.live++;if(blobs.has(file.sha256))continue;if(blobs.size>=maximum)continue;const storage=inspect(user,file);if(storage.state==='disposed')continue;blobs.set(file.sha256,storage);if(Object.hasOwn(counts,storage.state))counts[storage.state]++}const options=ctx.settings.get(user,'file-store'),failures=ctx.store.events(user.id).filter(event=>event.type==='files/operation-failed').length;return{...counts,bytes:[...blobs.values()].reduce((sum,row)=>sum+(row.bytes||0),0),uniqueBlobs:blobs.size,maximumBytes:options.maxTotalMb*1024*1024,maximumFileBytes:options.maxFileMb*1024*1024,failures,scanLimit:maximum,scanTruncated:new Set(rows.filter(row=>!row.disposedAt).map(row=>row.sha256)).size>maximum,bodyIncluded:false}}
 const archiveOnce=async(user,id,{reason='Removed from library',actor=user.actorId||user.id}={})=>{const file=get(user,id,{includeDeleted:true});if(file.deletedAt)return file;const saved={...file,deletedAt:now(),archivedAt:now(),archiveReason:String(reason).slice(0,1000),archivedBy:actor};await ctx.store.put(user.id,'files',saved,{event:'files/removed-from-library',actor:`human:${actor}`});return saved}
 const eligibility=async(user,id)=>{const file=get(user,id,{includeDeleted:true,includeDisposed:true});const reasons=[];for(const guard of guards.values()){const verdict=await guard.check(user,file,'dispose');if(verdict?.allowed===false)reasons.push(verdict.reason||guard.id)}return{file,storage:inspect(user,file),allowed:!file.disposedAt&&!reasons.length,reasons}}
 const disposeOnce=async(user,id,{expectedSha256,reason,actor=user.actorId||user.id,approvalId}={})=>{
  const file=get(user,id,{includeDeleted:true,includeDisposed:true});if(file.disposedAt)return{file,duplicate:true}
  if(!approvalId||!reason)fail('Disposal requires a reviewed approval and recorded reason.',409)
  if(expectedSha256!==file.sha256)fail('The artifact digest changed after the review was prepared.',409)
  await protect(user,file,'dispose');const state=inspect(user,file);if(!['available','missing'].includes(state.state))fail('Inspect the corrupted or unavailable artifact before disposing it.',409)
  const intent={...file,disposition:'disposing',disposalIntentId:randomUUID(),disposalApprovalId:approvalId,disposalReason:String(reason).slice(0,2000),disposalRequestedAt:now(),disposalActor:actor}
  await ctx.store.put(user.id,'files',intent,{event:'files/disposal-requested',actor:`human:${actor}`})
  try{
   const remaining=all(user).filter(row=>row.id!==id&&row.sha256===file.sha256&&!row.disposedAt),path=pathOf(user,file.sha256);let bytesRemoved=0
   if(!remaining.length&&existsSync(path)){await protect(user,intent,'dispose');bytesRemoved=lstatSync(path).size;unlinkSync(path)}
   const saved={...intent,disposition:'disposed',disposedAt:now(),deletedAt:file.deletedAt||now(),bytesRemoved,sharedContentRetained:!!remaining.length,contentPreviouslyMissing:state.state==='missing'}
   await ctx.store.put(user.id,'files',saved,{event:'files/disposed',actor:`human:${actor}`});return{file:saved,bytesRemoved,sharedContentRetained:!!remaining.length}
  }catch(error){await ctx.store.put(user.id,'files',{...intent,disposition:'interrupted',disposalError:error.message},{event:'files/disposal-interrupted',actor:`human:${actor}`}).catch(()=>{});throw error}
 }
 const recoverOnce=async user=>{const results=[];for(const file of all(user).filter(row=>row.disposition==='disposing')){const storage=inspect(user,file),missing=storage.state==='missing',saved={...file,disposition:missing?'disposed':'interrupted',...(missing?{disposedAt:now(),deletedAt:file.deletedAt||now()}:{}),recoveryAt:now(),recoveryReason:missing?'The reviewed artifact is absent; disposal completed before its result was recorded.':'Bytes remain; no deletion was inferred or repeated. Prepare a new review.'};await ctx.store.put(user.id,'files',saved,{event:'files/disposal-recovered',actor:'system:file-store'});results.push(saved)}return results}
 const preview=(user,id,{maxBytes=262144}={})=>{const file=get(user,id,{includeDeleted:true}),buffer=read(user,id,{includeDeleted:true}),extension=file.filename.split('.').at(-1).toLowerCase(),mime=file.mime.toLowerCase();let kind=null;if(['png','jpg','jpeg','gif','webp','avif'].includes(extension)&&/^image\/(png|jpeg|gif|webp|avif)$/.test(mime))kind='image';else if(extension==='pdf'&&mime==='application/pdf')kind='pdf';else if(['txt','csv','md','json','xml','yaml','yml','log'].includes(extension)||mime.startsWith('text/'))kind='text';if(!kind)return{kind:'unsupported',filename:file.filename,mime:file.mime,size:buffer.length,reason:'This file type has no inline preview. Download the original to use a suitable viewer.'};if(kind==='text'){const limit=Math.min(262144,Math.max(1,Number(maxBytes)||262144));return{kind,filename:file.filename,mime:'text/plain; charset=utf-8',text:buffer.subarray(0,limit).toString('utf8'),size:buffer.length,shownBytes:Math.min(buffer.length,limit),truncated:buffer.length>limit}}return{kind,filename:file.filename,mime:file.mime,size:buffer.length,truncated:false}}
 const dispose=(user,id,input)=>serial(user,()=>disposeOnce(user,id,input)),archive=(user,id,input)=>serial(user,()=>archiveOnce(user,id,input)),recover=user=>serial(user,()=>recoverOnce(user))
 return{stat,summary,archive,eligibility,dispose,recover,preview,guard:definition=>{if(guards.has(definition.id))throw new Error('Duplicate file lifecycle guard');guards.set(definition.id,definition);return()=>guards.delete(definition.id)}}
}
