import assert from 'node:assert/strict'
import {createHash} from 'node:crypto'
import {mkdirSync,mkdtempSync,readdirSync,readFileSync,writeFileSync,existsSync} from 'node:fs'
import {resolve,join,relative} from 'node:path'
import {Context} from '../../../../host/node_modules/cordis/lib/index.js'
import * as web from '../../webui/code/product-server.mjs'
import * as store from '../../workspace-store/code/index.mjs'
import * as settings from '../../settings/code/index.mjs'
import * as files from '../../file-store/code/index.mjs'
import * as sandbox from '../code/index.mjs'
import * as scenario from '../../../domain/procurement-sandbox/code/index.mjs'
const ctx=new Context(),fibers=[],users=[{id:'real-buyer',role:'contractor',name:'PRIVATE REAL NAME',company:'PRIVATE REAL COMPANY',permissions:[]},{id:'real-supplier',role:'supplier',name:'Private supplier',permissions:[]},{id:'real-admin',role:'admin',permissions:[]}],[buyer,supplier,admin]=users,checks=[];mkdirSync('tmp',{recursive:true});const root=mkdtempSync(resolve('tmp/sandbox-isolation-')),mount=async(module,config)=>{const fiber=await ctx.plugin(module,config);assert.equal(fiber.state,2);fibers.push(fiber);return fiber}
const privateHashes=()=>{const entries=[];const walk=directory=>{for(const item of readdirSync(directory,{withFileTypes:true})){if(item.name.startsWith('.sandbox'))continue;const path=join(directory,item.name);if(item.isDirectory())walk(path);else entries.push([relative(root,path),createHash('sha256').update(readFileSync(path)).digest('hex')])}};walk(root);return Object.fromEntries(entries)}
let address
try{await mount(web,{port:0});await mount(store,{root});await mount({name:'real-account-fixture',apply(child){child.provide('accounts',{get:id=>users.find(user=>user.id===id),list:()=>users,can:()=>true,resolve:req=>users.find(user=>user.id===req.headers['x-fixture-user'])})}});await mount(settings);await mount(files);ctx.settings.define({id:'private-fixture',scope:'account',fields:[{key:'password',label:'Private secret',type:'password'}],defaults:{password:''}});await ctx.settings.save(buyer,'private-fixture',{values:{password:'PRIVATE_REAL_CREDENTIAL'}});await ctx.store.put(buyer.id,'private-business',{id:'only-live',cost:98765,notes:'PRIVATE_REAL_BUSINESS'},{event:'fixture/real-record'});const liveFile=await ctx.files.put(buyer,{filename:'real.txt',buffer:Buffer.from('PRIVATE_REAL_FILE'),mime:'text/plain'});let sandboxFiber=await mount(sandbox),scenarioFiber=await mount(scenario);address=await ctx.web.listen();const base=`http://127.0.0.1:${address.port}/quotagent/api`,request=async(path,{user=buyer,body,method}={})=>{const response=await fetch(base+path,{method:method||(body?'POST':'GET'),headers:{'content-type':'application/json','x-fixture-user':user.id},...(body?{body:JSON.stringify(body)}:{})});const value=await response.json();return{status:response.status,value}}
 const before=privateHashes();await assert.rejects(ctx.sandbox.start(admin,{scenarioId:'quotation-to-order',confirmed:true}),/client perspective/);await assert.rejects(ctx.sandbox.start(buyer,{scenarioId:'quotation-to-order'}),/confirm/);const started=await request('/sandbox/start',{body:{scenarioId:'quotation-to-order',confirmed:true}});assert.equal(started.status,200,JSON.stringify(started.value));assert.equal(started.value.steps.length,8);assert(started.value.steps.every(step=>step.simulated&&step.status==='completed'));const child=ctx.sandbox.runtime(buyer),snapshot=child.ctx.procurement.snapshot(child.actor);assert.equal(snapshot.orders.length,1);assert.equal(snapshot.quotes.length,2);assert(snapshot.quotes.every(quote=>quote.items.every(item=>item.cost===undefined)));assert.equal(child.ctx.ai.status(child.actor).available,false);assert.equal(child.ctx.settings.get(child.actor,'ai').apiKey,'');assert.ok(!JSON.stringify(snapshot).includes('PRIVATE_REAL'));assert.deepEqual(privateHashes(),before);checks.push('Current native procurement/actions/teams/QEP generate8 simulated steps and an independently reviewed order in a separate ledger, without copying or changing real business/files/credentials')
 const bootstrap=(await request('/bootstrap')).value;assert.equal(bootstrap.user.sandbox,true);assert.equal(bootstrap.user.role,'contractor');assert.equal((await request('/bootstrap',{user:supplier})).value.user.id,supplier.id);assert.equal((await request('/workspace')).value.rfqs.length,2);const draft=await request('/workspace/create-rfq',{body:{title:'Isolated manual draft',items:[{description:'Sandbox edit',quantity:2,unit:'each'}],supplierIds:[]}});assert.equal(draft.status,200,JSON.stringify(draft.value));assert.equal(ctx.store.list(buyer.id,'rfqs').length,0);const upload=await request('/files',{body:{filename:'demo.txt',mime:'text/plain',contentBase64:Buffer.from('SANDBOX_FILE_ONLY').toString('base64')}});assert.equal(upload.status,200);const download=await fetch(base+'/files/'+upload.value.file.id+'/download',{headers:{'x-fixture-user':buyer.id}});assert.equal(await download.text(),'SANDBOX_FILE_ONLY');assert.equal((await request('/files/'+liveFile.id+'/download')).status,404);assert.equal(ctx.files.list(buyer).length,1);assert.deepEqual(privateHashes(),before);assert.equal((await request('/mail/sync',{body:{}})).status,404);assert.equal((await request('/account',{method:'PATCH',body:{role:'supplier'}})).status,400);checks.push('Same HTTP gateway routes bootstrap/read/write into fixed synthetic contractor identity; another real account stays live, file upload/download remain isolated, and role mutation/unavailable outbound plugins refuse')
 const oldRoot=ctx.sandbox.rootFor(buyer),oldOrder=snapshot.orders[0].id;const reset=await request('/sandbox/start',{body:{scenarioId:'quotation-to-order',confirmed:true}});assert.equal(reset.status,200,JSON.stringify(reset.value));assert.notEqual(reset.value.result.orderId,oldOrder);assert.equal((await request('/workspace')).value.rfqs.length,2);assert.equal(ctx.sandbox.runtime(buyer).ctx.procurement.snapshot(child.actor).rfqs.some(row=>row.title==='Isolated manual draft'),false);assert.deepEqual(privateHashes(),before);checks.push('Reset stops native children and replaces only that demo root; prior practice edits disappear while real bytes remain identical')
 const changedPerspectiveExit=await ctx.sandbox.leave({...buyer,role:'admin'});assert.equal(changedPerspectiveExit.active,false);const off=await request('/sandbox/exit',{body:{}});assert.equal(off.value.active,false);assert.equal((await request('/bootstrap')).value.user.id,buyer.id);assert(existsSync(oldRoot));const resumed=await request('/sandbox/start',{body:{scenarioId:'quotation-to-order',confirmed:true,reset:false}});assert.equal(resumed.value.result.orderId,reset.value.result.orderId);await scenarioFiber.dispose();const unavailable=await request('/workspace');assert.equal(unavailable.status,503);const fallback=(await request('/bootstrap')).value;assert.deepEqual(fallback.navigation.map(row=>row.id),['sandbox']);assert.equal((await request('/sandbox/status')).value.active,true);scenarioFiber=await mount(scenario);const restored=await request('/workspace');assert.equal(restored.status,200);assert.equal(restored.value.orders[0].id,reset.value.result.orderId);checks.push('Exit restores real identity; resume retains saved demo; unavailable scenario returns explicit503/minimal exit bootstrap and reload restores its existing ledger')
 const supplierStart=await request('/sandbox/start',{user:supplier,body:{scenarioId:'quotation-to-order',confirmed:true}});assert.equal(supplierStart.status,200,JSON.stringify(supplierStart.value));const supplierData=(await request('/workspace',{user:supplier})).value;assert.equal((await request('/bootstrap',{user:supplier})).value.user.role,'supplier');assert.equal(supplierData.quotes.length,1);assert(supplierData.quotes[0].items.every(row=>row.cost!==undefined));assert.notEqual(ctx.sandbox.rootFor(supplier),oldRoot);assert.deepEqual(privateHashes(),before);checks.push('Separate supplier sandbox keeps only that perspective and private own costs, isolated from contractor demo and real accounts')
 const supplierOrder=supplierData.orders[0].id;await scenarioFiber.dispose();await sandboxFiber.dispose();sandboxFiber=await mount(sandbox);scenarioFiber=await mount(scenario);const concurrent=await Promise.all([request('/bootstrap'),request('/workspace'),request('/workspace',{user:supplier})]);assert(concurrent.every(row=>row.status===200));assert.equal(concurrent[0].value.user.sandbox,true);assert.equal(concurrent[1].value.orders[0].id,reset.value.result.orderId);assert.equal(concurrent[2].value.orders[0].id,supplierOrder);assert.deepEqual(privateHashes(),before);checks.push('Whole sandbox-controller restart restores per-owner mode and existing isolated ledgers; concurrent first requests share a single native runtime per owner')
 const failedOwner={...buyer,id:'failed-owner'},removeBroken=ctx.sandbox.registerScenario({id:'broken',name:'Broken fixture',roles:['contractor'],steps:[],create:async()=>{throw new Error('Fixture factory unavailable')}});await assert.rejects(ctx.sandbox.start(failedOwner,{scenarioId:'broken',confirmed:true}),/Fixture factory unavailable/);assert.equal(ctx.sandbox.status(failedOwner).hasData,true);assert.equal(ctx.sandbox.status(failedOwner).active,true);await ctx.sandbox.leave({...failedOwner,role:'admin'},{clear:true,confirmed:true});assert.equal(ctx.sandbox.status(failedOwner).hasData,false);await removeBroken();checks.push('A failed factory still leaves visible owned controls; even a changed-role owner can exit and clear the failed demo without touching another account')
 await request('/sandbox/clear',{body:{confirmed:true}});assert(!existsSync(oldRoot));assert.equal(ctx.sandbox.status(buyer).active,false);assert.deepEqual(privateHashes(),before);await scenarioFiber.dispose();await sandboxFiber.dispose();assert.ok(!ctx.web.routes().some(row=>row.path.startsWith('/sandbox')));assert.equal((await request('/bootstrap')).value.user.id,supplier.id===buyer.id?supplier.id:buyer.id);checks.push('Clear deletes only owned demo directory; native unload removes routes/interception/children with real private bytes unchanged')
 const report={ok:true,root,checks};writeFileSync(join(root,'report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2))
}finally{for(const fiber of fibers.reverse())await fiber.dispose()}
