export const steps=[
 'Create an isolated same-party reviewer and authority policy',
 'Draft and publish a complete lighting request',
 'Prepare and submit two priced supplier offers',
 'Record the observed price and term comparison',
 'Propose an award and obtain the simulated supplier confirmation',
 'Obtain an independent simulated reviewer grant and sign the order',
 'Record the simulated supplier acknowledgement',
 'Publish an open cabling request for your own practice',
]
// Authored fictional scope, shown in the normal request editor and signed package.
// These declarations describe this scenario; no imported/live scope is inferred.
const countRule={id:'count',name:'Accepted complete components',dimension:'count',units:[{unit:'each',factor:1}]}
const lightingScope={measurementRules:[countRule],interfaces:[{id:'supply',name:'Supply, delivery and commissioning of listed lighting components',responsibilityOwner:'Awarded supplier'}],deliverables:'120 specified LED panels and 24 occupancy sensors, delivered to Riverside office; commission the supplied sensors.',exclusions:'Building wiring alterations, panel installation and disposal of existing fittings.'}
const cablingScope={measurementRules:[{id:'length',name:'Installed and tested cable length',dimension:'length',units:[{unit:'m',factor:1}]},countRule],interfaces:[{id:'installation',name:'Supply, install, test and label the listed data cabling and outlets',responsibilityOwner:'Awarded supplier'}],deliverables:'1500 metres of CAT6 cable and 48 complete dual data outlets, installed, labelled and tested with a test record.',exclusions:'Active network equipment, patch leads, new cable containment and building works.'}
export async function runScenario({ctx,actors,invoke,progress}){
 const[buyer,reviewer,supplier,second]=actors;let rfq,quotes=[],intent,order,openRequest,reviewAction
 const step=async(index,actor,operation)=>{const startedAt=new Date().toISOString();await ctx.store.append(actor.id,'sandbox/scenario-step-started',{index,title:steps[index],simulated:true,actor:actor.name},{actor:'system:sandbox'});try{const result=await operation();const receipt={index,title:steps[index],actor:actor.name,actorId:actor.id,status:'completed',simulated:true,startedAt,completedAt:new Date().toISOString()};await ctx.store.append(actor.id,'sandbox/scenario-step-completed',receipt,{actor:'system:sandbox'});await progress(receipt);return result}catch(error){const receipt={index,title:steps[index],actor:actor.name,status:'failed',simulated:true,error:error.message,startedAt};await progress(receipt);throw error}}
 await step(0,buyer,async()=>{const invite=await ctx.teams.invite(buyer,{email:reviewer.email,roleId:'lead'});await ctx.teams.answerInvite(reviewer,invite.id,true);await ctx.teams.select(reviewer,buyer.id);const policy=ctx.teams.state(buyer).workspace.policy;policy.currency='USD';policy.roles=policy.roles.map(role=>({...role,limit:role.id==='lead'?1000000:0}));const proposal=await ctx.teams.proposePolicy(buyer,{policy,reviewerId:reviewer.id,reason:'Simulated sandbox authority; no real commercial authority.'});await ctx.teams.decidePolicy(reviewer,proposal.id,{approved:true});await ctx.teams.applyPolicy(buyer,proposal.id)})
 await step(1,buyer,async()=>{rfq=(await invoke(buyer,'/workspace/create-rfq',{title:'[Sandbox] Riverside office lighting',description:'Fictitious supply and delivery of LED panels and occupancy sensors. Inspect the offers, approvals and order history.',currency:'USD',deadline:new Date(Date.now()+14*86400000).toISOString().slice(0,10),supplierIds:[supplier.id,second.id],scope:lightingScope,items:[{id:'panel',measurementRuleId:'count',interfaceId:'supply',description:'36 W LED panel, 4000 K, three-year warranty',quantity:120,unit:'each'},{id:'sensor',measurementRuleId:'count',interfaceId:'supply',description:'Ceiling occupancy sensor with commissioning',quantity:24,unit:'each'}]})).rfq;const review=await invoke(buyer,'/workspace/review/publish-rfq',{id:rfq.id});const result=await ctx.actions.approve(buyer,review.proposal.id,{confirmed:true});if(result.status!=='succeeded')throw new Error(result.error)})
 await step(2,supplier,async()=>{for(const[actor,prices,leadDays,paymentTerms]of [[supplier,[42.5,18],14,'30% deposit, balance after delivery'],[second,[39.8,21.5],35,'100% advance payment']]){const quote=(await invoke(actor,'/workspace/save-quote',{rfqId:rfq.id,items:[{id:'panel',unitPrice:prices[0],cost:Number((prices[0]*0.7).toFixed(2))},{id:'sensor',unitPrice:prices[1],cost:Number((prices[1]*0.7).toFixed(2))}],leadDays,paymentTerms,notes:'Fictitious sandbox offer. Freight and warranty included.',commercial:{taxMode:'inclusive',freight:0}})).quote;const review=await invoke(actor,'/workspace/review/submit-quote',{id:quote.id});const receipt=await ctx.actions.approve(actor,review.proposal.id,{confirmed:true});if(receipt.status!=='succeeded')throw new Error(receipt.error);quotes.push(quote)}})
 await step(3,buyer,async()=>{const rows=ctx.procurement.snapshot(buyer).comparison.filter(row=>row.rfqId===rfq.id);if(rows.length!==2)throw new Error('The isolated comparison did not receive both offers.');await ctx.store.append(buyer.id,'sandbox/comparison-observed',{rfqId:rfq.id,rows,simulated:true},{actor:'system:sandbox'})})
 await step(4,buyer,async()=>{intent=(await invoke(buyer,'/workspace/propose-award',{quoteId:quotes[0].id,reason:'Simulated choice: shorter quoted lead time and staged payments despite the higher total.',confirmed:true})).awardIntent;await invoke(supplier,'/workspace/confirm-award',{id:intent.id,confirmed:true})})
 await step(5,reviewer,async()=>{const proposal=await invoke(buyer,'/workspace/review/sign-order',{id:intent.id});reviewAction=proposal.proposal.id;await ctx.actions.nominate(buyer,reviewAction,{reviewerId:reviewer.id});await ctx.actions.grant(reviewer,reviewAction,{confirmed:true,reason:'Simulated independent review of the exact sandbox quote, supplier confirmation and amount.'});const signed=await ctx.actions.approve(buyer,reviewAction,{confirmed:true});if(signed.status!=='succeeded')throw new Error(signed.error);order=signed.result.order})
 await step(6,supplier,async()=>{const review=await invoke(supplier,'/workspace/review/acknowledge-order',{id:order.id});const result=await ctx.actions.approve(supplier,review.proposal.id,{confirmed:true});if(result.status!=='succeeded')throw new Error(result.error)})
 await step(7,buyer,async()=>{openRequest=(await invoke(buyer,'/workspace/create-rfq',{title:'[Sandbox] Cabling practice request',description:'Try drafting an offer or managing this request. Every change stays in your isolated demo.',currency:'USD',supplierIds:[supplier.id,second.id],scope:cablingScope,items:[{id:'cable',measurementRuleId:'length',interfaceId:'installation',description:'CAT6 cable installed and tested',quantity:1500,unit:'m'},{id:'outlet',measurementRuleId:'count',interfaceId:'installation',description:'Dual data outlet with faceplate',quantity:48,unit:'each'}]})).rfq;const review=await invoke(buyer,'/workspace/review/publish-rfq',{id:openRequest.id});const result=await ctx.actions.approve(buyer,review.proposal.id,{confirmed:true});if(result.status!=='succeeded')throw new Error(result.error)})
 return{label:'Simulated quotation-to-order example',simulated:true,rfqId:rfq.id,quoteIds:quotes.map(row=>row.id),orderId:order.id,reviewActionId:reviewAction,practiceRfqId:openRequest.id,notice:'Every participant and approval in this generated example is simulated. No real account was contacted.'}
}
