import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {browserHarness} from '../../../system/file-store/tests/browser-helpers.mjs'
const h=await browserHarness('business-measures')
const open=async page=>{await h.nav(page,'Responses & receipts');await page.getByRole('button',{name:'Business measures',exact:true}).click();await page.getByRole('table',{name:'Observed current and equal-duration baseline measures',exact:true}).waitFor()}
try{
 const buyer=await h.login('contractor@demo.local');await open(buyer);await buyer.getByText(/No time saved, win rate or superiority is inferred/).waitFor();await buyer.getByLabel('Include explicitly labelled demo records').check();let pending=buyer.waitForResponse(response=>response.url().includes('/responses/metrics?')&&response.request().method()==='GET');await buyer.getByRole('button',{name:'Apply measure filters',exact:true}).click();let data=await(await pending).json();assert(data.current.cohorts>0);assert.equal(data.coverage.baselinePredatesHistory,true);await buyer.getByText(/baseline starts before this recorded history/).waitFor();await buyer.getByText('Own configured-rate cost estimates',{exact:true}).waitFor();assert.equal(data.realm,'contractor-demo');assert.equal(data.baseline.metrics.lineCompleteness.value,null);assert(data.current.metrics.lineCompleteness.sources.some(ref=>ref.hash.startsWith('sha256:')));await h.shot(buyer,'01-observed-baseline');h.checks.push('Contractor GUI explicitly includes existing labelled demo records; actual ledger cohorts and source-backed values appear beside an honestly unmeasured prior window, with no saved-time/superiority claim')
 const cycles=buyer.getByRole('table',{name:'Source-linked local response-cycle cohorts',exact:true});await cycles.locator('summary').first().click();await cycles.getByText(/sha256:/).first().waitFor();const bars=buyer.getByLabel('Daily response cohorts');await bars.getByRole('button').first().click();await buyer.getByRole('button',{name:'Show every cohort day',exact:true}).waitFor();await buyer.getByRole('button',{name:'Show every cohort day',exact:true}).click();const file=await h.download(buyer,buyer.getByRole('link',{name:'Export measures and sources CSV',exact:true}),'business-measures.csv'),csv=readFileSync(file,'utf8');assert(csv.includes('sha256:'));assert(csv.includes('unmeasured'));assert(csv.includes('definition'));assert(csv.includes(data.realm));assert(csv.includes(data.sourceHash));assert(csv.includes(data.baseline.from));h.checks.push('Visible source details retain actual ledger hashes; daily cohort chart changes row selection; downloadedCSV contains both periods, denominators, definitions and full references')
 const selected=data.requests.find(row=>row.title.includes('lighting'))||data.requests[0];await buyer.getByLabel('Business measure request',{exact:true}).selectOption(selected.id);pending=buyer.waitForResponse(response=>response.url().includes('/responses/metrics?')&&response.request().method()==='GET');await buyer.getByRole('button',{name:'Apply measure filters',exact:true}).click();data=await(await pending).json();assert(data.current.rows.every(row=>row.rfqId===selected.id));const validStart=await buyer.getByLabel('Baseline start (UTC)',{exact:true}).inputValue();await buyer.getByLabel('Baseline start (UTC)',{exact:true}).fill('2020-01-01T00:00');await buyer.getByRole('button',{name:'Apply measure filters',exact:true}).click();await buyer.getByRole('alert').filter({hasText:'same duration'}).waitFor();assert.equal(await buyer.getByRole('table',{name:'Observed current and equal-duration baseline measures',exact:true}).count(),0);await buyer.getByLabel('Baseline start (UTC)',{exact:true}).fill(validStart);await buyer.getByRole('button',{name:'Apply measure filters',exact:true}).click();await buyer.getByRole('table',{name:'Observed current and equal-duration baseline measures',exact:true}).waitFor();h.checks.push('Request filter preserves exact record scope; unequal baseline duration is refused in the GUI instead of compared or shown as empty, and correction restores results')
 const supplier=await h.login('supplier@demo.local');await open(supplier);await supplier.getByLabel('Include explicitly labelled demo records').check();pending=supplier.waitForResponse(response=>response.url().includes('/responses/metrics?')&&response.request().method()==='GET');await supplier.getByRole('button',{name:'Apply measure filters',exact:true}).click();const own=await(await pending).json();assert.equal(own.realm,'supplier-demo');assert.equal(own.current.metrics.comparableRatio.value,null);assert(!JSON.stringify(own).includes('supplier2-demo'));await supplier.getByText('Your own offers only',{exact:true}).waitFor();await h.shot(supplier,'02-supplier-own-measures');h.checks.push('Supplier GUI reports own local scope/submissions only, no competing supplier identity and no buyer-private comparison score; own account usage scope is labelled')
 await supplier.setViewportSize({width:390,height:900});await supplier.waitForTimeout(400);assert.equal(await supplier.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);await h.shot(supplier,'03-mobile-measures');await supplier.reload();await supplier.getByRole('heading',{name:'Recorded business measures',exact:true}).waitFor();h.checks.push('390px measures fit the viewport with bounded table scrolling; selected Business measures tab survives browser reload and no JavaScript errors occur')
 await h.finish({scope:'Read-only existing local native ledgers; no fabricated baseline history or business mutation'})
}catch(error){await h.fail(error);throw error}finally{await h.close()}
