import assert from 'node:assert/strict'
import {mkdirSync,mkdtempSync,writeFileSync} from 'node:fs'
import {resolve} from 'node:path'
import {Context} from '../../../../host/node_modules/cordis/lib/index.js'
import * as store from '../../../system/workspace-store/code/index.mjs'
import * as web from '../../../system/webui/code/product-server.mjs'
import * as settings from '../../../system/settings/code/index.mjs'
import * as teams from '../../../system/teams/code/index.mjs'
import * as notifications from '../../../system/notifications/code/index.mjs'
import * as actions from '../../../system/action-center/code/index.mjs'
import * as procurement from '../../procurement/code/index.mjs'
import * as responses from '../code/index.mjs'
import {businessMetrics,metricsCsv,metricWindows} from '../code/metrics.mjs'
const checks=[],base=Date.parse('2026-01-01T00:00:00Z'),hour=3600000,day=24*hour,at=n=>new Date(base+n*hour).toISOString(),line={id:'a',description:'First required line',quantity:2,unit:'each'},second={id:'b',description:'Second required line',quantity:1,unit:'each'},commercial={taxMode:'inclusive',freight:0,paymentDays:0,advancePercent:0,warrantyMonths:0,penaltyPercent:0,validityUntil:'2026-02-01',deviations:[]},events=[]
const event=(h,collection,record,type='fixture/record',actor='human:buyer')=>{const seq=events.length+1,e={seq,entry_hash:'fixture-sha256-'+seq,ts:at(h),type,actor,body:{schema:'quotagent/workspace-record/v1',collection,record}};events.push(e);return e}
const rfq=(id,publishedRevision=1)=>({id,title:id,status:'published',publishedRevision,ownerId:'buyer',supplierIds:['supplier','rival'],items:[line,second]})
const quote=(id,rfqId,rfqRevision=1)=>({id,rfqId,rfqRevision,revision:1,status:'submitted',supplierId:'supplier',total:0,subtotal:0,currency:'USD',leadDays:0,commercial,items:[{...line,unitPrice:0,total:0},{...second,unitPrice:0,total:0}]})
event(1,'rfqs',rfq('baseline'));event(1,'quotes',quote('base-quote','baseline'))
event(25,'rfqs',rfq('current'));event(26,'rfqs',rfq('current',2));event(26.5,'quotes',quote('stale','current'));const current={...quote('current-quote','current',2),items:[{...line,unitPrice:3,total:6}],commercial:{taxMode:'inclusive',freight:0}};event(27,'quotes',current);event(27.1,'quotes',current);event(49,'quotes',{...current,id:'after-cutoff'})
event(27.2,'clarifications',{id:'question',rfqId:'current',rfqRevision:2,askerId:'supplier',status:'open'});event(28,'clarifications',{id:'question',rfqId:'current',rfqRevision:2,askerId:'supplier',published:true,answer:'Recorded answer'})
const draft={...current,id:'draft',status:'draft'};event(28,'quotes',draft,'procurement/quote-draft-saved','agent:supplier');event(29,'quotes',draft,'procurement/quote-draft-saved','human:supplier')
event(28,'commercial-evaluations',{id:'analysis',rfqId:'current',rfqRevision:2,rows:[{quoteId:current.id,quoteRevision:1,rfqRevision:2,score:{value:0}}]})
events.push({seq:100,entry_hash:'unaccepted',ts:at(27),type:'fixture/transfer',body:{schema:'quotagent/workspace-transfer/v1',collection:'quotes',record:{...current,id:'not-accepted'}}})
events.push({seq:101,entry_hash:'fixture-cost-zero',ts:at(28),type:'agent/model-usage',body:{callId:'known-zero',startedAt:at(28),finishedAt:at(28),status:'completed',cost:{currency:'USD',amountMicros:0},tokens:{total:0}}},{seq:102,entry_hash:'fixture-cost-unknown',ts:at(28),type:'agent/model-usage',body:{callId:'unknown',startedAt:at(28),finishedAt:at(28),status:'failed',cost:null}})
event(29,'evidence-rebuilds',{id:'rebuild',boundary:'measured',ok:true});event(29,'evidence-rebuilds',{id:'legacy-rebuild',ok:true});event(29,'evaluation-replays',{id:'replay',deterministic:true})
const query={from:at(24),to:at(48),baselineFrom:at(0),baselineTo:at(24)},snapshot={rfqs:[rfq('baseline'),rfq('current',2)],contacts:[]},input={events,realm:'buyer',role:'contractor',snapshot,query,now:base+48*hour},report=businessMetrics(input)
assert.equal(report.coverage.baselinePredatesHistory,true);assert.equal(report.coverage.currentPredatesHistory,false);assert.equal(report.coverage.requestsWithoutPublishedSource,0);assert(report.current.metrics.clarificationRounds.sources.some(ref=>ref.seq===10));assert.equal(report.baseline.metrics.responseCycleSeconds.value,0);assert.equal(report.current.metrics.responseCycleSeconds.value,3600);assert.equal(report.current.metrics.responseCycleSeconds.denominator,1);assert.equal(report.current.metrics.responseCycleSeconds.unanswered,1);assert.equal(report.current.submittedVersions,1);assert.equal(report.current.staleVersionsExcluded,1);assert.equal(report.current.metrics.lineCompleteness.value,0.5);assert.equal(report.baseline.metrics.commercialCompleteness.value,1);assert.equal(report.current.metrics.commercialCompleteness.value,0.4);assert.equal(report.current.metrics.clarificationRounds.value,0.5);assert.equal(report.current.metrics.humanRewriteRatio.value,0);assert.equal(report.baseline.metrics.humanRewriteRatio.value,null);assert.equal(report.current.metrics.comparableRatio.value,1);assert.equal(report.current.metrics.comparisonSeconds.value,3600);assert.equal(report.current.metrics.flagQuality.value,null);assert(report.current.metrics.lineCompleteness.sources.every(ref=>ref.seq&&ref.hash&&ref.realm==='buyer'));assert(!JSON.stringify(report).includes('not-accepted'));assert(!JSON.stringify(report).includes('after-cutoff'));assert.equal(report.sourceHash,businessMetrics(input).sourceHash);assert.equal(report.current.metrics.measurementConformance.value,null);assert.equal(report.current.metrics.inputReconstruction.value,1);assert.equal(report.current.metrics.inputReconstruction.denominator,1);assert.equal(report.current.metrics.recordedReplay.value,1);assert.equal(report.current.metrics.providerCosts.value[0].amount,0);assert.equal(report.current.metrics.providerCosts.unknownCalls,1);assert.equal(report.current.metrics.providerFailureRate.value,0.5);checks.push('Fixed-clock two-window independent arithmetic: measured zero versus unknown,3600second response and comparison,50%line/40%commercial completeness,50%rounds, zero paired rewrite, stable source anchors; stale/duplicate/late/unaccepted quotes excluded')
const edited=structuredClone(input),paired=edited.events.filter(e=>e.body?.record?.id==='draft');for(const event of paired){event.body.record=structuredClone(event.body.record);Object.assign(event.body.record,{assumptions:['Access provided'],exclusions:['Installation excluded'],schedule:[{id:'delivery',label:'Delivery',date:'2026-02-01',binding:'indicative'}]})}Object.assign(paired.find(e=>e.actor==='human:supplier').body.record,{assumptions:['Daytime access provided'],exclusions:['Installation and unloading excluded'],schedule:[{id:'delivery',label:'Delivery',date:'2026-02-02',binding:'indicative'}]});const rewritten=businessMetrics(edited);assert.equal(rewritten.current.editPairs.length,1);assert.equal(rewritten.current.editPairs[0].changed,3);assert(rewritten.current.metrics.humanRewriteRatio.value>0);assert.equal(rewritten.current.metrics.humanRewriteRatio.sources.length,2);checks.push('A paired human draft changing assumption text, exclusion text and milestone date counts exactly three editable changes with both source anchors');
const declared=structuredClone(input);declared.events.find(e=>e.body?.record?.id==='current'&&e.body.record.publishedRevision===2).body.record.scope={measurementRules:[{id:'rule-a',units:[{unit:'each',factor:1}]}]};declared.events.find(e=>e.body?.record?.id==='current'&&e.body.record.publishedRevision===2).body.record.items[0].measurementRuleId='rule-a';assert.equal(businessMetrics(declared).current.metrics.measurementConformance.value,1);const malformed=structuredClone(input);malformed.events.find(e=>e.body?.record?.id==='current-quote').body.record.commercial.freight=false;assert.equal(businessMetrics(malformed).current.metrics.commercialCompleteness.value,0.3);
const empty=businessMetrics({...input,query:{from:at(72),to:at(96)},now:base+96*hour});assert.equal(empty.current.metrics.responseCycleSeconds.value,null);assert.equal(empty.current.metrics.lineCompleteness.value,null);assert.throws(()=>metricWindows({...query,baselineFrom:at(1)},base+48*hour),/same duration/);assert.throws(()=>metricWindows({...query,baselineFrom:at(1),baselineTo:at(25)},base+48*hour),/baseline must finish/);assert.throws(()=>metricWindows({...query,to:at(49)},base+48*hour),/same duration|future/);const vendor=businessMetrics({...input,realm:'supplier',role:'supplier'});assert.equal(vendor.current.metrics.comparableRatio.value,null);assert(!JSON.stringify(vendor).includes('fixture-sha256-13'));assert(metricsCsv(report).includes('source_refs'));assert(metricsCsv(report).includes('unmeasured'));assert(metricsCsv(report).includes('baseline_window'));assert(metricsCsv(report).includes(report.baseline.from));assert(metricsCsv(report).includes(report.sourceHash));checks.push('Empty denominators stay unknown; unequal/overlapping/future periods refuse; supplier comparison is unmeasured; CSV carries definitions and ledger references')
const buyer={id:'metric-buyer',name:'Buyer',email:'metric-buyer@test.local',role:'contractor'},supplier={id:'metric-supplier',name:'Supplier',email:'metric-supplier@test.local',role:'supplier'},outsider={id:'metric-outsider',name:'Outsider',email:'metric-outsider@test.local',role:'contractor'},colleague={id:'metric-colleague',name:'Colleague',email:'metric-colleague@test.local',role:'contractor'},users=[buyer,supplier,outsider,colleague];mkdirSync('tmp',{recursive:true});const root=mkdtempSync(resolve('tmp/business-metrics-'));let host
async function boot(){const ctx=new Context(),fibers=[],mount=async(plugin,config)=>{const fiber=await ctx.plugin(plugin,config);assert.equal(fiber.state,2,plugin.name);fibers.push(fiber);return fiber};await mount(web);await mount({name:'metric-accounts-fixture',apply(child){child.provide('accounts',{get:id=>users.find(u=>u.id===id),list:()=>users,can:()=>true})}});await mount(store,{root});await mount(settings);await mount(teams);await mount(notifications);await mount(actions);await mount(procurement);const fiber=await mount(responses,{intervalMs:3600000});return{ctx,fiber,close:async()=>{for(const fiber of fibers.reverse())await fiber.dispose()}}}
try{host=await boot();let{ctx}=host;const r={...rfq('Native sourced fixture'),ownerId:buyer.id,supplierIds:[supplier.id]},q={...quote('native-quote',r.id),supplierId:supplier.id,privateNotes:'NEVER EXPOSE PRIVATE COST SENTINEL'};for(const realm of [buyer.id,supplier.id]){await ctx.store.put(realm,'rfqs',r,{event:'fixture/published-scope',actor:'fixture'});await ctx.store.put(realm,'quotes',q,{event:'fixture/submitted-quote',actor:'fixture'})}const before=ctx.store.events(buyer.id).length,actual=ctx.responses.metrics(buyer);assert.equal(actual.current.cohorts,1);assert.equal(actual.current.submittedVersions,1);assert(actual.current.metrics.responseCycleSeconds.value!==null);assert.equal(ctx.store.events(buyer.id).length,before);assert(!JSON.stringify(actual).includes('PRIVATE COST'));assert(actual.current.rows[0].sources.every(ref=>ref.hash.startsWith('sha256:')));assert.equal(ctx.responses.metrics(outsider).current.cohorts,0);assert.throws(()=>ctx.responses.metrics({...outsider,workspaceOwnerId:buyer.id}),/not an active member/);const invitation=await ctx.teams.invite(buyer,{email:colleague.email,roleId:'lead'});await ctx.teams.answerInvite(colleague,invitation.id,true);const team=ctx.responses.metrics({...colleague,workspaceOwnerId:buyer.id});assert.equal(team.realm,buyer.id);assert.equal(team.userId,colleague.id);assert.equal(team.current.cohorts,1);assert.equal(ctx.responses.metrics(supplier).current.metrics.comparableRatio.value,null);checks.push('Actual Cordis/Python ledger records produce hashed sources with no read writes; private quote text omitted, outsider empty/forged team refused, accepted colleague uses selected business realm and own personal analysis')
await host.close();host=await boot();ctx=host.ctx;assert.equal(ctx.responses.metrics(buyer).current.cohorts,1);await host.fiber.dispose();assert.equal(ctx.get('responses'),undefined);assert(!ctx.web.routes().some(row=>row.path.startsWith('/responses/metrics')));checks.push('Real ledger restart reconstructs measures; response owner disposal unregisters metrics HTTP and service')
const result={ok:true,at:new Date().toISOString(),root,checks};writeFileSync(root+'/report.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2))
}finally{await host?.close()}
