import React,{useState,useEffect} from 'react'
import {registry,useApp,useResource,api,Button,Badge,Field,Empty,ErrorNotice,date} from '../../webui/client/core.jsx'
const initial={requests:[],options:{permissions:[],plugins:[],configuration:[]}}
const open=new Set(['pending','blocked','awaiting-requester'])
export function CapabilityRequests({admin=false}){
 const app=useApp(),resource=useResource('/capability-requests',initial),[kind,setKind]=useState('permission'),[target,setTarget]=useState(''),[reason,setReason]=useState(''),[previousId,setPreviousId]=useState(null),[notes,setNotes]=useState({}),[filter,setFilter]=useState('open'),[busy,setBusy]=useState(''),[error,setError]=useState('')
 const all=resource.data.requests,rows=all.filter(row=>filter==='all'||open.has(row.status)),options=resource.data.options[{permission:'permissions',plugin:'plugins',configuration:'configuration'}[kind]]||[]
 useEffect(()=>{if(!all.some(row=>open.has(row.status)))return;const timer=setInterval(()=>resource.reload(),10000);return()=>clearInterval(timer)},[all.some(row=>open.has(row.status)),resource.reload])
 async function act(path,body){setBusy(path);setError('');try{await api(path,{method:'POST',body});await resource.reload();app.refresh();app.notify('Capability request updated.');return true}catch(error){setError(error.message);return false}finally{setBusy('')}}
 async function create(event){event.preventDefault();if(await act('/capability-requests',{kind,target,reason,previousId})){setReason('');setPreviousId(null)}}
 const scope=request=>request.kind==='plugin'?'Application-wide plugin activation':request.kind==='permission'?'Access for '+request.requesterName:'Configuration guidance; requester confirms the outcome'
 return <section className={'card capability-inbox'+(admin?' section-space':'')}><div className="section-heading"><div><h2>{admin?'Capability request inbox':'Get help with a blocked capability'}</h2><p>{admin?'Review a specific request and retain its result.':'Ask the administrator for access, an application plugin or setup guidance.'}</p></div><Badge>{all.filter(row=>open.has(row.status)).length} open</Badge></div><ErrorNotice error={error||resource.error} retry={resource.error?resource.reload:undefined}/>
 {!admin&&<form onSubmit={create}><div className="form-grid"><Field label="What do you need?"><select value={kind} onChange={event=>{setKind(event.target.value);setTarget('')}}><option value="permission">Account access</option><option value="plugin">Application plugin</option><option value="configuration">Configuration guidance</option></select></Field><Field label="Requested capability"><select required value={target} onChange={event=>setTarget(event.target.value)}><option value="">Choose a capability</option>{options.map(option=><option key={option.id} value={option.id}>{option.label}{option.available||option.active?' · Available now':''}</option>)}</select></Field></div><Field label="Reason for your request" hint="Only this explanation and the selected capability are shared with the administrator."><textarea required rows={3} value={reason} onChange={event=>setReason(event.target.value)} placeholder="Describe the work you need to complete and what is blocked."/></Field><Button type="submit" busy={busy==='/capability-requests'}>Send capability request</Button>{previousId&&<p className="muted">This creates a new request linked to the earlier outcome.</p>}</form>}
 <div className="filter-tabs section-space"><button className={filter==='open'?'active':''} onClick={()=>setFilter('open')}>Open requests</button><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>All outcomes</button></div>
 {rows.length?rows.map(request=><article className="capability-request" key={request.id}><div className="section-heading"><div><h3>{request.label}</h3><p>{scope(request)}</p></div><Badge status={request.status==='resolved'?'success':request.status==='blocked'?'warning':'neutral'}>{request.status.replaceAll('-',' ')}</Badge></div><p>{request.reason}</p><small className="muted">Requested by {request.requesterName} · {date(request.createdAt)} · Expires {date(request.expiresAt)}</small>{request.error&&<ErrorNotice error={request.error}/>}<div className="capability-decisions">{request.decisions.map((decision,index)=><p key={index}><strong>{decision.choice==='guide'?'Guidance':decision.choice==='grant'?'Administrative decision':'Declined'}</strong> · {date(decision.at)}<br/>{decision.reason}</p>)}</div>{request.verification?.kind==='requester-report'&&<p className="muted">The requester confirmed this works on {date(request.verification.at)}.</p>}
 {admin&&open.has(request.status)&&<><Field label={'Decision note for '+request.label}><textarea required rows={2} value={notes[request.id]||''} onChange={event=>setNotes({...notes,[request.id]:event.target.value})} placeholder="Explain the exact access change, or provide setup guidance."/></Field><div className="row-actions"><Button variant="secondary" disabled={!!busy||!notes[request.id]?.trim()} onClick={()=>act(`/capability-requests/${request.id}/decide`,{choice:'reject',reason:notes[request.id]})}>Reject request</Button><Button variant="secondary" disabled={!!busy||!notes[request.id]?.trim()} onClick={()=>act(`/capability-requests/${request.id}/decide`,{choice:'guide',reason:notes[request.id]})}>Send guidance</Button>{request.kind!=='configuration'&&<Button disabled={!!busy||!notes[request.id]?.trim()} onClick={()=>act(`/capability-requests/${request.id}/decide`,{choice:'grant',confirmed:true,reason:notes[request.id]})}>{request.kind==='permission'?'Grant requested access':'Enable requested plugin'}</Button>}</div></>}
 {!admin&&request.status==='awaiting-requester'&&<Button variant="secondary" disabled={!!busy} onClick={()=>act(`/capability-requests/${request.id}/confirm`,{confirmed:true,reason:'Confirmed working in the client GUI'})}>Confirm this is working</Button>}
 {!admin&&['resolved','rejected','expired'].includes(request.status)&&<Button variant="ghost" onClick={()=>{setKind(request.kind);setTarget(request.target);setReason(request.reason);setPreviousId(request.id);window.scrollTo({top:0,behavior:'smooth'})}}>Prepare a new request</Button>}
 </article>):<Empty icon="check" title={filter==='open'?'No open capability requests':'No requests yet'}>{admin?'Client requests will appear here for a deliberate decision.':'Your request and its administrative outcome stay visible here.'}</Empty>}
 </section>
}
function AccountRequests(){const app=useApp();return app.user.role==='admin'?null:<CapabilityRequests/>}
registry.slot('account:capability-requests',AccountRequests)
