import './manager.css'
import React, { useState } from 'react'
import { registry, useApp, useResource, api, Icon, Button, Badge, PageHeader, Modal, Empty, ErrorNotice, Loading } from '../../webui/client/core.jsx'
import { PluginSettings } from '../../settings/client/settings.jsx'
const display = value => typeof value === 'object' ? JSON.stringify(value) : String(value ?? '')

export function ApplicationPlugins() {
  const app=useApp(), resource=useResource('/plugins',{plugins:[]})
  const [filter,setFilter]=useState('runtime'),[search,setSearch]=useState(''),[inspect,setInspect]=useState(null),[settings,setSettings]=useState(null),[busy,setBusy]=useState(''),[error,setError]=useState('')
  const all=resource.data.plugins || [], runtime=all.filter(plugin=>plugin.status!=='available')
  const rows=all.filter(plugin=>(filter==='all' || (filter==='runtime' ? plugin.status!=='available' : plugin.status==='available')) && `${plugin.name} ${plugin.id} ${plugin.description || ''}`.toLowerCase().includes(search.toLowerCase()))
  async function toggle(plugin){setBusy(plugin.id);setError('');try{await api(`/plugins/${encodeURIComponent(plugin.id)}/${plugin.enabled ? 'disable' : 'enable'}`,{method:'POST',body:{}});app.refresh();app.notify(`${plugin.name} ${plugin.enabled ? 'disabled' : 'enabled'}.`)}catch(e){setError(e.message)}finally{setBusy('')}}
  return <><div className="studio-catalog-intro card"><div><h2>The application is made of plugins.</h2><p>Inspect every registered service and its settings. Optional runtime plugins can be enabled or disabled here. Supporting services are managed with their parent plugin.</p></div><div className="studio-catalog-count"><strong>{runtime.length}</strong><span>runtime entries</span></div></div><ErrorNotice error={error || resource.error} retry={resource.error ? resource.reload : undefined}/><div className="page-toolbar"><div className="search-field"><Icon name="search" size={18}/><input aria-label="Search application plugins" placeholder="Search plugins or services…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="filter-tabs"><button className={filter==='runtime' ? 'active' : ''} onClick={()=>setFilter('runtime')}>Runtime <span>{runtime.length}</span></button><button className={filter==='available' ? 'active' : ''} onClick={()=>setFilter('available')}>Repository <span>{all.length-runtime.length}</span></button><button className={filter==='all' ? 'active' : ''} onClick={()=>setFilter('all')}>All plugins <span>{all.length}</span></button></div></div>{resource.loading ? <Loading/> : <div className="studio-catalog-list">{rows.map(plugin=><article className="card studio-catalog-plugin" key={plugin.id}><span className="extension-icon"><Icon name={plugin.parentId ? 'grid' : 'puzzle'} size={21}/></span><div className="studio-catalog-description"><div className="studio-catalog-title"><h3>{plugin.name || plugin.id}</h3><Badge status={plugin.status==='active' ? 'success' : plugin.status==='available' ? 'neutral' : 'warning'}>{plugin.status==='active' ? 'Active' : plugin.status==='available' ? 'Repository only' : 'Disabled'}</Badge>{plugin.essential && <Badge>Required</Badge>}</div><p>{plugin.description || 'Application service plugin'}</p><small>{plugin.parentId ? `Managed with ${plugin.parentId}` : plugin.layer || 'Application'}{plugin.version ? ` · v${plugin.version}` : ''}</small></div><div className="studio-catalog-actions">{plugin.configurable && <Button variant="secondary" icon="settings" onClick={()=>setSettings({id:plugin.configurationId || plugin.id,name:plugin.name})}>Configure</Button>}{plugin.lifecycleAllowed && <Button variant={plugin.enabled ? 'secondary' : 'primary'} busy={busy===plugin.id} onClick={()=>toggle(plugin)}>{plugin.enabled ? 'Disable' : 'Enable'}</Button>}<button className="text-button" onClick={()=>setInspect(plugin)}>Details <Icon name="chevron" size={14}/></button></div></article>)}</div>}{!resource.loading && !rows.length && <Empty icon="puzzle" title="No matching plugins">Try another search or change the catalog filter.</Empty>}
    {settings && <PluginSettings key={settings.id} plugin={settings} onClose={()=>setSettings(null)}/>}
    {inspect && <Modal title={inspect.name || inspect.id} description={inspect.description} onClose={()=>setInspect(null)}><dl className="preference-list"><div><dt>Status</dt><dd>{inspect.status==='available' ? 'Repository entry — not loaded in this application' : inspect.status}</dd></div><div><dt>Layer</dt><dd>{inspect.layer || 'Application'}</dd></div>{inspect.source && <div><dt>Source</dt><dd>{display(inspect.source)}</dd></div>}{inspect.parentId && <div><dt>Managed by</dt><dd>{inspect.parentId}</dd></div>}{inspect.dependencies?.length>0 && <div><dt>Dependencies</dt><dd>{inspect.dependencies.join(', ')}</dd></div>}{inspect.provides?.length>0 && <div><dt>Provides</dt><dd>{inspect.provides.join(', ')}</dd></div>}</dl>{inspect.reason && <p className="studio-catalog-reason">{inspect.reason}</p>}<div className="form-actions">{inspect.configurable && <Button icon="settings" onClick={()=>{setSettings({id:inspect.configurationId || inspect.id,name:inspect.name});setInspect(null)}}>Configure</Button>}<Button variant="secondary" onClick={()=>setInspect(null)}>Close</Button></div></Modal>}
  </>
}
function ManagerPage(){return <><PageHeader eyebrow="APPLICATION MANAGEMENT" title="Application plugins">Inspect, configure, and manage the plugins that run your application.</PageHeader><ApplicationPlugins/></>}
registry.page('plugins',{component:ManagerPage,icon:'puzzle'})
