import React,{useEffect,useState,useRef} from 'react'
import {useApp,useResource,api,Field,Button,ErrorNotice} from './core.jsx'
import './collections.css'
const defaults={search:'',filters:{},sort:'',direction:'asc',size:25,page:1,exportColumns:[]}
export function useCollection(id){
 const app=useApp(),saved=useResource('/collections/'+id+'/preferences',{revision:0,values:defaults}),[query,setQuery]=useState(defaults),[ready,setReady]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),revision=useRef(0),identity=app.user.id+':'+app.user.role+':'+id,loaded=useRef(null),knownColumns=useRef([])
 useEffect(()=>{if(!saved.loading&&!saved.error&&loaded.current!==identity){loaded.current=identity;revision.current=saved.data.revision;setQuery({...defaults,...saved.data.values,page:1});setReady(true);setDirty(false)}},[identity,saved.loading,saved.error,saved.data])
 const resource=useResource(ready?'/collections/'+id+'?query='+encodeURIComponent(JSON.stringify(query)):null,{rows:[],query:{total:0,matched:0,page:1,pages:1,start:0,end:0,sent:0,enums:{}},columns:[]})
 if(resource.data.columns?.length)knownColumns.current=resource.data.columns
 const update=patch=>{setQuery(value=>({...value,...patch,...('page' in patch?{}:{page:1})}));if(!('page' in patch))setDirty(true)}
 async function save(reset=false){setBusy(true);setError('');try{const next=await api('/collections/'+id+'/preferences',{method:'PATCH',body:{values:query,reset,expectedRevision:revision.current}});revision.current=next.revision;setQuery({...defaults,...next.values,page:1});setDirty(false);app.notify(reset?'Default view restored.':'View saved to your account.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function reloadSaved(){const next=await saved.reload();if(next){revision.current=next.revision;setQuery({...defaults,...next.values,page:1});setDirty(false);setError('')}}
 async function allKeys(){return (await api('/collections/'+id+'?query='+encodeURIComponent(JSON.stringify({...query,keys:true})))).query.keys}
 async function download(){setBusy(true);setError('');try{const result=await api('/collections/'+id+'/export?query='+encodeURIComponent(JSON.stringify(query))),url=URL.createObjectURL(new Blob([result.content],{type:result.mime})),a=document.createElement('a');a.href=url;a.download=result.filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);app.notify('Exported '+result.rows+' matching rows.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 const preferenceError=!ready&&saved.error
 return {...resource,loading:resource.loading||(!ready&&!saved.error),error:resource.error||preferenceError,reload:()=>!ready?saved.reload():resource.reload(),data:{...resource.data,columns:knownColumns.current},query,update,ready,dirty,busy,save,reloadSaved,allKeys,download,viewError:error||(ready?saved.error:''),retryView:saved.error?saved.reload:undefined,selectionKey:JSON.stringify([identity,query.search,query.filters,query.sort,query.direction]),clear:()=>update({...defaults,size:query.size,exportColumns:query.exportColumns})}
}
export function CollectionControls({view,label='records',selection,children}){
 const {query,update,data}=view,meta=data.query,columns=data.columns||[],filter=(key,condition)=>update({filters:{...query.filters,[key]:condition}})
 return <section className="collection-controls" aria-label={label+' query controls'}><div className="collection-query"><Field label={'Search '+label}><input type="search" value={query.search} onChange={e=>update({search:e.target.value})}/></Field></div>
 <details><summary>Filters, saved view &amp; export columns</summary><div className="collection-query"><Field label="Sort by"><select value={query.sort} onChange={e=>update({sort:e.target.value})}><option value="">Default order</option>{columns.map(column=><option key={column.key} value={column.key}>{column.label}</option>)}</select></Field><Field label="Sort direction"><select value={query.direction} onChange={e=>update({direction:e.target.value})}><option value="asc">Ascending</option><option value="desc">Descending</option></select></Field></div><div className="collection-fields">{columns.map(column=><Field key={column.key} label={'Filter '+column.label}>{column.type==='enum'?<select value={query.filters[column.key]?.equals||''} onChange={e=>filter(column.key,{equals:e.target.value})}><option value="">Any</option>{(meta.enums?.[column.key]||[]).map(value=><option key={value} value={value}>{value||'(blank)'}</option>)}</select>:column.type==='number'||column.type==='date'?<span className="collection-range"><input aria-label={'Minimum '+column.label} type={column.type==='number'?'number':'date'} value={query.filters[column.key]?.min||''} onChange={e=>filter(column.key,{...query.filters[column.key],min:e.target.value})}/><input aria-label={'Maximum '+column.label} type={column.type==='number'?'number':'date'} value={query.filters[column.key]?.max||''} onChange={e=>filter(column.key,{...query.filters[column.key],max:e.target.value})}/></span>:<input value={query.filters[column.key]?.contains||''} onChange={e=>filter(column.key,{contains:e.target.value})}/>}</Field>)}</div><fieldset><legend>CSV export columns</legend><p className="muted">No selection exports all columns. Export includes all matching rows.</p><div className="collection-columns">{columns.map(column=><label key={column.key}><input type="checkbox" checked={query.exportColumns.includes(column.key)} onChange={e=>update({exportColumns:e.target.checked?[...query.exportColumns,column.key]:query.exportColumns.filter(key=>key!==column.key)})}/>{column.label}</label>)}</div></fieldset><div className="collection-buttons"><Button variant="secondary" busy={view.busy} disabled={!view.dirty} onClick={()=>view.save()}>Save view</Button><Button variant="ghost" disabled={view.busy} onClick={view.reloadSaved}>Load saved view</Button><Button variant="ghost" disabled={view.busy} onClick={()=>view.save(true)}>Restore default view</Button><Button variant="secondary" disabled={view.busy||view.loading||!!view.error} onClick={view.download}>Export matching CSV</Button></div></details>
 <ErrorNotice error={view.viewError} retry={view.retryView}/><div className="collection-pagination"><p role="status">{view.loading?'Loading records…':view.error?'Records unavailable. Retry the request below.':meta.total+' total · '+meta.matched+' matching · '+meta.sent+' on this page · Page '+meta.page+' of '+meta.pages+(view.refreshing?' · Updating…':'')}</p><Field label="Rows per page"><select value={query.size} onChange={e=>update({size:Number(e.target.value)})}>{[10,25,50,100,0].map(size=><option key={size} value={size}>{size||'All (may be slower)'}</option>)}</select></Field><div className="collection-buttons"><Button variant="ghost" disabled={meta.page<=1||view.loading} onClick={()=>update({page:1})}>First page</Button><Button variant="ghost" disabled={meta.page<=1||view.loading} onClick={()=>update({page:meta.page-1})}>Previous page</Button><Button variant="ghost" disabled={meta.page>=meta.pages||view.loading} onClick={()=>update({page:meta.page+1})}>Next page</Button><Button variant="ghost" disabled={meta.page>=meta.pages||view.loading} onClick={()=>update({page:meta.pages})}>Last page</Button><Button variant="ghost" onClick={view.clear}>Clear filters</Button></div></div>{selection}{children}</section>
}
