import assert from 'node:assert/strict'
import {browserHarness} from '../../file-store/tests/browser-helpers.mjs'
const h=await browserHarness('accessibility')
try{
 const page=await h.browser.newPage({viewport:{width:1440,height:1000}});h.pages.push(page);page.on('pageerror',error=>h.errors.push(error.message));await page.goto(h.base)
 const email=page.getByLabel('Email address',{exact:true}),password=page.getByLabel('Password',{exact:true});await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.locator('.field-error').first().waitFor();assert.equal(await email.getAttribute('aria-invalid'),'true');assert(await email.evaluate(node=>node.getAttribute('aria-describedby').split(' ').every(id=>document.getElementById(id)?.textContent)));await email.fill('invalid-email');await page.getByRole('button',{name:'Sign in',exact:true}).click();assert.equal(await email.getAttribute('aria-invalid'),'true');await h.shot(page,'01-invalid-fields');await email.fill('contractor@demo.local');await password.fill('demo1234');assert.equal(await email.getAttribute('aria-invalid'),null);await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('navigation',{name:'Main navigation'}).waitFor();await page.getByRole('button',{name:'Not now',exact:true}).click({timeout:1200}).catch(()=>{});h.checks.push('Native required and email validation expose persistent control-linked errors; valid edit removes invalid state and real sign-in still works')
 await h.nav(page,'Settings');const workspace=page.getByLabel('Workspace type',{exact:true});await workspace.waitFor();assert(await workspace.evaluate(node=>document.getElementById(node.getAttribute('aria-describedby'))?.textContent.includes('one business perspective')));await workspace.focus();assert(await workspace.evaluate(node=>getComputedStyle(node).boxShadow!=='none'||getComputedStyle(node).outlineStyle!=='none'));await h.shot(page,'02-hint-focus');h.checks.push('Visible workspace label and descriptive hint are programmatically associated; keyboard-focused native control has a visible indicator')
 const registration=await h.browser.newPage({viewport:{width:1200,height:1000}});h.pages.push(registration);registration.on('pageerror',error=>h.errors.push(error.message));await registration.goto(h.base);await registration.getByRole('button',{name:'Create an account',exact:true}).click();await registration.getByLabel('Your name',{exact:true}).fill('Accessibility check');await registration.getByLabel('Company',{exact:true}).fill('Read-only validation check');await registration.getByLabel('Email address',{exact:true}).fill('contractor@demo.local');await registration.getByLabel('Password',{exact:true}).fill('demo1234');const rejected=registration.waitForResponse(response=>response.url().endsWith('/auth/register')&&response.request().method()==='POST');await registration.getByRole('button',{name:'Create workspace',exact:true}).click();assert.equal((await rejected).status(),409);const registeredEmail=registration.getByLabel('Email address',{exact:true});await registration.locator('.field-error').filter({hasText:'already has an account'}).waitFor();assert.equal(await registeredEmail.getAttribute('aria-invalid'),'true');assert(await registeredEmail.evaluate(node=>node.getAttribute('aria-describedby').split(' ').some(id=>document.getElementById(id)?.textContent.includes('already has an account'))));await h.shot(registration,'03-server-field-error');await registeredEmail.fill('unsent@example.test');assert.equal(await registeredEmail.getAttribute('aria-invalid'),null);h.checks.push('Real server409 duplicate-email response renders beside its email control with described-by and invalid state; editing clears the field error; no account was created');
 const admin=await h.login('admin@demo.local');await h.nav(admin,'Administration');await admin.locator('table').first().waitFor();const names=await admin.locator('table').evaluateAll(tables=>tables.map(table=>({caption:table.caption?.textContent.trim(),label:table.getAttribute('aria-label'),heading:table.getAttribute('aria-labelledby')?.split(' ').map(id=>document.getElementById(id)?.textContent.trim()).join(' ')})));assert(names.every(row=>row.caption||row.label||row.heading));assert(names.some(row=>row.heading));await h.shot(admin,'03-named-admin-tables');h.checks.push('Actual administrator tables without owner captions inherit nonempty section-heading accessible names')
 await h.nav(page,'Operations & timeline');
 await page.getByRole('table',{name:'Event metadata in the current query',exact:true}).waitFor();assert.equal(await page.getByRole('table',{name:'Event metadata in the current query',exact:true}).getAttribute('aria-labelledby'),null);h.checks.push('Explicit event-table caption wins over automatic section-heading naming')
 await page.route('**/api/collections/event-timeline**',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({ok:false,error:'Accessibility check: source temporarily unavailable'})}));await page.reload();await page.getByRole('alert').filter({hasText:'source temporarily unavailable'}).waitFor();assert.equal(await page.getByRole('heading',{name:'No recorded events',exact:true}).count(),0);await page.unroute('**/api/collections/event-timeline**');await page.getByRole('button',{name:'Try again',exact:true}).click();await page.getByRole('table',{name:'Event metadata in the current query',exact:true}).waitFor();h.checks.push('Failed saved-view request exposes an alert and retry; it never displays the empty-history state, and retry restores records');await page.route('**/api/collections/event-timeline?*',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({ok:false,error:'Row source unavailable for check'})}));await page.reload();await page.getByRole('alert').filter({hasText:'Row source unavailable for check'}).waitFor();assert.equal(await page.getByRole('heading',{name:'No recorded events',exact:true}).count(),0);await page.unroute('**/api/collections/event-timeline?*');await page.getByRole('button',{name:'Try again',exact:true}).click();await page.getByRole('table',{name:'Event metadata in the current query',exact:true}).waitFor();h.checks.push('Separate row-source failure also preserves unavailable semantics and a working retry')
 await page.setViewportSize({width:390,height:900});await page.waitForTimeout(400);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.getByRole('button',{name:'Open navigation',exact:true}).click();await page.getByRole('button',{name:'Close navigation',exact:true}).click();await page.waitForTimeout(400);assert((await page.locator('.sidebar').boundingBox()).x<0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await h.shot(page,'04-mobile-settled');h.checks.push('Settled 390px sidebar opens/closes by keyboard-capable controls; closed sidebar is offscreen and document has no horizontal overflow')
 await h.finish({tableNames:names})
}catch(error){await h.fail(error);throw error}finally{await h.close()}
