import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {mkdirSync,mkdtempSync,writeFileSync} from 'node:fs'
import {resolve,join} from 'node:path'
import * as storePlugin from '../../workspace-store/code/index.mjs'
import {createCollections,windowRows} from '../code/collections.mjs'
const require=createRequire(new URL('../../../../host/package.json',import.meta.url)),{Context}=require('cordis')
mkdirSync('tmp',{recursive:true});const root=mkdtempSync(resolve('tmp/collections-')),ctx=new Context(),checks=[],user={id:'collection-user',role:'contractor'},columns=[{key:'id',label:'ID'},{key:'title',label:'Title'},{key:'status',label:'Status',type:'enum'},{key:'amount',label:'Amount',type:'number'}],rows=Array.from({length:257},(_,i)=>({id:'row-'+i,title:i===2?'=untrusted spreadsheet formula':'Item '+i,status:i%2?'closed':'open',amount:i%11}))
let fiber=await ctx.plugin(storePlugin,{root}),collections=createCollections({store:ctx.store})
const definition={id:'example',columns,roles:['contractor','supplier'],load:()=>rows}
let dispose=collections.register(definition)
try{
 const input={filters:{status:{equals:'open'},amount:{min:'3',max:'7'}},sort:'amount',direction:'desc',size:10},expected=rows.map((row,index)=>({row,index})).filter(({row})=>row.status==='open'&&row.amount>=3&&row.amount<=7).sort((a,b)=>b.row.amount-a.row.amount||a.index-b.index).map(item=>item.row.id),actual=[]
 const first=await collections.query(user,'example',input);for(let page=1;page<=first.query.pages;page++){const result=await collections.query(user,'example',{...input,page});actual.push(...result.rows.map(row=>row.id));assert(result.rows.length<=10);assert.equal(result.query.total,257);assert.equal(result.query.matched,expected.length)}assert.deepEqual(actual,expected);assert.deepEqual((await collections.query(user,'example',{...input,keys:true})).query.keys,expected);assert.deepEqual(first.query.enums.status,['closed','open']);assert.equal((await collections.query(user,'example',{...input,size:0})).rows.length,expected.length);checks.push('257-row source matches independent conjunctive filter and stable sort across every server page; complete totals, enum values, explicit all rows and matching-key selection')
 assert.equal(ctx.store.events(user.id).length,0);const saved=await collections.save(user,'example',{values:{...input,exportColumns:['title','amount']},expectedRevision:0});assert.equal(saved.revision,1);await assert.rejects(()=>collections.save(user,'example',{values:{search:'stale'},expectedRevision:0}),error=>error.status===409);assert.equal(collections.preference({...user,role:'supplier'},'example').revision,0);assert.equal(collections.preference({id:'other',role:'contractor'},'example').revision,0);assert.equal(ctx.store.events(user.id).length,1);checks.push('Queries are read-only; explicit saved preferences are account/role isolated; stale updates refuse without a fact')
 const exported=await collections.export(user,'example',{exportColumns:['title','amount']});assert.deepEqual(exported.columns,['title','amount']);assert.match(exported.content,/"'=untrusted spreadsheet formula"/);assert.equal(exported.rows,257);checks.push('CSV exports complete matching rows and chosen columns with spreadsheet formula escaping')
 dispose();assert.throws(()=>collections.preference(user,'example'),error=>error.status===404);collections.dispose();await fiber.dispose();fiber=await ctx.plugin(storePlugin,{root});collections=createCollections({store:ctx.store});dispose=collections.register(definition);assert.deepEqual(collections.preference(user,'example').values.exportColumns,['title','amount']);await collections.save(user,'example',{reset:true,expectedRevision:1});assert.equal(collections.preference(user,'example').revision,2);checks.push('Unregister removes query/preference access; process replay reconstructs saved view; reset adds a new ledger revision')
 assert.throws(()=>windowRows(Array.from({length:5001},(_,i)=>({id:String(i)})),columns,{keys:true}),error=>error.status===413);assert.throws(()=>collections.preference({...user,role:'admin'},'example'),error=>error.status===404);checks.push('Oversized all-match key selection refuses instead of silently truncating; undeclared roles cannot use collection')
 const report={ok:true,root,at:new Date().toISOString(),checks};writeFileSync(join(root,'report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2))
}finally{dispose();collections.dispose();await fiber.dispose()}
