import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {mkdirSync,mkdtempSync,writeFileSync,readFileSync} from 'node:fs'
import {resolve,join} from 'node:path'
import {spawn} from 'node:child_process'
import * as storePlugin from '../../workspace-store/code/index.mjs'
import {createActions} from '../../action-center/code/service.mjs'
const require=createRequire(new URL('../../../../host/package.json',import.meta.url)),{Context}=require('cordis'),{chromium}=require('playwright'),root=mkdtempSync(resolve('tmp/collection-gui-')),out=resolve(process.env.EVIDENCE_DIR||root),ctx=new Context(),user={id:'contractor-demo',role:'contractor',name:'Alex Morgan'},checks=[]
mkdirSync(out,{recursive:true});let host,browser,page;const report={at:new Date().toISOString(),root,checks,errors:[],screenshots:[]}
try{
 const fiber=await ctx.plugin(storePlugin,{root}),actions=createActions({store:ctx.store,accounts:{get:id=>id===user.id?user:null,list:()=>[user],can:()=>true}}),dispose=actions.register({kind:'collection-fixture',label:'Collection fixture',execute:()=>({ok:true})})
 for(let i=0;i<36;i++)await actions.propose(user,{kind:'collection-fixture',input:{fixtureNumber:i},title:'Collection sample '+String(i).padStart(2,'0')})
 dispose();await actions.dispose();await fiber.dispose()
 host=spawn('node',['host/product.mjs'],{env:{...process.env,QUOTAGENT_WEBUI_PORT:'0',QUOTAGENT_PRODUCT_DATA:root,QUOTAGENT_WEBUI_ASSETS:resolve('tmp/agent-experience/collections-build')},stdio:['ignore','pipe','pipe']});let logs='';host.stderr.on('data',data=>logs+=data);const ready=await new Promise((resolve,reject)=>{let output='';host.stdout.on('data',data=>{output+=data;for(const line of output.split('\n'))try{const row=JSON.parse(line);if(row.ready)resolve(row)}catch{}});host.once('exit',code=>reject(new Error('Host exited '+code+' '+logs)))}),base=ready.url;report.base=base
 browser=await chromium.launch({headless:true,executablePath:'/opt/hermes/.playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox']});page=await browser.newPage({viewport:{width:1440,height:1100}});page.setDefaultTimeout(20000);page.on('pageerror',error=>report.errors.push(error.message));await page.goto(base);await page.getByRole('button',{name:'I’m a contractor'}).click();await page.locator('.ws-navigation').waitFor();await page.getByRole('button',{name:'Not now',exact:true}).click();await page.getByRole('navigation',{name:'Main navigation'}).getByRole('button',{name:'Review actions',exact:true}).click();await page.getByLabel('Search actions',{exact:true}).fill('Collection sample');await page.getByLabel('Rows per page',{exact:true}).selectOption('10');await page.getByText('36 total · 36 matching · 10 on this page · Page 1 of 4',{exact:true}).waitFor();assert.equal(await page.locator('.review-list-row').count(),10)
 const first=page.locator('.review-choice').first(),firstTitle=await first.locator('strong').innerText();await first.getByRole('checkbox').check();await page.getByRole('button',{name:'Next page',exact:true}).click();await page.getByText('36 total · 36 matching · 10 on this page · Page 2 of 4',{exact:true}).waitFor();await page.locator('.review-choice').first().getByRole('checkbox').check();await page.getByRole('button',{name:'Previous page',exact:true}).click();await page.getByText('36 total · 36 matching · 10 on this page · Page 1 of 4',{exact:true}).waitFor();assert(await page.locator('.review-choice').filter({hasText:firstTitle}).getByRole('checkbox').isChecked());await page.getByText('2 selected across pages · 1 on this page',{exact:true}).waitFor();await page.getByText('Review selected action contents',{exact:true}).click();assert.equal(await page.locator('.review-batch article').count(),2);checks.push('Real 36-proposal ledger source: only10 rows rendered, complete totals, paging preserves selection and exact selected contents')
 await page.getByRole('button',{name:'Select all matching actions',exact:true}).click();await page.getByText('36 selected across pages · 10 on this page',{exact:true}).waitFor();await page.getByLabel('Search actions',{exact:true}).fill('Collection sample 0');await page.getByText('36 total · 10 matching · 10 on this page · Page 1 of 1',{exact:true}).waitFor();await page.getByText('0 selected across pages · 0 on this page',{exact:true}).waitFor();checks.push('Explicit all-match selection includes all36; query change clears cross-page selection and updates whole-source matched count')
 await page.getByText('Filters, saved view & export columns',{exact:true}).click();await page.getByLabel('Sort by',{exact:true}).selectOption('title');await page.getByLabel('Sort direction',{exact:true}).selectOption('asc');await page.getByRole('group',{name:'CSV export columns'}).getByRole('checkbox',{name:'Action',exact:true}).check();await page.getByRole('button',{name:'Save view',exact:true}).click();await page.getByText('View saved to your account.',{exact:true}).waitFor();await page.reload();await page.getByLabel('Search actions',{exact:true}).waitFor();await page.waitForFunction(()=>document.querySelector('[aria-label="Search actions"]')?.value==='Collection sample 0');await page.getByText('Filters, saved view & export columns',{exact:true}).click();assert(await page.getByRole('group',{name:'CSV export columns'}).getByRole('checkbox',{name:'Action',exact:true}).isChecked());const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Export matching CSV',exact:true}).click();const download=await pending;await download.saveAs(join(out,'matching.csv'));const csv=readFileSync(join(out,'matching.csv'),'utf8');assert.equal(csv.split('\r\n')[0],'"Action"');assert.equal(csv.trim().split('\r\n').length,11);checks.push('Saved filter/sort/page-size/export-column preferences survive reload; visible CSV control downloads matching rows')
  let releaseOld,markOld;const oldArrived=new Promise(resolve=>markOld=resolve),oldReleased=new Promise(resolve=>releaseOld=resolve);await page.route(url=>url.pathname.endsWith('/api/collections/review-actions')&&JSON.parse(url.searchParams.get('query')||'{}').search==='Collection sample 00',async route=>{const response=await route.fetch();markOld();await oldReleased;await route.fulfill({response})});await page.getByLabel('Search actions',{exact:true}).fill('Collection sample 00');await oldArrived;await page.getByLabel('Search actions',{exact:true}).fill('Collection sample 01');await page.locator('.review-list-row strong').filter({hasText:'Collection sample 01'}).waitFor();releaseOld();await page.waitForTimeout(500);assert.equal(await page.locator('.review-list-row strong').innerText(),'Collection sample 01');checks.push('A deliberately delayed older HTTP query cannot overwrite the newer query result');
 await page.setViewportSize({width:390,height:1000});await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:join(out,'mobile.png'),fullPage:true});report.screenshots.push('mobile.png');await page.setViewportSize({width:1440,height:1100});await page.route('**/api/collections/review-actions?*',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Fixture source is temporarily unavailable.'})}));await page.getByLabel('Search actions',{exact:true}).fill('Unavailable query');await page.getByRole('alert').filter({hasText:'Fixture source is temporarily unavailable.'}).waitFor();assert.equal(await page.getByRole('heading',{name:'No actions match these filters',exact:true}).count(),0);checks.push('390px collection view fits viewport; failed source request visibly reports unavailable instead of an empty result');assert.deepEqual(report.errors,[]);report.ok=true
}catch(error){report.error=error.stack;process.exitCode=1;if(page)await page.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>{})}finally{if(browser)await browser.close();if(host){host.kill('SIGTERM');await new Promise(resolve=>host.once('exit',resolve))}writeFileSync(join(out,'report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2))}
