import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {mkdirSync,writeFileSync} from 'node:fs'
import {resolve,join} from 'node:path'
const require=createRequire(new URL('../../../../host/package.json',import.meta.url)),{chromium}=require('playwright')
const base=(process.env.BASE_URL||'http://127.0.0.1:8649/quotagent/').replace(/\/?$/,'/'),output=resolve(process.env.EVIDENCE_DIR||'tmp/product-evidence/navigation/local')
mkdirSync(output,{recursive:true})
const browser=await chromium.launch({headless:true,executablePath:'/opt/hermes/.playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox']})
const report={base,at:new Date().toISOString(),checks:[],screenshots:[],errors:[]},pages=[]
async function login(role){const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();pages.push(page);page.on('pageerror',error=>report.errors.push(error.message));await page.goto(base);await page.getByRole('button',{name:role==='admin'?'Administrator sign in':`I’m a ${role}`}).click();await page.locator('.ws-navigation').waitFor();await page.waitForTimeout(300);for(const name of ['Not now','Hide walkthrough']){const button=page.getByRole('button',{name,exact:true});if(await button.isVisible())await button.click()}return page}
async function command(page,label){await page.getByRole('button',{name:'Find a page or action',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Find a page or action',exact:true});await dialog.getByLabel('Search pages and actions',{exact:true}).fill(label);await dialog.getByRole('button',{name:new RegExp('^'+label)}).click()}
async function shot(page,name){await page.screenshot({path:join(output,name),fullPage:true});report.screenshots.push(name)}
try{
 const buyer=await login('contractor');await buyer.keyboard.press('Control+k');const palette=buyer.getByRole('dialog',{name:'Find a page or action',exact:true});await palette.waitFor();await palette.getByLabel('Search pages and actions',{exact:true}).fill('Help');await palette.getByRole('button',{name:/^Help & getting started/}).click();await buyer.locator('.guide-topic-card').first().waitFor();const topic=buyer.locator('.guide-topic-card').first();report.topic=await topic.locator('strong').innerText();await topic.click();await buyer.waitForFunction(()=>location.hash.includes('context='));const linked=buyer.url();await buyer.reload();await buyer.locator('.guide-article h2').filter({hasText:report.topic}).waitFor();assert.equal(buyer.url(),linked);await shot(buyer,'01-restored-context.png');report.checks.push('Command palette opened through keyboard; actual Help topic selection remains in URL and survives browser reload')
 await command(buyer,'Settings');await buyer.getByRole('heading',{name:'A workspace that fits you',exact:true}).waitFor();await buyer.goBack();await buyer.locator('.guide-article h2').filter({hasText:report.topic}).waitFor();await buyer.goForward();await buyer.getByRole('heading',{name:'A workspace that fits you',exact:true}).waitFor();await buyer.goBack();await buyer.locator('.guide-article h2').filter({hasText:report.topic}).waitFor();report.checks.push('Browser back and forward restore page and selected context without losing the record identifier')
 const share=buyer.getByRole('button',{name:'Share this page',exact:true});await share.click();const dialog=buyer.getByRole('dialog',{name:'Share this page',exact:true});await dialog.waitFor();assert.equal(await dialog.getByLabel('Page link',{exact:true}).inputValue(),linked);await dialog.getByText(/Sharing a link does not invite someone or grant permission/).waitFor();assert.equal(await buyer.locator('#root').evaluate(node=>node.inert),true);const close=dialog.getByRole('button',{name:'Close dialog',exact:true});await close.focus();await buyer.keyboard.press('Shift+Tab');assert.equal(await dialog.getByRole('button',{name:'Copy link',exact:true}).evaluate(node=>node===document.activeElement),true);await buyer.keyboard.press('Tab');assert.equal(await close.evaluate(node=>node===document.activeElement),true);await buyer.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});assert.equal(await share.evaluate(node=>node===document.activeElement),true);assert.equal(await buyer.locator('#root').evaluate(node=>node.inert),false);report.checks.push('Sharing explains existing access; real modal makes background inert, traps Tab both ways, closes on Escape and returns focus')
 await buyer.getByRole('button',{name:'Find a page or action',exact:true}).click();await palette.getByLabel('Search pages and actions',{exact:true}).fill('Administration');assert.equal(await palette.getByRole('button',{name:/^Administration/}).count(),0);await palette.getByLabel('Search pages and actions',{exact:true}).fill('Replay the workspace');await palette.getByRole('button',{name:/^Replay the workspace walkthrough/}).waitFor();await buyer.keyboard.press('Escape');await buyer.goto(base+'#admin');await buyer.getByRole('heading',{name:'This page is unavailable',exact:true}).waitFor();await buyer.getByRole('button',{name:'Go to my home',exact:true}).click();await buyer.waitForURL(base);report.checks.push('Available plugin command is searchable, administrator pages are absent for client and inaccessible deep link explains the account restriction')
 await buyer.setViewportSize({width:390,height:900});await buyer.getByRole('button',{name:'Find a page or action',exact:true}).click();await palette.waitFor();assert.equal(await buyer.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const size=await palette.getByRole('button',{name:'Close dialog',exact:true}).boundingBox();assert(size.width>=44&&size.height>=44);await shot(buyer,'02-mobile-palette.png');await buyer.keyboard.press('Escape');const vendor=await login('supplier');await command(vendor,'Help & getting started');await vendor.getByRole('heading',{name:'Help & getting started',exact:true}).waitFor();report.checks.push('390px palette has no horizontal overflow and 44px close target; supplier can use its own available pages')
 assert.equal(report.errors.length,0);report.ok=true;report.completedAt=new Date().toISOString();console.log(JSON.stringify(report,null,2))
}catch(error){report.error=error.stack;process.exitCode=1;console.error(JSON.stringify(report,null,2));for(let i=0;i<pages.length;i++)await pages[i].screenshot({path:join(output,`failure-${i}.png`),fullPage:true}).catch(()=>{})}
finally{writeFileSync(join(output,'report.json'),JSON.stringify(report,null,2)+'\n');await browser.close()}
