import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {mkdirSync,writeFileSync} from 'node:fs'
import {resolve,join} from 'node:path'
const require=createRequire(new URL('../../../../host/package.json',import.meta.url)),{chromium}=require('playwright')
const base=(process.env.BASE_URL||'http://127.0.0.1:8651/quotagent/').replace(/\/?$/,'/'),output=resolve(process.env.EVIDENCE_DIR||'tmp/product-evidence/offline/local')
mkdirSync(output,{recursive:true})
const browser=await chromium.launch({headless:true,executablePath:'/opt/hermes/.playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox']})
const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),report={base,at:new Date().toISOString(),checks:[],screenshots:[],errors:[]}
page.on('pageerror',error=>report.errors.push(error.message))
const shot=async name=>{await page.screenshot({path:join(output,name),fullPage:true});report.screenshots.push(name)}
try{
 await page.goto(base);await page.getByRole('button',{name:'I’m a contractor'}).click();await page.locator('.ws-navigation').waitFor();await page.waitForTimeout(300);for(const name of ['Not now','Hide walkthrough']){const button=page.getByRole('button',{name,exact:true});if(await button.isVisible())await button.click()}
 await page.goto(base+'#settings');await page.getByRole('heading',{name:'Use Quotagent as an app',exact:true}).waitFor();const company=page.getByLabel('Company',{exact:true}),original=await company.inputValue();await page.getByRole('button',{name:'Enable offline shell',exact:true}).click();await page.waitForFunction(()=>navigator.serviceWorker.controller!==null);await page.locator('.offline-settings [role="status"]').filter({hasText:/available|ready/}).waitFor();await shot('01-enabled-shell.png')
 const cdp=await context.newCDPSession(page),manifest=await cdp.send('Page.getAppManifest');report.manifest={url:manifest.url,errors:manifest.errors,data:JSON.parse(manifest.data)};assert.equal(report.manifest.errors.length,0);assert.equal(report.manifest.data.display,'standalone');assert.deepEqual(report.manifest.data.icons.map(icon=>icon.sizes),['192x192','512x512']);report.installability=await cdp.send('Page.getInstallabilityErrors');assert.deepEqual(report.installability.installabilityErrors,[]);report.checks.push('Visible Settings opt-in activates and controls this browser; Chromium reports valid standalone manifest,192/512icons and no installability errors')
 await context.setOffline(true);await page.getByText('You are offline.',{exact:true}).waitFor();await company.fill('OFFLINE MUST NOT SAVE '+Date.now());await page.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByRole('alert').filter({hasText:/You are offline.*not queued/}).waitFor();await shot('02-offline-write-refused.png');const apiOffline=await page.evaluate(async()=>{try{await fetch('/quotagent/api/bootstrap');return false}catch{return true}});assert.equal(apiOffline,true);report.checks.push('Actual disconnection shows stale-data warning; profile write fails visibly and API has no offline cache response')
 await page.reload({waitUntil:'domcontentloaded'});await page.getByText('You are offline.',{exact:true}).waitFor();await page.getByRole('alert').filter({hasText:/You are offline/}).waitFor();assert.equal(await page.getByLabel('Company',{exact:true}).count(),0);await shot('03-offline-shell-only.png');report.cache=await page.evaluate(async()=>{const result={};for(const name of await caches.keys()){const cache=await caches.open(name);result[name]=(await cache.keys()).map(request=>new URL(request.url).pathname)}return result});assert.equal(Object.keys(report.cache).length,1);for(const paths of Object.values(report.cache)){assert(!paths.some(path=>path.includes('/api/')));for(const required of ['/quotagent/','/quotagent/manifest.webmanifest','/quotagent/app-icon-192.png','/quotagent/app-icon-512.png'])assert(paths.includes(required));assert(paths.some(path=>path.endsWith('.js')));assert(paths.some(path=>path.endsWith('.css')));assert(paths.every(path=>/^\/quotagent\/(?:$|manifest\.webmanifest$|app-icon-(?:192|512)\.png$|assets\/[^/]+\.(?:js|css|png|svg|woff2?)$)/.test(path)))}report.checks.push('Offline reload opens the cached empty shell without claiming an account or business data; cache contains the shell, manifest, icons and current static build assets with no API data')
 await context.setOffline(false);await page.getByRole('button',{name:'Reconnect',exact:true}).click();await company.waitFor();assert.equal(await company.inputValue(),original);assert.equal(await page.locator('.connection-warning').count(),0);await page.getByRole('button',{name:'Remove offline shell',exact:true}).click();await page.waitForFunction(async()=>!(await navigator.serviceWorker.getRegistration('/quotagent/'))&&(await caches.keys()).every(key=>!key.startsWith('quotagent-shell:/quotagent/:')));await page.getByRole('button',{name:'Enable offline shell',exact:true}).waitFor();report.checks.push('Reconnection reloads actual unchanged profile without replaying the failed write; removal unregisters the worker and deletes all owned cache versions')
 await page.setViewportSize({width:390,height:900});await shot('04-mobile-device-settings.png');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(report.errors.length,0);report.ok=true;report.completedAt=new Date().toISOString();report.limit='Headless Chromium installability only; no operating-system app installation was performed.';console.log(JSON.stringify(report,null,2))
}catch(error){report.error=error.stack;process.exitCode=1;console.error(JSON.stringify(report,null,2));await context.setOffline(false);await shot('failure.png').catch(()=>{})}
finally{writeFileSync(join(output,'report.json'),JSON.stringify(report,null,2)+'\n');await browser.close()}
