import {createHash} from 'node:crypto'
export const collections={rfq:'rfqs',quote:'quotes',order:'orders',change:'changes'}
export const stable=value=>Array.isArray(value)?value.map(stable):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(key=>[key,stable(value[key])])):value
export const digest=value=>createHash('sha256').update(JSON.stringify(stable(value))).digest('hex')
export const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status})}
export const iso=value=>{if(!value||!Number.isFinite(Date.parse(value)))fail('Choose a valid date and time.');return new Date(value).toISOString()}
export const revision=(kind,record)=>Number(kind==='rfq'?record.publishedRevision||record.revision:kind==='order'?record.orderRevision:record.revision||record.rfqRevision)||1
export const reference=(realm,event)=>event?{realm,seq:event.seq,hash:event.entry_hash,type:event.type,at:event.ts}:null
export const source=(store,realm,collection,id)=>reference(realm,store.events(realm).findLast(event=>event.body?.schema==='quotagent/workspace-record/v1'&&event.body.collection===collection&&event.body.record?.id===id))
export function coverage({snapshot,realm,role,promises=[],reminders=[],reads=[],asOf,minimum=2,soonHours=24}){
 const at=Date.parse(iso(asOf)),names=new Map(snapshot.contacts.map(row=>[row.id,row.company||row.name||row.id]))
 return snapshot.rfqs.filter(rfq=>rfq.status==='published').map(rfq=>{
  const rev=revision('rfq',rfq),invited=role==='contractor'?rfq.supplierIds:[realm]
  const people=invited.map(supplierId=>{const quote=snapshot.quotes.filter(row=>row.rfqId===rfq.id&&row.supplierId===supplierId&&['submitted','awarded'].includes(row.status)&&!row.stale&&row.rfqRevision===rev).sort((a,b)=>(b.revision||1)-(a.revision||1))[0],promise=promises.filter(row=>row.rfqId===rfq.id&&row.fromId===supplierId&&row.rfqRevision===rev).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)||b.id.localeCompare(a.id))[0],due=promise?.dueAt||rfq.deadline||null,remaining=due?(Date.parse(due)-at)/1000:null,reminder=reminders.filter(row=>row.rfqId===rfq.id&&row.toId===supplierId&&row.rfqRevision===rev).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0],receipt=reads.filter(row=>row.kind==='rfq'&&row.objectId===rfq.id&&row.fromId===supplierId&&row.objectRevision===rev);return{supplierId,name:names.get(supplierId)||supplierId,responded:!!quote,quoteId:quote?.id||null,dueAt:due,dueBasis:promise?'supplier promise':due?'quote deadline':'unknown',remainingSeconds:remaining,severity:quote?'responded':remaining===null?'unknown':remaining<0?'overdue':remaining<=soonHours*3600?'due-soon':'open',promise:promise||null,lastReminder:reminder||null,reads:receipt}})
  const responded=people.filter(row=>row.responded).length;return{rfqId:rfq.id,title:rfq.title,rfqRevision:rev,quoteDeadline:rfq.deadline||null,clarifyDeadline:rfq.clarifyDeadline||null,clarificationClosed:rfq.clarifyDeadline?Date.parse(rfq.clarifyDeadline)<at:null,people,...(role==='contractor'?{invited:people.length,responded,silent:people.filter(row=>!row.responded).map(row=>row.supplierId),minimum,belowMinimum:responded<minimum}:{}),asOf:new Date(at).toISOString()}
 })
}
export function weekly({store,snapshot,realm,role,asOf,from,to,minimum}){
 const asAt=iso(asOf),end=to?iso(to):asAt;let start=from?iso(from):null;if(!start){const day=new Date(end);day.setUTCHours(0,0,0,0);day.setUTCDate(day.getUTCDate()-(day.getUTCDay()+6)%7);start=day.toISOString()}if(Date.parse(start)>Date.parse(end)||Date.parse(end)-Date.parse(start)>93*86400000)fail('Choose a report range of at most 93 days, with start before end.')
 const events=store.events(realm).filter(event=>event.body?.schema==='quotagent/workspace-record/v1'),inRange=event=>Date.parse(event.ts)>=Date.parse(start)&&Date.parse(event.ts)<Date.parse(end),visible=new Set(snapshot.rfqs.map(row=>row.id)),rows=[],seen=new Set(),total={},firstOrders=new Map();for(const event of events){const value=event.body;if(value?.collection==='orders'&&value.record&&!firstOrders.has(value.record.id))firstOrders.set(value.record.id,event.seq)}const add=(event,type,record,amount=null)=>{const key=type+':'+record.id+':'+(record.publishedRevision||record.revision||1);if(seen.has(key))return;seen.add(key);rows.push({type,id:record.id,title:record.title||record.supplierName||record.id,amount,currency:amount===null?null:record.currency,source:reference(realm,event)})}
 for(const event of events.filter(inRange)){const {collection,record}=event.body||{};if(!record)continue;if(collection==='rfqs'&&['procurement/rfq-published','procurement/rfq-amended'].includes(event.type)&&visible.has(record.id)&&role==='contractor')add(event,'published request',record);if(collection==='quotes'&&visible.has(record.rfqId)&&record.status==='submitted'&&(role==='contractor'||record.supplierId===realm))add(event,role==='contractor'?'received quotation':'submitted quotation',record,record.total);if(collection==='orders'&&visible.has(record.rfqId)&&firstOrders.get(record.id)===event.seq&&['issued','acknowledged'].includes(record.status)){const key='order:'+record.id;if(seen.has(key))continue;seen.add(key);add(event,'signed order',record,record.originalTotal??record.total);const value=record.originalTotal??record.total;if(Number.isFinite(value)&&record.currency)total[record.currency]=(total[record.currency]||0)+Math.round(value*100)}}
 const proposed=new Map(),waits=[],unmatched=[];for(const event of events){const row=event.body?.record;if(event.body?.collection!=='review-actions'||!row)continue;const key=row.id+':'+row.inputHash;if(event.type==='actions/proposed')proposed.set(key,event);if(['actions/approved','actions/signed','actions/rejected'].includes(event.type)&&inRange(event)){const origin=proposed.get(key),seconds=origin?(Date.parse(event.ts)-Date.parse(origin.ts))/1000:null;if(seconds===null||seconds<0)unmatched.push(reference(realm,event));else waits.push({id:row.id,seconds,request:reference(realm,origin),decision:reference(realm,event)})}}
 const past={rfqs:new Map(),quotes:new Map(),'quote-status':new Map(),'response-promises':new Map()},pastSources=new Map();for(const event of events){const value=event.body;if(Date.parse(event.ts)>=Date.parse(end)||!value?.record||!past[value.collection])continue;past[value.collection].set(value.record.id,value.record);pastSources.set(value.collection+':'+value.record.id,reference(realm,event))}const pastRfqs=[...past.rfqs.values()].filter(row=>visible.has(row.id)),pastSnapshot={...snapshot,rfqs:pastRfqs,quotes:[...past.quotes.values()].map(row=>({...row,...past['quote-status'].get(row.id),stale:(row.rfqRevision||1)!==revision('rfq',past.rfqs.get(row.rfqId)||{})}))};const overdue=coverage({snapshot:pastSnapshot,realm,role,promises:[...past['response-promises'].values()],asOf:end,minimum}).flatMap(row=>row.people.filter(person=>person.severity==='overdue').map(person=>({rfqId:row.rfqId,title:row.title,supplierId:person.supplierId,dueAt:person.dueAt,source:pastSources.get('rfqs:'+row.rfqId)})))
 return{from:start,to:end,asOf:asAt,realm,rows,published:rows.filter(row=>row.type==='published request').length,quotations:rows.filter(row=>row.type.includes('quotation')).length,orders:rows.filter(row=>row.type==='signed order').length,orderAmounts:Object.fromEntries(Object.entries(total).map(([key,value])=>[key,value/100])),approvalWaitSeconds:waits.length?waits.reduce((sum,row)=>sum+row.seconds,0)/waits.length:null,approvalDecisions:waits,unmatchedDecisions:unmatched,overdue,notice:'Recorded activity from the inclusive start to the exclusive end, using ledger timestamps at one-second precision. Approval waiting uses only this party ledger; decisions in another personal realm are not included. Only the first local recording of a signed order contributes its amount; later acknowledgments and changes do not count it again. Overdue responses reconstruct records strictly before the range end. Currencies stay separate. No payment, savings or physical delivery is inferred. Missing approval matches are excluded; no matched decision means unknown waiting time.'}
}
