import React from 'react'
import { LineChangeTable } from './fulfillment.jsx'
import { PriceBreakdown } from './rfq-lifecycle.jsx'
import { registry, money, date } from '../../../system/webui/client/core.jsx'
function ProcurementProposal({ input }) {
  const preview = input.preview || {}
  return <div className="procurement-proposal-preview"><h3>{preview.title}</h3><p><strong>{preview.label}</strong></p><div className="request-meta"><div><span>Recipient{preview.recipients?.length > 1 ? 's' : ''}</span><strong>{preview.recipients?.map(person => person.name).join(', ')}</strong></div>{typeof preview.amount === 'number' && <div><span>{input.action === 'approve-change' ? 'Price adjustment' : 'Total'}</span><strong>{money(preview.amount, preview.currency)}</strong></div>}{preview.leadDays !== undefined && <div><span>Lead time</span><strong>{preview.leadDays} days</strong></div>}{preview.paymentTerms && <div><span>Payment terms</span><strong>{preview.paymentTerms}</strong></div>}{preview.deadline && <div><span>Deadline</span><strong>{date(preview.deadline)}</strong></div>}</div><PriceBreakdown value={preview.priceBreakdown} currency={preview.currency}/>{preview.text && <div className="message-body" style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere', lineHeight: 1.7, margin: '20px 0' }}>{preview.text}</div>}{preview.description && <p style={{ whiteSpace: 'pre-wrap' }}>{preview.description}</p>}{preview.items?.length > 0 && <div className="table-scroll"><table><thead><tr><th>Item</th><th>Quantity</th>{preview.items.some(item => item.unitPrice !== undefined) && <><th>Unit price</th><th>Total</th></>}</tr></thead><tbody>{preview.items.map(item => <tr key={item.id}><td>{item.description}</td><td>{item.quantity} {item.unit}</td>{item.unitPrice !== undefined && <><td>{money(item.unitPrice, preview.currency)}</td><td>{money(item.total, preview.currency)}</td></>}</tr>)}</tbody></table></div>}{preview.changes?.length > 0 && <><LineChangeTable lines={preview.changes} currency={preview.currency}/><p>Resulting order value: <strong>{money(preview.resultingTotal,preview.currency)}</strong> · Source order revision {preview.orderRevision}</p></>}{Object.keys(preview.commercial || {}).length > 0 && <details><summary>Structured commercial terms</summary><dl>{Object.entries({validityUntil:'Valid until',advancePercent:'Advance (%)',paymentDays:'Payment (days)',warrantyMonths:'Warranty (months)',penaltyPercent:'Penalty (%)',deliveryBinding:'Delivery commitment'}).filter(([key]) => preview.commercial[key] !== undefined).map(([key,label]) => <div key={key}><dt>{label}</dt><dd>{String(preview.commercial[key])}</dd></div>)}</dl>{preview.commercial.deviations?.map((row,i) => <p key={i}>{row.description}{row.priceImpact !== undefined ? ` · Price impact ${money(row.priceImpact,preview.currency)}` : ' · Price impact unstated'}{row.timeImpactDays !== undefined ? ` · ${row.timeImpactDays} days` : ''}</p>)}</details>}{preview.notes && <p><strong>Notes:</strong> {preview.notes}</p>}<p className="muted">Approval applies these reviewed details. If the underlying project or quotation changes, prepare a new review. Supplier costs and internal notes remain private.</p></div>
}
registry.slot('action-preview:procurement.commit', ProcurementProposal)
