import React,{useState} from 'react'
import {useResource,api,Button,Badge,ErrorNotice,money,date} from '../../../system/webui/client/core.jsx'
export function SubmissionBatches({work}){
 const {app,data}=work,resource=useResource('/workspace/submission-batches',{batches:[]}),[selected,setSelected]=useState([]),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const drafts=data.quotes.filter(row=>row.status==='draft'),current=resource.data.batches[0]
 async function prepare(){setBusy(true);setError('');try{const result=await api('/workspace/review-submissions',{method:'POST',body:{quoteIds:selected}});await resource.reload();setSelected([]);app.refresh();app.notify(result.message)}catch(error){setError(error.message)}finally{setBusy(false)}}
 const failed=batch=>batch.quoteIds.filter(id=>batch.items.find(row=>row.quoteId===id)?.status!=='prepared')
 return <section className="card section-space"><div className="section-heading"><div><h2>Prepare several quotations</h2><p>Select your drafts together. Each exact offer gets its own review; submissions happen only after your decisions.</p></div><Button variant="secondary" onClick={()=>setOpen(!open)}>{open?'Close quote selection':'Select quotation drafts'}</Button></div><ErrorNotice error={error||resource.error}/>{open&&<><fieldset className="lifecycle-checkbox-field"><legend>Quotation drafts to prepare</legend>{drafts.length?drafts.map(quote=>{const rfq=data.rfqs.find(row=>row.id===quote.rfqId);return <label className="fulfillment-check" key={quote.id}><input type="checkbox" checked={selected.includes(quote.id)} onChange={event=>setSelected(event.target.checked?[...selected,quote.id]:selected.filter(id=>id!==quote.id))}/><span><strong>{rfq?.title||'Unavailable request'}</strong> · {money(quote.total,quote.currency)} · quote revision {quote.version||1}{quote.stale&&<small>Rebid needed · selection will return a preparation error.</small>}</span></label>}):<p>No quotation drafts yet.</p>}</fieldset><div className="form-actions"><span>{selected.length} selected · up to 50 per preparation</span><Button busy={busy} disabled={!selected.length||selected.length>50} onClick={prepare}>Prepare selected for review</Button></div></>}{current&&<BatchReceipt batch={current} app={app} data={data} onRetry={()=>{setSelected(failed(current));setOpen(true)}}/>}{resource.data.batches.length>1&&<details className="section-space"><summary>Earlier quotation preparations ({resource.data.batches.length-1})</summary>{resource.data.batches.slice(1).map(batch=><BatchReceipt key={batch.id} batch={batch} app={app} data={data} onRetry={()=>{setSelected(failed(batch));setOpen(true)}}/>)}</details>}</section>
}
function BatchReceipt({batch,app,data,onRetry}){
 const prepared=batch.items.filter(row=>row.status==='prepared'),unprepared=batch.quoteIds.length-prepared.length
 return <section className="scope-subcard" aria-label="Quotation preparation receipt"><div className="section-heading"><h3>{prepared.length} of {batch.quoteIds.length} quotations ready for review</h3><Badge>{batch.status}</Badge></div><p>{date(batch.createdAt)} · Nothing is sent by preparation. Each review below shows the exact recipients, price, terms and scope.</p>{batch.items.map(item=><div className="scope-subcard" key={item.quoteId}><strong>{item.title||data.rfqs.find(rfq=>rfq.id===data.quotes.find(quote=>quote.id===item.quoteId)?.rfqId)?.title||batch.quoteIds.indexOf(item.quoteId)+1+'. Selected quotation'}</strong>{item.amount!==undefined&&<span> · {money(item.amount,item.currency)}</span>}<p>{item.status==='failed'?item.error:`Review status: ${item.actionStatus||'pending'}${item.reused?' · existing matching review reused':''}`}</p>{item.status==='failed'&&data.quotes.some(quote=>quote.id===item.quoteId)&&<Button variant="secondary" onClick={()=>app.navigate('quotes',{quoteId:item.quoteId,rfqId:data.quotes.find(quote=>quote.id===item.quoteId).rfqId})}>Open quotation</Button>}{item.actionId&&<Button variant="secondary" onClick={()=>app.navigate('approvals',{actionId:item.actionId})}>Review this quotation</Button>}</div>)}{unprepared>0&&<><p>{unprepared} quotation(s) need attention. Already prepared reviews remain available.</p><Button variant="secondary" onClick={onRetry}>Select unprepared quotations</Button></>}{prepared.length>1&&<Button variant="ghost" onClick={()=>app.navigate('approvals')}>Open review actions for batch decisions</Button>}</section>
}
