import React,{useState} from 'react'
import {Button,Badge,Field,Modal,ErrorNotice} from '../../../system/webui/client/core.jsx'
import {EditConflict} from './edit-conflict.jsx'
const families=['payment','warranty','penalty','acceptance','delivery','scope','other']
export function TermsEditor({form,setForm}){
 const rows=form.terms||[],set=terms=>setForm(current=>({...current,terms})),edit=(index,key,value)=>set(rows.map((row,i)=>i===index?{...row,[key]:value}:row))
 return <details className="scope-editor"><summary>Declared contract terms · {rows.length}</summary><p className="muted">State requirements or offered terms explicitly. New drafts also receive missing keys from your private library defaults. Existing documents retain their authored values.</p>{rows.map((row,index)=><div className="scope-subcard" key={index}><div className="form-grid"><Field label={`Term ${index+1} key`} hint="Use the same key on required and offered terms."><input value={row.key} onChange={e=>edit(index,'key',e.target.value)}/></Field><Field label={`Term ${index+1} family`}><select value={row.family} onChange={e=>edit(index,'family',e.target.value)}>{families.map(value=><option key={value}>{value}</option>)}</select></Field></div><Field label={`Term ${index+1} label`}><input value={row.label} onChange={e=>edit(index,'label',e.target.value)}/></Field><Field label={`Term ${index+1} declaration`}><textarea rows={2} value={row.text} onChange={e=>edit(index,'text',e.target.value)}/></Field><Button variant="ghost" onClick={()=>set(rows.filter((_,i)=>i!==index))}>Remove declaration</Button></div>)}<Button variant="secondary" onClick={()=>set([...rows,{key:'',family:'other',label:'',text:''}])}>Add term declaration</Button></details>
}
export function DeclaredTerms({record,label='Declared terms'}){return record.terms?.length?<details className="scope-editor" open><summary>{label}</summary>{record.terms.map(row=><div className="scope-subcard" key={row.key}><strong>{row.label}</strong><small> · {row.family} · {row.key}</small><p>{row.text}</p></div>)}</details>:null}
export function TermLibrary({work,onClose}){
 const {data,run}=work,empty={key:'',label:'',family:'other',text:'',defaultFor:'none'},[form,setForm]=useState(empty),[busy,setBusy]=useState(false),[error,setError]=useState('')
 async function save(e){e.preventDefault();setBusy(true);setError('');try{await run('save-term',form);setForm(empty)}catch(e){setError(e)}finally{setBusy(false)}}
 return <Modal title="Your private term library" wide onClose={onClose} description="Versioned starting declarations for your party. A revised entry never rewrites an existing request or offer."><div className="scope-library"><section><h3>Saved entries</h3>{(data.termLibrary||[]).map(row=><article className="scope-subcard" key={row.id}><strong>{row.label}</strong> <Badge>{row.active?'Active':'Archived'} · v{row.revision}</Badge><p>{row.text}</p><small>{row.key} · {row.family} · Default for {row.defaultFor}</small><div className="row-actions"><Button variant="ghost" onClick={()=>{setForm({...row,expectedRevision:row.revision});setError('')}}>Revise entry</Button>{row.active&&<Button variant="ghost" onClick={()=>run('archive-term',{id:row.id,expectedRevision:row.revision}).catch(e=>setError(e))}>Archive entry</Button>}</div><details><summary>Version history</summary>{(data.termVersions||[]).filter(version=>version.termId===row.id).sort((a,b)=>b.revision-a.revision).map(version=><p key={version.id}>v{version.revision} · {version.text}</p>)}</details></article>)}</section><form onSubmit={save}><h3>{form.id?'Revise declaration':'New declaration'}</h3><EditConflict error={error} onContinue={revision=>{setForm(current=>({...current,expectedRevision:revision}));setError('')}}/>{[['key','Term key'],['label','Term label']].map(([key,label])=><Field key={key} label={label}><input required value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></Field>)}<Field label="Term family"><select value={form.family} onChange={e=>setForm({...form,family:e.target.value})}>{families.map(value=><option key={value}>{value}</option>)}</select></Field><Field label="Term text"><textarea required rows={4} value={form.text} onChange={e=>setForm({...form,text:e.target.value})}/></Field><Field label="Default for new drafts"><select value={form.defaultFor} onChange={e=>setForm({...form,defaultFor:e.target.value})}><option value="none">Manual use</option><option value="request">Requests</option><option value="quote">Quotations</option><option value="both">Both</option></select></Field><div className="form-actions"><Button variant="ghost" onClick={()=>setForm(empty)}>Clear editor</Button><Button busy={busy} type="submit">Save term version</Button></div></form></div></Modal>
}
export function TermDifferences({work,quote,rfq}){
 const conflicts=(work.data.termConflicts||[]).filter(row=>row.quoteId===quote.id),[open,setOpen]=useState(false)
 if(!conflicts.length)return null
 return <div className="scope-editor"><strong>{conflicts.length} required / offered term difference{conflicts.length===1?'':'s'}</strong>{conflicts.map(row=><div className="scope-subcard" key={row.key}><strong>{row.label}</strong><div className="form-grid"><p><small>Required</small><br/>{row.required??'Not declared'}</p><p><small>Offered</small><br/>{row.offered??'Not declared'}</p></div><Badge status={row.decision?.resolution==='accept-offer'?'success':'warning'}>{row.decision?.resolution==='accept-offer'?'Offered exception accepted':row.decision?.resolution==='require-revision'?'Revised quote required':'Human decision needed'}</Badge>{row.decision&&<p>{row.decision.reason}</p>}</div>)}{work.app.user.role==='contractor'&&rfq.status==='published'&&<Button variant="secondary" onClick={()=>setOpen(true)}>Review term differences</Button>}{open&&<TermDecisionForm work={work} quote={quote} rfq={rfq} conflicts={conflicts} onClose={()=>setOpen(false)}/>}</div>
}
function TermDecisionForm({work,quote,rfq,conflicts,onClose}){
 const [decisions,setDecisions]=useState(conflicts.map(row=>({key:row.key,resolution:row.decision?.resolution||'',reason:row.decision?.reason||''}))),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 async function save(e){e.preventDefault();if(!review){setReview(true);return}setBusy(true);try{await work.run('resolve-terms',{quoteId:quote.id,quoteRevision:quote.revision,rfqRevision:rfq.publishedRevision,decisions,confirmed:true});onClose()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <Modal title={review?'Confirm term decisions':'Review term differences'} wide onClose={onClose} description={`Request revision ${rfq.publishedRevision} · quote revision ${quote.revision}. Original declarations remain unchanged.`}><form onSubmit={save}><ErrorNotice error={error}/>{conflicts.map((row,index)=><section className="scope-subcard" key={row.key}><h3>{row.label}</h3><div className="form-grid"><p><small>Required</small><br/>{row.required??'Not declared'}</p><p><small>Offered</small><br/>{row.offered??'Not declared'}</p></div><Field label={`Decision for ${row.label}`}><select required disabled={review} value={decisions[index].resolution} onChange={e=>setDecisions(values=>values.map((value,i)=>i===index?{...value,resolution:e.target.value}:value))}><option value="">Choose explicitly</option><option value="accept-offer">Accept offered exception</option><option value="require-revision">Require revised quotation</option></select></Field><Field label={`Reason for ${row.label}`}><textarea required readOnly={review} value={decisions[index].reason} onChange={e=>setDecisions(values=>values.map((value,i)=>i===index?{...value,reason:e.target.value}:value))}/></Field></section>)}<p className="muted">An accepted exception is tied to these revisions. A changed offer requires a new decision. This step does not award or issue an order.</p><div className="form-actions"><Button variant="secondary" onClick={review?()=>setReview(false):onClose}>{review?'Edit decisions':'Cancel'}</Button><Button busy={busy} type="submit">{review?'Confirm decisions':'Review decisions'}</Button></div></form></Modal>
}

export function TermExceptions({record}){return record.termExceptions?.length?<details className="scope-editor" open><summary>Accepted term exceptions</summary>{record.termExceptions.map(row=><section className="scope-subcard" key={row.key}><strong>{row.label}</strong><p>Required: {row.required??'Not declared'}<br/>Offered: {row.offered??'Not declared'}</p><p>{row.reason}</p><small>Human decision {row.decisionId} · request revision {row.rfqRevision} · quote revision {row.quoteRevision}</small></section>)}</details>:null}
