import React,{useEffect,useState} from 'react'
import {registry,useApp,useResource,api,Icon,Button,Badge,Field,PageHeader,Modal,Empty,ErrorNotice,Loading} from '../../webui/client/core.jsx'
import './workroom.css'
const labels={running:'Working',queued:'Ready to start','awaiting-plan':'Review plan','waiting-input':'Needs your input',paused:'Paused',completed:'Complete',cancelled:'Cancelled',failed:'Needs attention'}
const time=value=>value?new Date(value).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',second:'2-digit'}):''
const tone=status=>status==='completed'?'success':['awaiting-plan','waiting-input','failed','paused'].includes(status)?'warning':status==='running'?'accent':'neutral'
const active=status=>['running','awaiting-plan','waiting-input','paused','failed'].includes(status)
function State({status}){return <Badge status={tone(status)}>{status==='running'&&<span className="workroom-live-dot"/>}{labels[status]||status}</Badge>}
function Inline({text}){return String(text||'').split(/(\*\*[^*]+\*\*|`[^`]+`)/g).map((part,index)=>part.startsWith('**')?<strong key={index}>{part.slice(2,-2)}</strong>:part.startsWith('`')?<code key={index}>{part.slice(1,-1)}</code>:part)}
function Report({text}){
 const lines=String(text||'').split('\n'),output=[]
 const cells=line=>line.trim().replace(/^\||\|$/g,'').split('|').map(value=>value.trim())
 for(let index=0;index<lines.length;index++){
  const line=lines[index]
  if(line.includes('|')&&/^[\s|:\-]+$/.test(lines[index+1]||'')&&/-{2,}/.test(lines[index+1]||'')){
   const headers=cells(line),rows=[];index+=2
   while(index<lines.length&&lines[index].includes('|')&&lines[index].trim()){rows.push(cells(lines[index]));index++}index--
   output.push(<div className="workroom-report-table" key={index}><table><thead><tr>{headers.map((value,i)=><th key={i}><Inline text={value}/></th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((value,j)=><td key={j}><Inline text={value}/></td>)}</tr>)}</tbody></table></div>);continue
  }
  if(/^#{1,4}\s/.test(line))output.push(<h3 key={index}><Inline text={line.replace(/^#{1,4}\s/,'')}/></h3>)
  else if(/^[-*]\s/.test(line))output.push(<div className="workroom-report-bullet" key={index}><span>•</span><div><Inline text={line.slice(2)}/></div></div>)
  else if(/^---+$/.test(line))output.push(<hr key={index}/>)
  else output.push(line?<p key={index}><Inline text={line}/></p>:<div className="workroom-report-space" key={index}/>)
 }
 return <div className="workroom-report">{output}</div>
}
function Workroom(){
 const app=useApp(),resource=useResource('/workflows',{runs:[],memory:[],defaults:{reviewPlan:true}})
 const [tab,setTab]=useState(app.context.tab==='memory'?'memory':'runs'),[selected,setSelected]=useState(app.context.runId||''),[creating,setCreating]=useState(false)
 useEffect(()=>{if(app.context.runId){setSelected(app.context.runId);setTab('runs')}else if(app.context.tab==='memory')setTab('memory')},[app.context.runId,app.context.tab])
 return <><PageHeader eyebrow="YOUR AGENT TEAM" title="A clear path through complex work." actions={<Button icon="plus" onClick={()=>setCreating(true)}>New agent run</Button>}>Give the team an outcome. Review its plan, follow each specialist’s work, and step in when your judgment is needed.</PageHeader><div className="tabs workroom-tabs"><button className={tab==='runs'?'active':''} onClick={()=>setTab('runs')}>Agent runs <span>{resource.data.runs.length}</span></button><button className={tab==='memory'?'active':''} onClick={()=>setTab('memory')}>Account memory <span>{resource.data.memory.length}</span></button></div><ErrorNotice error={resource.error} retry={resource.reload}/>{tab==='memory'?<MemoryPanel/>:selected?<RunDetail key={selected} id={selected} onBack={()=>{setSelected('');resource.reload()}}/>:resource.loading?<Loading/>:<><section className="workroom-intro card"><span className="workroom-team-icon"><Icon name="users" size={30}/></span><div><h2>Specialists work together. You stay in control.</h2><p>A planner divides the work. Independent agents investigate in parallel. A coordinator brings the evidence into a decision brief. Questions and proposed actions wait for your review.</p><div className="workroom-capabilities"><span><Icon name="check" size={14}/> Visible plans and task states</span><span><Icon name="clock" size={14}/> Pause and resume</span><span><Icon name="shield" size={14}/> Account-scoped context</span></div></div></section>{resource.data.runs.length?<div className="workroom-run-list">{resource.data.runs.map(run=><button className="card workroom-run-card" key={run.id} onClick={()=>setSelected(run.id)}><div className="workroom-run-icon"><Icon name="users"/></div><div><div className="workroom-run-card-heading"><h3>{run.title}</h3><State status={run.status}/></div><p>{run.objective}</p><div className="workroom-run-meta"><span>{run.steps.filter(step=>step.status==='completed').length}/{run.steps.length} tasks complete</span><span>{time(run.createdAt)}</span>{run.question&&<span className="workroom-needs-input">Your input is needed</span>}</div></div><Icon name="chevron" size={18}/></button>)}</div>:<Empty icon="users" title="Give your next complicated task to a team" action={<Button onClick={()=>setCreating(true)}>Plan my first task</Button>}>For example: compare the complete scope, commercial terms and delivery risks across received quotations, then prepare a negotiation brief.</Empty>}</>}{creating&&<NewRun defaults={resource.data.defaults} close={()=>setCreating(false)} started={run=>{setCreating(false);setSelected(run.id);setTab('runs');app.refresh()}}/>}</>
}
function NewRun({defaults,close,started}){
 const app=useApp(),workspace=useResource('/workspace',{rfqs:[]}),[objective,setObjective]=useState(''),[rfqId,setRfqId]=useState(app.context.rfqId||''),[checkpoint,setCheckpoint]=useState(defaults?.reviewPlan!==false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const example=app.user.role==='supplier'?'Review my open RFQs, check scope and pricing gaps, assess delivery and payment risks, then prepare a clear quote-readiness and clarification brief. Ask me before assuming prices or commercial terms.':'Compare the scope, pricing, payment and delivery risks of my received quotations. Have separate specialists check completeness and commercial risk, then prepare a recommendation and negotiation brief. Keep the award decision open.'
 async function submit(event){event.preventDefault();setBusy(true);setError('');try{const result=await api('/workflows',{method:'POST',body:{objective,rfqId,checkpoint}});started(result.run)}catch(error){setError(error.message)}finally{setBusy(false)}}
 return <Modal title="Give your agent team an outcome" description="A real planner will propose specialist tasks based on your request and the records your account can access." wide onClose={close}><form onSubmit={submit}><ErrorNotice error={error}/><Field label="What should the team achieve?" hint="Include the decision you need, important constraints, and anything the agents should ask you before assuming."><textarea aria-label="Agent team objective" rows={6} required value={objective} onChange={event=>setObjective(event.target.value)} placeholder={example}/></Field><button type="button" className="text-button" onClick={()=>setObjective(example)}>Use this example <Icon name="arrow" size={14}/></button>{workspace.data.rfqs?.length>0&&<Field label="Focus on a request (optional)" className="section-space"><select aria-label="Focus on a request (optional)" value={rfqId} onChange={event=>setRfqId(event.target.value)}><option value="">Consider my workspace</option>{workspace.data.rfqs.map(rfq=><option key={rfq.id} value={rfq.id}>{rfq.title}</option>)}</select></Field>}<label className="workroom-check"><input type="checkbox" checked={checkpoint} onChange={event=>setCheckpoint(event.target.checked)}/><span><strong>Review the plan before specialists start</strong><small>You can add feedback, approve the plan, or cancel. Outbound commitments always require a separate approval.</small></span></label><div className="form-actions"><Button variant="secondary" onClick={close}>Cancel</Button><Button type="submit" icon="spark" busy={busy}>Create agent plan</Button></div></form></Modal>
}
function RunDetail({id,onBack}){
 const app=useApp(),resource=useResource(`/workflows/${encodeURIComponent(id)}`,{run:null}),[busy,setBusy]=useState(''),[error,setError]=useState(''),[answer,setAnswer]=useState(''),[feedback,setFeedback]=useState(''),[selectedTrace,setSelectedTrace]=useState(null),[memory,setMemory]=useState(null)
 const run=resource.data.run
 useEffect(()=>{if(run?.status!=='running')return;const timer=setInterval(resource.reload,1500);return()=>clearInterval(timer)},[run?.status,resource.reload])
 async function control(action,text){setBusy(action);setError('');try{await api(`/workflows/${id}/control`,{method:'POST',body:{action,text}});setAnswer('');setFeedback('');await resource.reload();app.refresh()}catch(error){setError(error.message)}finally{setBusy('')}}
 if(resource.loading&&!run)return <Loading/>
 if(!run)return <ErrorNotice error={resource.error} retry={resource.reload}/>
 const done=run.steps.filter(step=>step.status==='completed').length
 const actions=run.traces.flatMap(trace=>{const result=trace.details?.result?.data||trace.details?.result;return result?.actions || (result?.action?[result.action]:[])})
 const actionClick=action=>{const input=action.input||{};if(input.view)app.navigate(input.view,input);else app.navigate('approvals')}
 return <><button className="text-button workroom-back" onClick={onBack}>← All agent runs</button><section className="card workroom-run-summary"><div className="section-heading"><div><div className="eyebrow">{run.phase==='plan'?'PLANNING YOUR WORK':run.phase==='synthesis'?'BRINGING THE FINDINGS TOGETHER':'AGENT RUN'}</div><h2>{run.title}</h2></div><State status={run.status}/></div><p className="workroom-objective">{run.objective}</p><div className="workroom-run-meta"><span>{done}/{run.steps.length} tasks complete</span><span>Started {time(run.createdAt)}</span><span>Last update {time(run.updatedAt)}</span></div>{run.steps.length>0&&<div className="workroom-progress" aria-label={`${done} of ${run.steps.length} tasks complete`}><span style={{width:`${done/run.steps.length*100}%`}}/></div>}<div className="workroom-run-controls">{run.status==='running'&&<Button variant="secondary" icon="clock" busy={busy==='pause'} onClick={()=>control('pause')}>Pause run</Button>}{['paused','failed'].includes(run.status)&&<Button icon="arrow" busy={busy==='resume'} onClick={()=>control('resume')}>Resume run</Button>}{active(run.status)&&<Button variant="ghost" busy={busy==='cancel'} onClick={()=>control('cancel')}>Cancel run</Button>}<button className="text-button" onClick={resource.reload}>Refresh status</button></div><ErrorNotice error={error||resource.error||run.error}/></section>
 {run.question&&run.status!=='cancelled'&&<section className="card workroom-checkpoint" aria-label="Human checkpoint"><span className="workroom-checkpoint-icon"><Icon name="chat" size={24}/></span><div><div className="eyebrow">YOUR JUDGMENT MATTERS</div><h2>{run.status==='awaiting-plan'?'Your plan is ready to review':run.status==='waiting-input'?'A specialist needs your input':'Ready when you are'}</h2><p>{run.question.text}</p>{run.question.reason&&<p className="muted">{run.question.reason}</p>}{['awaiting-plan','waiting-input'].includes(run.status)&&<form onSubmit={event=>{event.preventDefault();control(run.status==='awaiting-plan'?'resume':'answer',answer)}}><Field label={run.status==='awaiting-plan'?'Priorities or changes (optional)':'Your answer'}><textarea rows={3} aria-label="Human checkpoint response" value={answer} required={run.status==='waiting-input'} onChange={event=>setAnswer(event.target.value)} placeholder={run.status==='awaiting-plan'?'Add constraints or corrections before the team starts…':'Give the missing fact, your decision, or guidance…'}/></Field><Button type="submit" icon="check" busy={busy==='resume'||busy==='answer'}>{run.status==='awaiting-plan'?'Approve plan & start agents':'Send answer & resume'}</Button></form>}</div></section>}
 {run.planSummary&&<div className="workroom-plan-summary"><h3>The plan</h3><p>{run.planSummary}</p><span>Up to {run.parallelism||3} independent specialists can work at the same time.</span></div>}
 {run.steps.length>0&&<div className="workroom-steps">{run.steps.map((step,index)=><article className={`card workroom-step ${step.status==='running'?'is-working':''}`} key={step.id}><div className="section-heading"><span className="workroom-step-number">{String(index+1).padStart(2,'0')}</span><State status={step.status}/></div><div className="eyebrow">{step.role}</div><h3>{step.title}</h3><p>{step.task}</p>{step.dependsOn.length>0&&<div className="workroom-dependencies">After {step.dependsOn.map(id=>run.steps.find(candidate=>candidate.id===id)?.title||id).join(', ')}</div>}{step.startedAt&&<small>{time(step.startedAt)}{step.completedAt?` → ${time(step.completedAt)}`:' · Separate agent context'}</small>}{step.error&&<ErrorNotice error={step.error}/>}<details open={run.steps.length<3&&!!step.output}><summary>{step.output?'Read specialist report':'Task context'}</summary>{step.output?<Report text={step.output}/>:<p className="muted">{step.status==='running'?'This specialist is using its own model conversation, the shared objective, permitted tools and any completed prerequisite reports.':'This task will use its own conversation and only the prerequisite reports listed above.'}</p>}</details></article>)}</div>}
 {run.result&&<section className="card workroom-result"><div className="section-heading"><div><div className="eyebrow">YOUR DECISION BRIEF</div><h2>The team’s findings</h2></div><Badge status="success">Synthesized from {run.steps.length} specialist reports</Badge></div><Report text={run.result}/>{actions.length>0&&<div className="workroom-result-actions">{actions.map((action,index)=><Button key={index} variant="secondary" onClick={()=>actionClick(action)}>{action.label||'Review proposed action'}</Button>)}</div>}<div className="form-actions"><Button variant="secondary" icon="file" onClick={()=>setMemory({key:run.title,value:'',source:{kind:'workflow',runId:run.id,reference:run.title}})}>Save a takeaway to memory</Button></div></section>}
 {active(run.status)&&run.status!=='awaiting-plan'&&run.status!=='waiting-input'&&<details className="card workroom-feedback"><summary>Add guidance for the team</summary><form onSubmit={event=>{event.preventDefault();control('feedback',feedback)}}><Field label="Feedback for unfinished work"><textarea aria-label="Feedback for unfinished work" value={feedback} onChange={event=>setFeedback(event.target.value)} required rows={3} placeholder="Change priorities or correct a fact. Completed reports stay visible; unfinished agents receive your guidance."/></Field><Button type="submit" busy={busy==='feedback'}>Send feedback & resume</Button></form></details>}
 <section className="card workroom-traces"><div className="section-heading"><div><h2>Activity & evidence</h2><p>Recorded plans, tool results, human input and outputs. Private model reasoning is never displayed.</p></div><Badge>{run.traces.length} records</Badge></div><div className="workroom-trace-list">{run.traces.map(trace=><button key={trace.id} onClick={()=>setSelectedTrace(trace)}><span className={`workroom-trace-dot trace-${trace.event}`}/><div><strong>{trace.event.replaceAll('-',' ')}</strong><p>{trace.summary}</p><small>{trace.stepId?run.steps.find(step=>step.id===trace.stepId)?.role||trace.agentId:trace.agentId||'You'} · {time(trace.at)}</small></div><Icon name="chevron" size={15}/></button>)}</div></section>
 {run.context&&<details className="card workroom-context"><summary>Inspect the context and memory used for planning</summary><p>Captured {time(run.context.capturedAt)}. Each specialist also receives current tool results and explicit human feedback. Source content is evidence; it cannot grant permission to act.</p><h3>Memory at planning time</h3>{run.context.memory?.length?run.context.memory.map(entry=><div className="workroom-context-memory" key={entry.id}><strong>{entry.key}</strong><p>{entry.value}</p><small>{entry.source?.kind} · revision {entry.revision}</small></div>):<p className="muted">No active account memory was present.</p>}<details><summary>Recorded account evidence</summary><pre>{JSON.stringify(run.context.workspace,null,2)}</pre></details></details>}
 {selectedTrace&&<Modal title={selectedTrace.event.replaceAll('-',' ')} description={`${time(selectedTrace.at)} · ${selectedTrace.agentId||'Human control'}`} wide onClose={()=>setSelectedTrace(null)}><Report text={selectedTrace.summary}/>{selectedTrace.details&&<details className="workroom-trace-json"><summary>Inspect recorded input and output</summary><pre>{JSON.stringify(selectedTrace.details,null,2)}</pre></details>}<div className="form-actions"><Button variant="secondary" onClick={()=>setSelectedTrace(null)}>Close</Button></div></Modal>}
 {memory&&<MemoryEditor entry={memory} close={()=>setMemory(null)} saved={()=>{setMemory(null);app.refresh()}}/>}
 </>
}
function MemoryPanel(){
 const app=useApp(),resource=useResource('/memory',{memories:[],archived:[]}),[editing,setEditing]=useState(null),[archived,setArchived]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState('')
 async function archive(entry){setBusy(entry.id);setError('');try{await api(`/memory/${entry.id}`,{method:'DELETE'});await resource.reload();app.refresh();app.notify('Memory archived. It will no longer be supplied to agents.')}catch(error){setError(error.message)}finally{setBusy('')}}
 const rows=archived?resource.data.archived:resource.data.memories
 return <><section className="card workroom-memory-intro"><div><h2>Remembered deliberately. Always editable.</h2><p>Agents use these reviewed facts and preferences in future conversations and tasks. Model suggestions wait for approval; source text cannot silently become a preference.</p></div><Button icon="plus" onClick={()=>setEditing({key:'',value:''})}>Add memory</Button></section><ErrorNotice error={error||resource.error}/><div className="filter-tabs workroom-memory-filter"><button className={!archived?'active':''} onClick={()=>setArchived(false)}>Active <span>{resource.data.memories.length}</span></button><button className={archived?'active':''} onClick={()=>setArchived(true)}>Archived <span>{resource.data.archived.length}</span></button></div>{resource.loading?<Loading/>:rows.length?<div className="workroom-memory-grid">{rows.map(entry=><article className="card workroom-memory-card" key={entry.id}><div className="section-heading"><Icon name="file" size={21}/><Badge>{archived?'Archived':`Revision ${entry.revision}`}</Badge></div><h3>{entry.key}</h3><p className="workroom-memory-value">{entry.value}</p><div className="workroom-memory-source"><span>{entry.source?.kind==='legacy-preference'?'Imported account preference':entry.source?.kind==='human'?'Added or edited by you':entry.source?.approvalId?'Reviewed model suggestion':'Saved from an agent run'}</span><small>{entry.source?.reference||entry.source?.evidence||'Explicit account memory'} · {time(entry.updatedAt)}</small></div>{entry.history?.length>0&&<details><summary>Previous revisions ({entry.history.length})</summary>{entry.history.map(version=><div className="workroom-memory-history" key={version.revision}><strong>{version.key} · revision {version.revision}</strong><p>{version.value}</p><small>{version.source?.kind} · {time(version.updatedAt)}</small></div>)}</details>}<div className="workroom-memory-actions"><Button variant="secondary" onClick={()=>setEditing(entry)}>{archived?'Edit & restore':'Edit memory'}</Button>{!archived&&<Button variant="ghost" busy={busy===entry.id} onClick={()=>archive(entry)}>Archive</Button>}{entry.source?.runId&&<button className="text-button" onClick={()=>app.navigate('workroom',{runId:entry.source.runId})}>Source run <Icon name="arrow" size={14}/></button>}</div></article>)}</div>:<Empty icon="file" title={archived?'No archived memories':'No active memories yet'}>Add a preference or useful fact explicitly. Your changes and their history remain visible here.</Empty>}{editing&&<MemoryEditor entry={editing} close={()=>setEditing(null)} saved={()=>{setEditing(null);resource.reload();app.refresh()}}/>}</>
}
function MemoryEditor({entry,close,saved}){
 const [key,setKey]=useState(entry.key||''),[value,setValue]=useState(entry.value||''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 async function submit(event){event.preventDefault();setBusy(true);setError('');try{await api('/memory',{method:'POST',body:{id:entry.id,key,value,source:entry.source}});saved()}catch(error){setError(error.message)}finally{setBusy(false)}}
 return <Modal title={entry.id?'Edit account memory':'Add account memory'} description="This becomes an explicit, active account memory. Keep facts specific and record only what you want future agents to use." onClose={close}><form onSubmit={submit}><ErrorNotice error={error}/><Field label="Memory name"><input aria-label="Memory name" value={key} onChange={event=>setKey(event.target.value)} required maxLength={120} placeholder="Preferred payment terms"/></Field><Field label="Fact or preference"><textarea aria-label="Fact or preference" rows={6} value={value} onChange={event=>setValue(event.target.value)} required maxLength={5000} placeholder="Prefer net 30 terms; flag full prepayment for review."/></Field>{entry.source?.reference&&<p className="muted">Source: {entry.source.reference}</p>}<div className="form-actions"><Button variant="secondary" onClick={close}>Cancel</Button><Button type="submit" busy={busy}>Save memory</Button></div></form></Modal>
}
registry.page('workroom',{component:Workroom,icon:'users'})

function AccountMemoryCard(){
 const app=useApp(),resource=useResource('/memory',{memories:[],archived:[]})
 return <section className="card workroom-account-memory"><div className="section-heading"><div><h2>Account memory</h2><p>Reviewed facts and preferences your agents can use.</p></div><Badge>{resource.data.memories.length} active</Badge></div><ErrorNotice error={resource.error} retry={resource.reload}/>{resource.loading?<Loading/>:resource.data.memories.length?<dl className="preference-list">{resource.data.memories.slice(0,3).map(entry=><div key={entry.id}><dt>{entry.key}</dt><dd>{entry.value}</dd></div>)}</dl>:<p className="muted">No active memories. Add one explicitly or ask your assistant to suggest a memory for review.</p>}<Button variant="secondary" icon="file" onClick={()=>app.navigate('workroom',{tab:'memory'})}>Manage memory</Button></section>
}
registry.slot('account:memory',AccountMemoryCard,{navigation:'workroom'})
