import React,{useState} from 'react'
import {registry,useApp,useResource,api,Button,Field,Modal,ErrorNotice,Loading,Badge} from '../../webui/client/core.jsx'
import './mail.css'
function DeliveryEmail({delivery,direction,close}){
 const app=useApp(),[open,setOpen]=useState(false),[to,setTo]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 if(direction==='inbox'&&!delivery.receipt)return null
 async function draft(event){event.preventDefault();setBusy(true);try{const result=await api(`/exchange/${delivery.id}/mail-draft`,{method:'POST',body:{to:to.split(/[,;\n]/).map(value=>value.trim()).filter(Boolean),direction}});setOpen(false);close?.();app.navigate('mail',result.action.input);app.refresh()}catch(error){setError(error.message)}finally{setBusy(false)}}
 return <><Button variant="secondary" disabled={app.user.permissions?.includes('workspace:read-only')} onClick={()=>setOpen(true)}>{direction==='inbox'?'Email signed receipt':'Prepare email delivery'}</Button>{open&&<Modal title="Email original signed exchange" onClose={()=>setOpen(false)}><form className="qep-mail-stack" onSubmit={draft}><p>Attach the exact original signed {direction==='inbox'?'receipt':'package'} with a readable summary. You can edit the email and review its recipients before sending.</p><Field label="Recipient email addresses"><input autoFocus required value={to} onChange={event=>setTo(event.target.value)} placeholder="partner@example.com"/></Field><ErrorNotice error={error}/><div className="form-actions"><Button variant="secondary" onClick={()=>setOpen(false)}>Cancel</Button><Button type="submit" busy={busy}>Create private email draft</Button></div><small>Mail-server acceptance will not mark the QEP exchange delivered. A signed recipient receipt is still required.</small></form></Modal>}</>
}
function AttachmentExchange({message,file}){
 const app=useApp(),[open,setOpen]=useState(false),[preview,setPreview]=useState(null),[imported,setImported]=useState(null),[busy,setBusy]=useState(''),[error,setError]=useState('')
 if(!/\.qep\.json$/i.test(file.filename))return null
 const task=async(kind,fn)=>{setBusy(kind);setError('');try{return await fn()}catch(error){setError(error.message)}finally{setBusy('')}}
 async function inspect(){setOpen(true);setPreview(null);setImported(null);await task('preview',async()=>setPreview(await api('/exchange/mail/preview',{method:'POST',body:{messageId:message.id,fileId:file.id}})))}
 async function importNow(){await task('import',async()=>{setImported(await api('/exchange/mail/import',{method:'POST',body:{messageId:message.id,fileId:file.id,fileSha256:preview.fileSha256,confirmed:true}}));app.refresh()})}
 async function reply(){await task('reply',async()=>{const result=await api(`/exchange/mail/${imported.record.id}/reply`,{method:'POST',body:{}});setOpen(false);app.navigate('mail',result.action.input);app.refresh()})}
 return <><Button variant="secondary" disabled={app.user.permissions?.includes('workspace:read-only')} onClick={inspect}>Preview signed exchange</Button>{open&&<Modal title="Review signed email attachment" onClose={()=>setOpen(false)} wide><div className="qep-mail-stack"><ErrorNotice error={error}/>{busy==='preview'?<Loading/>:preview&&<><Badge status="success">Pairing and signatures verified</Badge><p>{preview.note}</p><p><strong>{preview.filename}</strong> · workspace {preview.workspaceId}</p><small className="qep-mail-hash">Attachment SHA256: {preview.fileSha256}</small>{preview.packages.map(item=><section className="qep-mail-package" key={item.msgId}><strong>{item.title}</strong><p>{item.from} → {item.to} · {item.eventClass} · sequence {item.seq}</p><small className="qep-mail-hash">Message {item.msgId}<br/>{item.bodyHash}</small></section>)}{!imported?<Button busy={busy==='import'} disabled={!!busy} onClick={importNow}>Import verified package</Button>:<><h3>Import results</h3>{imported.record.results.map((item,i)=><p key={i}><Badge status={item.status==='applied'?'success':'neutral'}>{item.status}</Badge> {item.id}{item.released.length>0?` · ${item.released.length} held message(s) advanced`:''}</p>)}<p>Conflicts and held messages remain in Deliveries & exchange. Import does not sign a new agreement.</p><div className="form-actions"><Button variant="secondary" onClick={()=>{setOpen(false);app.navigate('exchange')}}>Open deliveries</Button>{imported.replyAvailable&&<Button busy={busy==='reply'} disabled={!!busy} onClick={reply}>Prepare receipt or recovery reply</Button>}</div><small>Replying creates a private draft. Review and approve it in Email before anything is sent.</small></>}</>}</div></Modal>}</>
}
function MailExchangeState({message}){
 const app=useApp(),resource=useResource('/exchange/mail/state',{records:[]}),rows=resource.data.records.filter(row=>row.mailId===message.id||row.deliveryReports?.some(report=>report.messageId===message.id))
 if(!rows.length)return null
 return <section className="qep-mail-stack qep-mail-status"><h3>Signed exchange delivery</h3>{rows.map(row=><div key={row.id}><p><strong>Email: {row.mailStatus}</strong></p>{row.qep.map(item=><p key={item.msgId}><span>QEP: <Badge status={item.status==='delivered'?'success':'neutral'}>{item.status}</Badge></span> <small className="qep-mail-hash">{item.msgId}</small></p>)}{row.deliveryReports.map(report=><div key={report.messageId}>{report.reports.map((item,i)=><p className="qep-mail-warning" key={i}>Reported {item.action}: {item.recipient} · {item.status} · {item.diagnostic}</p>)}<Button variant="ghost" onClick={()=>app.navigate('mail',{messageId:report.messageId})}>Read original delivery report</Button></div>)}</div>)}<small>SMTP acceptance and external delivery reports are separate from the paired recipient’s signed QEP receipt. No automatic resend.</small></section>
}
registry.slot('exchange:delivery-action:qep-mail',DeliveryEmail)
registry.slot('mail:attachment-action:qep-mail',AttachmentExchange)
registry.slot('mail:message-action:qep-mail',MailExchangeState)
