// Product composition: plugin-owned components register into the generic WebUI shell.
import '../src/system/accounts/client/accounts.jsx'
import '../src/system/plugin-manager/client/manager.jsx'
import '../src/system/settings/client/settings.jsx'
import '../src/domain/procurement/client/procurement.jsx'
import '../src/system/agent-runtime/client/assistant.jsx'
import '../src/system/agent-runtime/client/usage.jsx'
import '../src/system/plugin-studio/client/studio.jsx'
import '../src/domain/ingestion/client/ingestion.jsx'
import '../src/system/action-center/client/actions.jsx'
import '../src/system/notifications/client/notifications.jsx'
import '../src/system/mail/client/mail.jsx'
import '../src/system/telegram/client/telegram.jsx'
import '../src/system/agent-connections/client/connections.jsx'
import '../src/system/agent-workflows/client/workroom.jsx'
import '../src/system/workspace-styles/client/styles.jsx'
import '../src/system/user-guide/client/guide.jsx'
import '../src/system/installed-plugins/client/installed.jsx'
import '../src/system/teams/client/teams.jsx'
import { mountApp } from '../src/system/webui/client/core.jsx'
mountApp()
