import {randomUUID,createHash} from 'node:crypto'
import {createTransport} from './product-transport.mjs'
export const name='mail-digest'
export const inject=['store','web','accounts','settings','notifications']
export const provides=['mailDigest']
const hash=value=>createHash('sha256').update(JSON.stringify(value)).digest('hex'),fail=(message,status=400)=>{throw Object.assign(new Error(message),{status})},copy=value=>structuredClone(value),weight={info:0,warning:1,error:2}
export async function apply(ctx,config={}){
 const transport=config.transport||createTransport(),clock=config.clock||Date.now,iso=()=>new Date(clock()).toISOString(),running=new Map();let disposed=false,timer
 const guard=(user,write=false)=>{if(!user?.id)fail('Sign in to review your email digest.',401);if(write&&(user.disabled||user.permissions?.includes('workspace:read-only')))fail('This account cannot send activity digests.',403)}
 const options=user=>ctx.settings.get(user,'mail-digest'),history=user=>{guard(user);return ctx.store.list(user.id,'mail-digests').sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
 ctx.effect(()=>ctx.settings.define({id:'mail-digest',name:'Email activity digest',scope:'account',description:'Optional fixed summaries of unread activity. No email body, notification text, quotation or costs are included. SMTP uses this account’s Email connection.',defaults:{enabled:false,automatic:false,recipient:'',maxItems:20,minSeverity:'info',intervalMinutes:15,workspaceUrl:''},fields:[
  {key:'enabled',label:'Enable email activity digests',type:'boolean',description:'Allow a digest to the recipient below. Turn on automatic delivery separately if wanted.'},{key:'automatic',label:'Automatically send activity digests',type:'boolean',description:'Standing permission to send a bounded summary when new unread activity is eligible, no more often than the interval below.'},{key:'recipient',label:'Digest recipient email',type:'text'},{key:'maxItems',label:'Maximum activity items per digest',type:'number',min:1,max:40},{key:'minSeverity',label:'Minimum digest severity',type:'select',options:['info','warning','error']},{key:'intervalMinutes',label:'Minimum interval in minutes',type:'number',min:1,max:1440},{key:'workspaceUrl',label:'Workspace URL (optional)',type:'text',description:'An HTTP or HTTPS link to your Quotagent application. Without a configured URL the email contains no link.'}],validate:next=>{if(next.enabled&&!/^[^\s<>@]+@[^\s<>@]+\.[^\s<>@]+$/.test(next.recipient))fail('Set a complete digest recipient before enabling digests.');if(next.workspaceUrl){let url;try{url=new URL(next.workspaceUrl)}catch{fail('Use a complete HTTP or HTTPS workspace URL.')}if(!['http:','https:'].includes(url.protocol)||url.username||url.password)fail('Use an HTTP or HTTPS workspace URL without credentials.')}if(!Number.isInteger(next.maxItems))fail('Maximum activity items must be a whole number.')}}))
 // A send that was in flight across restart has unknown delivery, never automatic replay.
 for(const user of ctx.accounts.list()){let rows;try{rows=history(user)}catch(error){if(error.status===503)continue;throw error}for(const row of rows)if(row.status==='sending')await ctx.store.put(user.id,'mail-digests',{...row,status:'uncertain',reason:'Runtime stopped before a final SMTP receipt was recorded.',completedAt:iso()},{actor:'system:mail-digest',event:'mail/digest-interrupted'})}
 const key=item=>`${item.id}:${item.level||'info'}`
 const preview=user=>{guard(user);const settings=options(user),connection=ctx.settings.get(user,'mail'),records=history(user),used=new Set(records.filter(row=>['sending','sent','uncertain'].includes(row.status)).flatMap(row=>row.deliveryKeys)),prefs=ctx.notifications.preferences(user),all=ctx.notifications.list(user),eligible=all.filter(item=>!item.readAt&&weight[item.level||'info']>=weight[settings.minSeverity]&&ctx.notifications.visible(item,prefs)&&!used.has(key(item))),items=eligible.slice(0,settings.maxItems),counts={info:0,warning:0,error:0};for(const item of items)counts[item.level||'info']++
  const latest=records.find(row=>['sending','sent','uncertain'].includes(row.status)),nextAt=latest?Date.parse(latest.createdAt)+settings.intervalMinutes*60_000:0,blocked=!settings.enabled?'Digest is disabled.':!connection.enabled||!connection.smtpHost||!connection.fromAddress?'Configure and enable this account’s SMTP email connection.':!items.length?'No new unread activity is eligible.':clock()<nextAt?'The minimum delivery interval has not elapsed.':null
  const subject=`Quotagent activity digest · ${items.length} item${items.length===1?'':'s'}`,body=`There ${items.length===1?'is':'are'} ${items.length} unread activity item${items.length===1?'':'s'} waiting in your Quotagent workspace.\n\n${['error','warning','info'].filter(level=>counts[level]).map(level=>`${counts[level]} ${level} activity item${counts[level]===1?'':'s'}`).join('\n')}\n\nOpen Quotagent to review the details.${settings.workspaceUrl?'\n'+settings.workspaceUrl:''}\n\nThis digest includes activity counts only. Your quotations, costs and message content stay in your workspace.`,deliveryKeys=items.map(key),fingerprint=hash({recipient:settings.recipient,subject,body,deliveryKeys,smtp:{host:connection.smtpHost,port:connection.smtpPort,user:connection.smtpUser,from:connection.fromAddress},policy:{enabled:settings.enabled,automatic:settings.automatic,maxItems:settings.maxItems,minSeverity:settings.minSeverity,intervalMinutes:settings.intervalMinutes}})
  return{recipient:settings.recipient,from:connection.fromAddress,subject,body,items:items.map(item=>({id:item.id,level:item.level,createdAt:item.createdAt})),count:items.length,eligible:eligible.length,remaining:Math.max(0,eligible.length-items.length),unread:all.filter(item=>!item.readAt).length,counts,enabled:settings.enabled,automatic:settings.automatic,blocked,nextAllowedAt:nextAt>clock()?new Date(nextAt).toISOString():null,fingerprint,deliveryKeys,history:records.slice(0,20).map(({deliveryKeys,...row})=>({...row,itemCount:deliveryKeys.length}))}
 }
 const send=(user,input={})=>{guard(user,true);if(running.has(user.id))return running.get(user.id);const operation=(async()=>{if(disposed)fail('The mail digest plugin is unloading.',409);const review=preview(user),settings=options(user),connection=copy(ctx.settings.get(user,'mail')); if(input.automatic){if(!settings.automatic||!settings.enabled)return{skipped:true,reason:'Automatic delivery is disabled.'}}else if(input.confirmed!==true)fail('Review and confirm the recipient and summary before sending.');if(review.blocked){if(input.automatic)return{skipped:true,reason:review.blocked};fail(review.blocked,409)}if(!input.automatic&&input.fingerprint!==review.fingerprint)fail('Activity or connection settings changed. Preview the digest again before sending.',409)
   const id=randomUUID(),record={id,status:'sending',createdAt:iso(),recipient:review.recipient,from:review.from,subject:review.subject,body:review.body,deliveryKeys:review.deliveryKeys,fingerprint:review.fingerprint,mode:input.automatic?'automatic':'manual',standingPermission:input.automatic?'mail-digest.enabled+automatic':'human confirmed preview',counts:review.counts};await ctx.store.put(user.id,'mail-digests',record,{actor:input.automatic?'system:mail-digest':user.id,event:'mail/digest-dispatched'})
   try{if(disposed)throw new Error('Digest plugin unloaded before SMTP completed.');const receipt=await transport.send(connection,{from:{name:connection.fromName,address:review.from},to:[review.recipient],subject:review.subject,text:review.body,messageId:`<quotagent-digest-${id}@local.invalid>`});if(receipt.rejected?.length||!receipt.accepted?.length)throw new Error('SMTP did not accept the digest recipient. Inspect delivery before sending any replacement.');const sent={...record,status:'sent',completedAt:iso(),receipt};await ctx.store.put(user.id,'mail-digests',sent,{actor:'system:mail-digest',event:'mail/digest-sent'});return{ok:true,digest:sent}}
   catch(error){const uncertain={...record,status:'uncertain',completedAt:iso(),reason:'SMTP delivery could not be confirmed. This batch will not be sent again automatically.'};await ctx.store.put(user.id,'mail-digests',uncertain,{actor:'system:mail-digest',event:'mail/digest-uncertain'});return{ok:false,digest:uncertain}}
  })();running.set(user.id,operation);operation.finally(()=>running.delete(user.id)).catch(()=>{});return operation}
 const poll=async()=>{if(disposed)return;for(const user of ctx.accounts.list()){if(disposed)break;try{const settings=options(user);if(settings.enabled&&settings.automatic&&!user.disabled&&!user.permissions?.includes('workspace:read-only'))await send(user,{automatic:true})}catch{}}if(!disposed&&config.poll!==false){timer=setTimeout(poll,config.pollMs||30_000);timer.unref?.()}}
 ctx.provide('mailDigest',{preview,send,history,poll})
 ctx.effect(()=>ctx.web.route('GET','/mail-digest',({user})=>preview(user)))
 ctx.effect(()=>ctx.web.route('POST','/mail-digest/send',({user,body})=>send(user,{confirmed:body.confirmed,fingerprint:body.fingerprint})))
 ctx.effect(()=>{if(config.poll!==false){timer=setTimeout(poll,config.pollMs||30_000);timer.unref?.()}return async()=>{disposed=true;clearTimeout(timer);transport.dispose();await Promise.allSettled([...running.values()])}})
}
