import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {mkdirSync,mkdtempSync,writeFileSync} from 'node:fs'
import {resolve,join} from 'node:path'
import * as store from '../../workspace-store/code/index.mjs'
import * as settings from '../../settings/code/index.mjs'
import * as notifications from '../code/index.mjs'
const require=createRequire(new URL('../../../../host/package.json',import.meta.url)),{Context}=require('cordis'),ctx=new Context(),fibers=[],routes=[],users=[{id:'notice-owner',role:'contractor'},{id:'notice-other',role:'supplier'}],[user,other]=users
mkdirSync('tmp',{recursive:true});const root=mkdtempSync(resolve('tmp/notification-windows-')),checks=[];let delivered=0
const mount=async(module,config)=>{const fiber=await ctx.plugin(module,config);assert.equal(fiber.state,2);fibers.push(fiber);return fiber}
try{await mount({name:'notice-fixture',apply(child){child.provide('accounts',{list:()=>users,get:id=>users.find(user=>user.id===id),can:()=>true});child.provide('web',{route:(...args)=>{routes.push(args);return()=>routes.splice(routes.indexOf(args),1)},contribute:()=>()=>{}})}});await mount(store,{root});await mount(settings);const fiber=await mount(notifications),off=ctx.notifications.subscribe(()=>delivered++)
 for(let i=0;i<253;i++)await ctx.notifications.push(user,{type:i%2?'review':'mail',level:i%5===0?'warning':'info',title:`Notice ${i}`,body:`Fixture record ${i}`,dedupeKey:`notice-${i}`,source:{pluginId:i%2?'action-center':'mail',panelId:'fixture',sourceId:String(i)}})
 const events=ctx.store.events(user.id).length,first=ctx.notifications.window(user),last=ctx.notifications.window(user,{page:11});assert.equal(first.total,253);assert.equal(first.notifications.length,25);assert.equal(last.notifications.length,3);assert.equal(last.end,253);assert.equal(first.unread,253);assert.equal(ctx.notifications.window(other).total,0);assert.equal(ctx.store.events(user.id).length,events);checks.push('Full history has253 items; server pages cover all11 windows and complete unread counts, reads are pure and account-owned')
 const input={type:'review',title:'Paired source warning',body:'Fixture',level:'info',dedupeKey:'paired',source:{pluginId:'a',panelId:'first',sourceId:'event-1'}};await Promise.all(Array.from({length:5},()=>ctx.notifications.push(user,input)));assert.equal(ctx.notifications.window(user).total,254);const prior=ctx.notifications.list(user).find(row=>row.dedupeKey==='paired');assert.equal(prior.mergedCount,1);await ctx.notifications.read(user,prior.id);await ctx.notifications.push(user,{...input,source:{pluginId:'b',panelId:'second',sourceId:'event-2'},level:'error'});const merged=ctx.notifications.list(user).find(row=>row.id===prior.id);assert.equal(merged.mergedCount,2);assert.equal(merged.sources.length,2);assert.equal(merged.level,'error');assert.equal(merged.readAt,null);assert.equal(delivered,255);assert.equal(ctx.notifications.window(user).produced,255);checks.push('Concurrent duplicate reports coalesce; separate producers retain all attribution; severity escalation alerts once and reopens unread')
 const filtered=ctx.notifications.window(user,{source:'mail',level:'warning',q:'Fixture'}),marked=await ctx.notifications.readMatched(user,{source:'mail',level:'warning',q:'Fixture'});assert.equal(marked.marked,filtered.matched);assert.ok(marked.marked>25);assert.equal(ctx.notifications.window(user,{source:'mail',level:'warning',unread:'true'}).matched,0);assert.equal(ctx.notifications.window(user).total,254);checks.push('Server filters and mark-matching-read cover records outside the visible25-row page')
 await ctx.settings.save(user,'notifications',{values:{minSeverity:'error',mutedSources:'a,b'}});const muted=ctx.notifications.window(user);assert.equal(muted.unread,0);assert.ok(muted.unreadTotal>0);assert.equal(muted.total,254);off();const previous=delivered;await ctx.notifications.push(user,{title:'No subscriber',source:{pluginId:'a'}});assert.equal(delivered,previous);checks.push('Alert severity/mute preferences preserve complete activity history; subscription removal has immediate effect')
 await fiber.dispose();assert.ok(!routes.some(([,path])=>path.startsWith('/notifications')));assert.throws(()=>ctx.settings.get(user,'notifications'),/registered/);checks.push('Native unload removes service routes, settings schema and subscriptions')
 const report={ok:true,root,checks};writeFileSync(join(root,'report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2))
}finally{for(const fiber of fibers.reverse())await fiber.dispose()}
