import React,{useState,useEffect} from 'react'
import {registry,useApp,useResource,api,Icon,Button,Badge,Field,PageHeader,ErrorNotice,Empty,Loading,Modal} from '../../webui/client/core.jsx'
import {PluginSettings} from '../../settings/client/settings.jsx'
import './telegram.css'
const stamp=value=>value?new Date(value).toLocaleString():'Not checked yet'
function Telegram(){
  const app=useApp(),resource=useResource('/telegram',{status:{},messages:[]}),[selected,setSelected]=useState(app.context.chatId||''),[settingsOpen,setSettingsOpen]=useState(false)
  const [compose,setCompose]=useState(null),[busy,setBusy]=useState(''),[error,setError]=useState('')
  const {status,messages}=resource.data,readOnly=app.user.permissions?.includes('workspace:read-only')
  const conversations=[...new Map(messages.map(message=>[message.chatId,messages.find(row=>row.chatId===message.chatId)])).values()].filter(message=>message.chatId)
  const current=messages.filter(message=>message.chatId===selected).slice().reverse()
  useEffect(()=>{if(app.context.chatId)setSelected(app.context.chatId);else if(app.context.messageId){const message=messages.find(row=>row.id===app.context.messageId);if(message)setSelected(message.chatId)}},[app.context.chatId,app.context.messageId,messages])
  const task=async(name,fn)=>{setBusy(name);setError('');try{return await fn()}catch(error){setError(error.message)}finally{setBusy('')}}
  const sync=()=>task('sync',async()=>{const result=await api('/telegram/sync',{method:'POST',body:{}});await resource.reload();app.refresh();app.notify(`${result.imported} Telegram message${result.imported===1?'':'s'} received.`)})
  const test=()=>task('test',async()=>{const result=await api('/telegram/test',{method:'POST',body:{}});await resource.reload();app.notify(`Connected to @${result.bot.username||result.bot.name}. No message sent.`)})
  const ingest=message=>task(message.id,async()=>{const result=await api(`/telegram/${message.id}/ingest`,{method:'POST',body:{}});app.navigate('ingestion',result.action.input)})
  return <><PageHeader eyebrow="CONVERSATIONS IN CONTEXT" title="Keep Telegram close to the work." actions={<><Button variant="secondary" icon="settings" onClick={()=>setSettingsOpen(true)}>Telegram settings</Button><Button icon="plus" disabled={readOnly} onClick={()=>setCompose({chatId:selected||status.defaultChatId||'',text:''})}>New message</Button></>}>Receive bot conversations, extract attached scope, and prepare replies for your approval.</PageHeader><ErrorNotice error={error||resource.error} retry={resource.error?resource.reload:undefined}/>
    <section className="card telegram-connection"><div><Badge status={status.enabled?'accent':'neutral'}>{status.enabled?'Connection enabled':'Not connected'}</Badge><h2>{status.bot?.username?`@${status.bot.username}`:'Your Telegram bot'}</h2><p>{status.enabled?`Last update: ${stamp(status.lastSyncAt)}${status.polling?' · Automatic reception on':''}`:'Connect a bot token from @BotFather, then start a chat with that bot to receive your first message.'}</p>{status.lastError&&<p className="telegram-warning">{status.lastError}</p>}</div><div><Button variant="secondary" disabled={!status.enabled||!!busy||readOnly} busy={busy==='test'} onClick={test}>Test bot</Button><Button icon="refresh" disabled={!status.enabled||!!busy||readOnly} busy={busy==='sync'||status.syncing} onClick={sync}>Receive messages</Button></div></section>
    {status.warnings?.length>0&&<div className="telegram-warnings">{status.warnings.map((warning,i)=><p key={i}>{warning}</p>)}</div>}
    <div className="telegram-layout"><aside className="card telegram-chats"><h2>Conversations</h2>{resource.loading?<Loading/>:conversations.length?conversations.map(message=><button className={`telegram-chat ${selected===message.chatId?'selected':''}`} key={message.chatId} onClick={()=>setSelected(message.chatId)}><span className="telegram-avatar"><Icon name="message" size={20}/></span><span><strong>{message.chatTitle||message.chatId}</strong><small>Chat {message.chatId}</small><p>{message.text||message.document?.filename||'Document'}</p></span></button>):<Empty icon="message" title="No conversations yet">Start a chat with your bot in Telegram, then receive messages here.</Empty>}</aside>
      <section className="card telegram-thread">{selected?<><div className="section-heading"><div><h2>{current.at(-1)?.chatTitle||selected}</h2><p className="muted">Chat ID {selected}</p></div><Button variant="secondary" disabled={readOnly} onClick={()=>setCompose({chatId:selected,text:''})}>Write message</Button></div><div className="telegram-history">{current.map(message=><article key={message.id} className={`telegram-bubble ${message.direction==='outbound'?'outgoing':''}`}><header><strong>{message.direction==='outbound'?'You':message.sender}</strong><Badge>{message.status==='pending'?'Awaiting approval':message.status==='uncertain'?'Check delivery':message.status}</Badge></header><p className="telegram-message-text">{message.text||'Attached document'}</p>{message.file&&<div className="telegram-document"><Icon name="file"/><a href={`/quotagent/api/files/${message.file.id}/download`} download>{message.file.filename}</a></div>}{message.fileError&&<p className="telegram-warning">{message.fileError}</p>}{message.lastError&&<p className="telegram-warning">{message.lastError}</p>}<small>{stamp(message.sentAt||message.receivedAt||message.createdAt)}{message.editedAt?' · Edited':''}</small><footer>{message.direction==='inbound'&&<><button disabled={readOnly} onClick={()=>setCompose({chatId:message.chatId,replyToId:message.id,text:''})}>Reply</button><button disabled={!!busy||readOnly} onClick={()=>ingest(message)}>{busy===message.id?'Extracting…':'Extract items'}</button><button onClick={()=>app.ask(`Read Telegram message ${message.id} with telegram_read. Summarize its scope and prepare a helpful reply using telegram_draft, without sending.`)}>Draft with AI</button></>}{['draft','pending','failed'].includes(message.status)&&<button disabled={readOnly} onClick={()=>setCompose(message)}>Edit draft</button>}{message.actionId&&<button onClick={()=>app.navigate('approvals',{actionId:message.actionId})}>Open send review</button>}</footer></article>)}</div></>:<Empty icon="message" title="Choose a conversation">Messages, attached documents and private reply drafts stay together.</Empty>}</section>
    </div>{settingsOpen&&<PluginSettings plugin={{id:'telegram',name:'Telegram bot'}} onClose={()=>{setSettingsOpen(false);resource.reload()}}/>}{compose&&<TelegramComposer initial={compose} close={()=>setCompose(null)} saved={async message=>{setSelected(message.chatId);await resource.reload()}}/>}</>
}
function TelegramComposer({initial,close,saved}){
  const app=useApp(),[draft,setDraft]=useState(initial),[busy,setBusy]=useState(''),[error,setError]=useState('')
  async function save(review=false){setBusy(review?'review':'save');setError('');try{const result=await api('/telegram/draft',{method:'POST',body:draft});setDraft(previous=>({...previous,id:result.message.id}));await saved(result.message);if(review){const proposal=await api(`/telegram/${result.message.id}/review`,{method:'POST',body:{}});close();app.navigate('approvals',proposal.action.input)}else{close();app.notify('Private Telegram draft saved.')}}catch(error){setError(error.message)}finally{setBusy('')}}
  return <Modal title={draft.replyToId?'Reply on Telegram':'Telegram message'} description="Your message stays private until you approve the exact recipient and text." onClose={close}><ErrorNotice error={error}/><form onSubmit={event=>{event.preventDefault();save(false)}}><Field label="Recipient chat ID"><input aria-label="Telegram recipient chat" value={draft.chatId||''} onChange={event=>setDraft({...draft,chatId:event.target.value})} placeholder="123456789 or @channel"/></Field><Field label="Message"><textarea aria-label="Telegram message" rows={8} maxLength={4096} value={draft.text||''} onChange={event=>setDraft({...draft,text:event.target.value})}/></Field><p className="muted telegram-character-count">{draft.text?.length||0} / 4,096 characters</p><div className="form-actions"><Button variant="secondary" onClick={close}>Cancel</Button><Button variant="secondary" type="submit" busy={busy==='save'} disabled={!!busy}>Save draft</Button><Button icon="send" busy={busy==='review'} disabled={!!busy} onClick={()=>save(true)}>Review send</Button></div></form></Modal>
}
registry.page('telegram',{component:Telegram,icon:'send'})
function TelegramActionPreview({input}){return <section className="telegram-action-preview"><div><span>Recipient</span><h3>{input.chatTitle||input.chatId}</h3><p>Telegram chat ID {input.chatId}{input.replyToMessageId?` · Reply to message ${input.replyToMessageId}`:''}</p></div><p className="telegram-message-text">{input.text}</p><p className="telegram-preview-note">Approval sends this exact text through your configured Telegram bot. To change it, decline this action and edit the draft.</p></section>}
registry.slot('action-preview:telegram.send',TelegramActionPreview)
