import assert from 'node:assert/strict'
import {mkdirSync,writeFileSync} from 'node:fs'
import {join,resolve} from 'node:path'
import {chromium} from '../../../../host/node_modules/playwright/index.mjs'
const base=(process.env.BASE_URL||'http://127.0.0.1:8647/quotagent/').replace(/\/?$/,'/'),out=resolve(process.env.EVIDENCE_DIR||'tmp/agent-experience/g6-browser'),fixture=process.env.FIXTURE_BASE||'http://127.0.0.1:8653/v1'
mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:'/opt/hermes/.playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell'}),page=await browser.newPage({viewport:{width:1440,height:1100}}),report={base,fixture,at:new Date().toISOString(),checks:[],screenshots:[],errors:[],limitation:'UI writes use an explicit loopback transport fixture. This is not evidence of real model quality or business improvement.'};page.on('pageerror',error=>report.errors.push(error.message));page.setDefaultTimeout(20000)
const shot=async name=>{await page.screenshot({path:join(out,name),fullPage:true});report.screenshots.push(name)}
const nav=async(label,group='Personalize')=>{const item=page.locator('.sidebar').getByRole('button',{name:label,exact:true});if(!await item.isVisible())await page.locator('.sidebar').getByRole('button',{name:group,exact:true}).click();await item.click()}
const runtime=async()=>{await nav('AI usage');await page.getByRole('button',{name:'Runtime controls',exact:true}).click();await page.getByRole('heading',{name:'Current limits',exact:true}).waitFor()}
const settings=async(values)=>{await page.getByRole('button',{name:'Budget & context settings',exact:true}).click();const dialog=page.getByRole('dialog',{name:'AI runtime limits and pricing settings',exact:true});await dialog.getByRole('button',{name:'Save settings',exact:true}).waitFor();for(const[label,value]of Object.entries(values)){const input=dialog.getByLabel(label,{exact:true});if(typeof value==='boolean')await input.setChecked(value);else if(await input.evaluate(node=>node.tagName==='SELECT'))await input.selectOption(String(value));else await input.fill(String(value))}await dialog.getByRole('button',{name:'Save settings',exact:true}).click();await dialog.getByText('Settings saved.',{exact:true}).waitFor();await dialog.getByRole('button',{name:'Close',exact:true}).click()}
const caseTitle='G6 retained GUI counterexample '+Date.now()
let responsesBefore=0,priorPricedMicros=0,priorPricedCalls=0
const finished=async()=>{await page.locator('.assistant-message.from-assistant').nth(responsesBefore).waitFor();await page.getByRole('button',{name:'Send to AI assistant',exact:true}).waitFor()}
const send=async text=>{await nav('Agent workspace');await page.getByText('Ready to work with you',{exact:true}).waitFor();responsesBefore=await page.locator('.assistant-message.from-assistant').count();await page.getByLabel('Message your AI assistant',{exact:true}).fill(text);await page.getByRole('button',{name:'Send to AI assistant',exact:true}).click()}
try{
 await page.goto(base);if(process.env.FRESH_ACCOUNT==='1'){await page.getByRole('button',{name:'Create an account',exact:true}).click();report.account='runtime-check-'+Date.now()+'@local.test';await page.getByLabel('Your name',{exact:true}).fill('Runtime protocol check');await page.getByLabel('Company',{exact:true}).fill('Isolated protocol evidence');await page.getByLabel('Email address',{exact:true}).fill(report.account);await page.getByLabel('Password',{exact:true}).fill('runtime-fixture-only');await page.getByRole('button',{name:'Create workspace',exact:true}).click()}else{await page.getByLabel('Email address',{exact:true}).fill('contractor@demo.local');await page.getByLabel('Password',{exact:true}).fill('demo1234');await page.getByRole('button',{name:'Sign in',exact:true}).click()};await page.locator('.sidebar').waitFor();if(await page.getByRole('button',{name:'Not now',exact:true}).isVisible())await page.getByRole('button',{name:'Not now',exact:true}).click();await nav('AI usage');const priorUsage=await (await page.request.get(new URL('api/usage',base).href)).json();priorPricedMicros=priorUsage.summary.costs?.find(row=>row.currency==='USD')?.amountMicros||0;priorPricedCalls=priorUsage.summary.costs?.find(row=>row.currency==='USD')?.pricedCalls||0;await page.getByRole('button',{name:'Model settings',exact:true}).click();let dialog=page.getByRole('dialog',{name:'AI model connection settings',exact:true});await dialog.getByLabel('Provider name',{exact:true}).fill('g6-loopback');await dialog.getByLabel('Model',{exact:true}).fill('g6-protocol-fixture');await dialog.getByLabel('API base URL',{exact:true}).fill(fixture);await dialog.getByLabel('API key',{exact:true}).fill('fixture-only');await dialog.getByRole('button',{name:'Save settings',exact:true}).click();await dialog.getByText('Settings saved.',{exact:true}).waitFor();await dialog.getByRole('button',{name:'Close',exact:true}).click()
 await runtime();await settings({'Window token budget (0 = unlimited)':10,'Maximum output tokens per call':64,'Maximum records per source group':1,'Maximum prior completed turns':1,'I have entered an explicit matching tariff':false})
 await send('G6 budget evidence: review my sample project without changing anything.');await page.getByText('Needs attention',{exact:true}).waitFor();await page.locator('.runtime-run-notice').click();await page.getByText('Waiting does not reset this limit.',{exact:false}).waitFor();assert.match(await page.locator('.runtime-run-notice').innerText(),/token request too large|single request/);await shot('01-budget-refusal.png');report.checks.push('GUI configures explicit token budget; oversized task stops before dispatch with reason and next action')
 await runtime();await settings({'Window token budget (0 = unlimited)':0});await nav('Agent workspace');await page.getByRole('button',{name:'Resume task',exact:true}).click();await finished();await shot('02-context-receipt.png');report.checks.push('Human Resume succeeds after deliberate budget change; source omissions remain inspectable')
 await runtime();assert.match(await page.locator('.runtime-panel').innerText(),/Monetary cost is unknown/);await shot('03-unknown-cost-runtime.png');await settings({'I have entered an explicit matching tariff':true,'Tariff provider name':'g6-loopback','Tariff model identifier':'g6-protocol-fixture','Tariff source or contract reference':'Synthetic protocol fixture tariff, not a provider price','Tariff effective date (YYYY-MM-DD)':'2026-09-26','Input price per million tokens':2,'Output price per million tokens':4});await send('G6 priced protocol evidence: review recorded context only.');await finished()
 await nav('AI usage');await page.getByRole('button',{name:'Tokens & cost',exact:true}).click();await page.getByRole('heading',{name:'Configured-rate estimates',exact:true}).waitFor();assert.ok((await page.locator('.usage-costs').innerText()).includes('USD '+((priorPricedMicros+360)/1000000).toLocaleString(undefined,{maximumFractionDigits:6,minimumFractionDigits:2})));assert.ok((await page.locator('.usage-costs').innerText()).includes((priorPricedCalls+1)+' priced calls'));await shot('04-measured-estimate.png');report.checks.push('Configured matching synthetic tariff produces USD0.00036 from120input/30output tokens; other unknown calls remain visibly unpriced')
 await page.getByRole('button',{name:'Recorded evaluations',exact:true}).click();await page.getByRole('button',{name:'Capture a recorded run',exact:true}).click();await page.waitForFunction(()=>Array.from(document.querySelectorAll('select option')).some(node=>node.textContent.includes('G6 priced protocol')));const options=await page.getByLabel('Recorded run',{exact:true}).locator('option').evaluateAll(nodes=>nodes.map(node=>({value:node.value,text:node.textContent})));const chosen=options.find(row=>row.text.includes('G6 priced protocol'));assert.ok(chosen);await page.getByLabel('Recorded run',{exact:true}).selectOption(chosen.value);await page.getByLabel('Case title',{exact:true}).fill(caseTitle);await page.getByLabel('Scenario family',{exact:true}).selectOption('S4');await page.getByLabel('Check 1',{exact:true}).selectOption('output-contains');await page.getByLabel('Expected value 1',{exact:true}).fill('Impossible expected fixture phrase');await page.getByRole('button',{name:'Create case for review',exact:true}).click();await page.getByRole('heading',{name:'Captured output',exact:true}).waitFor();await shot('05-human-case-review.png');await page.getByRole('button',{name:'Approve & execute',exact:true}).click();await page.getByRole('button',{name:'Open evaluation case',exact:true}).click();const caseCard=page.locator('.runtime-case-grid .card').filter({has:page.getByRole('heading',{name:caseTitle,exact:true})});await caseCard.getByRole('button',{name:'Replay recorded checks',exact:true}).click();await caseCard.getByText('Last replay: failed',{exact:false}).waitFor();await shot('06-retained-failed-replay.png');assert.match(await page.locator('.runtime-panel').innerText(),/Business quality, quote completeness and procurement cycle-time improvement remain unmeasured/);report.checks.push('GUI captures actual recorded output, reviews immutable assertions, accepts case and replays retained failing counterexample without a model or business write')
 await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>document.querySelector('.sidebar').getBoundingClientRect().right<=1);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await shot('07-mobile-evaluation.png');report.checks.push('Runtime/evaluation flow fits390px viewport');assert.deepEqual(report.errors,[]);report.ok=true
}catch(error){report.error=error.stack;await shot('failure.png');process.exitCode=1}finally{writeFileSync(join(out,'report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));await browser.close()}
