import React, { useState } from 'react'
import { Button, Field } from '../../../system/webui/client/core.jsx'
import { Input, Select, SubmitForm, Source } from './common.jsx'
const scalar = [['taxRate','Tax rate (%)'],['freight','Freight charge'],['advancePercent','Advance (%)'],['paymentDays','Net payment days'],['warrantyMonths','Warranty months'],['penaltyPercent','Penalty (%)']]
export function TermsEditor({ quote, assumption, buyer = false, run, busy }) {
  const [terms, setTerms] = useState({ ...(quote.commercial || {}), ...(assumption?.quoteRevision === quote.revision ? assumption.commercial : {}) }), [source, setSource] = useState(assumption?.source || ''), [currency, setCurrency] = useState(quote.currency), [baseRevision,setBaseRevision] = useState(quote.revision)
  const changed = baseRevision !== quote.revision
  const reload = () => {setTerms({...(quote.commercial || {}),...(assumption?.quoteRevision === quote.revision ? assumption.commercial : {})});setSource(assumption?.source || '');setCurrency(quote.currency);setBaseRevision(quote.revision)}
  const set = (key, value) => setTerms(old => ({ ...old, [key]: value }))
  const update = (i, key, value) => set('deviations', terms.deviations.map((row, index) => index === i ? { ...row, [key]: value } : row))
  const payload = () => Object.fromEntries(Object.entries(terms).map(([key, value]) => [key, key === 'deviations' ? value.map(row => Object.fromEntries(Object.entries(row).map(([field, item]) => [field, item === '' ? null : item]))) : value === '' ? null : value]))
  return <SubmitForm className="card cw-stack" onSubmit={async () => {const result=await run(buyer ? 'save-assumptions' : 'save-terms', { quoteId: quote.id, expectedRevision:baseRevision, commercial: payload(), currency, source });setBaseRevision(result.quote?.revision || quote.revision)}}>
    <div><h2>{buyer ? 'Your sourced evaluation assumptions' : 'Declared commercial terms'}</h2><p>{buyer ? 'These private assumptions supplement or override this received quote for your analysis. They are not supplier commitments.' : 'Save terms into your private quote draft. Submit the reviewed quote separately to share them.'} Blank fields stay unknown.</p></div>
    {changed && <section className="cw-warning" role="status"><h3>The quotation changed while this form was open</h3><p>Your edited values are preserved. This form started at revision {baseRevision}; the current quote is revision {quote.revision}. Review the latest declaration before saving these edits.</p><details><summary>Latest saved commercial declaration</summary><p>Currency: {quote.currency}. Tax: {quote.commercial?.taxMode || 'Not declared'}.</p><ul>{scalar.map(([key,label])=><li key={key}>{label}: {quote.commercial?.[key] ?? 'Not declared'}</li>)}</ul><p>Valid until: {quote.commercial?.validityUntil || 'Not declared'}. Delivery: {quote.commercial?.deliveryBinding || 'Not declared'}.</p>{quote.commercial?.deviations?.map((row,i)=><p key={i}>{row.description} · price impact {row.priceImpact ?? 'unknown'} · days impact {row.timeImpactDays ?? 'unknown'}</p>)}</details><div className="row-actions"><Button variant="secondary" onClick={reload}>Load current saved values</Button><Button variant="secondary" onClick={()=>setBaseRevision(quote.revision)}>I reviewed the current quote; keep my edits</Button></div></section>}
    {assumption && assumption.quoteRevision !== quote.revision && <p className="cw-warning">The quotation changed. Old assumptions are retained but will not be used until you review and save them again.</p>}
    <div className="cw-grid">{!buyer && <Input label="Quote currency" value={currency} onChange={setCurrency} maxLength={3} required/>}<Select label="Tax treatment" value={terms.taxMode || ''} onChange={v => set('taxMode', v)}><option value="">Not declared</option><option value="inclusive">Included in quoted prices</option><option value="exclusive">Add tax to quoted prices</option><option value="unspecified">Explicitly unspecified</option></Select>{scalar.map(([key, label]) => <Input key={key} label={label} type="number" step={['freight','taxRate','advancePercent','penaltyPercent'].includes(key) ? '0.01' : '1'} min="0" max={key.endsWith('Percent') || key === 'taxRate' ? '100' : undefined} value={terms[key]} onChange={v => set(key, v)}/>)}<Input label="Quote valid until" type="date" value={terms.validityUntil} onChange={v => set('validityUntil', v)}/><Select label="Delivery commitment" value={terms.deliveryBinding || ''} onChange={v => set('deliveryBinding', v)}><option value="">Not declared</option><option value="firm">Firm date</option><option value="indicative">Indicative estimate</option></Select></div>
    <div><h3>Scope deviations</h3><p>Declare none explicitly, or record each difference. Leave an unknown price impact blank.</p><div className="row-actions"><Button variant="secondary" onClick={() => set('deviations', [])}>Declare no deviations</Button><Button variant="secondary" onClick={() => set('deviations', [...(terms.deviations || []), { description: '' }])}>Add deviation</Button></div>{!terms.deviations && <p className="muted">Deviation declaration is unknown.</p>}{terms.deviations?.length === 0 && <p>No deviations declared.</p>}{terms.deviations?.map((row, i) => <div className="cw-grid cw-inset" key={i}><Select label={`Deviation ${i + 1} item`} value={row.itemId} onChange={v => update(i, 'itemId', v)}><option value="">Whole quotation</option>{quote.items.map(item => <option key={item.id} value={item.id}>{item.description}</option>)}</Select><Input label={`Deviation ${i + 1} description`} value={row.description} onChange={v => update(i, 'description', v)} required/><Input label={`Deviation ${i + 1} price impact`} type="number" step="0.01" value={row.priceImpact} onChange={v => update(i, 'priceImpact', v)}/><Input label={`Deviation ${i + 1} days impact`} type="number" step="1" value={row.timeImpactDays} onChange={v => update(i, 'timeImpactDays', v)}/><Button variant="ghost" onClick={() => set('deviations', terms.deviations.filter((_, index) => index !== i))}>Remove deviation {i + 1}</Button></div>)}</div>
    {buyer && <Input label="Assumption source and rationale" value={source} onChange={setSource} required placeholder="Meeting note, supplier clarification, or explicitly labelled planning assumption"/>}
    <Button type="submit" busy={busy} disabled={changed}>{buyer ? 'Save sourced assumptions' : 'Save commercial terms to draft'}</Button><Source value={{ supplierDeclaration: quote.commercial || {}, receivedQuoteRevision: quote.revision, selectedAssumptions: assumption }} label="Inspect original declaration and saved assumptions"/>
  </SubmitForm>
}
