import React,{useState,useEffect} from 'react'
import {registry,useApp,useResource,api,Button,Badge,PageHeader,ErrorNotice,Loading,Empty} from '../../../system/webui/client/core.jsx'
import {PluginSettings} from '../../../system/settings/client/settings.jsx'
import {Select,Table,amount} from './common.jsx'
import {Costs,Capacity} from './supplier.jsx'
import {TermsEditor} from './terms.jsx'
import {Evaluation,Sources} from './evaluation.jsx'
import {History,Erp,Reports} from './exchange.jsx'
import './workbench.css'
const empty={rfqs:[],quotes:[],orders:[],costs:[],calendars:[],plans:[],fx:[],references:[],referencePrices:[],policies:[],assumptions:[],evaluations:[],prices:[],mappings:[],history:[],'erp-imports':[],reports:[],defaults:{}}
function Workbench(){
 const app=useApp(),resource=useResource('/commercial',empty),data=resource.data,supplier=app.user.role==='supplier'
 const [rfqId,setRfq]=useState(app.context.rfqId||''),[quoteId,setQuote]=useState(app.context.quoteId||''),[tab,setTab]=useState(app.context.tab||(supplier?'costs':'evaluation')),[busy,setBusy]=useState(''),[error,setError]=useState(''),[settings,setSettings]=useState(false)
 const rfq=data.rfqs.find(row=>row.id===rfqId)||data.rfqs[0],quotes=data.quotes.filter(row=>row.rfqId===rfq?.id),quote=quotes.find(row=>row.id===quoteId)||quotes[0]
 useEffect(()=>{if(app.context.rfqId)setRfq(app.context.rfqId);if(app.context.quoteId)setQuote(app.context.quoteId);if(app.context.tab)setTab(app.context.tab)},[app.context])
 const tabs=supplier?[['costs','Costs & pricing'],['terms','Commercial terms'],['capacity','Capacity'],['sources','FX & references'],['history','History'],['erp','ERP CSV'],['reports','Reports']]:[['evaluation','Compare & score'],['terms','Quote assumptions'],['sources','FX & references'],['history','History'],['erp','ERP CSV'],['reports','Reports']]
 async function run(action,input){setBusy(action);setError('');try{const result=await api(`/commercial/${action}`,{method:'POST',body:input});await resource.reload();app.refresh();app.notify(result.message||'Commercial workbench updated.');return result}catch(e){setError(e.message);throw e}finally{setBusy('')}}
 const props={data,run,busy:!!busy,rfq,quote},needsQuote=['costs','terms','capacity'].includes(tab)
 return <div className="commercial-workbench"><PageHeader eyebrow="PRIVATE, SOURCED DECISION SUPPORT" title="Commercial workbench" actions={<Button variant="secondary" onClick={()=>setSettings(true)}>Pricing policy settings</Button>}>{data.scope||'Costs, capacity and evaluation records stay in your own account.'}</PageHeader><ErrorNotice error={error||resource.error} retry={resource.error?resource.reload:undefined}/>{resource.loading?<Loading/>:<><div className="card cw-grid cw-selectors"><Select label="Workbench request" value={rfq?.id||''} onChange={value=>{setRfq(value);setQuote('')}}><option value="">Choose a request</option>{data.rfqs.map(row=><option value={row.id} key={row.id}>{row.title} · rev {row.publishedRevision||row.revision}</option>)}</Select>{needsQuote&&<Select label="Workbench quotation" value={quote?.id||''} onChange={setQuote}><option value="">Choose a quotation</option>{quotes.map(row=><option value={row.id} key={row.id}>{row.supplierName} · {row.status} · rev {row.revision}{row.stale?' · stale scope':''}</option>)}</Select>}</div><div className="filter-tabs cw-tabs" role="tablist" aria-label="Commercial workbench sections">{tabs.map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>{needsQuote&&!quote?<section className="card"><Empty title={supplier?'Prepare a quote draft first':'No received quotation to inspect'} action={<Button onClick={()=>app.navigate(supplier?'rfqs':'quotes',rfq?{rfqId:rfq.id}:{})}>{supplier?'Open requests':'Open quotes'}</Button>}>{supplier?'Choose a request and prepare a private quote before entering its costs, terms and delivery plan.':'Received quotations appear after suppliers submit them.'}</Empty></section>:tab==='costs'?<Costs key={`${quote.id}:${quote.revision}:${data.costs.find(row=>row.quoteId===quote.id)?.revision}`} {...props}/>:tab==='capacity'?<Capacity key={quote.id} {...props}/>:tab==='terms'?<TermsEditor key={`${quote.id}:${quote.revision}:${data.assumptions.find(row=>row.quoteId===quote.id)?.revision}`} {...props} buyer={!supplier} assumption={data.assumptions.find(row=>row.quoteId===quote.id)}/>:tab==='evaluation'?(rfq?<Evaluation key={rfq.id} {...props}/>:<Empty title="Choose a request to compare">Publish a request and receive quotations first.</Empty>):tab==='sources'?<Sources {...props}/>:tab==='history'?<History {...props}/>:tab==='erp'?<Erp {...props}/>:<Reports {...props}/>}</>}{settings&&<PluginSettings plugin={{id:"commercial",name:"Commercial workbench"}} onClose={()=>{setSettings(false);resource.reload()}}/>}</div>
}
function PricePreview({input}){const value=input.preview||{};return <div className="cw-stack"><h3>Exact private draft prices</h3><p>Applying these prices updates only your private quotation. Review and submit the final quote separately.</p><Table headers={['Item','Quantity','Unit price','Line total']}>{value.items?.map(row=><tr key={row.id}><td>{row.description}</td><td>{row.quantity} {row.unit}</td><td>{amount(row.unitPrice,value.currency)}</td><td>{amount(row.total,value.currency)}</td></tr>)}</Table><p><strong>Proposed total: {amount(value.total,value.currency)}</strong> · Cost: {amount(value.costTotal,value.currency)} · Item-price margin: {value.actualMarginPercent===null?'Unknown':`${value.actualMarginPercent?.toFixed(2)}%`}</p>{value.priceBreakdown&&<p>Item subtotal: {amount(value.subtotal,value.currency)} · Sales tax: {amount(value.priceBreakdown.taxAmount,value.currency)} · Freight: {amount(value.priceBreakdown.freightAmount,value.currency)}{!value.priceBreakdown.totalComplete?' · Total is provisional: commercial charges remain unknown.':''}</p>}<p>{value.marginBasis}</p><Badge status={value.belowFloor?'warning':'success'}>{value.belowFloor?'Margin exception: below configured floor':'Within configured margin floor'}</Badge><p>Minimum margin: {value.minimumMarginPercent}%. Changed quote, costs or policy invalidates this review.</p></div>}
registry.page('commercial',{component:Workbench,icon:'chart'})
registry.slot('action-preview:commercial.apply-prices',PricePreview,{navigation:'commercial'})
