import React,{useEffect,useRef,useState} from 'react'
import {Button,ErrorNotice,Loading} from '../../webui/client/core.jsx'
import PdfWorker from '../../../../host/node_modules/pdfjs-dist/build/pdf.worker.min.mjs?worker'
/** Each preview owns its parser worker, loading task and bounded page canvas. */
export function PdfPreview({url,filename}){const canvas=useRef(),document=useRef(),[page,setPage]=useState(1),[pages,setPages]=useState(0),[ready,setReady]=useState(false),[error,setError]=useState('')
 useEffect(()=>{const controller=new AbortController();let worker,parser,loading,closed=false;setError('');setPages(0);setReady(false);setPage(1);(async()=>{try{const pdfjs=await import('../../../../host/node_modules/pdfjs-dist/build/pdf.mjs');if(closed)return;const response=await fetch(url,{signal:controller.signal,credentials:'same-origin'});if(!response.ok)throw new Error('The original PDF is unavailable.');const bytes=new Uint8Array(await response.arrayBuffer());if(closed)return;worker=new PdfWorker();parser=new pdfjs.PDFWorker({port:worker});loading=pdfjs.getDocument({data:bytes,worker:parser,isEvalSupported:false,stopAtErrors:true});const pdf=await loading.promise;if(closed){await pdf.destroy();return}document.current=pdf;setPages(pdf.numPages)}catch(error){if(!closed)setError(`PDF preview could not be rendered: ${error.message}. Download the original to open it in your PDF viewer.`)}})();return()=>{closed=true;controller.abort();document.current=null;loading?.destroy().catch(()=>{});parser?.destroy();worker?.terminate()}},[url])
 useEffect(()=>{if(!pages||!document.current)return;let task,closed=false;setReady(false);(async()=>{try{const pdfPage=await document.current.getPage(page);if(closed)return;const original=pdfPage.getViewport({scale:1}),scale=Math.min(1.5,1200/original.width,1600/original.height),viewport=pdfPage.getViewport({scale});canvas.current.width=Math.ceil(viewport.width);canvas.current.height=Math.ceil(viewport.height);task=pdfPage.render({canvas:canvas.current,viewport});await task.promise;if(!closed)setReady(true)}catch(error){if(!closed)setError(`PDF page could not be rendered: ${error.message}. Download the original.`)}})();return()=>{closed=true;task?.cancel()}},[page,pages])
 return <div className="artifact-stack"><ErrorNotice error={error}/>{!ready&&!error&&<Loading/>}<canvas ref={canvas} className="artifact-pdf-canvas" aria-label={`PDF page ${page}: ${filename}`} data-rendered={ready}/>{pages>0&&<div className="artifact-line"><Button variant="secondary" disabled={page<=1} onClick={()=>setPage(page-1)}>Previous PDF page</Button><span>Page {page} of {pages}</span><Button variant="secondary" disabled={page>=pages} onClick={()=>setPage(page+1)}>Next PDF page</Button></div>}<small>One page is rendered at a time, up to 1,200 × 1,600 pixels. Download the original for full resolution and all document features.</small></div>
}
