import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {mkdtempSync,mkdirSync,readFileSync,writeFileSync,existsSync} from 'node:fs'
import {resolve,join} from 'node:path'
import {createServer} from 'node:http'
import {spawn} from 'node:child_process'
import {createInterface} from 'node:readline'
import * as storePlugin from '../code/index.mjs'
import * as settingsPlugin from '../../settings/code/index.mjs'
import * as teamsPlugin from '../../teams/code/index.mjs'
import * as exchangePlugin from '../../exchange-workbench/code/index.mjs'
const require=createRequire(new URL('../../../../host/package.json',import.meta.url)),{Context}=require('cordis')
mkdirSync('tmp',{recursive:true});const root=mkdtempSync(resolve('tmp/exchange-smoke-')),checks=[],users=[{id:'buyer',name:'Buyer',role:'contractor'},{id:'supplier',name:'Supplier',role:'supplier'}],buyer=users[0],supplier=users[1],member={id:'member',name:'Member',role:'contractor',email:'member@example.test'},secret='fixture-private-pairing-only'
users.push(member);for(const user of users)user.email ||= `${user.id}@example.test`
async function mount(directory){const ctx=new Context(),fibers=[],routes=[];fibers.push(await ctx.plugin({name:'exchange-test-host',apply(inner){inner.provide('accounts',{list:()=>structuredClone(users),get:id=>users.find(row=>row.id===id),can:()=>true});inner.provide('web',{prefix:'/quotagent',contribute:()=>()=>{},route:(...args)=>{routes.push(args);return()=>routes.splice(routes.indexOf(args),1)}})}}));for(const plugin of [storePlugin,settingsPlugin,teamsPlugin,exchangePlugin])fibers.push(await ctx.plugin(plugin,plugin===storePlugin?{root:directory}:plugin===exchangePlugin?{retryIntervalMs:3600000,timeoutMs:400}:{}));const disposePolicy=ctx.store.exchangePolicy({id:'fixture-public',collections:['offers'],async prepare({from,record}){const event=ctx.store.events(from).filter(row=>row.type==='procurement/human-approved'&&row.body.recordId===record.id).at(-1);return{type:'fixture/offer',eventClass:record.commitment?'commitment':'fact',refs:{},approvals:record.commitment&&event?[{by:`human:${event.body.humanId}`,at:event.body.approvedAt,scope:{semantic:record},sourceRef:{realm:from,seq:event.seq,hash:event.entry_hash}}]:[]}},validate({record,metadata}){return record.reject?{ok:false,message:'Fixture domain refuses obsolete scope.'}:record.commitment&&(!metadata.approvals.length||JSON.stringify(metadata.approvals[0].scope.semantic)!==JSON.stringify(record))?{ok:false,message:'Decision scope mismatch.'}:{ok:true}},authority:({path,record})=>({owner:'sender',commitment:record.commitment&&path[0]==='amount'})});return{ctx,routes,close:async()=>{disposePolicy();for(const fiber of fibers.reverse())await fiber.dispose();assert.equal(routes.length,0);assert.equal(ctx.get('exchange'),undefined);assert.equal(ctx.get('store'),undefined)}}}
const ar=join(root,'left'),br=join(root,'right');let a=await mount(ar),b=await mount(br),server,port
async function approve(target,realm,record){await target.ctx.store.append(realm,'procurement/human-approved',{humanId:realm,recordId:record.id,approvedAt:new Date().toISOString(),scope:record},{actor:`human:${realm}`})}
const pair=async(target,user,peer,mode='manual',endpoint='')=>(await target.ctx.exchange.savePeer(user,{name:`Fixture ${peer.id}`,peerRealm:peer.id,role:peer.role,mode,channel:'fixture',pairingSecret:secret,endpoint})).peer
async function receive(target,user,source,id){return target.ctx.exchange.receive(user.id,(await source.ctx.store.package(source===a?'buyer':'supplier',id)).package,{user})}
const exportRow=async(target,realm,id)=>(await target.ctx.store.package(realm,id)).package
try{
 assert.equal(a.ctx.store.capabilities.protocol,'quotagent-store/2');assert.equal(a.ctx.store.capabilities.commit,false)
 const first={id:'cas',revision:1,amount:10};await a.ctx.store.put('buyer','local-only',first)
 const race=await Promise.allSettled([a.ctx.store.put('buyer','local-only',{...first,revision:2,amount:20},{expectedRevision:1}),a.ctx.store.put('buyer','local-only',{...first,revision:2,amount:30},{expectedRevision:1})]);assert.equal(race.filter(row=>row.status==='fulfilled').length,1);const conflict=race.find(row=>row.status==='rejected').reason;assert.equal(conflict.status,409);assert.equal(conflict.details.currentRevision,2)
 const version1=a.ctx.store.events('buyer').find(row=>row.body.collection==='local-only').seq;assert.equal(a.ctx.store.projection('buyer',{seq:version1,collection:'local-only'})['local-only'][0].amount,10)
 await a.ctx.store.append('buyer','fixture/malformed',{schema:'quotagent/workspace-record/v1',collection:'bad',record:null});assert.equal(a.ctx.store.health().buyer.recordMetadataDropped,1);assert.deepEqual(a.ctx.store.list('buyer','bad'),[])
 checks.push('Bridge capability negotiation, atomic compare-and-swap race, exact historical sequence projection, malformed metadata diagnostics')
 const ap=await pair(a,buyer,supplier),bp=await pair(b,supplier,buyer)
 const invitation=await a.ctx.teams.invite(buyer,{email:member.email,roleId:'lead'});await a.ctx.teams.answerInvite(member,invitation.id,true);await a.ctx.teams.select(member,'buyer')
 const shared=a.ctx.exchange.list(member);assert.equal(shared.realm,'buyer');assert.equal(shared.peers[0].id,ap.id);assert.equal(shared.canManageRoutes,false);assert.equal(shared.peers[0].ownerId,'buyer');assert.equal(JSON.stringify(shared).includes(secret),false)
 await assert.rejects(a.ctx.exchange.savePeer(member,{name:'Hidden conflicting route',peerRealm:'supplier',mode:'manual'}),/party workspace owner/);await assert.rejects(a.ctx.exchange.removePeer(member,ap.id),/party workspace owner/)
 checks.push('Real accepted team member sees selected party route metadata; only its explicit owner can configure credentials or create a competing hidden route')
 const offer={id:'offer',revision:1,amount:100,commitment:true,terms:{freight:5,note:'initial'},items:[{id:'line',amount:100}]};await assert.rejects(a.ctx.store.exchange('buyer','supplier','offers',offer),/approval/)
 await approve(a,'buyer',offer);const queued=await a.ctx.store.exchange('buyer','supplier','offers',offer);assert.equal(queued.status,'queued');assert.equal(queued.received,false);const original=await exportRow(a,'buyer',queued.msgId)
 assert.equal(JSON.stringify(a.ctx.store.events('buyer')).includes(secret),false)
 const tampered=structuredClone(original);tampered.envelope.body.record.amount=999;await assert.rejects(b.ctx.exchange.receive('supplier',tampered,{user:supplier}),/signature|hash/);assert.equal(b.ctx.store.get('supplier','offers','offer'),undefined);assert(b.ctx.store.events('supplier').some(row=>row.type==='exchange/package-rejected'))
 let incoming=await b.ctx.exchange.receive('supplier',original,{user:supplier});assert.equal(incoming.status,'applied');await a.ctx.exchange.receive('buyer',incoming.receipt,{user:buyer});assert.equal(a.ctx.store.get('buyer','exchange-outbox',queued.msgId).status,'delivered');assert.equal(b.ctx.store.get('supplier','offers','offer').amount,100)
 const acceptedCount=()=>b.ctx.store.events('supplier').filter(row=>row.type==='exchange/record-applied'&&row.body.record.id==='offer').length;await b.ctx.exchange.receive('supplier',original,{user:supplier});assert.equal(acceptedCount(),1)
 checks.push('Independent roots with explicit private pairing; real approved commitment, signature tampering refusal, exact public projection and signed receipt, duplicate applies once')
 const package1=await a.ctx.store.exchange('buyer','supplier','offers',{id:'gap-one',revision:1,amount:1}),package2=await a.ctx.store.exchange('buyer','supplier','offers',{id:'gap-two',revision:1,amount:2});const gap2=await exportRow(a,'buyer',package2.msgId),held=await b.ctx.exchange.receive('supplier',gap2,{user:supplier});assert.equal(held.status,'held');assert.equal(b.ctx.store.get('supplier','offers','gap-two'),undefined)
 await b.close();b=await mount(br);const filled=await b.ctx.exchange.receive('supplier',await exportRow(a,'buyer',package1.msgId),{user:supplier});assert.equal(filled.status,'applied');assert.equal(filled.released[0].status,'applied');for(const receipt of [filled.receipt,...filled.released.map(row=>row.receipt)])await a.ctx.exchange.receive('buyer',receipt,{user:buyer});assert.equal(b.ctx.store.get('supplier','offers','gap-two').amount,2)
 checks.push('Out-of-order signed packages stay held across restart; missing predecessor releases durable successor and receipts without a sequence skip')
 // The supplier retains private data absent from the signed public contract.
 await b.ctx.store.put('supplier','offers',{...offer,amount:110,privateCost:37,items:[{id:'line',amount:100,privateCost:23}]})
 const revised={...offer,revision:2,amount:120,terms:{freight:0},items:[{id:'line',amount:120}]};await approve(a,'buyer',revised);const q2=await a.ctx.store.exchange('buyer','supplier','offers',revised),c2=await b.ctx.exchange.receive('supplier',await exportRow(a,'buyer',q2.msgId),{user:supplier});assert.equal(c2.status,'conflict');assert.equal(b.ctx.store.get('supplier','offers','offer').amount,110);assert.equal(JSON.stringify(c2.conflicts).includes('privateCost'),false)
 await a.ctx.exchange.receive('buyer',c2.receipt,{user:buyer});assert.equal(a.ctx.store.get('buyer','exchange-outbox',q2.msgId).status,'conflict');await assert.rejects(b.ctx.exchange.resolveConflict(supplier,c2.id,{}),/Confirm/)
 const resolved=await b.ctx.exchange.resolveConflict(supplier,c2.id,{confirmed:true});assert.equal(resolved.inbox.status,'applied');assert.equal(b.ctx.store.get('supplier','offers','offer').amount,120);assert.equal(b.ctx.store.get('supplier','offers','offer').privateCost,37);assert.equal(b.ctx.store.get('supplier','offers','offer').items[0].privateCost,23);assert.equal(b.ctx.store.get('supplier','offers','offer').terms.freight,0);assert.equal(b.ctx.store.get('supplier','offers','offer').terms.note,undefined);await a.ctx.exchange.receive('buyer',resolved.inbox.receipt,{user:buyer});assert.equal(a.ctx.store.get('buyer','exchange-outbox',q2.msgId).status,'delivered')
 const rejected=await a.ctx.store.exchange('buyer','supplier','offers',{id:'bad-domain',reject:true});const rejection=await b.ctx.exchange.receive('supplier',await exportRow(a,'buyer',rejected.msgId),{user:supplier});assert.equal(rejection.status,'rejected');assert.equal(b.ctx.store.get('supplier','offers','bad-domain'),undefined)
 checks.push('Three-way commitment conflict preserves local value and private fields; original sender proof plus explicit recipient acceptance resolves exact incoming terms; domain rejection never projects')
 server=createServer(async(req,res)=>{let raw='';for await(const part of req)raw+=part;try{const value=await b.ctx.exchange.receive('supplier',JSON.parse(raw).packages||JSON.parse(raw).package);res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify(value))}catch(error){res.writeHead(error.status||400,{'content-type':'application/json'});res.end(JSON.stringify({error:error.message}))}});await new Promise(done=>server.listen(0,'127.0.0.1',done));port=server.address().port
 await a.ctx.exchange.savePeer(buyer,{...ap,mode:'http',endpoint:`http://127.0.0.1:${port}/receive`});const http=await a.ctx.store.exchange('buyer','supplier','offers',{id:'http',amount:250});assert.equal(http.status,'delivered')
 await new Promise(done=>server.close(done));const offline=await a.ctx.store.exchange('buyer','supplier','offers',{id:'outage',amount:360});assert.equal(offline.status,'failed');const frozen=await exportRow(a,'buyer',offline.msgId)
 await a.close();a=await mount(ar);await new Promise(done=>server.listen(port,'127.0.0.1',done));const retry=await a.ctx.exchange.retry(buyer,offline.msgId);assert.equal(retry.status,'delivered');assert.deepEqual(await exportRow(a,'buyer',offline.msgId),frozen)
 checks.push('Real loopback HTTP delivery, closed-port failure retained after local write, sender process restart and exact-byte retry without duplicate commitment')
 // Keep only the valid durable prefix ending immediately after QEP send.
 await a.ctx.exchange.savePeer(buyer,{...ap,mode:'manual'});const crash=await a.ctx.store.exchange('buyer','supplier','offers',{id:'crash-send',amount:42});const crashPackage=await exportRow(a,'buyer',crash.msgId);await a.close();const ledger=join(ar,'ledgers/buyer.jsonl'),rows=readFileSync(ledger,'utf8').trim().split('\n'),cut=rows.findIndex(line=>{const event=JSON.parse(line);return event.type==='kernel/qep-sent'&&event.body.msg_id===crash.msgId});writeFileSync(ledger,rows.slice(0,cut+1).join('\n')+'\n');a=await mount(ar);assert.equal(a.ctx.store.get('buyer','exchange-outbox',crash.msgId).status,'queued');assert.deepEqual(await exportRow(a,'buyer',crash.msgId),crashPackage)
 const firstReceive=await b.ctx.exchange.receive('supplier',crashPackage,{user:supplier});assert.equal(firstReceive.status,'applied');await b.close();const rightLedger=join(br,'ledgers/supplier.jsonl'),rightRows=readFileSync(rightLedger,'utf8').trim().split('\n'),rightCut=rightRows.findIndex(line=>{const event=JSON.parse(line);return event.type==='kernel/qep-received'&&event.body.msg_id===crash.msgId});assert(rightCut>=0);writeFileSync(rightLedger,rightRows.slice(0,rightCut+1).join('\n')+'\n');b=await mount(br);assert.equal(b.ctx.store.get('supplier','offers','crash-send'),undefined);const crashRetry=await b.ctx.exchange.receive('supplier',crashPackage,{user:supplier});assert.equal(crashRetry.status,'applied');assert.equal(b.ctx.store.events('supplier').filter(row=>row.type==='exchange/record-applied'&&row.body.record.id==='crash-send').length,1)
 checks.push('Crash-prefix recovery after signed send rebuilds missing outbox; crash after raw receive never projects until replay validates and applies exactly once')
 await a.ctx.settings.save(buyer,ap.configurationId,{clearSecrets:['pairingSecret']});await assert.rejects(a.ctx.store.exchange('buyer','supplier','offers',{id:'cleared',amount:1}),/pairing secret/);assert.equal(a.ctx.exchange.list(buyer).peers[0].paired,false)
 // One corrupted realm is quarantined, not repaired, while another remains usable.
 await a.close();writeFileSync(join(ar,'ledgers/broken.jsonl'),'not-json\n');a=await mount(ar);assert.equal(a.ctx.store.health().broken.healthy,false);for(const read of [()=>a.ctx.store.list('broken','anything'),()=>a.ctx.store.get('broken','anything','x'),()=>a.ctx.store.events('broken'),()=>a.ctx.store.projection('broken')])assert.throws(read,error=>error.status===503&&!!error.code&&!!error.nextAction);assert.deepEqual(a.ctx.store.list('new-realm','anything'),[]);await assert.rejects(a.ctx.store.put('broken','anything',{id:'x'}),/integrity|ledger|storage/i);await a.ctx.store.put('buyer','still-healthy',{id:'ok'});assert.equal(readFileSync(join(ar,'ledgers/broken.jsonl'),'utf8'),'not-json\n')
 checks.push('Clearing pairing credentials disables cached key use; corrupt ledger quarantine preserves original bytes and healthy account operations')

 const bridgeRoot=join(root,'handshake'),child=spawn('python3',['src/system/workspace-store/code/bridge.py',bridgeRoot],{stdio:['pipe','pipe','pipe']}),lines=createInterface({input:child.stdout}),pending=new Map();let rpc=0;lines.on('line',line=>{const response=JSON.parse(line);pending.get(response.id)?.(response);pending.delete(response.id)})
 const call=body=>new Promise(resolve=>{const rpcId=++rpc;pending.set(rpcId,resolve);child.stdin.write(JSON.stringify({...body,rpcId})+'\n')})
 try{assert.equal((await call({op:'hello',protocol:'obsolete/0'})).code,'PROTOCOL_VERSION');assert.equal((await call({op:'put',realm:'test',collection:'x',record:{id:'x'}})).code,'HANDSHAKE_REQUIRED');assert.equal(existsSync(join(bridgeRoot,'ledgers/test.jsonl')),false);assert.equal((await call({op:'hello',protocol:'quotagent-store/2'})).ok,true);assert.equal((await call({op:'commit',realm:'test'})).code,'OPERATION_UNAVAILABLE');assert.equal(JSON.parse(readFileSync(join(bridgeRoot,'ledgers/test.jsonl'),'utf8').trim()).type,'workspace/bridge-operation-denied')}finally{lines.close();child.kill()}
 checks.push('Incompatible bridge handshake produces zero events; no operation runs before negotiation; generic commit is explicitly unavailable and diagnosed')
 const report={at:new Date().toISOString(),root,checks,passed:checks.length};writeFileSync(join(root,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2))
}finally{if(server?.listening)await new Promise(done=>server.close(done));await a.close().catch(()=>{});await b.close().catch(()=>{})}
