import assert from 'node:assert/strict'
import {chromium} from '../../../../host/node_modules/playwright/index.mjs'
import {quotationFixture} from './protocol-fixture.mjs'
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs'
const base=process.env.BASE_URL||'http://127.0.0.1:8646/quotagent/',evidence=process.env.EVIDENCE_DIR||'tmp/agent-experience/exchange/local';mkdirSync(evidence,{recursive:true})
const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||'/opt/hermes/.playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell'}),pages=[],checks=[],responses=[],errors=[]
let fixture
const title=`[Exchange fixture] ${new Date().toISOString()}`,secret='local-gui-pairing-fixture-only',channel=`gui-${Date.now()}`
const field=(page,label)=>page.locator('label.field').filter({has:page.getByText(label,{exact:true})}).locator('input,textarea,select').first()
const shot=(page,name)=>page.screenshot({path:`${evidence}/${name}.png`,fullPage:true,animations:'disabled'})
async function post(page,path,trigger){const waiting=page.waitForResponse(response=>response.url().endsWith(`/api/${path}`)&&response.request().method()==='POST');await trigger();const response=await waiting,value=await response.json();responses.push({path,status:response.status(),value});assert.equal(response.status(),200,JSON.stringify(value));return value}
const click=(page,path,label)=>post(page,path,()=>page.getByRole('button',{name:label,exact:true}).click())
async function login(email){const page=await browser.newPage({viewport:{width:1450,height:1040}});pages.push(page);page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(20000);await page.goto(base);await page.getByLabel('Email address').fill(email);await page.getByLabel('Password',{exact:true}).fill('demo1234');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('navigation',{name:'Main navigation'}).waitFor();await page.getByRole('button',{name:'Not now',exact:true}).click({timeout:1500}).catch(()=>{});return page}
async function nav(page,name='Deliveries & exchange'){const navigation=page.getByRole('navigation',{name:'Main navigation'});await navigation.waitFor();await page.waitForTimeout(100);const button=navigation.getByRole('button',{name,exact:true});if(!await button.isVisible())await navigation.locator('.ws-nav-group').filter({has:page.getByRole('button',{name,exact:true,includeHidden:true})}).locator('.ws-group-toggle').click();const waiting=name==='Deliveries & exchange'?page.waitForResponse(response=>response.url().endsWith('/api/exchange')&&response.request().method()==='GET'):null;await button.click();if(waiting)return(await waiting).json()}
async function peer(page,data,other,role){await page.getByRole('button',{name:'Pair a partner',exact:true}).click();await field(page,'Peer name').fill('[Local fixture] '+other);await field(page,'Recipient realm ID').fill(other);await field(page,'Peer role').selectOption(role);await field(page,'Shared channel ID').fill(channel);await field(page,'Shared pairing secret').fill(secret);return(await click(page,'exchange/peers','Save delivery route')).peer}
async function download(page,label,name){const pending=page.waitForEvent('download');await page.getByRole('link',{name:label,exact:true}).click();await(await pending).saveAs(`${evidence}/${name}`);return JSON.parse(readFileSync(`${evidence}/${name}`,'utf8'))}
async function importFile(page,name){return post(page,'exchange/import',()=>page.getByLabel('Import QEP package or receipt',{exact:true}).setInputFiles(`${evidence}/${name}`))}
async function createRequest(page,label){await nav(page,'Requests');await page.getByRole('button',{name:'New request',exact:true}).click();await field(page,'Request title').fill(label);await field(page,'Project brief').fill('Labelled local protocol verification; no real order or external service.');await page.getByLabel('Item 1 description',{exact:true}).fill('Fixture panel');await page.getByLabel('Item 1 quantity',{exact:true}).fill('1');await page.locator('.supplier-options label').filter({hasText:'supplier@demo.local'}).getByRole('checkbox').check();const created=await click(page,'workspace/create-rfq','Save request draft');await page.getByRole('button',{name:'Publish request',exact:true}).click();const published=await click(page,'workspace/publish-rfq','Confirm & continue');return{created,published}}
try{
 const buyer=await login('contractor@demo.local'),supplier=await login('supplier@demo.local'),admin=await login('admin@demo.local'),buyerData=await nav(buyer),supplierData=await nav(supplier)
 const buyerPeer=await peer(buyer,buyerData,supplierData.realm,'supplier'),supplierPeer=await peer(supplier,supplierData,buyerData.realm,'contractor');assert(!JSON.stringify(buyerPeer).includes(secret));await buyer.getByRole('tab',{name:'Partner routes',exact:true}).click();await shot(buyer,'01-paired-routes')
 const request=await createRequest(buyer,title),rfqId=request.created.rfq.id;const sent=await nav(buyer),pending=sent.outbox.find(row=>row.recordId===rfqId);assert.equal(pending.status,'queued');await buyer.locator('.ex-delivery').filter({has:buyer.getByText(title,{exact:true})}).click();await download(buyer,'Download original package','request.qep.json');await shot(buyer,'02-pending-package');await buyer.getByRole('button',{name:'Close dialog',exact:true}).click()
 let received=await importFile(supplier,'request.qep.json');assert.equal(received.status,'applied');await download(supplier,'Download signed receipt','request-receipt.qep.json');await shot(supplier,'03-received-signed-receipt');await supplier.getByRole('button',{name:'Close dialog',exact:true}).click();const receipt=await importFile(buyer,'request-receipt.qep.json');assert.equal(receipt.delivery.status,'delivered')
 await nav(supplier,'Requests');await supplier.getByLabel('Search requests').fill(title);await supplier.getByRole('button').filter({has:supplier.getByRole('heading',{name:title,exact:true})}).click();await supplier.getByRole('heading',{name:title,exact:true}).waitFor()
 checks.push('Both business accounts configure private paired portable routes through GUI; contractor publication queues, exact package download/import reveals supplier request, signed receipt returns delivered')
 // A failed HTTP handoff must remain visible and retry the same message.
 await nav(buyer);await buyer.getByRole('tab',{name:'Partner routes',exact:true}).click();await buyer.getByRole('button',{name:'Edit route',exact:true}).click();await field(buyer,'Delivery method').selectOption('http');await field(buyer,'Peer receive URL').fill('http://127.0.0.1:1/fixture-offline');await click(buyer,'exchange/peers','Save delivery route');const second=await createRequest(buyer,title+' outage'),secondId=second.created.rfq.id;const failedData=await nav(buyer),failed=failedData.outbox.find(row=>row.recordId===secondId);assert.equal(failed.status,'failed');await buyer.locator('.ex-delivery').filter({has:buyer.getByText(title+' outage',{exact:true})}).click();const frozen=await download(buyer,'Download original package','outage-before.qep.json');await shot(buyer,'04-outage-retained');await buyer.getByRole('button',{name:'Close dialog',exact:true}).click()
 await buyer.getByRole('tab',{name:'Partner routes',exact:true}).click();await buyer.getByRole('button',{name:'Edit route',exact:true}).click();await field(buyer,'Peer receive URL').fill(new URL(`api/exchange/receive/${supplierData.realm}`,base).href);await click(buyer,'exchange/peers','Save delivery route');await buyer.getByRole('tab',{name:'Sent & pending',exact:true}).click();await buyer.locator('.ex-delivery').filter({has:buyer.getByText(title+' outage',{exact:true})}).click();const retried=await click(buyer,`exchange/${failed.id}/retry`,'Retry exact delivery');assert.equal(retried.status,'delivered');assert.deepEqual(await download(buyer,'Download original package','outage-after.qep.json'),frozen);await shot(buyer,'05-retry-delivered');await buyer.getByRole('button',{name:'Close dialog',exact:true}).click()
 checks.push('Failed HTTP handoff preserves approved business record; GUI corrects endpoint and retries exact signed bytes, with recipient receipt verified')
 // A separate native Ledger/QEP fixture authors two competing signed quote
 // branches from the same acknowledged base. Application imports and the local
 // human conflict decision all occur through visible GUI controls.
 await buyer.getByRole('tab',{name:'Partner routes',exact:true}).click();await click(buyer,'exchange/peers','Disable');await buyer.getByRole('button',{name:'Pair a partner',exact:true}).click();await field(buyer,'Peer name').fill('[Local fixture] Concurrent quotation branch');await field(buyer,'Recipient realm ID').fill(supplierData.realm);await field(buyer,'Peer role').selectOption('supplier');await field(buyer,'Shared channel ID').fill(channel+'-conflict');await field(buyer,'Shared pairing secret').fill(secret);await click(buyer,'exchange/peers','Save delivery route')
 fixture=await quotationFixture({buyer:buyerData.realm,supplier:supplierData.realm,rfq:request.published.rfq,channel:channel+'-conflict',secret,evidence});await fixture.offer(1,100,'quote-v1.qep.json');received=await importFile(buyer,'quote-v1.qep.json');assert.equal(received.status,'applied');const firstQuoteReceipt=await download(buyer,'Download signed receipt','quote-v1-receipt.qep.json');await fixture.receipt(firstQuoteReceipt);await buyer.getByRole('button',{name:'Close dialog',exact:true}).click()
 await fixture.offer(2,110,'quote-branch-a.qep.json');await fixture.offer(3,120,'quote-branch-b.qep.json');received=await importFile(buyer,'quote-branch-a.qep.json');assert.equal(received.status,'applied');await buyer.getByRole('button',{name:'Close dialog',exact:true}).click();received=await importFile(buyer,'quote-branch-b.qep.json');assert.equal(received.status,'conflict');await buyer.getByRole('heading',{name:'Changes requiring review',exact:true}).waitFor();await shot(buyer,'06-conflict-before-decision');assert.equal(await buyer.getByRole('button',{name:'Accept reviewed incoming version',exact:true}).isEnabled(),false);await buyer.getByRole('checkbox',{name:'I reviewed the differences and accept the exact received record.',exact:true}).check();const accepted=await click(buyer,`exchange/${received.id}/resolve`,'Accept reviewed incoming version');assert.equal(accepted.inbox.status,'applied');await buyer.getByText('Signed receipt: applied',{exact:true}).waitFor();await shot(buyer,'07-conflict-reviewed');await buyer.getByRole('button',{name:'Close dialog',exact:true}).click();await fixture.close();fixture=null
 checks.push('Independent labelled QEP supplier fixture sends concurrent committed quote branches; GUI shows base/current/incoming differences, requires exact human confirmation, and retains applied receipt')
 await buyer.getByRole('tab',{name:'History',exact:true}).click();await field(buyer,'Collection').selectOption('rfqs');await buyer.getByRole('button',{name:'Rebuild history',exact:true}).click();await buyer.locator('.ex-json').filter({hasText:rfqId}).waitFor();await shot(buyer,'06-historical-projection');await buyer.reload();await nav(buyer);await buyer.locator('.ex-delivery').filter({has:buyer.getByText(title+' outage',{exact:true})}).click();await buyer.getByText('Signed receipt: applied',{exact:true}).waitFor();await buyer.getByRole('button',{name:'Close dialog',exact:true}).click();await buyer.setViewportSize({width:390,height:844});await buyer.waitForTimeout(150);assert.equal(await buyer.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);await shot(buyer,'07-mobile-delivery')
 await nav(admin);await admin.getByRole('heading',{name:'Exchange storage health',exact:true}).waitFor();await shot(admin,'08-admin-health');assert.equal(await admin.getByText(title,{exact:true}).count(),0);assert.deepEqual(errors,[])
 checks.push('Accepted history reconstructed through GUI, receipt retained after reload, mobile delivery screen fits viewport; separate admin sees storage metadata without private record titles')
 const report={ok:true,at:new Date().toISOString(),base,title,rfqId,checks,jsErrors:errors};writeFileSync(`${evidence}/report.json`,JSON.stringify(report,null,2));writeFileSync(`${evidence}/responses.json`,JSON.stringify(responses,null,2));console.log(JSON.stringify(report,null,2))
}catch(error){for(const [i,page]of pages.entries()){await shot(page,`failure-${i}`).catch(()=>{});writeFileSync(`${evidence}/failure-${i}.txt`,await page.locator('body').innerText().catch(()=>''))}writeFileSync(`${evidence}/failure.json`,JSON.stringify({error:error.stack,checks,responses,errors},null,2));throw error}finally{if(fixture)await fixture.close();await browser.close()}
