import assert from 'node:assert/strict'
import {chromium} from '../../../../host/node_modules/playwright/index.mjs'
import {createServer} from 'node:http'
import {mkdirSync,writeFileSync} from 'node:fs'
import {quotationFixture} from './protocol-fixture.mjs'
const base=process.env.BASE_URL||'http://127.0.0.1:8650/quotagent/',out=process.env.EVIDENCE_DIR||'tmp/agent-experience/resend-browser';mkdirSync(out,{recursive:true})
const browser=await chromium.launch({headless:true,executablePath:'/opt/hermes/.playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell'}),page=await browser.newPage({viewport:{width:1440,height:1000}}),report={at:new Date().toISOString(),base,checks:[],errors:[],screenshots:[]};let fixture,server
page.setDefaultTimeout(20000);page.on('pageerror',error=>report.errors.push(error.message));const secret='local-gui-resend-fixture-only',channel=`resend-${Date.now()}`
const field=label=>page.locator('label.field').filter({has:page.getByText(label,{exact:true})}).locator('input,select').first(),shot=async name=>{await page.screenshot({path:`${out}/${name}`,fullPage:true});report.screenshots.push(name)}
async function post(path,trigger){const waiting=page.waitForResponse(response=>response.url().endsWith('/api'+path)&&response.request().method()==='POST');await trigger();const response=await waiting,value=await response.json();assert.equal(response.status(),200,JSON.stringify(value));return value}
async function nav(){const navigation=page.getByRole('navigation',{name:'Main navigation'}),button=navigation.getByRole('button',{name:'Deliveries & exchange',exact:true});await navigation.getByRole('button',{name:'Deliveries & exchange',exact:true,includeHidden:true}).waitFor({state:'attached'});if(!await button.isVisible())await navigation.locator('.ws-nav-group').filter({has:page.getByRole('button',{name:'Deliveries & exchange',exact:true,includeHidden:true})}).locator('.ws-group-toggle').click();await button.click()}
try{
 await page.goto(base);await page.getByLabel('Email address',{exact:true}).fill('contractor@demo.local');await page.getByLabel('Password',{exact:true}).fill('demo1234');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('navigation',{name:'Main navigation'}).waitFor();await page.getByRole('button',{name:'Not now',exact:true}).click({timeout:1500}).catch(()=>{})
 const workspace=await(await page.request.get(new URL('api/workspace',base).href)).json(),rfq=workspace.rfqs.find(row=>row.status==='published'&&row.supplierIds.includes('supplier-demo'));assert(rfq,'Labelled seeded request must exist')
 fixture=await quotationFixture({buyer:'contractor-demo',supplier:'supplier-demo',rfq,channel,secret,evidence:out});const first=await fixture.offer(1,100,'first.qep.json'),second=await fixture.offer(2,100,'second.qep.json');report.quoteId=fixture.id;report.firstMessageId=first.queued.msgId
 server=createServer(async(req,res)=>{let raw='';for await(const part of req)raw+=part;try{const value=await fixture.recovery(JSON.parse(raw).packages);res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify(value))}catch(error){res.writeHead(error.status||500,{'content-type':'application/json'});res.end(JSON.stringify({error:error.message}))}});await new Promise(done=>server.listen(0,'127.0.0.1',done))
 await nav();await page.getByRole('tab',{name:'Partner routes',exact:true}).click();const old=page.locator('.ex-peer').filter({hasText:'[Local protocol fixture] Missing quote recovery'});for(const element of await old.all()){const disable=element.getByRole('button',{name:'Disable',exact:true});if(await disable.isVisible())await post('/exchange/peers',()=>disable.click())}await page.getByRole('button',{name:'Pair a partner',exact:true}).click();await field('Peer name').fill('[Local protocol fixture] Missing quote recovery');await field('Recipient realm ID').fill('supplier-demo');await field('Peer role').selectOption('supplier');await field('Delivery method').selectOption('http');await field('Shared channel ID').fill(channel);await field('Shared pairing secret').fill(secret);await field('Peer receive URL').fill(`http://127.0.0.1:${server.address().port}/receive`);await post('/exchange/peers',()=>page.getByRole('button',{name:'Save delivery route',exact:true}).click())
 const held=await post('/exchange/import',()=>page.getByLabel('Import QEP package or receipt',{exact:true}).setInputFiles(`${out}/second.qep.json`));assert.equal(held.status,'held');await page.getByText('Missing earlier sequences: 1. Deliver those first; this record has not advanced.',{exact:true}).waitFor();await shot('01-successor-held.png');await page.getByRole('button',{name:'Close dialog',exact:true}).click();await page.getByRole('tab',{name:'Recovery',exact:true}).click();await page.locator('.ex-delivery').filter({hasText:'Recover missing sequences 1'}).first().click();await page.getByRole('heading',{name:'Missing-message recovery',exact:true}).waitFor();await shot('02-signed-request.png');report.checks.push('GUI pairs a labelled independent fixture, imports an out-of-order signed quotation and shows the held successor plus durable recovery request instead of skipping a sequence')
 const result=await post(`/exchange/${held.resendRequestId}/retry`,()=>page.getByRole('button',{name:'Retry recovery request',exact:true}).click());assert.equal(result.status,'fulfilled');await page.getByText('All requested original messages are now recorded.',{exact:true}).waitFor();await page.getByText(first.queued.msgId,{exact:true}).waitFor();await shot('03-original-recovered.png');await page.getByRole('button',{name:'Close dialog',exact:true}).click();await page.getByRole('tab',{name:'Received',exact:true}).click();const current=await(await page.request.get(new URL('api/exchange',base).href)).json();assert.equal(current.inbox.find(row=>row.id===first.queued.msgId).status,'applied');assert.equal(current.inbox.find(row=>row.id===second.queued.msgId).status,'applied');report.checks.push('Visible recovery retry sends the signed request over actual loopback HTTP, retrieves the original missing quote, releases the successor and records exact original message identity without new commercial approval')
 await page.reload();await nav();await page.getByRole('tab',{name:'Recovery',exact:true}).click();await page.locator('.ex-delivery').filter({hasText:'Recover missing sequences 1'}).first().click();await page.getByText('All requested original messages are now recorded.',{exact:true}).waitFor();await page.setViewportSize({width:390,height:844});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await shot('04-mobile-recovered.png');assert.deepEqual(report.errors,[]);report.checks.push('Fulfilled request and original IDs survive full reload; recovery dialog fits390px with zero JavaScript errors');report.ok=true
}catch(error){report.error=error.stack;process.exitCode=1;await shot('failure.png').catch(()=>{});writeFileSync(`${out}/failure.txt`,await page.locator('body').innerText().catch(()=>''))}finally{if(server?.listening)await new Promise(done=>server.close(done));if(fixture)await fixture.close();await browser.close();writeFileSync(`${out}/report.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2))}
