import {mkdirSync,readFileSync,existsSync,writeFileSync,renameSync,readdirSync,unlinkSync,chmodSync} from 'node:fs'
import {join,basename} from 'node:path'
import {randomUUID,createHash} from 'node:crypto'
import {createRequire} from 'node:module'
const require=createRequire(new URL('../../../../host/package.json',import.meta.url)),yaml=require('yaml')
const copy=value=>structuredClone(value),now=()=>new Date().toISOString(),fail=(message,status=400)=>{throw Object.assign(new Error(message),{status})},GLOBAL='system',order=['workspace','project','section']
const stable=value=>Array.isArray(value)?value.map(stable):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().filter(key=>value[key]!==undefined).map(key=>[key,stable(value[key])])):value
const digest=value=>createHash('sha256').update(JSON.stringify(stable(value))).digest('hex')
const plain=value=>value&&typeof value==='object'&&!Array.isArray(value)
export async function createSettings(ctx,config={}){
 const schemas=new Map(),scopeProviders=new Map(),vetoes=new Map(),held=new Map(),directory=join(ctx.store.root,'settings'),journals=join(directory,'transactions'),secretFile=join(directory,'credentials.json');let heldSecrets=null,pending=Promise.resolve(),disposed=false,initTimer=null,initializing=false,initialization={status:'not-configured'}
 mkdirSync(journals,{recursive:true,mode:0o700});chmodSync(directory,0o700);chmodSync(journals,0o700);let secrets=existsSync(secretFile)?JSON.parse(readFileSync(secretFile,'utf8')):{}
 if(existsSync(secretFile))chmodSync(secretFile,0o600)
 const atomic=(filename,value)=>{const temporary=`${filename}.${process.pid}.${randomUUID()}.tmp`;writeFileSync(temporary,JSON.stringify(value,null,2)+'\n',{mode:0o600});chmodSync(temporary,0o600);renameSync(temporary,filename)}
 const writeSecrets=value=>{atomic(secretFile,value);secrets=value}
 const schema=id=>schemas.get(id)||fail('This plugin has not registered editable settings.',404)
 const authorize=(user,definition,write=false)=>{if(!user?.id)fail('Please sign in.',401);if(definition.ownerId&&definition.ownerId!==user.id)fail('These settings belong to another account.',403);if(definition.scope==='admin'&&user.role!=='admin')fail('Only administrators can configure this application plugin.',403);if(write&&user.role!=='admin'&&!ctx.accounts.can(user,'plugins:manage'))fail('Your administrator has disabled plugin configuration.',403)}
 const baseRealm=(user,definition)=>definition.scope==='account'?user?.id:!user||user.role==='admin'||definition.scope==='admin'?GLOBAL:user.id
 const record=(realm,id)=>{const key=realm+':'+id;return held.has(key)?held.get(key):ctx.store.get(realm,'plugin-settings',id)}
 const defaults=definition=>copy(typeof definition.defaults==='function'?definition.defaults():definition.defaults||{})
 const hasScope=(id,user,context)=>id==='workspace'?!!(context.workspaceId||user?.workspaceOwnerId):!!context[id+'Id']
 const scopeTarget=(user,definition,scope,context={},write=false)=>{
  authorize(user,definition,write)
  if(!scope||scope==='account'||scope==='global'){const realmId=baseRealm(user,definition);if(scope==='global'&&realmId!==GLOBAL)fail('Only administrators may change shared defaults.',403);return{scope:realmId===GLOBAL?'global':'account',realmId,recordId:definition.id,key:realmId,label:realmId===GLOBAL?'Shared defaults':'My account',context:{}}}
  if(definition.scope==='account'||!(definition.scopes||[]).includes(scope))fail('This plugin does not support that configuration scope.')
  const provider=scopeProviders.get(scope);if(!provider)fail('The plugin that owns this scope is unavailable.',409)
  const resolved=provider.resolve(user,{...context,workspaceId:context.workspaceId||user.workspaceOwnerId},{write});if(!resolved?.realmId||!resolved?.key)fail('Choose an accessible configuration scope.',403)
  return{scope,realmId:resolved.realmId,recordId:`${definition.id}@${scope}:${digest(String(resolved.key)).slice(0,24)}`,key:String(resolved.key),label:resolved.label||String(resolved.key),context:copy(context)}
 }
 const resolve=(user,id,context={})=>{
  const definition=schema(id);if(definition.ownerId||definition.scope==='account')authorize(user,definition)
  const credentialState=heldSecrets||secrets,originDefaults=definition.origins?.(user)||{},values=defaults(definition),provenance={},shadowed={}
  for(const key of Object.keys(values))provenance[key]={source:originDefaults[key]?.source||'default',layer:'schema',reference:originDefaults[key]?.reference||`plugin:${id}`,editable:definition.fields.some(field=>field.key===key)}
  const layers=[],realmId=baseRealm(user,definition)
  if(definition.scope!=='account')layers.push({realmId:GLOBAL,recordId:id,scope:'global',label:'Shared defaults'})
  if(realmId!==GLOBAL)layers.push({realmId,recordId:id,scope:'account',label:'My account'})
  for(const scope of order)if((definition.scopes||[]).includes(scope)&&hasScope(scope,user,context))layers.push(scopeTarget(user,definition,scope,context))
  const globalValues={...values,...(definition.scope==='account'?{}:record(GLOBAL,id)?.values||{}),...(definition.scope==='account'?{}:credentialState[GLOBAL]?.[id]||{})},overriddenKeys=[]
  for(const layer of layers){const saved=record(layer.realmId,layer.recordId),patch=saved?.values||{},passwords=['global','account'].includes(layer.scope)?credentialState[layer.realmId]?.[id]||{}:{}
   for(const[key,value]of Object.entries({...patch,...passwords})){shadowed[key]||=[];shadowed[key].push(provenance[key]);values[key]=value;provenance[key]={source:saved?.origins?.[key]?.source||'runtime',layer:layer.scope,scopeLabel:layer.label,reference:saved?.origins?.[key]?.reference||saved?.transactionId||saved?.updatedAt||'legacy override',patchId:saved?.origins?.[key]?.transactionId||saved?.transactionId||null,changedBy:saved?.changedBy||null};if(layer.realmId===realmId)overriddenKeys.push(key)}
  }
  const effective=definition.resolve?definition.resolve(values,{user,globalValues,overriddenKeys:[...new Set(overriddenKeys)],context}):values
  return{definition,values:effective,provenance:Object.fromEntries(Object.keys(provenance).map(key=>[key,{...provenance[key],shadowed:shadowed[key]||[]}])),layers}
 }
 const get=(user,id,context={})=>resolve(user,id,context).values
 const scopes=(user,id,context={})=>{const definition=schema(id);authorize(user,definition);const base=scopeTarget(user,definition);return[{id:base.scope,label:base.label,scope:base.scope,context:{}},...(definition.scopes||[]).flatMap(scope=>{const provider=scopeProviders.get(scope);return provider?(provider.list(user,context)||[]).map(item=>({...copy(item),scope,context:copy(item.context||{})})):[]})]}
 const view=(user,id,context={},targetScope)=>{
  const {definition,values,provenance}=resolve(user,id,context);authorize(user,definition);const target=scopeTarget(user,definition,targetScope,context),saved=record(target.realmId,target.recordId),configuredSecrets=[],overriddenKeys=new Set(Object.keys(saved?.values||{}))
  for(const field of definition.fields)if(field.type==='password'){if(values[field.key])configuredSecrets.push(field.key);if(Object.hasOwn((heldSecrets||secrets)[target.realmId]?.[id]||{},field.key))overriddenKeys.add(field.key);values[field.key]='';provenance[field.key]={...provenance[field.key],writeOnly:true}}
  return{id,name:definition.name||id,description:definition.description||'',fields:copy(definition.fields),values,configuredSecrets,overriddenKeys:[...overriddenKeys],scope:target.scope==='global'?'global':'personal',target,availableScopes:scopes(user,id,context),provenance,hasOverrides:overriddenKeys.size>0,revision:saved?.updatedAt||null,transactionId:saved?.transactionId||null}
 }
 const validate=(field,value)=>{if(field.type==='boolean'){if(typeof value!=='boolean')fail(`${field.label} must be on or off.`);return value}if(field.type==='number'){const number=Number(value);if(value===''||!Number.isFinite(number)||field.min!==undefined&&number<field.min||field.max!==undefined&&number>field.max)fail(`Enter a valid ${field.label.toLowerCase()}.`);return number}const text=field.type==='select'?String(value??''):String(value??'').trim();if(text.length>(field.maxLength||16000))fail(`${field.label} is too long.`);if(field.required&&!text)fail(`${field.label} is required.`);if(field.type==='color'&&!/^#[\da-f]{6}$/i.test(text))fail('Use a six-digit color.');if(field.type==='select'&&!(field.options||[]).map(option=>typeof option==='object'?String(option.value):String(option)).includes(text))fail(`Choose a valid ${field.label.toLowerCase()}.`);return text}
 const prepareCandidate=async(user,input={})=>{
  if(disposed)fail('Settings are reloading.',409);if(!Array.isArray(input.changes)||!input.changes.length||input.changes.length>100)fail('Choose between one and100 configuration patches.')
  if(!['merge','initialize'].includes(input.mode||'merge'))fail('Choose merge or initialize mode.');const plans=[],seen=new Set(),source=input.source?.kind==='file'?'file':'runtime',reference=source==='file'?String(input.source.filename||'uploaded.yaml').slice(0,160):'settings GUI'
  for(const change of input.changes){const definition=schema(change.id),context=plain(change.context)?change.context:{},target=scopeTarget(user,definition,change.scope,context,true),key=target.realmId+':'+target.recordId;if(seen.has(key))fail('A bundle cannot update the same schema/scope twice.');seen.add(key);const beforeRecord=record(target.realmId,target.recordId),before=get(user,change.id,context),oldSecrets=copy((heldSecrets||secrets)[target.realmId]?.[change.id]||{}),values=copy(beforeRecord?.values||{}),nextSecrets=copy(oldSecrets),origins=copy(beforeRecord?.origins||{}),known=new Map(definition.fields.map(field=>[field.key,field]));let skipped=false
   if(input.mode==='initialize'&&(Object.keys(values).length||['global','account'].includes(target.scope)&&Object.keys(oldSecrets).length))skipped=true
   if(change.reset===true){for(const key of Object.keys(values))delete values[key];for(const key of Object.keys(origins))delete origins[key];if(['global','account'].includes(target.scope))for(const key of Object.keys(nextSecrets))delete nextSecrets[key]}
   if(change.context!==undefined&&!plain(change.context))fail('Configuration context must be a mapping.');if(change.clearSecrets!==undefined&&!Array.isArray(change.clearSecrets))fail('Credential removal must be a list.');if(!plain(change.values||{}))fail('Settings values must be a mapping.')
   for(const[key,value]of Object.entries(change.values||{})){const field=known.get(key);if(!field)fail(`Unknown setting: ${key}`);const normalized=validate(field,value);if(field.type==='password'){if(!['global','account'].includes(target.scope))fail('Credentials cannot be written to a project or shared workspace.');if(normalized)nextSecrets[key]=normalized}else{values[key]=normalized;origins[key]={source,reference}}}
   for(const key of change.clearSecrets||[]){if(known.get(key)?.type!=='password'||!['global','account'].includes(target.scope))fail('Only account connection credentials may be cleared.');nextSecrets[key]=''}
   plans.push({id:change.id,definition,target,beforeRecord:copy(beforeRecord||null),before,values,origins,oldSecrets,nextSecrets,skipped,baseDigest:digest({record:beforeRecord||null,secrets:oldSecrets})})
  }
  // All layers in one bundle are resolved together. No await occurs while this temporary read view exists.
  const previousHeld=new Map(held),previousSecrets=secrets,previousHeldSecrets=heldSecrets,candidateSecrets=copy(heldSecrets||secrets)
  try{heldSecrets=null;for(const plan of plans.filter(row=>!row.skipped)){held.set(plan.target.realmId+':'+plan.target.recordId,{...plan.beforeRecord,id:plan.target.recordId,values:plan.values,origins:plan.origins});if(['global','account'].includes(plan.target.scope)){candidateSecrets[plan.target.realmId]||={};candidateSecrets[plan.target.realmId][plan.id]=plan.nextSecrets}}secrets=candidateSecrets;for(const plan of plans)plan.next=get(user,plan.id,plan.target.context)}finally{secrets=previousSecrets;heldSecrets=previousHeldSecrets;held.clear();for(const[key,value]of previousHeld)held.set(key,value)}
  for(const plan of plans){const{definition,next,before,target,skipped}=plan,context=target.context
   if(!skipped){if(definition.validate)await definition.validate(copy(next),{user,previous:copy(before),context});for(const hook of [definition.preflight,...(vetoes.get(plan.id)||[])].filter(Boolean)){const result=await hook(copy(next),{user,previous:copy(before),context,target:copy(target),dryRun:true});if(result===false||result?.allowed===false)fail(result?.reason||`${definition.name||plan.id} rejected this configuration.`,409)}}
   plan.fields=definition.fields.map(field=>{const secret=field.type==='password',oldValue=secret?(before[field.key]?'Configured':'Not configured'):before[field.key],newValue=secret?(next[field.key]?'Configured':'Not configured'):next[field.key],changed=secret?digest(before[field.key]||'')!==digest(next[field.key]||''):digest(oldValue??null)!==digest(newValue??null);return{key:field.key,label:field.label,secret,before:oldValue??null,after:newValue??null,changed}}).filter(row=>row.changed)
  }
  const previewId=digest(plans.map(plan=>({id:plan.id,target:plan.target,values:plan.values,secrets:digest(plan.nextSecrets),base:plan.baseDigest,skipped:plan.skipped})))
  return{plans,preview:{previewId,mode:input.mode||'merge',source,reference,changes:plans.map(({id,target,fields,skipped})=>({id,name:schema(id).name||id,target,fields,skipped})),changedFields:plans.reduce((sum,row)=>sum+(row.skipped?0:row.fields.length),0),secretValuesReturned:false}}
 }
 const safeReason=(error,input={})=>{let reason=String(error.message||error);const passwords=Object.values(secrets).flatMap(realm=>Object.values(realm).flatMap(values=>Object.values(values)));for(const change of input.changes||[])for(const field of schemas.get(change.id)?.fields||[])if(field.type==='password')passwords.push(change.values?.[field.key]);for(const value of passwords.filter(value=>typeof value==='string'&&value.length).sort((a,b)=>b.length-a.length))reason=reason.split(value).join('[credential redacted]');return reason.slice(0,400)}
 const prepare=async(user,input={})=>{try{return await prepareCandidate(user,input)}catch(error){throw Object.assign(new Error(safeReason(error,input)),{status:error.status||400})}}
 const preview=async(user,input)=>(await prepare(user,input)).preview
 const restoreJournal=async journal=>{const failures=[];for(const plan of journal.plans){try{await ctx.store.put(plan.target.realmId,'plugin-settings',plan.beforeRecord||{id:plan.target.recordId,values:{},origins:{}},{actor:'system:settings',event:'settings/config-rolled-back'})}catch(error){failures.push({scope:plan.target.scope,id:plan.id,code:error.code||'RESTORE_FAILED'})}}const restored=copy(secrets);for(const plan of journal.plans){restored[plan.target.realmId]||={};restored[plan.target.realmId][plan.id]=plan.oldSecrets}writeSecrets(restored);return failures}
 // The private journal is recovery material, never returned through an HTTP view.
 for(const filename of readdirSync(journals).filter(value=>value.endsWith('.json'))){const path=join(journals,filename),journal=JSON.parse(readFileSync(path,'utf8'));if(journal.status==='committed'){unlinkSync(path);continue}const failures=await restoreJournal(journal);await ctx.store.append(journal.actorId,'settings/transaction-recovered',{transactionId:journal.id,status:failures.length?'recovery-incomplete':'rolled-back',failures},{actor:'system:settings'}).catch(()=>{});if(!failures.length)unlinkSync(path)}
 const apply=async(user,input={})=>{const operation=async()=>{
  let prepared;try{prepared=await prepare(user,input);if(input.previewId&&input.previewId!==prepared.preview.previewId)fail('Configuration changed after preview. Preview again before applying.',409)}catch(error){if(user?.id)await ctx.store.append(user.id,'settings/transaction-refused',{stage:'preflight',reason:safeReason(error,input),rolledBack:false,applied:false},{actor:user.id}).catch(()=>{});throw error}
  const plans=prepared.plans.filter(plan=>!plan.skipped),id=randomUUID(),journal={id,actorId:user.id,status:'prepared',createdAt:now(),plans:plans.map(({id,target,beforeRecord,oldSecrets})=>({id,target,beforeRecord,oldSecrets}))},filename=join(journals,id+'.json'),applied=[];if(!plans.length)return{ok:true,skipped:true,...prepared.preview}
  atomic(filename,journal);heldSecrets=copy(secrets);for(const plan of plans)held.set(plan.target.realmId+':'+plan.target.recordId,plan.beforeRecord)
  try{await ctx.store.append(user.id,'settings/transaction-prepared',{transactionId:id,source:prepared.preview.source,reference:prepared.preview.reference,changes:prepared.preview.changes},{actor:user.id})
   const nextSecrets=copy(secrets)
   for(const plan of plans){const saved={id:plan.target.recordId,schemaId:plan.id,values:plan.values,origins:Object.fromEntries(Object.entries(plan.origins).map(([key,value])=>[key,{...value,transactionId:value.transactionId||id}])),scope:plan.target.scope,context:plan.target.context,updatedAt:now(),changedBy:user.id,transactionId:id};await ctx.store.put(plan.target.realmId,'plugin-settings',saved,{actor:user.id,event:'settings/config-saved'});if(['global','account'].includes(plan.target.scope)){nextSecrets[plan.target.realmId]||={};nextSecrets[plan.target.realmId][plan.id]=plan.nextSecrets}}
   writeSecrets(nextSecrets)
   for(const plan of plans){applied.push(plan);if(plan.definition.onChange){const rollback=await plan.definition.onChange(copy(plan.next),{user,previous:copy(plan.before),context:copy(plan.target.context),transactionId:id});if(typeof rollback==='function')plan.rollback=rollback}}
   await ctx.store.append(user.id,'settings/transaction-applied',{transactionId:id,source:prepared.preview.source,reference:prepared.preview.reference,changes:prepared.preview.changes},{actor:user.id});atomic(filename,{...journal,status:'committed'});unlinkSync(filename);return{ok:true,transactionId:id,...prepared.preview}
  }catch(error){const failures=await restoreJournal(journal);for(const plan of applied.reverse())try{if(plan.rollback)await plan.rollback();else if(plan.definition.rollback)await plan.definition.rollback(copy(plan.before),{user,failed:copy(plan.next),context:copy(plan.target.context),transactionId:id})}catch{failures.push({id:plan.id,code:'PLUGIN_ROLLBACK_FAILED'})}await ctx.store.append(user.id,'settings/transaction-refused',{transactionId:id,reason:safeReason(error,input),rolledBack:!failures.length,failures},{actor:user.id}).catch(()=>{});if(!failures.length)unlinkSync(filename);throw Object.assign(new Error(failures.length?'Configuration failed and needs recovery. Inspect transaction status before changing it again.':`Configuration was not applied; previous values restored. ${safeReason(error,input)}`),{status:409,transactionId:id,rolledBack:!failures.length})
  }finally{heldSecrets=null;for(const plan of plans)held.delete(plan.target.realmId+':'+plan.target.recordId)}
 };const result=pending.then(operation);pending=result.catch(()=>{});return result}
 const save=async(user,id,input={})=>{const result=await apply(user,{changes:[{id,...input}],previewId:input.previewId,source:input.source});return{...result,...view(user,id,input.context||{},input.scope)}}
 const list=user=>[...schemas.values()].filter(definition=>(definition.scope!=='admin'||user?.role==='admin')&&(!definition.ownerId||definition.ownerId===user?.id)).map(definition=>view(user,definition.id))
 const define=definition=>{if(!/^[\w.-]+$/.test(definition.id||'')||schemas.has(definition.id))throw new Error('Settings ID is invalid or already registered.');if(!Array.isArray(definition.fields))throw new Error('A settings schema needs fields.');const keys=new Set();for(const field of definition.fields){if(!field.key||keys.has(field.key)||!['text','textarea','password','number','boolean','select','color'].includes(field.type))throw new Error(`Invalid settings field in ${definition.id}`);keys.add(field.key)}if((definition.scopes||[]).some(scope=>!order.includes(scope)))throw new Error('Unsupported layered configuration scope.');schemas.set(definition.id,{scope:'user',...definition});scheduleInit();return()=>schemas.delete(definition.id)}
 const registerScope=provider=>{if(!order.includes(provider.id)||scopeProviders.has(provider.id)||typeof provider.list!=='function'||typeof provider.resolve!=='function')throw new Error('Scope provider needs a unique supported ID, list and resolve.');scopeProviders.set(provider.id,provider);scheduleInit();return()=>scopeProviders.delete(provider.id)}
 const beforeUpdate=(id,hook)=>{if(typeof hook!=='function')throw new Error('Configuration veto must be callable.');if(!vetoes.has(id))vetoes.set(id,new Set());vetoes.get(id).add(hook);return()=>vetoes.get(id)?.delete(hook)}
 const decode=(text,filename='settings.yaml')=>{if(typeof text!=='string'||Buffer.byteLength(text)>1_000_000)fail('Upload a YAML configuration file of at most1MB.');const doc=yaml.parseDocument(text,{uniqueKeys:true,customTags:[],maxAliasCount:0});if(doc.errors.length||doc.warnings.length)fail('The YAML configuration is invalid or uses unsupported tags.');let bundle;try{bundle=doc.toJS({maxAliasCount:0})}catch{fail('YAML aliases are not supported.')}if(!plain(bundle)||bundle.format!=='quotagent/settings/v1'||!Array.isArray(bundle.settings))fail('Use a Quotagent native settings bundle. Download a template first.');return{changes:bundle.settings,source:{kind:'file',filename:basename(filename),digest:digest(text)},ownerId:bundle.ownerId}}
 const exportYaml=(user,{template=false,id,scope,context={}}={})=>{const definitions=id?[schema(id)]:list(user).map(row=>schema(row.id)),redacted=[];const settings=definitions.map(definition=>{authorize(user,definition);const target=scopeTarget(user,definition,scope,context),input=template?defaults(definition):record(target.realmId,target.recordId)?.values||{},values={};for(const field of definition.fields){if(field.type==='password'){redacted.push(definition.id+'.'+field.key);continue}if(Object.hasOwn(input,field.key))values[field.key]=input[field.key]}return{id:definition.id,scope:target.scope,context:target.context,values}});return{filename:template?'quotagent-settings-template.yaml':'quotagent-settings.yaml',content:yaml.stringify({format:'quotagent/settings/v1',ownerId:user.id,generatedAt:now(),note:template?'Template values initialize explicit overrides; inspect before applying.':'Only explicit non-secret overrides are exported; inherited values stay inherited.',settings,redactedSecrets:redacted}),redactedSecrets:redacted}}
 const importPreview=async(user,input)=>preview(user,{...decode(input.yaml,input.filename),mode:input.mode||'merge'}),importApply=async(user,input)=>apply(user,{...decode(input.yaml,input.filename),mode:input.mode||'merge',previewId:input.previewId})
 const history=user=>ctx.store.events(user.id).filter(event=>event.type.startsWith('settings/transaction-')).map(event=>({id:event.event_id||event.id,type:event.type,at:event.ts,...event.body})).slice(-100).reverse()
 const initializationStatus=user=>user?.role==='admin'||initialization.ownerId===user?.id?copy(initialization):{status:'not-configured-for-account'}
 async function initializeFile(){if(disposed||initializing)return;const filename=config.initFile===false?null:config.initFile||process.env.QUOTAGENT_SETTINGS_INIT;if(!filename)return;initialization={status:'waiting',filename:basename(filename)};if(!existsSync(filename)){initialization.status='file-missing';initialization.reason='The configured initialization file does not exist.';return}let bundle;try{bundle=decode(readFileSync(filename,'utf8'),filename)}catch{initialization.status='refused';initialization.reason='The file is not a valid native settings bundle.';return}initialization.ownerId=bundle.ownerId;if(bundle.changes.some(change=>!schemas.has(change.id)||change.scope&&order.includes(change.scope)&&!scopeProviders.has(change.scope))){initialization.reason='Waiting for the referenced schemas and scope providers to load.';return}const user=ctx.accounts.get(bundle.ownerId);if(!user){initialization.status='refused';initialization.reason='The initialization account is unavailable.';return}const sourceId=digest({ownerId:user.id,content:readFileSync(filename,'utf8')}),already=ctx.store.get(user.id,'settings-initializations',sourceId);if(already){initialization={...initialization,status:'already-initialized',transactionId:already.transactionId};return}initializing=true;try{const result=await apply(user,{...bundle,mode:'initialize'});await ctx.store.put(user.id,'settings-initializations',{id:sourceId,filename:basename(filename),initializedAt:now(),transactionId:result.transactionId||null},{actor:'system:settings',event:'settings/file-initialized'});initialization={...initialization,status:result.skipped?'existing-values-preserved':'initialized',transactionId:result.transactionId||null}}catch(error){initialization={...initialization,status:'refused',reason:safeReason(error,bundle)};await ctx.store.append(user.id,'settings/file-initialization-refused',{filename:basename(filename),reason:initialization.reason},{actor:'system:settings'}).catch(()=>{})}finally{initializing=false}}
 function scheduleInit(){clearTimeout(initTimer);if(config.initFile!==false&&(config.initFile||process.env.QUOTAGENT_SETTINGS_INIT)){initTimer=setTimeout(()=>initializeFile().catch(()=>{}),1000);initTimer.unref?.()}}
 return{define,registerScope,beforeUpdate,get,view,list,scopes,save,preview,apply,exportYaml,importPreview,importApply,history,initializeFile,initializationStatus,dispose:async()=>{disposed=true;clearTimeout(initTimer);await pending;schemas.clear();scopeProviders.clear();vetoes.clear();held.clear()}}
}
