import {createProtocolAccount} from '../../exchange-workbench/tests/gui-account.mjs'
import {fillDeclaredScope} from '../../../domain/procurement/tests/declared-scope-fixture.mjs'
import assert from 'node:assert/strict'
import {chromium} from '../../../../host/node_modules/playwright/index.mjs'
import {mkdirSync,writeFileSync} from 'node:fs'
import {createRequire} from 'node:module'
import {localServices} from '../../mail/tests/product-fixtures.mjs'
import {bounce} from './dsn-fixture.mjs'
const require=createRequire(new URL('../../../../host/package.json',import.meta.url)),{simpleParser}=require('mailparser')
const base=process.env.BASE_URL||'http://127.0.0.1:8650/quotagent/',out=process.env.EVIDENCE_DIR||'tmp/agent-experience/qep-mail-browser';mkdirSync(out,{recursive:true})
let buyerServer,supplierServer;buyerServer=await localServices({mailboxMessages:[],onSmtp:message=>supplierServer.appendMail(message.source)});supplierServer=await localServices({mailboxMessages:[],onSmtp:message=>buyerServer.appendMail(message.source)})
const browser=await chromium.launch({headless:true,executablePath:'/opt/hermes/.playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell'}),pages=[],report={at:new Date().toISOString(),base,checks:[],screenshots:[],errors:[],scope:'Fictitious loopback SMTP/IMAP; fixture servers route only to each other and never forward externally.'},title=`[QEP mail fixture] Valve package ${Date.now()}`,channel=`mail-${Date.now()}`,secret='local-qep-mail-browser-pairing'
const shot=async(page,name)=>{await page.screenshot({path:`${out}/${name}.png`,fullPage:true});report.screenshots.push(name+'.png')},read=async(page,path)=>(await page.request.get(new URL('api'+path,base).href)).json()
async function post(page,path,trigger){const pending=page.waitForResponse(response=>response.url().endsWith('/api'+path)&&response.request().method()==='POST');await trigger();const response=await pending,result=await response.json();assert.equal(response.status(),200,JSON.stringify(result));return result}
async function nav(page,label){const navigation=page.getByRole('navigation',{name:'Main navigation'}),button=navigation.getByRole('button',{name:label,exact:true});await navigation.getByRole('button',{name:label,exact:true,includeHidden:true}).waitFor({state:'attached'});if(!await button.isVisible())await navigation.locator('.ws-nav-group').filter({has:page.getByRole('button',{name:label,exact:true,includeHidden:true})}).locator('.ws-group-toggle').click();await button.click()}
async function login(email){const page=await browser.newPage({viewport:{width:1440,height:1100}});pages.push(page);page.setDefaultTimeout(20000);page.on('pageerror',error=>report.errors.push(error.message));await page.goto(base);await page.getByLabel('Email address',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill('demo1234');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('navigation',{name:'Main navigation'}).waitFor();await page.getByRole('button',{name:'Not now',exact:true}).click({timeout:1200}).catch(()=>{});return page}
async function fill(dialog,label,value){const field=dialog.getByLabel(label,{exact:true});if(await field.evaluate(e=>e.tagName==='SELECT'))await field.selectOption(String(value));else await field.fill(String(value))}
async function configure(page,server,address){await nav(page,'Email');await page.getByRole('button',{name:'Email settings',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Email connection settings',exact:true});await dialog.locator('.studio-boolean-field').filter({hasText:'Enable this account’s email connection'}).locator('input').check();for(const[label,value]of[['Sender name','Local QEP fixture'],['Sender email address',address],['IMAP host','127.0.0.1'],['IMAP port',server.imapPort],['IMAP encryption','plain'],['IMAP username','fixture'],['IMAP app password','fixture-password'],['Sent folder (optional)',''],['SMTP host','127.0.0.1'],['SMTP port',server.smtpPort],['SMTP encryption','plain'],['SMTP username','fixture'],['SMTP app password','fixture-password']])await fill(dialog,label,value);await dialog.getByRole('button',{name:'Save settings',exact:true}).click();await dialog.getByText('Settings saved.',{exact:true}).waitFor();await dialog.getByRole('button',{name:'Close',exact:true}).click();await page.getByRole('button',{name:'Test connection',exact:true}).click();await page.locator('.mail-test-result').getByText('SMTP: Connected and authenticated. No email was sent.',{exact:true}).waitFor()}
async function pair(page,realm,role){await nav(page,'Deliveries & exchange');await page.getByRole('tab',{name:'Partner routes',exact:true}).click();for(const row of await page.locator('.ex-peer').all()){const disable=row.getByRole('button',{name:'Disable',exact:true});if(await disable.isVisible())await post(page,'/exchange/peers',()=>disable.click())}await page.getByRole('button',{name:'Pair a partner',exact:true}).click();const dialog=page.getByRole('dialog');for(const[label,value]of[['Peer name','[Local QEP mail fixture] '+realm],['Recipient realm ID',realm],['Peer role',role],['Shared channel ID',channel],['Shared pairing secret',secret]])await fill(dialog,label,value);await post(page,'/exchange/peers',()=>dialog.getByRole('button',{name:'Save delivery route',exact:true}).click())}

async function sendCurrent(page,server){await page.getByRole('button',{name:'Edit draft',exact:true}).click();const compose=page.getByRole('dialog').last(),before=server.smtpMessages.length,pending=page.waitForResponse(response=>/\/api\/mail\/[^/]+\/review$/.test(response.url())&&response.request().method()==='POST');await compose.getByRole('button',{name:'Review send',exact:true}).click();const proposal=await(await pending).json();await page.getByRole('button',{name:'Approve & execute',exact:true}).waitFor();assert.equal(server.smtpMessages.length,before);await shot(page,`review-${before}-${server===buyerServer?'buyer':'supplier'}`);await post(page,`/actions/${proposal.review.id}/approve`,()=>page.getByRole('button',{name:'Approve & execute',exact:true}).click());await page.getByText('Action completed.',{exact:true}).waitFor();assert.equal(server.smtpMessages.length,before+1);return proposal}
async function importCurrent(page){const preview=await post(page,'/exchange/mail/preview',()=>page.getByRole('button',{name:'Preview signed exchange',exact:true}).click());await page.getByText('Pairing and signatures verified',{exact:true}).waitFor();const result=await post(page,'/exchange/mail/import',()=>page.getByRole('button',{name:'Import verified package',exact:true}).click());return {preview,result}}
try{
 const buyer=await browser.newPage({viewport:{width:1440,height:1100}}),supplier=await browser.newPage({viewport:{width:1440,height:1100}});for(const page of [buyer,supplier]){pages.push(page);page.setDefaultTimeout(20000);page.on('pageerror',error=>report.errors.push(error.message))}const buyerUser=await createProtocolAccount(buyer,base,{prefix:'qep-mail',role:'contractor'}),supplierUser=await createProtocolAccount(supplier,base,{prefix:'qep-mail',role:'supplier'});report.accounts={buyer:buyerUser.id,supplier:supplierUser.id};await configure(buyer,buyerServer,'buyer@fixture.invalid');await configure(supplier,supplierServer,'supplier@fixture.invalid');assert.equal(buyerServer.smtpMessages.length+supplierServer.smtpMessages.length,0);await pair(buyer,supplierUser.id,'supplier');await pair(supplier,buyerUser.id,'contractor')
 await nav(buyer,'Requests');await buyer.getByRole('button',{name:'New request',exact:true}).click();let dialog=buyer.getByRole('dialog');for(const[label,value]of[['Request title',title],['Item 1 description','Valve'],['Item 1 quantity','4'],['Item 1 unit','each']])await dialog.getByLabel(label,{exact:true}).fill(value);await fillDeclaredScope(buyer);await dialog.locator('.supplier-options label').filter({hasText:supplierUser.id}).getByRole('checkbox').check();const created=await post(buyer,'/workspace/create-rfq',()=>dialog.getByRole('button',{name:'Save request draft',exact:true}).click());report.rfqId=created.rfq.id;await buyer.getByRole('button',{name:'Publish request',exact:true}).click();await post(buyer,'/workspace/publish-rfq',()=>buyer.getByRole('button',{name:'Confirm & continue',exact:true}).click())
 await nav(buyer,'Deliveries & exchange');const queued=(await read(buyer,'/exchange')).outbox.find(row=>row.recordId===report.rfqId);assert.equal(queued.status,'queued');report.deliveryId=queued.id;await buyer.locator('.ex-delivery').filter({has:buyer.getByText(title,{exact:true})}).click();await buyer.getByRole('button',{name:'Prepare email delivery',exact:true}).click();dialog=buyer.getByRole('dialog',{name:'Email original signed exchange',exact:true});await fill(dialog,'Recipient email addresses','supplier@fixture.invalid');const prepared=await post(buyer,`/exchange/${queued.id}/mail-draft`,()=>dialog.getByRole('button',{name:'Create private email draft',exact:true}).click());report.mailId=prepared.message.id;await shot(buyer,'01-private-package-draft');await sendCurrent(buyer,buyerServer);assert.equal((await read(buyer,'/exchange')).outbox.find(row=>row.id===queued.id).status,'queued');report.checks.push('Both accounts configure and test actual IMAP/SMTP through GUI without sending; contractor publishes explicit scoped RFQ, prepares exact private QEP email and approves one SMTP send while QEP remains queued')
 await nav(supplier,'Email');await post(supplier,'/mail/sync',()=>supplier.getByRole('button',{name:'Sync email',exact:true}).click());await supplier.locator('.mail-list-item').filter({hasText:title}).click();await shot(supplier,'02-received-original-package');const imported=await importCurrent(supplier);assert.equal(imported.result.record.results[0].status,'applied');await shot(supplier,'03-verified-import');const reply=await post(supplier,`/exchange/mail/${imported.result.record.id}/reply`,()=>supplier.getByRole('button',{name:'Prepare receipt or recovery reply',exact:true}).click());await sendCurrent(supplier,supplierServer);assert.equal((await read(buyer,'/exchange')).outbox.find(row=>row.id===queued.id).status,'queued');report.checks.push('Supplier synchronizes the actual MIME attachment, previews verified paired signatures, explicitly imports the request, then separately reviews and sends its original signed receipt reply')
 await nav(buyer,'Email');await buyer.getByRole('button',{name:'Inbox',exact:true}).click();await post(buyer,'/mail/sync',()=>buyer.getByRole('button',{name:'Sync email',exact:true}).click());await buyer.locator('.mail-list-item').filter({hasText:reply.message.subject}).click();await importCurrent(buyer);await buyer.getByRole('button',{name:'Close dialog',exact:true}).click();assert.equal((await read(buyer,'/exchange')).outbox.find(row=>row.id===queued.id).status,'delivered');await buyer.getByRole('button',{name:'Sent',exact:true}).click();await buyer.locator('.mail-list-item').filter({hasText:title}).click();await buyer.locator('.qep-mail-status').getByText('delivered',{exact:true}).waitFor();await shot(buyer,'04-mail-accepted-qep-delivered');report.checks.push('Only buyer import of the original signed receipt marks QEP delivered; the email reader distinguishes mail sent from QEP delivered')
 const original=await simpleParser(buyerServer.smtpMessages[0].source);buyerServer.appendMail(bounce(original.messageId,{id:'gui-matched-bounce'}));await post(buyer,'/mail/sync',()=>buyer.getByRole('button',{name:'Sync email',exact:true}).click());await buyer.locator('.qep-mail-status').getByText('Email: reported-failure',{exact:true}).waitFor();await buyer.locator('.qep-mail-status').getByText('delivered',{exact:true}).waitFor();assert.equal(buyerServer.smtpMessages.length,1);await shot(buyer,'05-reported-bounce-with-signed-receipt');await buyer.reload();await buyer.getByRole('button',{name:'Sent',exact:true}).click();await buyer.locator('.mail-list-item').filter({hasText:title}).click();await buyer.locator('.qep-mail-status').getByText('Email: reported-failure',{exact:true}).waitFor();await buyer.setViewportSize({width:390,height:844});await buyer.waitForTimeout(100);assert.equal(await buyer.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await shot(buyer,'06-mobile-mail-provenance');report.checks.push('An exact structured fixture bounce is linked as external reported failure, preserves the signed QEP receipt, causes no resend and survives full reload/mobile view')
 const admin=await login('admin@demo.local'),inventory=await read(admin,'/plugins'),native=inventory.plugins.find(row=>row.id==='exchange-mail'||row.repoId==='system/exchange-mail');assert(native,'Actual native inventory includes independent exchange-mail plugin');report.nativeInventory={id:native.id,state:native.state,enabled:native.enabled,repoId:native.repoId};assert.deepEqual(report.errors,[]);report.ok=true
}catch(error){report.error=error.stack;process.exitCode=1;for(const [i,page]of pages.entries()){await shot(page,`failure-${i}`).catch(()=>{});writeFileSync(`${out}/failure-${i}.txt`,await page.locator('body').innerText().catch(()=>''))}}finally{report.smtpSends={buyer:buyerServer.smtpMessages.length,supplier:supplierServer.smtpMessages.length};writeFileSync(`${out}/report.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();await buyerServer.close();await supplierServer.close()}
