import {bounce} from './dsn-fixture.mjs'
import {declaredScope} from '../../../domain/procurement/tests/declared-scope-fixture.mjs'
import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {mkdirSync,mkdtempSync,writeFileSync} from 'node:fs'
import {resolve,join} from 'node:path'
import * as store from '../../workspace-store/code/index.mjs'
import * as settings from '../../settings/code/index.mjs'
import * as files from '../../file-store/code/index.mjs'
import * as procurement from '../../../domain/procurement/code/index.mjs'
import * as ingestion from '../../../domain/ingestion/code/index.mjs'
import * as actions from '../../action-center/code/index.mjs'
import * as notifications from '../../notifications/code/index.mjs'
import * as mail from '../../mail/code/product.mjs'
import * as exchange from '../../exchange-workbench/code/index.mjs'
import * as qepMail from '../code/index.mjs'
import {localServices} from '../../mail/tests/product-fixtures.mjs'
const require=createRequire(new URL('../../../../host/package.json',import.meta.url)),{Context}=require('cordis'),{simpleParser}=require('mailparser')
mkdirSync('tmp',{recursive:true});const root=mkdtempSync(resolve('tmp/qep-mail-')),checks=[],users=[{id:'mail-buyer',role:'contractor',name:'Buyer fixture',email:'buyer@fixture.invalid'},{id:'mail-supplier',role:'supplier',name:'Supplier fixture',email:'supplier@fixture.invalid'}],buyer=users[0],supplier=users[1],secret='fictitious-qep-mail-pairing'
let leftServer,rightServer,left,right
leftServer=await localServices({mailboxMessages:[],onSmtp:message=>rightServer.appendMail(message.source)})
rightServer=await localServices({mailboxMessages:[],onSmtp:message=>leftServer.appendMail(message.source)})
async function mount(directory){const ctx=new Context(),fibers=[],routes=[],tools=[];const add=(array,item)=>{array.push(item);return()=>array.splice(array.indexOf(item),1)};fibers.push(await ctx.plugin({name:'qep-mail-fixture-host',apply(ctx){ctx.provide('accounts',{list:()=>users,get:id=>users.find(row=>row.id===id),can:()=>true});ctx.provide('web',{route:(...args)=>add(routes,args),contribute:()=>()=>{}});ctx.provide('assistant',{tool:definition=>add(tools,definition)})}}));for(const plugin of [store,settings,files,procurement,ingestion,notifications,actions,exchange,mail,qepMail])fibers.push(await ctx.plugin(plugin,plugin===store?{root:directory}:plugin===exchange?{retryIntervalMs:3600000}:{}));return{ctx,routes,tools,mailFiber:fibers.at(-2),qepFiber:fibers.at(-1),async close(){for(const fiber of fibers.reverse())await fiber.dispose();assert.equal(routes.length,0);assert.equal(tools.length,0)}}}
const configure=async(target,user,server)=>target.ctx.settings.save(user,'mail',{values:{enabled:true,fromName:user.name,fromAddress:user.email,imapHost:'127.0.0.1',imapPort:server.imapPort,imapSecurity:'plain',imapUser:'fixture',imapPassword:'fixture-password',smtpHost:'127.0.0.1',smtpPort:server.smtpPort,smtpSecurity:'plain',smtpUser:'fixture',smtpPassword:'fixture-password',sentMailbox:''}})
const send=async(target,user,message)=>{const review=await target.ctx.mail.propose(user,message.id);const done=await target.ctx.actions.approve(user,review.review.id,{confirmed:true});assert.equal(done.status,'succeeded',done.error);return done}

try{
 left=await mount(join(root,'left'));right=await mount(join(root,'right'))
 await left.ctx.exchange.savePeer(buyer,{name:'Fixture supplier',peerRealm:supplier.id,role:'supplier',mode:'manual',channel:'mail-fixture',pairingSecret:secret});await right.ctx.exchange.savePeer(supplier,{name:'Fixture buyer',peerRealm:buyer.id,role:'contractor',mode:'manual',channel:'mail-fixture',pairingSecret:secret});await configure(left,buyer,leftServer);await configure(right,supplier,rightServer)
 const created=await left.ctx.procurement.execute(buyer,'create-rfq',{title:'[Local mail fixture] Valves',description:'No external supplier; protocol evidence only.',currency:'USD',...declaredScope([{id:'valve',description:'Valve',quantity:4,unit:'each'}]),supplierIds:[supplier.id]});await left.ctx.procurement.execute(buyer,'publish-rfq',{id:created.rfq.id,confirmed:true});const delivery=left.ctx.store.deliveryState(buyer.id).outbox.find(row=>row.recordId===created.rfq.id);assert.equal(delivery.status,'queued')
 const draft=await left.ctx.qepMail.draftDelivery(buyer,delivery.id,{to:[supplier.email]});assert.equal(leftServer.smtpMessages.length,0);const originalBytes=left.ctx.files.read(buyer,draft.record.fileId),review=await left.ctx.mail.propose(buyer,draft.message.id);assert.equal(leftServer.smtpMessages.length,0);await left.ctx.actions.approve(buyer,review.review.id,{confirmed:true});assert.equal(leftServer.smtpMessages.length,1);await left.ctx.actions.approve(buyer,review.review.id,{confirmed:true});assert.equal(leftServer.smtpMessages.length,1);const mime=await simpleParser(leftServer.smtpMessages[0].source);assert.deepEqual(mime.attachments[0].content,originalBytes);assert.equal(left.ctx.store.get(buyer.id,'exchange-outbox',delivery.id).status,'queued')
 checks.push('Actual published QEP package becomes a private editable mail draft; propose sends zero; human approval sends once over SMTP and MIME attachment bytes are identical; SMTP acceptance leaves QEP queued')
 assert.equal((await right.ctx.mail.sync(supplier)).imported,1);const received=right.ctx.mail.list(supplier).find(row=>row.direction==='inbound'),file=received.attachments.find(row=>row.filename.endsWith('.qep.json'));assert(file);assert.equal(right.ctx.store.get(supplier.id,'rfqs',created.rfq.id),undefined)
 const preview=await right.ctx.qepMail.preview(supplier,{messageId:received.id,fileId:file.id});assert.equal(preview.verified,true);assert.equal(right.ctx.store.get(supplier.id,'rfqs',created.rfq.id),undefined);await assert.rejects(right.ctx.qepMail.importAttachment(supplier,{messageId:received.id,fileId:file.id,fileSha256:preview.fileSha256}),/Confirm/);const imported=await right.ctx.qepMail.importAttachment(supplier,{messageId:received.id,fileId:file.id,fileSha256:preview.fileSha256,confirmed:true});assert.equal(imported.record.results[0].status,'applied');assert.equal(right.ctx.store.get(supplier.id,'rfqs',created.rfq.id).title,created.rfq.title)
 await right.ctx.qepMail.importAttachment(supplier,{messageId:received.id,fileId:file.id,fileSha256:preview.fileSha256,confirmed:true});assert.equal(right.ctx.store.events(supplier.id).filter(row=>row.type==='exchange/record-applied'&&row.body.record.id===created.rfq.id).length,1)
 checks.push('Actual IMAP sync stores original MIME and signed attachment; preview applies no business record; explicit verified import validates domain and duplicate import applies once')
 const receipt=await right.ctx.qepMail.reply(supplier,imported.record.id);assert.equal(rightServer.smtpMessages.length,0);await send(right,supplier,receipt.message);assert.equal(rightServer.smtpMessages.length,1);assert.equal(left.ctx.store.get(buyer.id,'exchange-outbox',delivery.id).status,'queued');await left.ctx.mail.sync(buyer);const receiptMail=left.ctx.mail.list(buyer).find(row=>row.direction==='inbound'),receiptFile=receiptMail.attachments.find(row=>row.filename.endsWith('.qep.json')),receiptPreview=await left.ctx.qepMail.preview(buyer,{messageId:receiptMail.id,fileId:receiptFile.id});await left.ctx.qepMail.importAttachment(buyer,{messageId:receiptMail.id,fileId:receiptFile.id,fileSha256:receiptPreview.fileSha256,confirmed:true});assert.equal(left.ctx.store.get(buyer.id,'exchange-outbox',delivery.id).status,'delivered')
 checks.push('Supplier prepares original signed receipt reply, separately approves SMTP, buyer receives through IMAP and imports the verified receipt before QEP becomes delivered')
 await assert.rejects(right.ctx.qepMail.preview(buyer,{messageId:received.id,fileId:file.id}),/not in your account/);await right.ctx.settings.save(supplier,'qep-mail',{values:{maxPackageMb:1}});const oversized=await right.ctx.files.put(supplier,{filename:'oversized.qep.json',buffer:Buffer.alloc(1024*1024+1,32)}),mailWithLarge=await right.ctx.mail.draft(supplier,{to:[buyer.email],subject:'Bounded fixture',body:'Private only',attachmentIds:[oversized.id]});await assert.rejects(right.ctx.qepMail.preview(supplier,{messageId:mailWithLarge.id,fileId:oversized.id}),error=>error.status===413);assert.equal(rightServer.smtpMessages.length,1)
 checks.push('Another account cannot inspect the mail attachment; explicit package-size refusal preserves source file and sends nothing')
 const sent=left.ctx.mail.get(buyer,draft.message.id);leftServer.appendMail(bounce(sent.messageId));leftServer.appendMail(bounce('<unmatched@fixture.invalid>',{id:'unmatched'}));await left.ctx.mail.sync(buyer);const state=left.ctx.qepMail.state(buyer).records.find(row=>row.id===draft.record.id);assert.equal(state.mailStatus,'reported-failure');assert.equal(state.deliveryReports.length,1);assert.equal(state.deliveryReports[0].reports[0].status,'5.1.1');assert.equal(state.qep[0].status,'delivered');assert.equal(leftServer.smtpMessages.length,1)
 checks.push('Structured MIME bounce matches exact outgoing Message-ID and recipient with source references; unmatched report stays unlinked and neither report rewrites signed QEP acceptance or triggers a resend')
 // Deliberately deliver a later signed message by mail first, then carry the
 // automatically created gap request and exact originals through reviewed replies.
 for(const [target,user,peer]of [[left,buyer,supplier],[right,supplier,buyer]]){for(const route of target.ctx.exchange.list(user).peers)await target.ctx.exchange.savePeer(user,{...route,enabled:false});await target.ctx.exchange.savePeer(user,{name:'Fixture mail recovery',peerRealm:peer.id,role:peer.role,mode:'manual',channel:'mail-recovery',pairingSecret:secret})}
 const firstNote=await right.ctx.procurement.execute(supplier,'send-message',{rfqId:created.rfq.id,toId:buyer.id,text:'[Fixture] Original missing note'}),secondNote=await right.ctx.procurement.execute(supplier,'send-message',{rfqId:created.rfq.id,toId:buyer.id,text:'[Fixture] Later held note'}),notes=right.ctx.store.deliveryState(supplier.id).outbox,firstDelivery=notes.find(row=>row.id===firstNote.deliveries[0].msgId),laterDelivery=notes.find(row=>row.id===secondNote.deliveries[0].msgId),firstPackage=(await right.ctx.store.package(supplier.id,firstDelivery.id)).package
 const receiveLast=async(target,user,server)=>{const original=await simpleParser(server.smtpMessages.at(-1).source);await target.ctx.mail.sync(user);const message=target.ctx.mail.list(user).find(row=>row.direction==='inbound'&&row.messageId===original.messageId),file=message.attachments.find(row=>row.filename.endsWith('.qep.json')),preview=await target.ctx.qepMail.preview(user,{messageId:message.id,fileId:file.id});return target.ctx.qepMail.importAttachment(user,{messageId:message.id,fileId:file.id,fileSha256:preview.fileSha256,confirmed:true})}
 const laterMail=await right.ctx.qepMail.draftDelivery(supplier,laterDelivery.id,{to:[buyer.email]});await send(right,supplier,laterMail.message);const heldImport=await receiveLast(left,buyer,rightServer);assert.equal(heldImport.record.results[0].status,'held');assert.equal(left.ctx.store.get(buyer.id,'messages',secondNote.deliveries[0].recordId),undefined);assert(heldImport.replyAvailable)
 const recovery=await left.ctx.qepMail.reply(buyer,heldImport.record.id);assert(recovery.record.packages.some(row=>row.type==='relay/resend-request'));await send(left,buyer,recovery.message);const requestImport=await receiveLast(right,supplier,leftServer);assert(requestImport.replyAvailable)
 const replay=await right.ctx.qepMail.reply(supplier,requestImport.record.id),replayValue=JSON.parse(right.ctx.files.read(supplier,replay.record.fileId)),replayPackages=Array.isArray(replayValue)?replayValue:[replayValue];assert.deepEqual(replayPackages.find(row=>row.envelope.msg_id===firstDelivery.id),firstPackage);await send(right,supplier,replay.message);await receiveLast(left,buyer,rightServer);assert.equal(left.ctx.store.get(buyer.id,'messages',firstNote.deliveries[0].recordId).text,'[Fixture] Original missing note');assert.equal(left.ctx.store.get(buyer.id,'messages',secondNote.deliveries[0].recordId).text,'[Fixture] Later held note');assert.equal(left.ctx.store.deliveryState(buyer.id).outbox.find(row=>row.controlKind==='resend-request').status,'fulfilled')
 checks.push('Mail carries an out-of-order signed message, reviewed signed missing-message request and separately reviewed exact original replay; importing original bytes releases the held successor and fulfills recovery without generating a new commercial commitment')
 await left.close();left=await mount(join(root,'left'));assert.equal(left.ctx.qepMail.state(buyer).records.find(row=>row.id===draft.record.id).mailStatus,'reported-failure');assert.equal(left.ctx.store.get(buyer.id,'exchange-outbox',delivery.id).status,'delivered');await left.qepFiber.dispose();assert.equal(left.ctx.get('qepMail'),undefined);assert.deepEqual(left.ctx.exchange.list(buyer).extensions,[]);const mailRoute=left.routes.find(([method,path])=>method==='GET'&&path==='/mail');assert.deepEqual(mailRoute[2]({user:buyer}).extensions,[]);assert.equal(left.ctx.mail.get(buyer,draft.message.id).status,'sent');assert(!left.routes.some(([,path])=>path.startsWith('/exchange/mail/')))
 checks.push('Native restart preserves exact mail/QEP/report linkage; independent plugin unload removes routes/service and both GUI extension IDs while ordinary retained mail remains readable')
 const report={ok:true,at:new Date().toISOString(),root,checks,smtpSends:{buyer:leftServer.smtpMessages.length,supplier:rightServer.smtpMessages.length},scope:'Only fictitious independent native accounts and loopback IMAP/SMTP; no external service or real commercial recipient.'};writeFileSync(join(root,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2))
}finally{await left?.close().catch(()=>{});await right?.close().catch(()=>{});await leftServer.close();await rightServer.close()}
