// Browser-only business writes; response capture records exact visible outcomes.
import assert from 'node:assert/strict'
import { chromium } from '../../../../host/node_modules/playwright/index.mjs'
import { mkdirSync, writeFileSync } from 'node:fs'
const base=process.env.BASE_URL||'http://127.0.0.1:8620/quotagent/',evidence=process.env.EVIDENCE_DIR||'tmp/agent-experience/commercial/local'
mkdirSync(evidence,{recursive:true})
const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||'/opt/hermes/.playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell'})
const stamp=Date.now(),itemLabel=`Fixture panel ${stamp}`,reviewerName=`Commercial reviewer ${stamp}`,reviewerEmail=`commercial-reviewer-${stamp}@local.test`
const pages=[],errors=[],checks=[],receipts=[],title=`[Commercial check] Panels ${new Date().toISOString()}`
const field=(page,label)=>page.locator('label.field').filter({has:page.getByText(label,{exact:true})}).locator('input,textarea,select').first()
const shot=(page,name)=>page.screenshot({path:`${evidence}/${name}.png`,fullPage:true,animations:'disabled'})
const addDays=(days)=>new Date(Date.now()+days*86400000).toISOString().slice(0,10)
async function post(page,path,trigger){const pending=page.waitForResponse(response=>response.url().endsWith(`/api/${path}`)&&response.request().method()==='POST');await trigger();const response=await pending,body=await response.json();assert.equal(response.status(),200,`${path}: ${JSON.stringify(body)}`);receipts.push({path,response:body});return body}
const clickPost=(page,path,label)=>post(page,path,()=>page.getByRole('button',{name:label,exact:true}).click())
async function login(email){const page=await browser.newPage({viewport:{width:1480,height:1100}});pages.push(page);page.setDefaultTimeout(20000);page.on('pageerror',error=>errors.push(error.message));await page.goto(base);if(!email)return page;await page.getByLabel('Email address').fill(email);await page.getByLabel('Password',{exact:true}).fill('demo1234');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('navigation',{name:'Main navigation'}).waitFor();await page.getByRole('button',{name:'Not now',exact:true}).click({timeout:1500}).catch(()=>{});return page}
async function navigate(page,name){
 await page.getByRole('navigation',{name:'Main navigation'}).waitFor();const nav=page.getByRole('navigation',{name:'Main navigation'}),target=nav.getByRole('button',{name,exact:true})
 for(let attempt=0;attempt<5;attempt++){if(!await target.isVisible())await nav.locator('.ws-nav-group').filter({has:page.getByRole('button',{name,exact:true,includeHidden:true})}).locator('.ws-group-toggle').click();try{await target.click({timeout:2500});return}catch(error){if(attempt===4)throw error}}
}
async function request(page){await navigate(page,'Requests');await page.getByLabel('Search requests').fill(title);await page.getByRole('button').filter({has:page.getByRole('heading',{name:title,exact:true})}).click();await page.getByRole('heading',{name:title,exact:true}).waitFor()}
async function workbench(page,rfqId,tab){await navigate(page,'Commercial workbench');await page.getByLabel('Workbench request',{exact:true}).selectOption(rfqId);await page.getByRole('tab',{name:tab,exact:true}).click()}
async function fillTerms(page,{currency='GBP',tax='inclusive',rate='',freight='0'}={}){await page.getByLabel('Quote currency',{exact:true}).fill(currency);await page.getByLabel('Tax treatment',{exact:true}).selectOption(tax);if(rate)await page.getByLabel('Tax rate (%)',{exact:true}).fill(rate);for(const [label,value]of [['Freight charge',freight],['Advance (%)','0'],['Net payment days','30'],['Warranty months','12'],['Penalty (%)','2']])await page.getByLabel(label,{exact:true}).fill(value);await page.getByLabel('Quote valid until',{exact:true}).fill(addDays(60));await page.getByLabel('Delivery commitment',{exact:true}).selectOption('firm');await page.getByRole('button',{name:'Declare no deviations',exact:true}).click();return clickPost(page,'commercial/save-terms','Save commercial terms to draft')}
async function setupReviewer(buyer){
 const reviewer=await login();await reviewer.getByRole('button',{name:'Create an account',exact:true}).click();for(const [name,value]of [['Your name',reviewerName],['Company','Review colleague'],['Email address',reviewerEmail],['Password','commercial-fixture-pass']])await reviewer.getByLabel(name,{exact:true}).fill(value);await reviewer.getByRole('button',{name:'Create workspace',exact:true}).click();await reviewer.getByRole('navigation',{name:'Main navigation'}).waitFor();await reviewer.getByRole('button',{name:'Not now',exact:true}).click({timeout:700}).catch(()=>{})
 await navigate(buyer,'My day & team');await buyer.getByRole('button',{name:'Colleagues',exact:true}).click();await buyer.getByRole('button',{name:'Invite colleague',exact:true}).click();let modal=buyer.getByRole('dialog');await modal.getByLabel('Colleague email',{exact:true}).fill(reviewerEmail);await modal.getByLabel('Team role',{exact:true}).selectOption('lead');await modal.getByRole('button',{name:'Send invitation',exact:true}).click();await modal.waitFor({state:'hidden'});await navigate(reviewer,'My day & team');await reviewer.getByRole('button',{name:'Accept invitation',exact:true}).click();await post(reviewer,'teams/select',()=>reviewer.getByLabel('Active party workspace',{exact:true}).selectOption({label:'Northstar Construction'}));await reviewer.waitForFunction(()=>!document.querySelector('[aria-label="Active party workspace"]').disabled)
 await buyer.getByRole('button',{name:/^Authority/}).click();await buyer.getByRole('button',{name:'Propose authority changes',exact:true}).click();modal=buyer.getByRole('dialog');await modal.getByLabel('Authority currency',{exact:true}).fill('GBP');for(const [role,value]of [['Director','0'],['Team lead','10000']]){await modal.getByLabel('Limit type for '+role,{exact:true}).selectOption('amount');await modal.getByLabel('Amount in GBP for '+role,{exact:true}).fill(value)}await modal.getByLabel('Independent reviewer',{exact:true}).selectOption({label:reviewerName+' · Team lead'});await modal.getByLabel('Reason for change',{exact:true}).fill('Independent commercial commitment review in GBP.');await modal.getByRole('button',{name:'Request policy review',exact:true}).click();await modal.waitFor({state:'hidden'});await navigate(reviewer,'My day & team');await reviewer.getByRole('button',{name:/^Authority/}).click();await reviewer.locator('.team-policy-proposal').filter({has:reviewer.getByRole('button',{name:'Approve policy',exact:true})}).first().getByRole('button',{name:'Approve policy',exact:true}).click();await buyer.reload();await buyer.getByRole('button',{name:/^Authority/}).click();await buyer.locator('.team-policy-proposal').first().getByRole('button',{name:'Apply approved policy',exact:true}).click();await buyer.locator('.team-policy-proposal').first().getByText('applied',{exact:true}).waitFor();return reviewer
}
async function signOrder(buyer,supplier,reviewer){
 await request(buyer);await buyer.getByRole('button',{name:'Compare offers',exact:true}).click();await buyer.getByRole('button',{name:'Propose award',exact:true}).first().click();await buyer.getByLabel('Selection reason',{exact:true}).fill('Reviewed declared price, scope and sourced commercial analysis.');await clickPost(buyer,'workspace/propose-award','Send nonbinding award intent');await navigate(supplier,'Orders');const intent=supplier.locator('.fulfillment-record').filter({has:supplier.getByRole('heading',{name:title,exact:true})});await intent.getByRole('button',{name:'Confirm award intent',exact:true}).click();await clickPost(supplier,'workspace/confirm-award','Confirm & continue');await buyer.reload();const buyerIntent=buyer.locator('.fulfillment-record').filter({has:buyer.getByRole('heading',{name:title,exact:true})});const prepared=await post(buyer,'workspace/review/sign-order',()=>buyerIntent.getByRole('button',{name:'Prepare order for review',exact:true}).click());await buyer.getByLabel('Independent colleague',{exact:true}).selectOption({label:reviewerName+' · Team lead'});await buyer.getByRole('button',{name:'Request independent review',exact:true}).click();await navigate(reviewer,'Review actions');await reviewer.locator('.review-list-row').filter({hasText:prepared.proposal.title}).click();await clickPost(reviewer,`actions/${prepared.proposal.id}/grant`,'Grant independent approval');await buyer.reload();await buyer.locator('.review-list-row').filter({hasText:prepared.proposal.title}).click();const signed=await clickPost(buyer,`actions/${prepared.proposal.id}/approve`,'Sign & execute');assert.equal(signed.action.status,'succeeded',signed.action.error);return signed.action.result
}

try{
 const buyer=await login('contractor@demo.local'),supplier=await login('supplier@demo.local'),second=await login('supplier2@demo.local'),reviewer=await setupReviewer(buyer)
 await navigate(buyer,'Requests');await buyer.getByRole('button',{name:'New request',exact:true}).click();await field(buyer,'Request title').fill(title);await field(buyer,'Project brief').fill('Labelled local commercial-workbench verification fixture. Ten panels.');await field(buyer,'Currency').selectOption('GBP');await buyer.getByLabel('Item 1 description',{exact:true}).fill(itemLabel);await buyer.getByLabel('Item 1 quantity',{exact:true}).fill('10');await buyer.locator('.supplier-options label').filter({hasText:'supplier@demo.local'}).getByRole('checkbox').check();await buyer.locator('.supplier-options label').filter({hasText:'supplier2@demo.local'}).getByRole('checkbox').check()
 const created=await clickPost(buyer,'workspace/create-rfq','Save request draft'),rfqId=created.rfq.id
 await buyer.getByRole('button',{name:'Publish request',exact:true}).click();await clickPost(buyer,'workspace/publish-rfq','Confirm & continue')
 const quoteIds=[]
 for(const [page,price]of [[supplier,'20'],[second,'30']]){await request(page);await page.getByRole('button',{name:'Prepare quote',exact:true}).click();await page.getByLabel(`Unit price for ${itemLabel}`,{exact:true}).fill(price);const draft=await clickPost(page,'workspace/save-quote','Save quotation draft');quoteIds.push(draft.quote.id)}
 await workbench(supplier,rfqId,'Commercial terms');const terms=await fillTerms(supplier,{tax:'exclusive',rate:'20',freight:'5'});assert.equal(terms.quote.total,245)
 await supplier.getByRole('tab',{name:'Costs & pricing',exact:true}).click()
 for(const [key,value]of Object.entries({material:'8',labor:'1',equipment:'1',overhead:'10',risk:'0',tax:'0',finance:'0'}))await supplier.getByLabel(`${itemLabel}: ${key}${['material','labor','equipment'].includes(key)?' unit rate':' (%)'}`,{exact:true}).fill(value)
 await supplier.getByLabel(`${itemLabel}: cost source`,{exact:true}).fill('Private labelled test worksheet, material/labor/equipment rates reviewed.')
 for(let refresh=0;refresh<2;refresh++)await supplier.waitForResponse(response=>response.url().endsWith('/api/commercial')&&response.request().method()==='GET')
 for(const [key,value]of Object.entries({material:'8',labor:'1',equipment:'1',overhead:'10',risk:'0',tax:'0',finance:'0'}))assert.equal(await supplier.getByLabel(`${itemLabel}: ${key}${['material','labor','equipment'].includes(key)?' unit rate':' (%)'}`,{exact:true}).inputValue(),value)
 assert.equal(await supplier.evaluate(()=>document.activeElement?.getAttribute('aria-label')),`${itemLabel}: cost source`)
 const cost=await clickPost(supplier,'commercial/save-costs','Calculate and save costs');assert.equal(cost.costs.total,110)
 await supplier.getByRole('button',{name:'Pricing policy settings',exact:true}).click();await field(supplier,'Minimum margin (%)').fill('25');await supplier.getByRole('button',{name:'Save settings',exact:true}).click();await supplier.getByText('Settings saved.',{exact:true}).waitFor();await supplier.getByRole('button',{name:'Close',exact:true}).click()
 await supplier.getByLabel('Target margin (%)',{exact:true}).fill('20');const pricing=await clickPost(supplier,'commercial/propose-prices','Prepare price review');assert.equal(pricing.proposal.belowFloor,true);assert.equal(pricing.proposal.total,170)
 await supplier.getByRole('heading',{name:'Exact private draft prices',exact:true}).waitFor();await shot(supplier,'01-private-prices-review')
 const approval=await clickPost(supplier,`actions/${pricing.approval.id}/approve`,'Approve & execute');assert.equal(approval.action.status,'succeeded',approval.action.error)
 checks.push('Supplier GUI commercial terms, unsaved cost fields/focus across two background refreshes, private seven-factor costing, account margin setting and exact reviewed below-floor draft prices (£170 including tax/freight)')
 await workbench(supplier,rfqId,'Capacity');await supplier.getByLabel('Capacity per working day',{exact:true}).fill('8');await supplier.getByLabel('Availability source',{exact:true}).fill('Declared fixture machine hours');await supplier.getByRole('checkbox',{name:'Sat',exact:true}).check();await supplier.getByRole('checkbox',{name:'Sun',exact:true}).check();await clickPost(supplier,'commercial/save-calendar','Save capacity calendar')
 await supplier.getByLabel('Plan start',{exact:true}).fill(addDays(0));await supplier.getByLabel('Target delivery',{exact:true}).fill(addDays(0));await supplier.getByLabel('Task 1 effort',{exact:true}).fill('16');await supplier.getByRole('button',{name:'Add task',exact:true}).click();await supplier.getByLabel('Task 2 name',{exact:true}).fill('Inspection');await supplier.getByLabel('Task 2 effort',{exact:true}).fill('8');await supplier.getByLabel('Task 2 depends on IDs',{exact:true}).fill('fabricate')
 const plan=await clickPost(supplier,'commercial/save-plan','Save and check plan');assert.equal(plan.plan.schedule.finishDate,addDays(2));assert.equal(plan.plan.schedule.feasible,false);await shot(supplier,'02-capacity-conflict')
 await clickPost(supplier,'commercial/archive-plan','Archive plan and release capacity')
 checks.push('Dated supplier availability, task dependency scheduling, visible delivery conflict and archival capacity release without altering firm quotation')
 await request(supplier);await supplier.getByRole('button',{name:'My quotes',exact:true}).click();await supplier.getByRole('button',{name:'Review & submit',exact:true}).click();const submitted=await clickPost(supplier,'workspace/submit-quote','Confirm & continue');assert.equal(submitted.quote.total,170)
 await workbench(second,rfqId,'Commercial terms');await fillTerms(second,{currency:'EUR'});await request(second);await second.getByRole('button',{name:'My quotes',exact:true}).click();await second.getByRole('button',{name:'Review & submit',exact:true}).click();await clickPost(second,'workspace/submit-quote','Confirm & continue')
 await workbench(buyer,rfqId,'Compare & score');await clickPost(buyer,'commercial/save-policy','Save comparison policy');await buyer.getByLabel('Analysis currency',{exact:true}).fill('JPY');let comparison=await clickPost(buyer,'commercial/evaluate','Compute and save comparison');assert.equal(comparison.evaluation.rows.find(row=>row.quoteId===quoteIds[1]).amounts.price.value,null)
 await buyer.getByRole('tab',{name:'FX & references',exact:true}).click();await buyer.getByLabel('From currency',{exact:true}).fill('EUR');await buyer.getByLabel('To currency',{exact:true}).fill('GBP');await buyer.getByLabel('Conversion rate',{exact:true}).fill('1.2');await buyer.getByLabel('Rate effective time',{exact:true}).fill(addDays(-1)+'T00:00');await buyer.getByLabel('Rate expiry time',{exact:true}).fill(addDays(7)+'T23:59');await buyer.getByLabel('Exchange rate source',{exact:true}).fill('Manual dated fixture rate, not a live market quote');await clickPost(buyer,'commercial/save-fx','Save exchange rate')
 for(const [label,value]of [['Reference item description',itemLabel],['Reference unit','each'],['Reference unit price','50'],['Reference currency','GBP'],['Reference price source','Manual comparable fixture price']])await buyer.getByLabel(label,{exact:true}).fill(value)
 await buyer.getByLabel('Reference observed time',{exact:true}).fill(addDays(-1)+'T00:00');await clickPost(buyer,'commercial/save-reference','Save reference price')
 await buyer.getByRole('tab',{name:'Compare & score',exact:true}).click();await buyer.getByLabel('Analysis currency',{exact:true}).fill('GBP');comparison=await clickPost(buyer,'commercial/evaluate','Compute and save comparison');const rows=comparison.evaluation.rows;assert.equal(rows.find(row=>row.quoteId===quoteIds[0]).amounts.price.value,170);assert.equal(rows.find(row=>row.quoteId===quoteIds[1]).amounts.price.value,360);assert(rows.find(row=>row.quoteId===quoteIds[0]).flags.some(flag=>flag.kind==='reference-price-anomaly'));await shot(buyer,'03-sourced-comparison')
 const download=buyer.waitForEvent('download');await buyer.getByRole('link',{name:'Download comparison CSV',exact:true}).click();await (await download).saveAs(`${evidence}/comparison.csv`)
 await buyer.getByLabel('Price weight (%)',{exact:true}).fill('100');for(const label of ['Delivery','Payment','Warranty','Deviation'])await buyer.getByLabel(`${label} weight (%)`,{exact:true}).fill('0');await clickPost(buyer,'commercial/save-policy','Save comparison policy');await clickPost(buyer,'commercial/evaluate','Compute and save comparison');await buyer.waitForFunction(()=>document.querySelector('[aria-label="Saved what-if result"]')?.options.length>=3)
 await buyer.getByRole('tab',{name:'Quote assumptions',exact:true}).click();await buyer.getByLabel('Workbench quotation',{exact:true}).selectOption(quoteIds[1]);await buyer.getByLabel('Freight charge',{exact:true}).fill('10');await buyer.getByLabel('Assumption source and rationale',{exact:true}).fill('Reviewed planning assumption for delivery handling, not supplier commitment');await clickPost(buyer,'commercial/save-assumptions','Save sourced assumptions')
 checks.push('Received terms; missing FX explicitly unknown; manually sourced timestamp-valid FX/reference price; exact GBP normalization, warning source, weighted what-if archive, CSV export and private sourced assumptions')
 await buyer.getByRole('tab',{name:'History',exact:true}).click();await buyer.getByLabel('Filter descriptive history',{exact:true}).fill(itemLabel);assert.equal(await buyer.locator('details.cw-inset > summary').count(),2);await buyer.locator('details.cw-inset > summary').first().click();await shot(buyer,'04-descriptive-history')
 const awarded=await signOrder(buyer,supplier,reviewer);assert(awarded.order)
 await workbench(buyer,rfqId,'ERP CSV');await buyer.getByRole('checkbox',{name:'CSV uses this workspace’s exact order and item IDs',exact:true}).check();await clickPost(buyer,'commercial/save-erp-mapping','Save ERP mapping')
 const ordersDownload=buyer.waitForEvent('download');await buyer.getByRole('link',{name:'Download PO lines CSV',exact:true}).click();const file=await ordersDownload;await file.saveAs(`${evidence}/orders.csv`);await buyer.getByLabel('Choose ERP CSV file',{exact:true}).setInputFiles(`${evidence}/orders.csv`);const imported=await clickPost(buyer,'commercial/import-erp','Import and compare PO lines');assert.equal(imported.import.status,'matched')
 await buyer.getByLabel('ERP CSV content',{exact:true}).fill('po_number,item_id,quantity,unit_price\nUNMAPPED,item-X,2,10\n');const broken=await clickPost(buyer,'commercial/import-erp','Import and compare PO lines');assert.equal(broken.import.rows[0].status,'mapping-error');assert.equal(broken.import.rows[0].raw.po_number,'UNMAPPED');await shot(buyer,'05-erp-retained-error')
 await buyer.getByRole('tab',{name:'Reports',exact:true}).click();const report=await clickPost(buyer,'commercial/create-report','Create activity report');assert(report.report.orders.some(row=>row.id===awarded.order.id));await shot(buyer,'06-sourced-report')
 checks.push('Descriptive item/currency history without rankings; supplier-confirmed independently reviewed fixture award; genuine PO CSV download/upload round trip; retained original failed mapping; sourced weekly activity report')
 await supplier.reload();await navigate(supplier,'Commercial workbench');await supplier.getByLabel('Workbench request',{exact:true}).selectOption(rfqId);await supplier.getByRole('tab',{name:'Costs & pricing',exact:true}).click();assert.equal(await supplier.getByLabel(`${itemLabel}: material unit rate`,{exact:true}).inputValue(),'8')
 await buyer.setViewportSize({width:390,height:844});await buyer.waitForTimeout(300);assert.equal(await buyer.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);await shot(buyer,'07-mobile-report');assert.deepEqual(errors,[])
 checks.push('Private cost reconstruction after browser reload, no JavaScript errors and mobile report without horizontal overflow')
 const result={ok:true,base,title,rfqId,quoteIds,reviewer:{name:reviewerName,email:reviewerEmail},checks,jsErrors:errors,at:new Date().toISOString()};writeFileSync(`${evidence}/report.json`,JSON.stringify(result,null,2));writeFileSync(`${evidence}/responses.json`,JSON.stringify(receipts,null,2));console.log(JSON.stringify(result,null,2))
}catch(error){for(const [i,page]of pages.entries()){await shot(page,`failure-${i}`).catch(()=>{});writeFileSync(`${evidence}/failure-${i}.txt`,await page.locator('body').innerText().catch(()=>''))}writeFileSync(`${evidence}/failure.json`,JSON.stringify({error:error.stack,checks,errors,receipts},null,2));throw error}finally{await browser.close()}
