import assert from 'node:assert/strict'
import {mkdirSync,writeFileSync} from 'node:fs'
import {chromium} from '../../../../host/node_modules/playwright/index.mjs'
const base=process.env.BASE_URL||'http://127.0.0.1:8645/quotagent/',output=process.env.EVIDENCE_DIR||'tmp/product-evidence/commercial-editors'
mkdirSync(output,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:'/opt/hermes/.playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox']})
const pages=[],errors=[],responses=[],checks=[],title=`[Commercial edit check] ${Date.now()}`,report={base,title}
async function fresh(email){const page=await browser.newPage({viewport:{width:1440,height:1000}});pages.push(page);page.setDefaultTimeout(18000);page.on('pageerror',error=>errors.push(error.message));await page.goto(base);await page.getByLabel('Email address',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill('demo1234');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('navigation',{name:'Main navigation'}).waitFor();for(const name of ['Not now','Hide walkthrough'])await page.getByRole('button',{name,exact:true}).click({timeout:600}).catch(()=>{});return page}
async function write(page,path,label,status=200){const pending=page.waitForResponse(row=>row.url().endsWith('/api/'+path)&&row.request().method()==='POST');await page.getByRole('button',{name:label,exact:true}).click();const response=await pending,body=await response.json();responses.push({path,status:response.status(),input:response.request().postDataJSON(),body});assert.equal(response.status(),status,JSON.stringify(body));return body}
async function terms(page,rfqId){await page.goto(base+'#commercial');await page.getByLabel('Workbench request',{exact:true}).selectOption(rfqId);await page.getByRole('tab',{name:'Commercial terms',exact:true}).click();await page.getByLabel('Freight charge',{exact:true}).waitFor()}
const shot=(page,name)=>page.screenshot({path:`${output}/${name}.png`,fullPage:true})
try{
 const buyer=await fresh('contractor@demo.local'),first=await fresh('supplier@demo.local'),second=await fresh('supplier@demo.local')
 await buyer.goto(base+'#rfqs');await buyer.getByRole('button',{name:'New request',exact:true}).click();await buyer.getByLabel('Request title',{exact:true}).fill(title);await buyer.getByLabel('Item 1 description',{exact:true}).fill('Cable reel');await buyer.getByLabel('Item 1 quantity',{exact:true}).fill('10');await buyer.locator('.supplier-options label').filter({hasText:'supplier@demo.local'}).getByRole('checkbox').check();const rfq=(await write(buyer,'workspace/create-rfq','Save request draft')).rfq;await buyer.getByRole('button',{name:'Publish request',exact:true}).click();await write(buyer,'workspace/publish-rfq','Confirm & continue')
 await first.goto(base+'#rfqs?context='+encodeURIComponent(JSON.stringify({rfqId:rfq.id})));await first.getByRole('button',{name:'Prepare quote',exact:true}).click();await first.getByLabel('Unit price for Cable reel',{exact:true}).fill('20');const quote=(await write(first,'workspace/save-quote','Save quotation draft')).quote;report.ids={rfq:rfq.id,quote:quote.id}
 await terms(first,rfq.id);await terms(second,rfq.id);await first.getByLabel('Tax treatment',{exact:true}).selectOption('inclusive');await first.getByLabel('Freight charge',{exact:true}).fill('7');await second.getByLabel('Tax treatment',{exact:true}).selectOption('inclusive');await second.getByLabel('Freight charge',{exact:true}).fill('12')
 // Delay only the second editor's read refresh to reproduce a real stale form.
 let release;const gate=new Promise(resolve=>{release=resolve});let hold=true
 await second.route('**/api/commercial',async route=>{if(hold&&route.request().method()==='GET')await gate;await route.continue()})
 await write(first,'commercial/save-terms','Save commercial terms to draft');const conflict=await write(second,'commercial/save-terms','Save commercial terms to draft',409);assert.equal(conflict.code,'REVISION_CONFLICT');assert.equal(await second.getByLabel('Freight charge',{exact:true}).inputValue(),'12');hold=false;release();await second.getByRole('heading',{name:'The quotation changed while this form was open',exact:true}).waitFor();await shot(second,'01-stale-terms-preserved');checks.push('Delayed read refresh plus concurrent GUI save produces real409; stale editor retains12 freight and exposes the current quotation source')
 await second.getByRole('button',{name:'I reviewed the current quote; keep my edits',exact:true}).click();const saved=await write(second,'commercial/save-terms','Save commercial terms to draft');assert.equal(saved.quote.commercial.freight,12);assert.equal(saved.quote.revision,quote.revision+2)
 await first.getByRole('heading',{name:'The quotation changed while this form was open',exact:true}).waitFor();assert.equal(await first.getByLabel('Freight charge',{exact:true}).inputValue(),'7');await first.getByRole('button',{name:'Load current saved values',exact:true}).click();assert.equal(await first.getByLabel('Freight charge',{exact:true}).inputValue(),'12');await shot(first,'02-explicit-reload');checks.push('Human review-and-keep saves against the new revision; another editor preserves its old draft until explicitly loading current saved values');assert.deepEqual(errors,[]);Object.assign(report,{ok:true,checks,errors})
}catch(error){Object.assign(report,{ok:false,error:error.stack,checks,errors});for(const [i,page]of pages.entries()){await shot(page,'failure-'+i).catch(()=>{});writeFileSync(`${output}/failure-${i}.txt`,await page.locator('body').innerText().catch(()=>''))}process.exitCode=1}
finally{writeFileSync(`${output}/report.json`,JSON.stringify(report,null,2)+'\n');writeFileSync(`${output}/responses.json`,JSON.stringify(responses,null,2)+'\n');console.log(JSON.stringify(report,null,2));await browser.close()}
