import assert from 'node:assert/strict'
import {readFileSync,writeFileSync} from 'node:fs'
import {browserHarness} from '../../file-store/tests/browser-helpers.mjs'
const h=await browserHarness('evidence'),{login,nav,post,click,download,shot,checks}=h,marker=`EVIDENCE_RECONSTRUCTION_READY_${Date.now()}`
try{
 const buyer=await login('contractor@demo.local'),reviewer=await login('supplier@demo.local'),admin=await login('admin@demo.local');await nav(buyer,'Evidence & verification');await buyer.getByLabel('First event sequence').fill('1');await buyer.getByLabel('Last event sequence').fill('10');const exported=await click(buyer,'evidence/export','Create signed audit package'),packageFile=await download(buyer,buyer.getByRole('link',{name:'Download audit package',exact:true}).first(),'source.audit.json'),keyFile=await download(buyer,buyer.getByRole('link',{name:'Download public verification key',exact:true}),'trusted.public.pem');const bundle=JSON.parse(readFileSync(packageFile,'utf8'));assert.equal(bundle.schema,'quotagent/audit-bundle/v1');await shot(buyer,'01-signed-export');checks.push('GUI chooses real ledger range, creates Ed25519 signed audit bundle and separately downloads its public verification key with fingerprint/trust explanation')
 await nav(reviewer,'Evidence & verification');await reviewer.getByRole('tab',{name:'Verify a package',exact:true}).click();await reviewer.getByLabel('Audit package file').setInputFiles(packageFile);let result=await click(reviewer,'evidence/verify','Verify uploaded package');assert.equal(result.verification.ok,false);assert.equal(result.verification.identityStatus,'untrusted-key');await reviewer.getByText('Verification failed',{exact:true}).waitFor();await reviewer.getByRole('button',{name:'Close dialog',exact:true}).click();await reviewer.getByLabel('Trusted public key file').setInputFiles(keyFile);result=await click(reviewer,'evidence/verify','Verify uploaded package');assert.equal(result.verification.ok,true);await reviewer.getByText('Verification passed',{exact:true}).waitFor();await shot(reviewer,'02-independent-verified');await reviewer.getByRole('button',{name:'Close dialog',exact:true}).click();const tampered=structuredClone(bundle);tampered.signature=Buffer.alloc(64).toString('base64');const badFile=`${h.directory}/altered.audit.json`;writeFileSync(badFile,JSON.stringify(tampered));await reviewer.getByLabel('Audit package file').setInputFiles(badFile);result=await click(reviewer,'evidence/verify','Verify uploaded package');assert.equal(result.verification.ok,false);await shot(reviewer,'03-altered-package-refused');await reviewer.getByRole('button',{name:'Close dialog',exact:true}).click();checks.push('Separate reviewer account uploads carried package: missing trusted key fails, independently supplied key validates chain/Merkle/proofs/signature, altered signature fails with retained readable report')
 await nav(buyer,'Agent workspace');const pending=buyer.waitForResponse(response=>response.url().endsWith('/api/assistant/chat')&&response.request().method()==='POST');await buyer.getByLabel('Message your AI assistant').fill(`For a model-input reconstruction check, reply with exactly ${marker}. Do not invoke tools or change any workspace records.`);await buyer.getByRole('button',{name:'Send to AI assistant',exact:true}).click();await pending;await buyer.locator('.assistant-message.from-assistant').filter({hasText:marker}).last().waitFor({timeout:180000});await nav(buyer,'Evidence & verification');await buyer.getByRole('tab',{name:'Model inputs',exact:true}).click();let rebuilt;const response=buyer.waitForResponse(value=>/\/api\/evidence\/calls\/[^/]+\/rebuild$/.test(value.url())&&value.request().method()==='POST');await buyer.getByRole('button',{name:'Reconstruct input',exact:true}).first().click();rebuilt=(await(await response).json()).rebuild;assert.equal(rebuilt.ok,true,JSON.stringify(rebuilt));assert.equal(rebuilt.boundary,'measured');assert.equal(rebuilt.coverage,'matched');await shot(buyer,'04-real-model-reconstruction');await buyer.getByRole('button',{name:'Close dialog',exact:true}).click();const requestFile=await download(buyer,buyer.getByRole('link',{name:'Download recorded request',exact:true}).first(),'recorded-request.json');assert(JSON.parse(readFileSync(requestFile,'utf8')).messages.some(row=>row.content?.includes(marker)));checks.push('Actual configured model invoked only through assistant GUI; evidence GUI reconstructs its containing ledger, source digest and exact dispatch bytes and downloads the recorded request')
 await nav(admin,'Evidence & verification');await admin.getByRole('tab',{name:'Ledger statistics',exact:true}).click();await admin.getByRole('button',{name:'Read all-account totals',exact:true}).click();await admin.getByText(/available accounts.*No event bodies/).waitFor();await shot(admin,'05-admin-counts');assert.equal(await admin.getByText(marker,{exact:true}).count(),0);await reviewer.setViewportSize({width:390,height:844});assert.equal(await reviewer.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);await shot(reviewer,'06-mobile-verification');await reviewer.reload();await reviewer.getByRole('tab',{name:'Verify a package',exact:true}).click();assert(await reviewer.getByRole('button',{name:/Passed ·/}).count()>0);checks.push('Role-owned verification history survives reload; admin observations expose only counts, mobile verification screen fits viewport')
 await h.finish({exportId:exported.export.id,fileId:exported.export.fileId,modelCallId:rebuilt.callId})
}catch(error){await h.fail(error);throw error}finally{await h.close()}
