import assert from 'node:assert/strict'
import {mkdirSync,mkdtempSync,writeFileSync,readFileSync} from 'node:fs'
import {resolve,join} from 'node:path'
import {createServer} from 'node:http'
import {generateKeyPairSync} from 'node:crypto'
import {mount,buyer,supplier,other,admin} from '../../file-store/tests/native-harness.mjs'
import {canonical,sha256,signBundle} from '../code/bundle.mjs'
import * as provider from '../../agent-runtime/code/product-ai.mjs'
mkdirSync('tmp',{recursive:true});const root=mkdtempSync(resolve('tmp/evidence-native-')),checks=[];let a=await mount(join(root,'source')),b=await mount(join(root,'independent')),server
try{
 await a.ctx.store.append(buyer.id,'fixture/business-fact',{quantity:3,note:'原始 evidence\nwith newline',privateCost:17},{actor:'human:buyer'})
 const before=a.ctx.store.events(buyer.id).length,view=a.ctx.evidence.list(buyer),all=a.ctx.evidence.aggregate(admin);assert.equal(a.ctx.store.events(buyer.id).length,before);assert(!JSON.stringify(all).includes('privateCost'));assert.equal(view.summary.events,before);assert.throws(()=>a.ctx.evidence.aggregate(buyer),/Administrator/)
 const exported=await a.ctx.evidence.export(buyer,{fromSeq:1,toSeq:before}),buffer=a.ctx.evidence.download(buyer,exported.export.id).buffer,bundle=JSON.parse(buffer),key=a.ctx.evidence.identity(buyer).publicKey
 assert.equal(a.ctx.store.events(buyer.id).filter(row=>row.type==='evidence/native-exported').length,1);assert.throws(()=>a.ctx.evidence.download(other,exported.export.id),/not found/);assert(!JSON.stringify(a.ctx.store.events(buyer.id)).includes('BEGIN PRIVATE KEY'))
 const verified=(await b.ctx.evidence.verify(supplier,{bundle,trustedPublicKey:key})).verification;assert.equal(verified.ok,true,JSON.stringify(verified));assert.equal(verified.identityStatus,'trusted-signature');assert(verified.checks.some(row=>row.name==='Required event inclusion proofs'&&row.ok));assert.equal(b.ctx.store.events(buyer.id).length,0)
 checks.push('Native exact-byte Unicode ledger slice, Ed25519 wrapper, independent second-store hash-chain/Merkle/inclusion verification, no source ledger or private key needed')
 const noKey=(await b.ctx.evidence.verify(supplier,{bundle})).verification;assert.equal(noKey.ok,false);assert.equal(noKey.identityStatus,'untrusted-key');const wrong=generateKeyPairSync('ed25519').publicKey.export({format:'pem',type:'spki'});assert.equal((await b.ctx.evidence.verify(supplier,{bundle,trustedPublicKey:wrong})).verification.ok,false)
 for(const mutation of ['payload','proof','signature']){const changed=structuredClone(bundle);if(mutation==='payload'){const payload=JSON.parse(Buffer.from(changed.payloadBase64,'base64'));payload.events[0].body.quantity=900;changed.payloadBase64=Buffer.from(JSON.stringify(payload)).toString('base64')}if(mutation==='proof')changed.proofs[0].leaf='0'.repeat(64);if(mutation==='signature')changed.signature=Buffer.alloc(64).toString('base64');assert.equal((await b.ctx.evidence.verify(supplier,{bundle:changed,trustedPublicKey:key})).verification.ok,false,mutation)}
 const altered=structuredClone(bundle),payload=JSON.parse(Buffer.from(altered.payloadBase64,'base64'));payload.events[0].body.quantity=800;const pair=JSON.parse(readFileSync(join(a.ctx.store.root,'evidence-keys',sha256(buyer.id)+'.json'),'utf8')),resigned=signBundle({payloadBase64:Buffer.from(JSON.stringify(payload)).toString('base64'),manifest:payload.manifest,proofs:altered.proofs,scope:payload.scope},{...pair,realm:buyer.id,exportedBy:buyer.id,generatedAt:new Date().toISOString()});const corrupted=(await b.ctx.evidence.verify(supplier,{bundle:resigned,trustedPublicKey:key})).verification;assert.equal(corrupted.identityStatus,'trusted-signature');assert.equal(corrupted.ok,false);assert(corrupted.checks.some(row=>row.name==='Event and body hash chain'&&!row.ok))
 checks.push('Missing/wrong independently trusted key, altered payload/proof/signature, and even re-signed corrupted event all fail without fabricated identity or integrity passes')
 let actualWire='';server=createServer(async(req,res)=>{for await(const part of req)actualWire+=part;res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({choices:[{message:{role:'assistant',content:'Fixture acknowledged'}}],usage:{prompt_tokens:21,completion_tokens:4,total_tokens:25}}))});await new Promise(done=>server.listen(0,'127.0.0.1',done));const configFile=join(root,'provider.json');writeFileSync(configFile,JSON.stringify({llm:{provider:'local-evidence-fixture',model:'fixture'},api_keys:{'local-evidence-fixture':{value:'fixture-key-not-secret',base_url:`http://127.0.0.1:${server.address().port}/v1`,env:'UNUSED_EVIDENCE_KEY'}}}));await a.add(provider,{configFile});await a.ctx.ai.complete(buyer,{purpose:'evidence-fixture',messages:[{role:'user',content:'SOURCE_DATA: '+JSON.stringify({note:'原始\nline',price:123})}]});const event=a.ctx.store.events(buyer.id).find(row=>row.type==='agent/model-requested'&&row.body.purpose==='evidence-fixture'),rebuilt=(await a.ctx.evidence.rebuild(buyer,event.body.callId)).rebuild;assert.equal(rebuilt.ok,true,JSON.stringify(rebuilt));assert.equal(rebuilt.boundary,'measured');assert.equal(rebuilt.requestSha256,sha256(actualWire));assert.equal(rebuilt.coverage,'matched');assert.throws(()=>a.ctx.evidence.request(supplier,event.body.callId),/missing/)
 await a.ctx.store.append(buyer.id,'agent/model-requested',{callId:'historical',request:{model:'old',messages:[{role:'user',content:'old recorded facts'}]}});const historical=(await a.ctx.evidence.rebuild(buyer,'historical')).rebuild;assert.equal(historical.ok,true);assert.equal(historical.boundary,'unmeasured');assert(historical.limitations.some(row=>row.includes('historical')))
 await a.ctx.store.append(buyer.id,'agent/model-requested',{callId:'bad-source',request:{model:'fixture',messages:[{role:'user',content:'SOURCE_DATA: {"price":1}'}]},contextReceipt:{selectedSourceHash:'0'.repeat(64),groups:[]}});const failed=(await a.ctx.evidence.rebuild(buyer,'bad-source')).rebuild;assert.equal(failed.ok,false);assert.equal(failed.coverage,'mismatch');assert(a.ctx.notifications.list(buyer).some(row=>row.title==='Model input reconstruction failed'));assert.equal((await a.ctx.evidence.rebuild(buyer,'missing-call')).rebuild.ok,false)
 checks.push('Actual local HTTP provider request reconstructed byte-for-byte from dispatch receipt, source digest matched, historical boundary explicitly unknown, missing/mismatched input records failure and alert')
 await a.close();a=await mount(join(root,'source'));assert.equal(a.ctx.evidence.identity(buyer).publicKey,key);assert.equal(a.ctx.evidence.download(buyer,exported.export.id).buffer.toString(),buffer.toString());assert(a.ctx.evidence.list(buyer).rebuilds.length>=4)
 checks.push('Public identity, original exported bytes and reconstruction outcomes survive native restart; read-only stats append nothing; private realms and body-free admin observations preserved')
 const report={ok:true,at:new Date().toISOString(),root,checks,passed:checks.length};writeFileSync(join(root,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2))
}finally{if(server?.listening)await new Promise(done=>server.close(done));await a.close();await b.close()}
