import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {mkdirSync,writeFileSync} from 'node:fs'
import {resolve,join} from 'node:path'
const require=createRequire(new URL('../../../../host/package.json',import.meta.url)),{chromium}=require('playwright')
const base=(process.env.BASE_URL||'http://127.0.0.1:8642/quotagent/').replace(/\/?$/,'/'),output=resolve(process.env.EVIDENCE_DIR||'tmp/product-evidence/extension-evolution'),name=process.env.EXISTING_NAME||`Quantity trial ${Date.now()}`
mkdirSync(output,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:'/opt/hermes/.playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox']});const report={base,at:new Date().toISOString(),name,checks:[],screenshots:[],browserErrors:[]};let admin,client,disabled=false
const shot=async(page,name)=>{await page.screenshot({path:join(output,name),fullPage:true});report.screenshots.push(name)}
async function login(role){const page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(20000);page.on('pageerror',e=>report.browserErrors.push(e.message));await page.goto(base);await page.getByRole('button',{name:role==='admin'?'Administrator sign in':'I’m a contractor'}).click();await page.locator('.sidebar').waitFor();const dismiss=page.getByRole('button',{name:'Not now',exact:true});if(await dismiss.isVisible())await dismiss.click();return page}
async function nav(page,label,group){const button=page.locator('.sidebar').getByRole('button',{name:label,exact:true});if(!await button.isVisible()&&group)await page.locator('.sidebar').getByRole('button',{name:group,exact:true}).click();await button.click()}
async function toggle(enabled){await admin.getByLabel('Search application plugins',{exact:true}).fill('Personal plugins and marketplace');const card=admin.locator('.studio-catalog-plugin').filter({has:admin.getByRole('heading',{name:'Personal plugins and marketplace',exact:true})});await card.getByRole('button',{name:enabled?'Enable':'Disable',exact:true}).click();await card.getByRole('button',{name:enabled?'Disable':'Enable',exact:true}).waitFor();disabled=!enabled}
try{
 client=await login('contractor');await nav(client,'Plugin studio','Personalize');if(!process.env.EXISTING_NAME){await client.getByLabel('Describe an extension',{exact:true}).fill(`Create a calculator plugin named exactly "${name}". One numeric input field name quantity, label Quantity, default3. Implement pure function returning exactly {total: input.quantity * 2}. No summary, extra fields or rounding. This is an isolated test tool for doubling quantity, not a price or commitment.`);await client.getByRole('button',{name:'Create with AI',exact:true}).click();}const card=client.locator('.plugin-card').filter({has:client.getByRole('heading',{name,exact:true})});await card.waitFor({timeout:180000});report.pluginId=await card.getAttribute('data-plugin-id');report.checks.push('Actual configured model generated an executable personal tool through GUI')
 await card.getByRole('button',{name:'Improve & history',exact:true}).click();let modal=client.getByRole('dialog',{name:`Improve ${name}`,exact:true});await modal.getByLabel('What should improve?',{exact:true}).fill('Improve the calculation: quantity must be multiplied by 3 instead of 2. Keep the exact same name, single quantity input, and return shape with only total. At quantity3 the expected total is9. This is not a price commitment.');await modal.getByRole('button',{name:'Save feedback',exact:true}).click();await modal.getByRole('button',{name:'Create revision proposal with AI',exact:true}).click();await modal.getByRole('button',{name:'Evaluate this proposal',exact:true}).waitFor({timeout:180000});await shot(client,'01-feedback-proposal-diff.png');report.checks.push('Original feedback saved; actual model returned inactive proposed revision with rationale, risks, rollback and exact diff')
 await modal.getByRole('button',{name:'Inspect both revisions',exact:true}).click();await modal.getByText('Revision history',{exact:true}).last().waitFor();await shot(client,'02-immutable-revision-source.png');await modal.getByRole('button',{name:'Paired evaluation',exact:true}).click();await modal.getByLabel('Example name',{exact:true}).fill('Three units');await modal.getByLabel('Case Quantity',{exact:true}).fill('3');await modal.getByRole('button',{name:'Retain this case',exact:true}).click();await modal.getByRole('button',{name:'Run paired evaluation',exact:true}).click();await modal.getByRole('heading',{name:'Observed paired results',exact:true}).waitFor();const pair=modal.locator('.evolution-case-result');assert.match(await pair.innerText(),/6/);assert.match(await pair.innerText(),/9/);await modal.getByLabel('baseline result Three units',{exact:true}).selectOption('no');await modal.getByLabel('candidate result Three units',{exact:true}).selectOption('yes');await modal.getByLabel('baseline intervention Three units',{exact:true}).selectOption('yes');await modal.getByLabel('candidate intervention Three units',{exact:true}).selectOption('no');await modal.getByLabel('Review notes',{exact:true}).fill('Observed actual total6 before and9 after at quantity3. Candidate meets the requested example without correction.');await modal.getByRole('button',{name:'Record paired review',exact:true}).click();await modal.getByRole('button',{name:'Set up limited trial',exact:true}).waitFor();await modal.locator('button:enabled').filter({hasText:'Set up limited trial'}).waitFor();await shot(client,'03-paired-results-five-checks.png');report.checks.push('Retained frozen counterexample, actual6→9 paired execution, explicit human classification and five passed checks')
 await modal.getByRole('button',{name:'Set up limited trial',exact:true}).click();await modal.getByLabel('Maximum observations',{exact:true}).fill('1');await modal.getByRole('button',{name:'Start limited trial',exact:true}).click();await modal.getByRole('button',{name:'Try candidate tool',exact:true}).click();const tool=client.getByRole('dialog').last();await tool.getByRole('button',{name:'Run tool',exact:true}).click();await tool.getByRole('region',{name:'Utility result'}).waitFor();await tool.getByText('Result details',{exact:true}).click();assert.match(await tool.getByRole('region',{name:'Utility result'}).innerText(),/9/);await tool.getByRole('button',{name:'Close',exact:true}).click();await modal.getByText(/Baseline restoration verified/).waitFor();await shot(client,'04-observed-trial-rollback.png');await modal.getByRole('button',{name:'Make reviewed revision current',exact:true}).click();await modal.getByRole('button',{name:'Revision is current',exact:true}).waitFor();report.checks.push('Explicit owner-only live trial executed candidate; one-observation window unloaded it and verified baseline restoration before human deployment')
 await modal.getByRole('button',{name:'Revision history',exact:true}).click();await modal.getByRole('button',{name:'Restore revision 1',exact:true}).click();await modal.getByText('Current revision 1',{exact:true}).waitFor();await shot(client,'05-restored-historical-artifact.png');report.checks.push('GUI restored previous immutable revision1 after reviewed deployment')
 await client.setViewportSize({width:390,height:900});assert.equal(await client.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await shot(client,'06-mobile-history.png');await client.setViewportSize({width:1440,height:1000});await modal.getByRole('button',{name:'Close dialog',exact:true}).click()
 admin=await login('admin');await nav(admin,'Application plugins','Manage application');await toggle(false);await client.reload();await nav(client,'Installed tools','Personalize');assert.equal(await client.locator('.sidebar').getByRole('button',{name:'Plugin studio',exact:true}).count(),0);await client.getByText('Plugin studio is currently disabled.',{exact:false}).waitFor();const installed=client.locator('.installed-card').filter({has:client.getByRole('heading',{name,exact:true})});await installed.getByRole('button',{name:'Open tool',exact:true}).click();const running=client.getByRole('dialog').last();await running.getByRole('button',{name:'Run tool',exact:true}).click();await running.getByRole('region',{name:'Utility result'}).waitFor();await running.getByText('Result details',{exact:true}).click();assert.match(await running.getByRole('region',{name:'Utility result'}).innerText(),/6/);await shot(client,'07-studio-off-installed-tool-runs.png');await running.getByRole('button',{name:'Close',exact:true}).click();await client.getByRole('button',{name:'Check artifact status',exact:true}).click();await client.getByRole('heading',{name:'Installed artifact status',exact:true}).waitFor();assert.equal(await client.getByText('inconsistent',{exact:true}).count(),0);await shot(client,'08-consistent-artifact-inventory.png');await toggle(true);report.checks.push('Admin disabled Studio through GUI; independent installed page, artifact inspection and actual tool execution survived; management restored')
 assert.equal(report.browserErrors.length,0);report.ok=true;console.log(JSON.stringify(report,null,2))
}catch(error){report.error=error.stack;console.error(JSON.stringify(report,null,2));if(client)await shot(client,'failure.png');process.exitCode=1}
finally{if(disabled&&admin)try{await toggle(true)}catch(error){report.restoreError=error.message}writeFileSync(join(output,'report.json'),JSON.stringify(report,null,2)+'\n');await browser.close()}
