import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {mkdtempSync,mkdirSync,readFileSync,writeFileSync} from 'node:fs'
import {resolve,join} from 'node:path'
import * as store from '../../workspace-store/code/index.mjs'
import * as runtime from '../../installed-plugins/code/index.mjs'
import * as studio from '../code/product.mjs'
const require=createRequire(new URL('../../../../host/package.json',import.meta.url)),{Context}=require('cordis')
const users=[{id:'evo-owner',name:'Owner',role:'contractor'},{id:'evo-other',name:'Other',role:'supplier'},{id:'evo-admin',name:'Admin',role:'admin'}],owner=users[0],other=users[1],admin=users[2]
mkdirSync('tmp',{recursive:true});const root=mkdtempSync(resolve('tmp/extension-evolution-')),checks=[]
const descriptor=(multiplier=2)=>({name:'Quantity total',description:'A real fixture calculation.',kind:'calculator',spec:{title:'Quantity total',fields:[{name:'quantity',label:'Quantity',type:'number',default:2}],code:`function(input) { return {total: input.quantity * ${multiplier}} }`}})
const tools=new Map();const fixtureAI={status:()=>({available:true}),complete:async()=>({content:JSON.stringify(descriptor())})}
async function boot(){const ctx=new Context(),fibers=[],routes=[],extensions=[],navigation=[];const add=(rows,row)=>{rows.push(row);return()=>{const index=rows.indexOf(row);if(index>=0)rows.splice(index,1)}};const mount=async(module,config)=>{const fiber=await ctx.plugin(module,config);assert.equal(fiber.state,2);fibers.push(fiber);return fiber}
 await mount({name:'evolution-test-fixture',apply(child){child.provide('accounts',{list:()=>users,get:id=>users.find(user=>user.id===id),can:()=>true});child.provide('ai',fixtureAI);child.provide('assistant',{tool:definition=>{tools.set(definition.name,definition);return()=>tools.delete(definition.name)}});child.provide('web',{route:(...args)=>add(routes,args),extension:(scope,descriptor)=>add(extensions,{scope,descriptor}),contribute:item=>add(navigation,item)})}});await mount(store,{root});const runtimeFiber=await mount(runtime),studioFiber=await mount(studio);return{ctx,routes,extensions,navigation,runtimeFiber,studioFiber,mount,close:async()=>{for(const fiber of fibers.reverse())await fiber.dispose()}}}
let run=await boot(),pluginId,trialId
try{
 let {ctx}=run,rt=ctx.installedPlugins,evo=ctx.studio.evolution
 const made=await ctx.studio.generate(owner,{prompt:'Fixture: double quantity'});pluginId=made.plugin.id;const first=rt.history(owner,pluginId).revisions[0],firstBytes=first.source
 assert.equal((await rt.run(owner,pluginId,{input:{quantity:3}})).result.total,6)
 await ctx.studio.execute(owner,pluginId,'configure',{spec:{code:descriptor(3).spec.code},expectedRevisionId:first.id});assert.equal((await rt.run(owner,pluginId,{input:{quantity:3}})).result.total,9)
 assert.equal(rt.revision(owner,pluginId,first.id).source,firstBytes);assert.equal(rt.history(owner,pluginId).revisions.length,2)
 await assert.rejects(rt.configure(owner,pluginId,{expectedRevisionId:first.id,name:'Stale'}),/changed/)
 await rt.restore(owner,pluginId,first.id);assert.equal((await rt.run(owner,pluginId,{input:{quantity:3}})).result.total,6);assert.equal(readFileSync(join(rt.artifactRoot,owner.id,pluginId,'index.mjs'),'utf8'),firstBytes)
 assert.ok(rt.history(owner,pluginId).revisions.every(row=>row.everActive));checks.push('actual generated utility, immutable revision/edit/conflict and exact-byte restore')
 await rt.mutate(owner,pluginId,'publish');const copied=(await rt.mutate(other,pluginId,'install')).plugin;assert.equal(rt.revision(other,copied.id,copied.revisionId).origin.sourceHash,first.sourceHash)
 await rt.configure(other,copied.id,{spec:{code:descriptor(4).spec.code}});await rt.restore(owner,pluginId,first.id);assert.equal((await rt.run(other,copied.id,{input:{quantity:3}})).result.total,12);assert.equal(rt.list(other).plugins.filter(row=>row.lineageId===pluginId).length,1)
 assert.throws(()=>rt.history(other,pluginId),/belongs/);checks.push('realm ownership and independent copied revision provenance')
 const feedback=await evo.feedback(owner,pluginId,{body:'  For a quantity of 3, return 9.\n',view:'extensions'}),proposal=await evo.propose(owner,pluginId,{feedbackId:feedback.id,descriptor:descriptor(3),rationale:'Triple the input',expectedEffect:{minimumDelta:0,description:'Return the expected total'},risks:['Other inputs must be retained'],rollbackPlan:'Restore the doubled baseline'})
 assert.equal(feedback.body,'  For a quantity of 3, return 9.\n');assert.equal(rt.lookup(pluginId).revisionId,first.id);assert.ok(proposal.diff.some(row=>row.field==='spec.code'));assert.equal(evo.detail(owner,pluginId).feedback[0].bodyHash.length,64)
 const test=await evo.addCase(owner,pluginId,{title:'Three units',input:{quantity:3},counterexample:true,expected:{total:9}})
 const report=await evo.shadow(owner,proposal.id,{maxLatencyMs:1000,maxTokens:0});assert.equal(report.pairs[0].baseline.output.total,6);assert.equal(report.pairs[0].candidate.output.total,9);assert.equal(report.gates.allPassed,false)
 await assert.rejects(evo.startTrial(owner,proposal.id,{}),/five paired/)
 const reviewed=await evo.assess(owner,report.id,{assessments:[{caseId:test.id,baselineAccept:false,candidateAccept:true,baselineNeedsHuman:true,candidateNeedsHuman:false}],note:'Exact expectation matches the candidate.'});assert.equal(reviewed.gates.allPassed,true)
 await assert.rejects(evo.deploy(owner,proposal.id),/observed trial/);checks.push('frozen paired actual execution, visible unmeasured gates, five simultaneous reviewed checks')
 const trial=await evo.startTrial(owner,proposal.id,{cohortIds:[owner.id],maxObservations:1});trialId=trial.id;assert.equal(rt.get(owner,pluginId).revisionId,proposal.candidateRevisionId)
 assert.equal((await rt.run(owner,pluginId,{input:{quantity:3}})).result.total,9);const ended=rt.trials(owner,pluginId)[0];assert.equal(ended.status,'rolled-back');assert.equal(ended.rollbackVerified,true);assert.equal(rt.get(owner,pluginId).revisionId,first.id)
 assert.equal((await evo.deploy(owner,proposal.id)).plugin.revisionId,proposal.candidateRevisionId);assert.equal(evo.detail(owner,pluginId).feedback[0].status,'resolved');checks.push('explicit owner canary, actual observed execution, automatic window rollback and reviewed promotion')
 const baselineNow=rt.lookup(pluginId).revisionId,bad=await rt.stage(owner,pluginId,{...descriptor(),spec:{...descriptor().spec,code:'function() { throw new Error("fixture failure") }'}},{baseRevisionId:baselineNow})
 await rt.startTrial(owner,pluginId,bad.id,{cohortIds:[owner.id],maxErrors:0});await assert.rejects(rt.run(owner,pluginId,{input:{quantity:3}}),/fixture failure/);assert.equal(rt.trials(owner,pluginId)[0].rollbackVerified,true);assert.equal(rt.get(owner,pluginId).revisionId,baselineNow);checks.push('execution failure triggers real candidate disposal and verified baseline restoration')
 const global=(await rt.mutate(admin,pluginId,'promote')).plugin,candidate=await rt.stage(admin,global.id,descriptor(8),{baseRevisionId:global.revisionId});await rt.startTrial(admin,global.id,candidate.id,{cohortIds:[admin.id],maxObservations:3});assert.equal((await rt.run(admin,global.id,{input:{quantity:2}})).result.total,16);assert.equal((await rt.run(other,global.id,{input:{quantity:2}})).result.total,6);await rt.rollback(admin,rt.trials(admin,global.id)[0].id);checks.push('global canary only affects declared account cohort')
 const failed=await evo.feedback(owner,pluginId,{body:'Try the same unchanged source.'});for(let i=0;i<3;i++)await assert.rejects(evo.propose(owner,pluginId,{feedbackId:failed.id,descriptor:descriptor(3)}),/does not change/)
 await assert.rejects(evo.propose(owner,pluginId,{feedbackId:failed.id,descriptor:descriptor(5)}),/Three attempts/);await evo.retry(owner,failed.id,{note:'Human reviewed the failure and chose a changed expected outcome.'});assert.ok(await evo.propose(owner,pluginId,{feedbackId:failed.id,descriptor:descriptor(5)}));checks.push('three similar failures escalate and require explicit human retry note')
 const path=join(rt.artifactRoot,owner.id,pluginId,'index.mjs'),bytes=readFileSync(path);writeFileSync(path,'// deliberate fixture drift');const inv=rt.inventory(owner,{limit:1});assert.ok(inv.inconsistent>=1);assert.ok(rt.inventory(owner).items.some(row=>row.differences.some(item=>item.field==='active artifact.sourceHash')));assert.equal(Object.hasOwn(inv.items[0],'source'),false);assert.ok(inv.total>=1);writeFileSync(path,bytes);assert.equal(rt.inventory(owner).inconsistent,0);checks.push('metadata-only artifact inventory detects ledger/disk/live disagreement')
 const skill=await rt.create(owner,{name:'Prompt fixture',description:'No external actions',kind:'skill',spec:{prompt:'Summarize this recorded request.',steps:[]}}),sf=await evo.feedback(owner,skill.plugin.id,{body:'Make the draft shorter.'}),sp=await evo.propose(owner,skill.plugin.id,{feedbackId:sf.id,descriptor:{name:'Prompt fixture',description:'No external actions',kind:'skill',spec:{prompt:'Summarize this recorded request in one sentence.',steps:[]}}})
 const sc=await evo.addCase(owner,skill.plugin.id,{title:'Short request',input:{request:'Prepare a draft'},counterexample:true}),sr=await evo.shadow(owner,sp.id,{maxTokens:10000}),sa=await evo.assess(owner,sr.id,{assessments:[{caseId:sc.id,baselineAccept:true,candidateAccept:true,baselineNeedsHuman:false,candidateNeedsHuman:false}]})
 assert.equal(sa.gates.items.find(row=>row.id==='resources').status,'unmeasured');await assert.rejects(evo.startTrial(owner,sp.id,{}),/five paired/);checks.push('model-only skill replay does not invent missing token usage or permit an unmeasured trial')
 const inspected=await tools.get('inspect_extension_evolution').execute(owner,{pluginId});assert.equal(inspected.plugin.id,pluginId);assert.ok(ctx.store.events(owner.id).some(event=>event.type==='studio/revision-inspected'));assert.equal(tools.get('propose_extension_revision').effect,'draft');checks.push('assistant self-inspection is ledger-visible and revision generation remains draft-only')
 const summary=evo.summary(owner);assert.ok(summary.counts.feedback>=2);assert.ok(!JSON.stringify(summary).includes('For a quantity'));checks.push('metadata-only bounded evolution summary')
 await run.studioFiber.dispose();assert.equal(tools.has('propose_extension_revision'),false);assert.ok(!run.routes.some(([,path])=>path.startsWith('/studio')));assert.ok(run.routes.some(([,path])=>path==='/installed-plugins/:id/run'));assert.equal((await rt.run(owner,pluginId,{input:{quantity:2}})).result.total,6);assert.ok(run.extensions.some(row=>row.descriptor.installedId===pluginId));checks.push('Studio native unload removes management while installed fibers and run routes remain')
 const pending=await rt.stage(owner,pluginId,descriptor(10),{baseRevisionId:rt.lookup(pluginId).revisionId});await rt.startTrial(owner,pluginId,pending.id,{cohortIds:[owner.id]});await run.close();run=await boot();ctx=run.ctx;rt=ctx.installedPlugins;assert.equal((await rt.run(owner,pluginId,{input:{quantity:2}})).result.total,6);assert.equal(rt.trials(owner,pluginId)[0].status,'rolled-back');assert.equal(rt.trials(owner,pluginId)[0].rollbackVerified,true);assert.equal(ctx.studio.evolution.detail(owner,pluginId).cases.length,1);checks.push('restart reconstructs immutable history/counterexamples and safely restores interrupted canary baseline')
 console.log(JSON.stringify({ok:true,root,checks},null,2))
}finally{await run.close()}
