import assert from 'node:assert/strict'
import {mkdirSync,writeFileSync} from 'node:fs'
import {chromium} from '../../../../host/node_modules/playwright/index.mjs'
export async function browserHarness(name){const base=process.env.BASE_URL||'http://127.0.0.1:8648/quotagent/',directory=process.env.EVIDENCE_DIR||`tmp/agent-experience/artifacts/${name}`;mkdirSync(directory,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||'/opt/hermes/.playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell'}),pages=[],errors=[],responses=[],checks=[]
 const shot=(page,name)=>page.screenshot({path:`${directory}/${name}.png`,fullPage:true,animations:'disabled'})
 const login=async email=>{const page=await browser.newPage({viewport:{width:1440,height:1100}});pages.push(page);page.setDefaultTimeout(20000);page.on('pageerror',error=>errors.push(error.message));await page.goto(base);await page.getByLabel('Email address').fill(email);await page.getByLabel('Password',{exact:true}).fill('demo1234');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('navigation',{name:'Main navigation'}).waitFor();await page.getByRole('button',{name:'Not now',exact:true}).click({timeout:1200}).catch(()=>{});return page}
 const nav=async(page,name)=>{const navigation=page.getByRole('navigation',{name:'Main navigation'}),target=navigation.getByRole('button',{name,exact:true});await navigation.waitFor();await page.waitForTimeout(100);if(!await target.isVisible())await navigation.locator('.ws-nav-group').filter({has:page.getByRole('button',{name,exact:true,includeHidden:true})}).locator('.ws-group-toggle').click();await target.click()}
 const post=async(page,path,trigger)=>{const response=page.waitForResponse(row=>row.url().endsWith(`/api/${path}`)&&row.request().method()==='POST');await trigger();const value=await response,body=await value.json();responses.push({path,body});assert.equal(value.status(),200,`${path}: ${JSON.stringify(body)}`);return body}
 const click=(page,path,label)=>post(page,path,()=>page.getByRole('button',{name:label,exact:true}).click())
 const download=async(page,locator,filename)=>{const pending=page.waitForEvent('download');await locator.click();await(await pending).saveAs(`${directory}/${filename}`);return`${directory}/${filename}`}
 const finish=async(extra={})=>{assert.deepEqual(errors,[]);const report={ok:true,at:new Date().toISOString(),base,checks,jsErrors:errors,...extra};writeFileSync(`${directory}/report.json`,JSON.stringify(report,null,2));writeFileSync(`${directory}/responses.json`,JSON.stringify(responses,null,2));console.log(JSON.stringify(report,null,2));return report}
 const fail=async error=>{for(const [index,page]of pages.entries()){await shot(page,`failure-${index}`).catch(()=>{});writeFileSync(`${directory}/failure-${index}.txt`,await page.locator('body').innerText().catch(()=>''))}writeFileSync(`${directory}/failure.json`,JSON.stringify({error:error.stack,checks,errors,responses},null,2))}
 return{base,directory,browser,pages,errors,responses,checks,shot,login,nav,post,click,download,finish,fail,close:()=>browser.close()}
}
