const clients=['contractor','supplier'],all=[...clients,'admin']
export const contentSources=[
 'docs/design/architecture.md','docs/product/getting-started.md',
 'src/domain/procurement/code/service.mjs','src/domain/ingestion/requirements/README.md',
 'src/system/mail/requirements/product.md','src/system/telegram/requirements/README.md',
 'src/system/agent-connections/requirements/functional.md','src/system/agent-workflows/code/index.mjs',
 'src/domain/procurement/requirements/public-declarations.md','src/domain/procurement/requirements/submission-batches.md',
 'src/domain/procurement/requirements/fulfillment.md','src/domain/response-workbench/requirements/business-measures.md',
 'src/system/attachments/requirements/native.md','src/system/evidence/requirements/native.md','src/system/retention/requirements/native.md',
 'src/system/exchange-mail/requirements.md','src/system/sandbox/requirements.md',
 'src/system/workspace-styles/requirements/README.md','src/system/agent-runtime/client/assistant.jsx','src/system/agent-runtime/requirements/usage.md',
]
export const tours={
 contractor:{title:'From a brief to a considered decision',intro:'Your agent prepares the work. You choose the suppliers and approve what leaves your workspace.',steps:[
  {title:'Start with the outcome',body:'Tell your agent what you need to source. Paste a brief, ask it to compare existing offers, or ask for your next useful step. Drafts remain editable.',view:'agent',label:'Open agent workspace',icon:'spark'},
  {title:'Bring in the source',body:'Upload an email, spreadsheet or document. Review the extracted descriptions, quantities, units and currency before importing a private request draft.',view:'ingestion',label:'Open document ingestion',icon:'file'},
  {title:'Review the quotation work',body:'Check the request and invited suppliers before publishing. When offers arrive, compare price, delivery and terms together. Ask your agent to draft a clarification when details are missing.',view:'rfqs',label:'Open requests',icon:'quote'},
  {title:'Make the decision',body:'Prepare an award intent and obtain the supplier’s confirmation. An eligible colleague grants independent approval; the proposer then signs the exact order. Follow delivery and invoice matching in Orders.',view:'approvals',label:'Open review actions',icon:'check'},
 ]},
 supplier:{title:'From an opportunity to a reviewed offer',intro:'Keep your pricing work private while your agent helps you understand and respond to the request.',steps:[
  {title:'Ask where to begin',body:'Ask your agent to read your incoming requests, point out missing scope, and suggest which opportunity needs attention first. It works with your account’s information.',view:'agent',label:'Open agent workspace',icon:'spark'},
  {title:'Check the scope',body:'Open an incoming request. Read quantities, units, deadline and requirements before preparing an offer. Use project messages to clarify anything that affects your price.',view:'rfqs',label:'Open requests',icon:'file'},
  {title:'Build your private quote',body:'Enter unit prices, your private costs, lead time and payment terms. Import an existing offer if useful, then reconcile its currency and units with the chosen request. Review the draft before submitting.',view:'quotes',label:'Open quotations',icon:'quote'},
  {title:'Review and follow through',body:'Review agent-prepared submissions and replies before sending. Confirm an acceptable award intent, then inspect and acknowledge the issued order. Your private costs stay in your workspace.',view:'approvals',label:'Open review actions',icon:'check'},
 ]},
 admin:{title:'A workspace your team can rely on',intro:'Administration is separate from supplier and contractor work. Start with the capabilities your team needs.',steps:[
  {title:'Work with your agent',body:'Use your agent workspace for questions and personal tools. Use an agent run when a task benefits from an explicit plan, specialist work and checkpoints.',view:'agent',label:'Open agent workspace',icon:'spark'},
  {title:'Manage people and access',body:'Administration lets you manage account roles and access controls. Each person has one client role, or a separate administrator role.',view:'admin',label:'Open administration',icon:'users'},
  {title:'Choose the application capabilities',body:'Application plugins shows the actual native plugins and their dependencies. Enable the capabilities the team needs; disabling a plugin removes its registered effects.',view:'plugins',label:'Open application plugins',icon:'puzzle'},
  {title:'Set shared defaults deliberately',body:'Plugin settings contains shared defaults and your own account settings. Mail, messaging and connection credentials belong only to the signed-in account. Shared personal extensions can be reviewed in Plugin studio.',view:'plugin-settings',label:'Open plugin settings',icon:'settings'},
 ]},
}
export const topics=[
 {id:'contractor-work',group:'Get started',roles:['contractor'],title:'Prepare a request and compare offers',summary:'Turn the source into clear scope, then judge price and terms together.',icon:'file',steps:[
  'Start in the agent workspace with the outcome, source brief and any known deadline or delivery constraints. Ask for an editable request draft.',
  'Open Requests to check the title, quantities, units, currency and invited suppliers. Declare measurement rules, interface responsibilities, deliverables and exclusions before publishing. Saved private drafts remain in your party workspace.',
  'After supplier submissions arrive, open the request comparison. Look at the full total, lead time, payment terms and missing scope. Ask the agent for a grounded comparison or a draft clarification.',
  'Prepare the chosen award intent, obtain the supplier’s confirmation and nominate an eligible independent colleague. After their grant, sign the reviewed order and follow supplier acknowledgment in Orders.',
 ],note:'The agent can prepare a decision, but your approval is required to publish, award or commit. A low price alone does not resolve missing scope.',actions:[{view:'rfqs',label:'Open requests'},{view:'quotes',label:'Open quotations'},{view:'orders',label:'Open orders'}]},
 {id:'supplier-work',group:'Get started',roles:['supplier'],title:'Prepare and submit a quotation',summary:'Understand the requested scope and keep your cost work private.',icon:'quote',steps:[
  'Open Requests and choose an incoming request. Check line quantities, units, currency and deadline. Clarify missing scope before pricing it.',
  'Prepare a quote with unit prices, private costs if useful, lead time, payment terms and notes. Save it as a draft while you are still working.',
  'Ask the agent to check the draft or prepare a response. Review the complete quote before submitting it to the contractor.',
  'Respond to the contractor’s award intent. Once the independently approved order arrives, inspect and acknowledge it. Use the same project conversation for follow-up questions and changes.',
 ],note:'Your costs stay in your supplier party workspace, never the contractor’s. Your view contains your own offers; it does not reveal or rank competitors’ private bids.',actions:[{view:'rfqs',label:'Open requests'},{view:'quotes',label:'Open quotations'},{view:'orders',label:'Open orders'}]},
 {id:'admin-work',group:'Get started',roles:['admin'],title:'Manage accounts and the application',summary:'Separate team access, native capabilities and shared defaults.',icon:'shield',steps:[
  'Open Administration to review people, roles and access controls. Client roles see only their own side of the quotation workflow.',
  'Open Application plugins to inspect the native inventory and dependencies. Enable or disable optional capabilities there.',
  'Use Plugin settings for shared defaults. Read the setting scope: account-owned connections and personal preferences remain yours, even when you are an administrator.',
  'Review shared extensions in Plugin studio before promoting a useful one to a global default. A personal workspace style does not change everyone else’s style.',
 ],actions:[{view:'admin',label:'Open administration'},{view:'plugins',label:'Open application plugins'},{view:'plugin-settings',label:'Open plugin settings'}]},
 {id:'agent-chat',group:'Work with AI',roles:all,title:'Give your agent a useful task',summary:'Start with an outcome and the information that matters.',icon:'spark',steps:[
  'Describe what you want to achieve, then provide the brief, selected request or source document. For example: “Compare these offers and draft the two most useful questions before I decide.”',
  'Say what is known, what is missing and any constraints. The agent can read your workspace, use available tools, prepare drafts and suggest next steps.',
  'Open the returned draft or source link and review the facts. If a source is incomplete, add the missing detail rather than treating an invented assumption as agreed scope.',
  'For a longer task, use Agent workroom to follow an explicit plan and specialist steps. For a reusable task, ask for a saved skill.',
 ],note:'A provider must be configured for live AI. Drafting and analysis do not replace your review of a commercial decision.',actions:[{view:'agent',label:'Open agent workspace'},{view:'plugin-settings',label:'Open provider settings'}]},
 {id:'assistant-controls',group:'Work with AI',roles:all,title:'Pause, steer or stop your assistant',summary:'Change direction without losing the work already recorded.',icon:'spark',steps:[
  'While the assistant is working, its task card shows the current state and the tool results already saved. Use Pause task when you want to inspect the direction.',
  'Type a correction or extra detail in the same composer. While work is running, guidance updates the current task; while paused, it is saved until you resume.',
  'Choose Resume task when you are ready to continue. Choose Stop task when this task should end.',
  'Return after a reload to inspect the saved state. Stopping does not remove drafts or undo actions that already completed; review those records separately.',
 ],note:'Your request context and account data remain available through the owning tools. An agent still needs your approval for a proposed external commitment.',actions:[{view:'agent',label:'Open agent workspace'}]},
 {id:'ai-usage',group:'Work with AI',roles:all,title:'Understand your AI usage',summary:'Inspect reported token counts and the calls behind them.',icon:'grid',steps:[
  'Open AI usage under Personalize. Choose the date range, model, provider, activity or status you want to inspect.',
  'Use the chart and recent calls to see when usage occurred and which work it served. Input and output counts come from recorded provider responses.',
  'Read the coverage note. Some providers or failed calls do not report every count; a missing value is different from a reported zero.',
 ],note:'Configured-rate cost estimates are separate from token counts and are not invoices. Unpriced calls remain unknown; different currencies stay separate. Cache and reasoning counts are subsets of input/output totals. Administrators can select the separate all-account scope.',actions:[{view:'ai-usage',label:'Open AI usage'}]},
 {id:'agent-runs',group:'Work with AI',roles:all,title:'Follow an agent run',summary:'Plan, specialists, questions and a trace you can return to.',icon:'users',steps:[
  'Open Agent workroom and start a run with the desired outcome. Review the proposed plan and its specialist tasks.',
  'Follow each step as it works. When the team needs your input, answer the specific question so it can continue with the missing fact.',
  'Pause or cancel a run when the direction needs to change. Read its synthesis and source/tool trace before acting on the result.',
  'If work was interrupted, return to the saved run and choose its available recovery action. External commitments still go through their own human review.',
 ],actions:[{view:'workroom',label:'Open agent workroom'}]},
 {id:'reviews',group:'Get started',roles:all,title:'Review an action and understand its receipt',summary:'See the exact request before it is sent or applied.',icon:'check',steps:[
  'Open Review actions from navigation or from an agent’s proposed-action card. Check the exact recipient, text, record or tool input.',
  'Approve only when the contents are ready. Decline if they need changing, then edit the draft and prepare a new review.',
  'Read the result after execution. A succeeded receipt records what the service confirmed; an uncertain result means completion could not be established.',
  'For an uncertain external send, check the destination service before preparing another attempt. Do not assume that the absence of a receipt means nothing was delivered.',
 ],note:'SMTP acceptance confirms the mail server accepted the message. It does not prove that the recipient received or read it.',actions:[{view:'approvals',label:'Open review actions'},{view:'notifications',label:'Open notifications'}]},
 {id:'documents',group:'Sources & connections',roles:clients,title:'Import a document into editable line items',summary:'Review the source, mapping and units before creating a draft.',icon:'file',steps:[
  'Open Ingest documents and upload your files. Supported families include EML/MBOX/MSG, XLSX/XLS, CSV/TSV, DOCX, text PDF, TXT, HTML and JSON. Automatic selection chooses an available matching engine.',
  'Review the parsed text and table rows. Check column mapping, item descriptions, quantities, units and prices. Use AI extraction when a supported live provider is available.',
  'Edit the extracted lines and inspect their source citations. Explicitly confirm uncited assumptions before import; changing their values requires fresh confirmation. Missing-detail questions can open a grounded agent discussion. A contractor creates a private request draft; a supplier matches a received request before creating a private quote.',
  'Reconcile currency and units explicitly before a supplier import. The application does not silently convert exchange rates or units for you.',
 ],note:'Image-only PDFs are not supported by the current text parser; use a file with selectable text. Check visible parser warnings and the available-engine choices.',actions:[{view:'ingestion',label:'Open document ingestion'}]},
 {id:'mail',group:'Sources & connections',roles:clients,title:'Connect email and prepare a reply',summary:'Read IMAP messages and review SMTP delivery inside your workspace.',icon:'mail',steps:[
  'Open Email settings and enter your account’s IMAP and SMTP endpoints, encryption, username and supported credentials. Use your mail provider’s connection details.',
  'Test the connection, then choose Sync email. Optional automatic sync can check for new mail. The initial sync reads a recent message window, not the whole archive.',
  'Open an email to read it, extract an attachment, or ask the agent to draft a reply. Review the recipient, subject, body and attachments.',
  'Choose Review send, then approve the frozen message in Review actions. The email page shows the recorded sending result.',
 ],note:'App passwords or a supplied OAuth access token are supported; provider sign-in and automatic OAuth token refresh are not included. Your credentials belong only to your account.',actions:[{view:'mail',label:'Open email'}]},
 {id:'telegram',group:'Sources & connections',roles:clients,title:'Connect a Telegram bot',summary:'Receive text and documents, then review outbound replies.',icon:'send',steps:[
  'Create a bot through Telegram’s BotFather, then enter its token in Telegram settings. This connects a bot, not your personal Telegram account.',
  'Start a conversation with that bot in Telegram, test the connection and receive messages. Use one polling consumer for the token; an existing webhook can prevent polling.',
  'Open a received document to extract line items, or prepare a reply. Review the text and chat destination before approving the send.',
  'If useful, explicitly enable generic activity reminders and choose a notification chat. Those reminders say new work is waiting; they do not forward private quote details.',
 ],note:'The current integration handles received text/documents and outbound text. Personal chat history, voice, stickers and outbound document sending are not included.',actions:[{view:'telegram',label:'Open Telegram'}]},
 {id:'connections',group:'Sources & connections',roles:all,title:'Connect an MCP server or A2A agent',summary:'Let your agent use a configured external capability.',icon:'puzzle',steps:[
  'Open Agent connections and add the endpoint and credentials for an MCP server or A2A agent that you control or intend to use.',
  'Test or discover the connection, then inspect the tools, resources or remote agent capabilities it exposes.',
  'Ask your agent to use a specific capability for your task. It can bring returned information into the current account’s work, with recorded tool activity.',
  'Review proposed external operations before execution. A remote agent may ask for more input or require you to continue or cancel a task.',
 ],note:'Connection success depends on the remote service and its protocol support. Received material is source data, not permission to ignore your instructions.',actions:[{view:'connections',label:'Open agent connections'}]},
 {id:'project-messages',group:'Get started',roles:clients,title:'Keep clarification with the project',summary:'Use the request conversation for scope and negotiation context.',icon:'chat',steps:[
  'Open Messages and choose the request. Select the intended participant and explain the specific scope or commercial question.',
  'Ask your agent for a draft when useful. Check names, numbers and the question you want answered before sending.',
  'Return to the thread when revising a quotation or considering an award so that agreed clarifications are not lost in a separate conversation.',
 ],actions:[{view:'messages',label:'Open project messages'}]},
 {"id": "declared-scope", "group": "Quotation workflow", "roles": ["contractor", "supplier"], "title": "Keep scope, terms and alternatives explicit", "summary": "Separate declared scope from assumptions and make accepted changes traceable.", "icon": "file", "steps": ["In Requests, inspect the measurement basis, named interface owners, deliverables and exclusions. A new publication needs these declarations; older missing information stays visibly unknown.", "In a quotation, name assumptions, exclusions and schedule milestones. Mark timing as binding or indicative. Identify alternatives and additional lines against the source scope rather than presenting them as identical coverage.", "Use the term library and explicit conflict decisions for conflicting commercial terms. Review the complete public offer; private costs and negotiation limits stay in your party workspace.", "A contractor can publish a reusable structured FAQ from a reviewed answer. Reuse is exact-version lookup; adapting an older answer creates separate private work for review."], "actions": [{"view": "rfqs", "label": "Inspect requests"}, {"view": "quotes", "label": "Inspect quotations"}]},
 {"id": "response-tracking", "group": "Quotation workflow", "roles": ["contractor", "supplier"], "title": "Follow responses, promises and reminders", "summary": "See which current scope has a response and what still needs attention.", "icon": "clock", "steps": ["Open Responses and choose a request. Review current-scope response coverage; stale offers do not count. Supplier views include only their own work.", "A supplier can review a response promise before sending it. A contractor can prepare a targeted reminder for the selected participant; sending still needs human review.", "Read receipts describe recorded opens, with a disclosed deduplication window. They do not prove understanding or contractual acceptance.", "Use source-linked weekly reports and printable request, quotation, order or change views for handoffs. Reports retain their historical cutoff."], "actions": [{"view": "responses", "label": "Open responses"}]},
 {"id": "business-measures", "group": "Quotation workflow", "roles": ["contractor", "supplier"], "title": "Compare recorded business measures", "summary": "Inspect observed response cycles and completeness against a dated baseline.", "icon": "grid", "steps": ["In Responses, select Business measures. Choose equal-length current and earlier baseline windows, optionally narrowed to an accessible request. Demo records are excluded unless selected.", "Read each definition and denominator. Response cycles use locally recorded facts; unanswered requests and missing commercial fields remain visible. Human rewrite measures require an actual paired agent draft and human edit.", "Open ledger sources or export the measures with their scope. Missing history, comparison records or quality labels stays unmeasured. An earlier window is an observed baseline, not proof the agent saved time or caused a better result."], "actions": [{"view": "responses", "label": "Open business measures", "context": {"tab": "metrics"}}]},
 {"id": "batch-quotes", "group": "Quotation workflow", "roles": ["supplier"], "title": "Prepare several quotes for separate review", "summary": "Keep successful preparations and per-item outcomes when some quotes need attention.", "icon": "check", "steps": ["In Quotations, choose Select quotation drafts and select the drafts to prepare. Preparation creates an exact review for each eligible quote; it sends nothing.", "Open each quotation review to inspect its recipient, scope, total, schedule and terms. Correct stale or unavailable drafts, then select only unprepared items again.", "In Review actions, select the intended reviews and expand Review selected action contents. Confirm the selected decisions when ready. Each item keeps its own receipt; a failed item does not resend one that succeeded."], "actions": [{"view": "quotes", "label": "Select quotation drafts"}, {"view": "approvals", "label": "Open review actions"}]},
 {"id": "fulfillment", "group": "Quotation workflow", "roles": ["contractor", "supplier"], "title": "Follow an order through changes and invoices", "summary": "Keep delivery quantities and price changes tied to the agreed source.", "icon": "box", "steps": ["Open Orders after award intent, supplier confirmation, independent approval and signature are complete. Inspect the exact accepted quotation basis and the supplier acknowledgment.", "Prepare changes against the original lines and rates. Review the resulting amount and scope before the relevant people approve the change.", "Record partial delivery acceptance and deficiencies. Match an invoice against the order and accepted quantities; correct a mismatch without erasing its earlier result."], "actions": [{"view": "orders", "label": "Open orders"}]},
 {"id": "artifacts", "group": "Sources & connections", "roles": ["contractor", "supplier"], "title": "Attach versions, export evidence and manage retention", "summary": "Keep private files separate from explicitly delivered business evidence.", "icon": "file", "steps": ["Use Object attachments to add a version to a request, quote or order. Inspect the exact version before explicitly delivering it to the intended party.", "Evidence exports a signed ledger range and proofs. Supply an independently trusted public key when someone verifies it; a valid signature establishes consistency, not the truth of every claim.", "Files & retention previews eligibility and holds. Only reviewed eligible local bytes can be removed. Ledger facts, exports and counterparty copies remain."], "actions": [{"view": "attachments", "label": "Open object attachments"}, {"view": "evidence", "label": "Open evidence"}, {"view": "retention", "label": "Open files & retention"}]},
 {"id": "signed-exchange-mail", "group": "Sources & connections", "roles": ["contractor", "supplier"], "title": "Deliver a signed exchange by email", "summary": "Review an original QEP attachment and track email and signed receipts separately.", "icon": "mail", "steps": ["In Message delivery, choose Prepare email delivery for an outgoing package. Enter the recipient to create a private email draft containing the original signed package and readable summary.", "Inspect the draft and attachments in Email, then review and approve the SMTP send. Mail-server acceptance is separate from a signed recipient receipt.", "For an incoming .qep.json attachment, choose Preview signed exchange. After pairing and signature checks, explicitly import the package. Prepare a receipt or recovery reply when offered; it is another private draft requiring review.", "Inspect held messages, signed receipts and linked delivery reports before preparing a retry. A reported bounce is a mail-service report; it is not a signed QEP response."], "actions": [{"view": "exchange", "label": "Open message delivery"}, {"view": "mail", "label": "Open email"}]},
 {"id": "demo-sandbox", "group": "Get started", "roles": ["contractor", "supplier"], "title": "Try a quotation scenario in the sandbox", "summary": "Explore the workflow in an isolated demonstration runtime.", "icon": "layers", "steps": ["Open Demo sandbox and create the offered quotation scenario. Its records and fixture participants are separate from live party work.", "Follow the scenario’s controls to inspect requests, quotes and results. Demonstration outcomes are labelled and do not prove live model quality.", "Dispose the sandbox when finished. Its runtime effects are removed without deleting your real account’s business records."], "actions": [{"view": "sandbox", "label": "Open demo sandbox"}]},
 {"id": "operations", "group": "Administration", "roles": ["admin"], "title": "Inspect application operations", "summary": "Read scoped workload and plugin metadata without opening other parties’ private records.", "icon": "clock", "steps": ["Open Operations & timeline for current plugin, workload and provider counts. Read the stated source and account coverage.", "Download the metadata snapshot or configure its periodic output. The event timeline remains your own account’s metadata; administration does not turn it into every party’s business ledger."], "actions": [{"view": "operations", "label": "Open operations"}]},
 {id:'memory',group:'Work with AI',roles:all,title:'Inspect and change account memory',summary:'Keep useful preferences explicit and editable.',icon:'file',steps:[
  'Open Account memory in Agent workroom to inspect the preferences currently available to your agent.',
  'Add or edit a specific preference, such as a preferred comparison format. Include enough context for it to be useful later.',
  'Review model-suggested memories before accepting them. Archive a memory when it is outdated or no longer appropriate.',
 ],note:'Email bodies, remote tool output and quotation notes are source material. They should not silently become a permanent instruction.',actions:[{view:'workroom',label:'Open account memory',context:{tab:'memory'}}]},
 {id:'personal-tools',group:'Personalize',roles:all,title:'Build a personal plugin or saved skill',summary:'Ask for a useful capability and inspect it before sharing.',icon:'puzzle',steps:[
  'Open Plugin studio or ask your agent for a specific tool. Describe the input, expected result and how you want to use it.',
  'Inspect the generated extension or skill. Try it in your own workspace, adjust its configuration and disable it when it is not useful.',
  'Share a useful extension in the marketplace when ready. Other accounts can install it; administrators can review shared work for a global default.',
 ],note:'Personal extensions can customize the supported plugin surface. They do not grant access to another account’s private quotation data.',actions:[{view:'extensions',label:'Open Plugin studio'}]},
 {id:'workspace-style',group:'Personalize',roles:all,title:'Change layout, colors and spacing',summary:'Make the workspace fit the way you work.',icon:'sun',steps:[
  'Open Workspace style and choose Focus, Balanced or Classic. Focus starts with your agent and opens the assistant on demand elsewhere; Balanced keeps it beside detailed work on wide screens; Classic starts with records or administration.',
  'Choose a light color palette and comfortable or compact spacing, then save your workspace style.',
  'The choice stays with your account across reloads. An active generated theme supplies its own colors until you disable it in Plugin studio.',
 ],actions:[{view:'workspace-style',label:'Choose workspace style'}]},
 {id:'settings-help',group:'Personalize',roles:all,title:'Find account and plugin settings',summary:'Change the right scope without mixing personal and shared preferences.',icon:'settings',steps:[
  'Account settings contains your profile and account controls. Plugin settings groups configuration contributed by enabled plugins; preview YAML changes, export non-secret overrides or initialize an unconfigured scope there.',
  'Choose the specific plugin and edit the fields you intend to change. Password fields can stay blank to keep the saved secret; use the explicit clear control to remove it.',
  'Check the scope description before saving. Connection credentials and workspace styles belong to your account; administrators also have separate shared defaults where supported.',
 ],actions:[{view:'settings',label:'Open account settings'},{view:'plugin-settings',label:'Open plugin settings'}]},
]
export const forRole=role=>topics.filter(topic=>topic.roles.includes(role)).map(({roles,...topic})=>structuredClone(topic))
