/** GUI-only writes. SMTP/IMAP/Telegram are fictitious loopback protocol services. */
import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {mkdirSync,readFileSync,writeFileSync} from 'node:fs'
import {resolve,join} from 'node:path'
const require=createRequire(new URL('../../../../host/package.json',import.meta.url)),{chromium}=require('playwright'),yaml=require('yaml'),base=process.env.BASE_URL||'http://127.0.0.1:8650/quotagent/',out=resolve(process.env.EVIDENCE_DIR||'tmp/agent-experience/g9-browser'),fixture=JSON.parse(readFileSync(process.env.FIXTURE_FILE||'tmp/agent-experience/g9-fixture/connection.json','utf8'));mkdirSync(out,{recursive:true})
const browser=await chromium.launch({headless:true,executablePath:'/opt/hermes/.playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox']}),page=await browser.newPage({viewport:{width:1440,height:1100}}),report={base,at:new Date().toISOString(),evidence:'Synthetic notification history and loopback-only IMAP/SMTP; no external deliveries.',checks:[],screenshots:[],errors:[]};page.on('pageerror',error=>report.errors.push(error.message))
const shot=async name=>{await page.screenshot({path:join(out,name),fullPage:true});report.screenshots.push(name)},receipt=async()=>await(await fetch(fixture.statusUrl)).json(),read=async path=>await(await page.request.get(new URL('api'+path,base).href)).json()
const nav=async label=>{if(await page.getByRole('button',{name:'Not now',exact:true}).isVisible()&&await page.getByRole('button',{name:'Not now',exact:true}).isEnabled()){await page.getByRole('button',{name:'Not now',exact:true}).click();await page.getByRole('button',{name:'Not now',exact:true}).waitFor({state:'hidden'})}const sidebar=page.locator('.sidebar'),item=sidebar.getByRole('button',{name:label,exact:true});for(const group of ['Quotation work','Sources & connections','Personalize','Administration'])if(!await item.isVisible()&&await sidebar.getByRole('button',{name:group,exact:true}).isVisible())await sidebar.getByRole('button',{name:group,exact:true}).click();await item.click()}
const openFiles=async()=>{await nav('Plugin settings');await page.getByRole('button',{name:'Import or export YAML',exact:true}).click()}
const upload=async(value,filename)=>{const file=join(out,filename);writeFileSync(file,yaml.stringify(value));await page.getByLabel('YAML configuration file',{exact:true}).setInputFiles(file);await page.getByRole('button',{name:'Preview YAML changes',exact:true}).click()}
try{
 await page.goto(base);await page.getByLabel('Email address',{exact:true}).fill('contractor@demo.local');await page.getByLabel('Password',{exact:true}).fill('demo1234');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.locator('.sidebar').waitFor();if(await page.getByRole('button',{name:'Not now',exact:true}).isVisible())await page.getByRole('button',{name:'Not now',exact:true}).click()
 await openFiles();const before=await receipt(),mailBefore=await read('/mail');await upload({format:'quotagent/settings/v1',settings:[{id:'mail',scope:'account',values:fixture.mailSettings},{id:'mail-digest',scope:'account',values:{enabled:true,automatic:false,recipient:'digest@fixture.invalid',maxItems:2,intervalMinutes:1,workspaceUrl:'https://quotagent.fixture.invalid/'}}]},'connection-and-digest.yaml');await page.getByRole('button',{name:'Apply reviewed configuration',exact:true}).waitFor();assert.equal((await read('/mail')).status.enabled,mailBefore.status.enabled);assert.equal((await receipt()).smtpSent,before.smtpSent);assert.ok(!(await page.locator('.settings-diff').innerText()).includes('fixture-password'));await shot('01-yaml-preview.png');await page.getByRole('button',{name:'Apply reviewed configuration',exact:true}).click();await page.getByText(/Reviewed configuration applied.|Existing configuration preserved./).waitFor();assert.equal((await read('/mail')).status.enabled,true);report.checks.push('GUI imports a two-schema native YAML file; zero-write masked preview precedes explicit apply, including account-only connection credentials')
 const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Export my overrides',exact:true}).click();const download=await downloadEvent;await download.saveAs(join(out,'exported-overrides.yaml'));const exported=readFileSync(join(out,'exported-overrides.yaml'),'utf8');assert.ok(!exported.includes('fixture-password'));assert.ok(exported.includes('redactedSecrets'));await page.getByLabel('Import behavior',{exact:true}).selectOption('merge');await upload({format:'quotagent/settings/v1',settings:[{id:'mail-digest',values:{enabled:true,recipient:'not-an-address'}}]},'invalid-digest.yaml');await page.getByText('Set a complete digest recipient before enabling digests.',{exact:true}).waitFor();assert.equal((await read('/mail-digest')).recipient,'digest@fixture.invalid');await shot('02-plugin-veto-keeps-configuration.png');report.checks.push('GUI export omits passwords; plugin preflight rejects an invalid recipient and preserves the working configuration')
 await nav('Email');await page.getByRole('button',{name:'Test connection',exact:true}).click();await page.locator('.mail-test-result').getByText(/Connected and authenticated/).first().waitFor();await page.getByRole('button',{name:'Sync email',exact:true}).click();await page.locator('.mail-list-item').filter({hasText:'Riverside cabling offer'}).first().waitFor();assert.equal((await receipt()).smtpSent,before.smtpSent);await page.getByRole('button',{name:'Preview activity digest',exact:true}).click();let dialog=page.getByRole('dialog',{name:'Review activity digest',exact:true});await dialog.getByRole('button',{name:'Send reviewed digest',exact:true}).waitFor();assert.match(await dialog.innerText(),/digest@fixture.invalid/);assert.ok(!(await dialog.innerText()).includes('Riverside cabling offer'));await shot('03-digest-exact-human-review.png');await dialog.getByRole('button',{name:'Send reviewed digest',exact:true}).click();await page.getByText('SMTP accepted the activity digest.',{exact:true}).waitFor();const after=await receipt();assert.equal(after.smtpSent,before.smtpSent+1);assert.match(after.smtpMessages.at(-1).source,/2 unread activity/);assert.ok(!after.smtpMessages.at(-1).source.includes('Pagination fixture'));await page.getByText('Digest delivery history',{exact:true}).click();await shot('04-local-smtp-receipt.png');report.checks.push('GUI tests real IMAP/SMTP without delivery, receives a MIME email, then explicit digest confirmation sends exactly one capped summary with a durable receipt')
 await nav('Notifications');const all=await read('/notifications');assert.ok(all.total>25);await page.getByRole('button',{name:'Next page',exact:true}).click();await page.getByText('Page 2 of '+all.pages,{exact:true}).waitFor();await shot('05-notification-second-page.png');await page.getByLabel('Activity source',{exact:true}).selectOption('fixture-two');await page.locator('.notification-card').getByRole('heading',{name:'Paired source fixture',exact:true}).waitFor();await page.getByText('2 reports · 2 sources',{exact:true}).click();assert.match(await page.locator('.notification-card').innerText(),/fixture-one/);assert.match(await page.locator('.notification-card').innerText(),/fixture-two/);await shot('06-cross-source-provenance.png');await page.getByLabel('Activity source',{exact:true}).selectOption('pagination-fixture');await page.getByRole('button',{name:'Mark matching read',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('.notification-card.unread'));assert.equal((await read('/notifications?source=pagination-fixture&unread=true')).matched,0);report.checks.push('GUI pages beyond the first25 items, displays both merged producers, and marks all61 filtered notices read across pages')
 await page.getByRole('button',{name:'Notification preferences',exact:true}).click();dialog=page.getByRole('dialog',{name:'Notifications settings',exact:true});await dialog.getByLabel('Muted alert source IDs',{exact:true}).fill('fixture-one,fixture-two,mail');await dialog.getByRole('button',{name:'Preview changes',exact:true}).click();await dialog.locator('.settings-diff').getByText('Muted alert source IDs',{exact:true}).waitFor();await dialog.getByRole('button',{name:'Save settings',exact:true}).click();await dialog.getByText('Settings saved.',{exact:true}).waitFor();await dialog.getByRole('button',{name:'Close',exact:true}).click();await page.reload();await page.locator('.sidebar').waitFor();await nav('Notifications');const muted=await read('/notifications');assert.ok(muted.unreadTotal>0);assert.equal(muted.unread,0);await page.getByRole('button',{name:'Notification preferences',exact:true}).click();dialog=page.getByRole('dialog',{name:'Notifications settings',exact:true});assert.equal(await dialog.getByLabel('Muted alert source IDs',{exact:true}).inputValue(),'fixture-one,fixture-two,mail');await dialog.getByLabel('Muted alert source IDs',{exact:true}).fill('unsaved-preserved-edit');await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await page.waitForTimeout(1200);assert.equal(await dialog.getByLabel('Muted alert source IDs',{exact:true}).inputValue(),'unsaved-preserved-edit');await dialog.getByRole('button',{name:'Close',exact:true}).click();await shot('07-persisted-alert-preferences.png');report.checks.push('Account mute preferences persist across browser reload and suppress header alerts without deleting unread history; unsaved form text remains intact')
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(250);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await shot('08-mobile-notification-window.png');assert.deepEqual(report.errors,[]);report.checks.push('Notification filters/windows fit390px with no JavaScript errors');report.ok=true
}catch(error){report.error=error.stack;await shot('failure.png');process.exitCode=1}finally{writeFileSync(join(out,'report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));await browser.close()}
