/** Fresh-account public GUI proof; inline loopback IMAP/SMTP never forwards. */
import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {mkdirSync,readFileSync,writeFileSync} from 'node:fs'
import {resolve,join} from 'node:path'
import {localServices} from '../../mail/tests/product-fixtures.mjs'
import {createProtocolAccount} from '../../exchange-workbench/tests/gui-account.mjs'
const require=createRequire(new URL('../../../../host/package.json',import.meta.url)),{chromium,expect}=require('playwright/test'),yaml=require('yaml')
const base=process.env.BASE_URL||'http://127.0.0.1:8650/quotagent/',out=resolve(process.env.EVIDENCE_DIR||'tmp/product-evidence/settings-public');mkdirSync(out,{recursive:true})
const services=await localServices({mailboxMessages:[]}),browser=await chromium.launch({headless:true,executablePath:'/opt/hermes/.playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell'}),page=await browser.newPage({viewport:{width:1440,height:1100}}),report={at:new Date().toISOString(),base,checks:[],screenshots:[],errors:[],scope:'New GUI-created fixture account; real loopback IMAP/SMTP only, no Telegram call or synthetic application-ledger seeding. Multi-producer merging remains covered by native/local evidence.'},sentinel='PRIVATE_NOTIFICATION_DETAIL_72941'
page.setDefaultTimeout(20000);page.on('pageerror',error=>report.errors.push(error.message))
const mailSettings={enabled:true,fromName:'[Local settings fixture]',fromAddress:'buyer@fixture.invalid',imapHost:'127.0.0.1',imapPort:services.imapPort,imapSecurity:'plain',imapUser:'fixture',imapPassword:'fixture-password',smtpHost:'127.0.0.1',smtpPort:services.smtpPort,smtpSecurity:'plain',smtpUser:'fixture',smtpPassword:'fixture-password',sentMailbox:'',autoSync:false}
const shot=async name=>{await page.screenshot({path:join(out,name+'.png'),fullPage:true});report.screenshots.push(name+'.png')},read=async path=>{const response=await page.request.get(new URL('api'+path,base).href),value=await response.json();assert.equal(response.status(),200,JSON.stringify(value));return value}
async function post(path,trigger){const pending=page.waitForResponse(response=>response.url().endsWith('/api'+path)&&response.request().method()==='POST');await trigger();const response=await pending,value=await response.json();assert.equal(response.status(),200,JSON.stringify(value));return value}
async function nav(label){const navigation=page.getByRole('navigation',{name:'Main navigation'}),button=navigation.getByRole('button',{name:label,exact:true});await navigation.getByRole('button',{name:label,exact:true,includeHidden:true}).waitFor({state:'attached'});if(!await button.isVisible())await navigation.locator('.ws-nav-group').filter({has:page.getByRole('button',{name:label,exact:true,includeHidden:true})}).locator('.ws-group-toggle').click();await button.click()}
async function upload(value,filename){const file=join(out,filename);writeFileSync(file,yaml.stringify(value));await page.getByLabel('YAML configuration file',{exact:true}).setInputFiles(file);await page.getByRole('button',{name:'Preview YAML changes',exact:true}).click()}
const envelope=index=>Buffer.from(`From: Local supplier fixture <supplier@fixture.invalid>\r\nTo: buyer@fixture.invalid\r\nSubject: [Local settings fixture] Activity ${index}\r\nMessage-ID: <settings-activity-${index}@fixture.invalid>\r\nMIME-Version: 1.0\r\nContent-Type: text/plain; charset=utf-8\r\n\r\n${sentinel} ${index}. Fictitious protocol message, no order.\r\n`)
try{
 const user=await createProtocolAccount(page,base,{prefix:'settings',role:'contractor'});report.account={id:user.id,email:user.email};await nav('Plugin settings');await page.getByRole('button',{name:'Import or export YAML',exact:true}).click();assert.equal((await read('/mail')).status.enabled,false)
 const bundle={format:'quotagent/settings/v1',settings:[{id:'mail',scope:'account',values:mailSettings},{id:'mail-digest',scope:'account',values:{enabled:true,automatic:false,recipient:'digest@fixture.invalid',maxItems:2,intervalMinutes:1,workspaceUrl:'https://quotagent.fixture.invalid/'}}]}
 await upload(bundle,'connection-and-digest.yaml');await page.getByRole('button',{name:'Apply reviewed configuration',exact:true}).waitFor();assert.equal((await read('/mail')).status.enabled,false);assert.equal(services.smtpMessages.length,0);assert(!await page.locator('.settings-diff').innerText().then(text=>text.includes('fixture-password')));await shot('01-masked-yaml-preview');await page.getByRole('button',{name:'Apply reviewed configuration',exact:true}).click();await page.getByText('Reviewed configuration applied.',{exact:true}).waitFor();assert.equal((await read('/mail')).status.enabled,true);assert.equal((await read('/mail-digest')).automatic,false)
 const view=await read('/settings/mail');assert.equal(view.provenance.imapHost.source,'file');assert.equal(view.provenance.imapHost.reference,'connection-and-digest.yaml');report.checks.push('Fresh account imports two native schemas through zero-write masked YAML preview and explicit apply; effective provenance names the actual file and digest automatic permission stays off')
 const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'Export my overrides',exact:true}).click();await(await downloading).saveAs(join(out,'exported-overrides.yaml'));const exported=readFileSync(join(out,'exported-overrides.yaml'),'utf8');assert(!exported.includes('fixture-password'));assert(exported.includes('redactedSecrets'))
 await upload({format:'quotagent/settings/v1',settings:[{id:'mail-digest',scope:'account',values:{recipient:'not-replaced@fixture.invalid'}}]},'initialize-existing.yaml');await page.getByText('Already configured. Initialization preserves these values.',{exact:true}).waitFor();await page.getByRole('button',{name:'Apply reviewed configuration',exact:true}).click();await page.getByText('Existing configuration preserved.',{exact:true}).waitFor();assert.equal((await read('/mail-digest')).recipient,'digest@fixture.invalid');await page.getByLabel('Import behavior',{exact:true}).selectOption('merge');await upload({format:'quotagent/settings/v1',settings:[{id:'mail-digest',values:{enabled:true,recipient:'not-an-address'}}]},'invalid-digest.yaml');await page.getByText('Set a complete digest recipient before enabling digests.',{exact:true}).waitFor();assert.equal((await read('/mail-digest')).recipient,'digest@fixture.invalid');assert.equal(services.smtpMessages.length,0);await shot('02-initialize-and-plugin-veto');report.checks.push('Export redacts secrets; initialize-only import preserves existing account overrides, and a plugin preflight veto keeps the valid digest recipient without sending')
 await nav('Email');await post('/mail/test',()=>page.getByRole('button',{name:'Test connection',exact:true}).click());await page.locator('.mail-test-result').getByText(/Connected and authenticated/).first().waitFor();assert.equal(services.smtpMessages.length,0)
 for(let index=1;index<=27;index++){services.appendMail(envelope(index));const result=await post('/mail/sync',()=>page.getByRole('button',{name:'Sync email',exact:true}).click());assert.equal(result.imported,1)}
 const beforeDuplicate=await read('/notifications'),duplicate=await post('/mail/sync',()=>page.getByRole('button',{name:'Sync email',exact:true}).click());assert.equal(duplicate.imported,0);assert.equal((await read('/notifications')).total,beforeDuplicate.total);assert.equal(beforeDuplicate.total,27);assert.equal(services.smtpMessages.length,0);report.checks.push('27 separate visible IMAP syncs import actual fictitious MIME messages and produce 27 durable notifications; a no-new-mail sync adds none, and connection/sync never send SMTP')
 await page.getByRole('button',{name:'Compose email',exact:true}).click();let dialog=page.getByRole('dialog',{name:'Compose email',exact:true});await dialog.getByLabel('Email recipients',{exact:true}).fill('review-only@fixture.invalid');await dialog.getByLabel('Email subject',{exact:true}).fill('[Local settings fixture] Private review only');await dialog.getByLabel('Email message',{exact:true}).fill(sentinel);await dialog.getByRole('button',{name:'Review send',exact:true}).click();await page.getByRole('button',{name:'Approve & execute',exact:true}).waitFor();assert.equal(services.smtpMessages.length,0);report.checks.push('Private mail send review produces a second real notification source without executing or sending that email')
 await nav('Email');await page.getByRole('button',{name:'Preview activity digest',exact:true}).click();dialog=page.getByRole('dialog',{name:'Review activity digest',exact:true});await expect(dialog.getByRole('button',{name:'Send reviewed digest',exact:true})).toBeEnabled();assert.match(await dialog.innerText(),/digest@fixture.invalid/);assert(!await dialog.innerText().then(text=>text.includes(sentinel)||text.includes('Activity 27')));const preview=await read('/mail-digest');assert.equal(preview.count,2);assert.equal(preview.remaining,26);await shot('03-bounded-digest-review');await post('/mail-digest/send',()=>dialog.getByRole('button',{name:'Send reviewed digest',exact:true}).click());await page.getByText('SMTP accepted the activity digest.',{exact:true}).waitFor();assert.equal(services.smtpMessages.length,1);const mime=services.smtpMessages[0].source.toString();assert.match(mime,/2 unread activity/);assert(!mime.includes(sentinel));assert(!mime.includes('[Local settings fixture] Activity'));const sent=await read('/mail-digest');assert.equal(sent.history[0].status,'sent');assert.equal(sent.history[0].itemCount,2);assert.equal(sent.count,2);assert.equal(sent.eligible,26);assert.match(sent.blocked,/interval/);await page.getByText('Digest delivery history',{exact:true}).click();await shot('04-smtp-receipt-and-throttle');report.checks.push('Exact GUI digest review sends one capped two-item count summary over SMTP, excludes source/private detail, records its receipt and blocks immediate repeat while preserving 26 eligible items')
 await nav('Notifications');const all=await read('/notifications');assert.equal(all.total,28);await page.getByRole('button',{name:'Next page',exact:true}).click();await page.getByText('Page 2 of 2',{exact:true}).waitFor();await shot('05-real-activity-second-page');await page.getByLabel('Activity source',{exact:true}).selectOption('approvals');const reviewCard=page.locator('.notification-card').filter({hasText:'Ready for your review'});await reviewCard.waitFor();await reviewCard.getByText('1 report · 1 source',{exact:true}).click();assert.match(await reviewCard.innerText(),/approvals.*origin-view/);await shot('06-review-source-attribution');await page.getByLabel('Activity source',{exact:true}).selectOption('mail');await expect(page.locator('.notification-card')).toHaveCount(25);await page.locator('.notification-card').first().getByText('1 report · 1 source',{exact:true}).click();assert.match(await page.locator('.notification-card').first().innerText(),/Email · mail \/ mail/);const marked=await post('/notifications/read-all',()=>page.getByRole('button',{name:'Mark matching read',exact:true}).click());assert.equal(marked.marked,27);assert.equal((await read('/notifications?source=mail&unread=true')).matched,0);report.checks.push('Server pagination reaches actual activity beyond25; GUI shows explicit mail and origin-view review attribution, then marks all27 matching mail notices read across pages')
 await page.getByLabel('Activity source',{exact:true}).selectOption('');await page.getByRole('button',{name:'Notification preferences',exact:true}).click();dialog=page.getByRole('dialog',{name:'Notifications settings',exact:true});await dialog.getByLabel('Muted alert source IDs',{exact:true}).fill('approvals');await dialog.getByRole('button',{name:'Preview changes',exact:true}).click();await dialog.locator('.settings-diff').getByText('Muted alert source IDs',{exact:true}).waitFor();await dialog.getByRole('button',{name:'Save settings',exact:true}).click();await dialog.getByText('Settings saved.',{exact:true}).waitFor();await dialog.getByRole('button',{name:'Close',exact:true}).click();await page.reload();await nav('Notifications');const muted=await read('/notifications');assert.equal(muted.unreadTotal,1);assert.equal(muted.unread,0);assert.equal(muted.total,28);await page.getByRole('button',{name:'Notification preferences',exact:true}).click();dialog=page.getByRole('dialog',{name:'Notifications settings',exact:true});await expect(dialog.getByLabel('Muted alert source IDs',{exact:true})).toHaveValue('approvals');await dialog.getByLabel('Muted alert source IDs',{exact:true}).fill('unsaved-private-edit');await page.waitForTimeout(10000);await expect(dialog.getByLabel('Muted alert source IDs',{exact:true})).toHaveValue('unsaved-private-edit');await dialog.getByRole('button',{name:'Close',exact:true}).click();await shot('07-persisted-mute-preserved-history');report.checks.push('Account mute survives reload and suppresses alerts while retaining unread history; unsaved preferences remain intact during a 10-second open-form check')
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await shot('08-mobile-notification-window');assert.deepEqual(report.errors,[]);assert.equal(services.smtpMessages.length,1);report.checks.push('390px notification controls fit without horizontal overflow or JavaScript errors; fixture records exactly one explicitly reviewed digest delivery');report.ok=true
}catch(error){report.error=error.stack;process.exitCode=1;await shot('failure').catch(()=>{});writeFileSync(join(out,'failure.txt'),await page.locator('body').innerText().catch(()=>''))}finally{report.smtpSends=services.smtpMessages.length;report.telegramSends=services.telegramSent.length;writeFileSync(join(out,'fixture-receipts.json'),JSON.stringify({smtp:services.smtpMessages.map(message=>({envelope:message.envelope,source:message.source.toString()})),protocolRequests:services.requests},null,2));writeFileSync(join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();await services.close()}
