import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {mkdirSync,mkdtempSync,readFileSync,readdirSync,statSync,writeFileSync} from 'node:fs'
import {resolve,join} from 'node:path'
import * as store from '../../workspace-store/code/index.mjs'
import * as settings from '../code/index.mjs'
const require=createRequire(new URL('../../../../host/package.json',import.meta.url)),{Context}=require('cordis'),ctx=new Context(),fibers=[],routes=[],users=[{id:'settings-owner',role:'contractor'},{id:'settings-other',role:'supplier'},{id:'settings-admin',role:'admin'}],[user,other,admin]=users
mkdirSync('tmp',{recursive:true});const root=mkdtempSync(resolve('tmp/settings-transactions-')),checks=[];let liveMode='normal'
const mount=async(module,config)=>{const fiber=await ctx.plugin(module,config);assert.equal(fiber.state,2);fibers.push(fiber);return fiber}
try{
 await mount({name:'settings-transaction-fixture',apply(child){child.provide('accounts',{get:id=>users.find(row=>row.id===id),list:()=>users,can:()=>true});child.provide('web',{route:(...args)=>{routes.push(args);return()=>routes.splice(routes.indexOf(args),1)},contribute:()=>()=>{}})}})
 const storeFiber=await mount(store,{root:join(root,'data')}),settingsFiber=await mount(settings)
 const register=()=>{ctx.settings.define({id:'connection',name:'Fixture connection',scope:'account',defaults:{host:'local',password:''},fields:[{key:'host',label:'Host',type:'text'},{key:'password',label:'Password',type:'password'}]});ctx.settings.define({id:'process',name:'Fixture process',scope:'user',scopes:['workspace','project','section'],defaults:{currency:'USD',mode:'normal',limit:3},fields:[{key:'currency',label:'Currency',type:'select',options:['USD','EUR','GBP']},{key:'mode',label:'Mode',type:'text'},{key:'limit',label:'Limit',type:'number',min:1,max:10}],preflight:next=>next.limit===9?{allowed:false,reason:'Fixture plugin veto'}:true,onChange:next=>{liveMode=next.mode;if(next.mode==='failure')throw new Error('Controlled apply failure')},rollback:previous=>{liveMode=previous.mode}});for(const scope of ['workspace','project','section'])ctx.settings.registerScope({id:scope,label:scope,list:who=>who.id===user.id?[{id:scope+'-one',label:scope+' one',context:{workspaceId:'workspace-one',...(scope!=='workspace'?{projectId:'project-one'}:{}),...(scope==='section'?{sectionId:'section-one'}:{})}}]:[],resolve:(who,context,{write})=>{if(who.id!==user.id||context.workspaceId!=='workspace-one'||scope!=='workspace'&&context.projectId!=='project-one'||scope==='section'&&context.sectionId!=='section-one')throw Object.assign(new Error('Forbidden fixture scope'),{status:403});return{realmId:user.id,key:context[scope+'Id'],label:scope+' one'}}})}
 register();await ctx.settings.save(admin,'process',{values:{currency:'EUR'}});await ctx.settings.save(user,'connection',{values:{password:'SECRET_SENTINEL_DO_NOT_EXPORT'}});assert.equal(ctx.settings.get(other,'connection').password,'');assert.equal(ctx.settings.view(user,'connection').values.password,'');assert.ok(ctx.settings.view(user,'connection').configuredSecrets.includes('password'))
 const exportValue=ctx.settings.exportYaml(user),template=ctx.settings.exportYaml(user,{template:true});assert.ok(!exportValue.content.includes('SECRET_SENTINEL'));assert.ok(!template.content.includes('SECRET_SENTINEL'));assert.equal(statSync(join(root,'data/settings/credentials.json')).mode&0o777,0o600);checks.push('Account credentials remain private and write-only in schemas, export and template; private file mode0600')
 const context={workspaceId:'workspace-one',projectId:'project-one',sectionId:'section-one'};await ctx.settings.save(user,'process',{scope:'workspace',context,values:{limit:4}});await ctx.settings.save(user,'process',{scope:'project',context,values:{currency:'GBP'}});await ctx.settings.save(user,'process',{scope:'section',context,values:{limit:5}});assert.equal(ctx.settings.get(user,'process',context).currency,'GBP');assert.equal(ctx.settings.get(user,'process',context).limit,5);assert.equal(ctx.settings.get(user,'process').currency,'EUR');assert.equal(ctx.settings.view(user,'process',context).provenance.limit.layer,'section');assert.equal(ctx.settings.view(user,'process',context).provenance.limit.shadowed.length,2);assert.throws(()=>ctx.settings.get(other,'process',context),/Forbidden/);await assert.rejects(ctx.settings.save(user,'connection',{scope:'project',context,values:{password:'no'}}),/support/);checks.push('Authorized workspace→project→section inheritance retains per-key shadow provenance; other accounts and scoped credentials refuse')
 const change={changes:[{id:'process',values:{limit:6}}]},before=ctx.store.events(user.id).length,credentialBefore=readFileSync(join(root,'data/settings/credentials.json'),'utf8'),preview=await ctx.settings.preview(user,change);assert.equal(ctx.store.events(user.id).length,before);assert.equal(readFileSync(join(root,'data/settings/credentials.json'),'utf8'),credentialBefore);assert.equal(preview.changedFields,1);await ctx.settings.apply(user,{...change,previewId:preview.previewId});assert.equal(ctx.settings.get(user,'process').limit,6);checks.push('Dry run is zero-write and reviewed digest applies the exact staged changes')
 const stale=await ctx.settings.preview(user,{changes:[{id:'process',values:{limit:7}}]});await ctx.settings.save(user,'process',{values:{limit:8}});await assert.rejects(ctx.settings.apply(user,{changes:[{id:'process',values:{limit:7}}],previewId:stale.previewId}),/changed after preview/);await assert.rejects(ctx.settings.save(user,'process',{values:{limit:9}}),/plugin veto/);assert.equal(ctx.settings.get(user,'process').limit,8);const off=ctx.settings.beforeUpdate('process',()=>false);await assert.rejects(ctx.settings.save(user,'process',{values:{limit:7}}),/rejected/);off();checks.push('Concurrent edits invalidate preview; schema preflight and disposable registered veto prevent activation')
 await assert.rejects(ctx.settings.apply(user,{changes:[{id:'connection',values:{host:'changed',password:'NEW_SECRET_SENTINEL'}},{id:'process',values:{mode:'failure'}}]}),/previous values restored/);assert.equal(ctx.settings.get(user,'connection').host,'local');assert.equal(ctx.settings.get(user,'connection').password,'SECRET_SENTINEL_DO_NOT_EXPORT');assert.equal(liveMode,'normal');assert.equal(ctx.settings.get(user,'process').mode,'normal');assert.ok(ctx.settings.history(user).some(row=>row.type==='settings/transaction-refused'&&row.rolledBack));assert.ok(!JSON.stringify(ctx.store.events(user.id)).includes('SECRET_SENTINEL'));checks.push('Failed multi-schema apply restores values, credentials and plugin runtime with explicit compensation receipt')
 const yaml='format: quotagent/settings/v1\nsettings:\n  - id: process\n    values:\n      currency: USD\n      limit: 2\n';const imported=await ctx.settings.importPreview(user,{yaml,filename:'fixture.yaml'});await ctx.settings.importApply(user,{yaml,filename:'fixture.yaml',previewId:imported.previewId});assert.equal(ctx.settings.get(user,'process').limit,2);assert.equal(ctx.settings.view(user,'process').provenance.limit.source,'file');assert.equal(ctx.settings.view(user,'process').provenance.limit.reference,'fixture.yaml');await ctx.settings.importApply(user,{yaml:yaml.replace('limit: 2','limit: 3'),mode:'initialize'});assert.equal(ctx.settings.get(user,'process').limit,2);await assert.rejects(ctx.settings.importPreview(user,{yaml:'format: quotagent/settings/v1\nsettings: &x [*x]'}),/alias|mapping|schema|YAML/i);checks.push('Native YAML import validates structure, exposes file provenance and initialize-only preserves existing overrides')
 const exported=ctx.settings.exportYaml(user,{id:'process'});await ctx.settings.save(user,'process',{reset:true});await ctx.settings.importApply(user,{yaml:exported.content,filename:exported.filename});assert.equal(ctx.settings.get(user,'process').limit,2);checks.push('Export/import round-trip restores explicit values without freezing shared inherited defaults')
 const journalDir=join(root,'data/settings/transactions'),oldRecord=ctx.store.get(user.id,'plugin-settings','process');writeFileSync(join(journalDir,'interrupted.json'),JSON.stringify({id:'interrupted',actorId:user.id,status:'prepared',plans:[{id:'process',target:{realmId:user.id,recordId:'process',scope:'account'},beforeRecord:oldRecord,oldSecrets:{}}]}),{mode:0o600});await ctx.store.put(user.id,'plugin-settings',{...oldRecord,values:{limit:10,currency:'USD',mode:'wrong'}},{event:'fixture/interrupted-config'});await settingsFiber.dispose();await mount(settings);register();assert.equal(ctx.settings.get(user,'process').limit,2);assert.equal(readdirSync(journalDir).length,0);assert.ok(ctx.settings.history(user).some(row=>row.type==='settings/transaction-recovered'));checks.push('Restart rolls back an interrupted private journal before schema consumers initialize; no transaction auto-replays')
 const combined={changes:[{id:'process',scope:'workspace',context,values:{limit:7}},{id:'process',scope:'section',context,reset:true}]};const combinedPreview=await ctx.settings.preview(user,combined);assert.ok(combinedPreview.changes[1].fields.some(field=>field.key==='limit'&&field.after===7));await ctx.settings.apply(user,{...combined,previewId:combinedPreview.previewId});assert.equal(ctx.settings.get(user,'process',context).limit,7);checks.push('A bundle previews and applies multiple inherited layers together, including removal of a narrower override')
 const secretOff=ctx.settings.beforeUpdate('connection',next=>{throw new Error('Bad password '+next.password)});await assert.rejects(ctx.settings.save(user,'connection',{values:{password:'LEAK_SENTINEL'}}),error=>error.message.includes('[credential redacted]')&&!error.message.includes('LEAK_SENTINEL'));secretOff();assert.ok(!JSON.stringify(ctx.store.events(user.id)).includes('LEAK_SENTINEL'));checks.push('Plugin refusal messages redact submitted credentials before HTTP errors and durable refusal receipts')
 const initFile=join(root,'initialize.yaml');writeFileSync(initFile,'format: quotagent/settings/v1\nownerId: settings-other\nsettings:\n  - id: process\n    values:\n      limit: 4\n');await settingsFiber.dispose();await ctx.settings.dispose();const current=fibers.at(-1);await current.dispose();await mount(settings,{initFile});register();await ctx.settings.initializeFile();assert.equal(ctx.settings.get(other,'process').limit,4);const initializedCount=ctx.store.events(other.id).filter(event=>event.type==='settings/file-initialized').length;await ctx.settings.initializeFile();assert.equal(ctx.store.events(other.id).filter(event=>event.type==='settings/file-initialized').length,initializedCount);await ctx.settings.save(other,'process',{values:{limit:5}});await ctx.settings.initializeFile();assert.equal(ctx.settings.get(other,'process').limit,5);checks.push('Operator-selected native YAML file initializes a fresh account once and preserves subsequent user edits')
 const report={ok:true,root,checks};writeFileSync(join(root,'report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2))
}finally{for(const fiber of fibers.reverse())await fiber.dispose()}
