import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {mkdirSync,writeFileSync} from 'node:fs'
import {resolve,join} from 'node:path'
const require=createRequire(new URL('../../../../host/package.json',import.meta.url)),{chromium}=require('playwright'),base=process.env.BASE_URL||'http://127.0.0.1:8650/quotagent/',out=resolve(process.env.EVIDENCE_DIR||'tmp/agent-experience/g9-window-browser');mkdirSync(out,{recursive:true})
const browser=await chromium.launch({headless:true,executablePath:'/opt/hermes/.playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox']}),page=await browser.newPage({viewport:{width:1440,height:1000}}),report={base,checks:[],errors:[]};page.on('pageerror',error=>report.errors.push(error.message))
try{await page.goto(base+'#notifications');await page.getByLabel('Email address',{exact:true}).fill('contractor@demo.local');await page.getByLabel('Password',{exact:true}).fill('demo1234');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.getByRole('heading',{name:'Notifications',exact:true}).waitFor();await page.getByRole('button',{name:'Last page',exact:true}).click();await page.getByText('Page 3 of 3',{exact:true}).waitFor();assert.equal(await page.locator('.notification-card').count(),13);await page.screenshot({path:join(out,'09-last-page.png'),fullPage:true});await page.getByRole('button',{name:'First page',exact:true}).click();await page.getByText('Page 1 of 3',{exact:true}).waitFor();report.checks.push('Latest runtime/browser first and last controls reach exact final13 of63 persisted notices after restart')
 await page.getByRole('button',{name:'Notification preferences',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Notifications settings',exact:true});await dialog.getByLabel('Muted alert source IDs',{exact:true}).fill('unsaved-refresh-check');await page.waitForTimeout(12000);assert.equal(await dialog.getByLabel('Muted alert source IDs',{exact:true}).inputValue(),'unsaved-refresh-check');await dialog.getByRole('button',{name:'Close',exact:true}).click();report.checks.push('Pending input survives the configured periodic background refresh without saving it')
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(250);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:join(out,'10-mobile-final-controls.png'),fullPage:true});assert.deepEqual(report.errors,[]);report.ok=true
}catch(error){report.error=error.stack;await page.screenshot({path:join(out,'failure.png'),fullPage:true});process.exitCode=1}finally{writeFileSync(join(out,'report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));await browser.close()}
