import React,{useState} from 'react'
import {registry,useApp,useResource,api,PageHeader,Button,Badge,Icon,Empty,ErrorNotice,Loading,date} from '../../webui/client/core.jsx'
import './notifications.css'
function Notifications(){
 const app=useApp(),resource=useResource('/notifications',{notifications:[],unread:0,enabled:true}),[unreadOnly,setUnreadOnly]=useState(false),[error,setError]=useState('')
 const rows=resource.data.notifications.filter(item=>!unreadOnly||!item.readAt)
 async function read(item,navigate=false){try{await api(`/notifications/${item.id}/read`,{method:'POST',body:{}});resource.reload();app.refresh();if(navigate&&item.link?.view)app.navigate(item.link.view,item.link)}catch(e){setError(e.message)}}
 return <><PageHeader eyebrow="KEEP WORK MOVING" title="Notifications" actions={<Button variant="secondary" disabled={!resource.data.unread} onClick={async()=>{try{await api('/notifications/read-all',{method:'POST',body:{}});resource.reload();app.refresh()}catch(e){setError(e.message)}}}>Mark all read</Button>}>New messages, agent questions and completed actions in your account.</PageHeader><ErrorNotice error={error||resource.error}/><div className="page-toolbar"><div className="filter-tabs"><button className={!unreadOnly?'active':''} onClick={()=>setUnreadOnly(false)}>All activity</button><button className={unreadOnly?'active':''} onClick={()=>setUnreadOnly(true)}>Unread <span>{resource.data.unread}</span></button></div><Button variant="ghost" onClick={()=>app.navigate('plugin-settings')}>Notification preferences</Button></div>{!resource.data.enabled&&<p className="muted">Notification alerts are muted. Your activity history remains available here.</p>}{resource.loading?<Loading/>:rows.length?<div className="notification-list">{rows.map(item=><article className={`card notification-card ${item.readAt?'':'unread'}`} key={item.id}><span className="notification-icon"><Icon name={item.type==='review'?'check':item.type==='mail'?'mail':'bell'}/></span><div><div className="section-heading"><h3>{item.title}</h3>{!item.readAt&&<Badge status="accent">New</Badge>}</div><p>{item.body}</p><small>{date(item.createdAt)}</small></div><div className="notification-actions">{item.link?.view&&<Button variant="secondary" onClick={()=>read(item,true)}>Open</Button>}{!item.readAt&&<Button variant="ghost" onClick={()=>read(item)}>Mark read</Button>}</div></article>)}</div>:<div className="card"><Empty icon="bell" title={unreadOnly?'You’re up to date':'Your activity will appear here'}>Connected inboxes and agent workflows post updates here with links to the next action.</Empty></div>}</>
}
function NotificationIndicator(){const app=useApp(),resource=useResource('/notifications',{unread:0,enabled:true});return <button className="notification-indicator" aria-label={`Notifications, ${resource.data.unread} unread`} onClick={()=>app.navigate('notifications')}><Icon name="bell" size={17}/>{resource.data.enabled&&resource.data.unread>0&&<span>{Math.min(99,resource.data.unread)}</span>}</button>}
registry.page('notifications',{component:Notifications,icon:'bell'})
registry.slot('header:notifications',NotificationIndicator,{navigation:'notifications'})
