import assert from 'node:assert/strict'
import {mkdirSync,mkdtempSync,writeFileSync,readFileSync,existsSync,unlinkSync} from 'node:fs'
import {resolve,join} from 'node:path'
import {createHash} from 'node:crypto'
import {mount,sourceObjects,buyer,supplier,other,admin} from '../../file-store/tests/native-harness.mjs'
mkdirSync('tmp',{recursive:true});const root=mkdtempSync(resolve('tmp/retention-native-')),checks=[];let a=await mount(root)
const path=file=>join(root,'files',createHash('sha256').update(buyer.id).digest('hex'),file.sha256+'.bin'),configure=()=>a.ctx.retention.configure(buyer,{values:{retentionDays:0,kinds:'upload,attachment,received-attachment,audit-export',includeActive:true}})
async function approve(files,reason='Completed local review'){const proposal=await a.ctx.retention.propose(buyer,{fileIds:files.map(row=>row.id),reason});return a.ctx.actions.approve(buyer,proposal.proposal.id,{confirmed:true})}
try{
 await sourceObjects(a.ctx);const one=await a.ctx.files.put(buyer,{filename:'one.txt',buffer:Buffer.from('shared original')}),two=await a.ctx.files.put(buyer,{filename:'two.txt',buffer:Buffer.from('shared original')});assert.notEqual(one.id,two.id);const before=a.ctx.store.events(buyer.id).length,summary=a.ctx.files.summary(buyer),aggregate=a.ctx.retention.aggregate(admin);assert.equal(summary.uniqueBlobs,1);assert.equal(summary.bytes,one.size);assert.equal(a.ctx.store.events(buyer.id).length,before);assert(!JSON.stringify(aggregate).includes('shared original'));assert(!JSON.stringify(aggregate).includes('one.txt'));assert.throws(()=>a.ctx.retention.aggregate(buyer),/Administrator/)
 const originalPrefix=readFileSync(join(root,'ledgers/buyer.jsonl'),'utf8');await configure();const frozen=await a.ctx.retention.propose(buyer,{fileIds:[one.id],reason:'Archive obsolete review'});const held=await a.ctx.retention.hold(buyer,{name:'Contract review',reason:'Retain until the issue is resolved',fileIds:[one.id]});const blocked=await a.ctx.actions.approve(buyer,frozen.proposal.id,{confirmed:true});assert.equal(blocked.status,'failed');assert(existsSync(path(one)));assert.equal((await a.ctx.retention.preview(buyer)).files.find(row=>row.id===one.id).eligible,false)
 await a.ctx.retention.release(buyer,held.hold.id,{confirmed:true,reason:'Review complete'});const first=await approve([one]);assert.equal(first.status,'succeeded');assert.equal(first.result.report.results[0].sharedContentRetained,true);assert(existsSync(path(one)));assert.equal(a.ctx.files.read(buyer,two.id).toString(),'shared original');assert.throws(()=>a.ctx.files.read(buyer,one.id,{includeDeleted:true}),/not available/);const second=await approve([two]);assert.equal(second.status,'succeeded');assert.equal(existsSync(path(two)),false);assert(readFileSync(join(root,'ledgers/buyer.jsonl'),'utf8').startsWith(originalPrefix));assert.equal(a.ctx.files.summary(buyer).disposed,2)
 checks.push('Real shared blob counted once; observations append zero events and admin totals omit names/bodies; hold added after proposal blocks approval; two reviewed copies dispose bytes only after last reference and preserve exact ledger prefix')
 const attachment=(await a.ctx.attachments.upload(buyer,{kind:'rfq',objectId:'rfq-fixture',filename:'active.txt',buffer:Buffer.from('active scope')})).attachment;assert.equal((await a.ctx.retention.preview(buyer)).files.find(row=>row.id===attachment.fileId).eligible,false);await assert.rejects(a.ctx.retention.propose(buyer,{fileIds:[attachment.fileId],reason:'Cannot bypass object'}),/no longer eligible/);await a.ctx.attachments.remove(buyer,attachment.id,{confirmed:true,reason:'Scope superseded'});const disposedAttachment=await approve([{id:attachment.fileId}]);assert.equal(disposedAttachment.result.report.status,'complete');assert.throws(()=>a.ctx.attachments.download(buyer,attachment.id),/not available/);assert.equal(a.ctx.attachments.list(buyer,{kind:'rfq',objectId:'rfq-fixture'}).versions[0].storage.state,'disposed')
 checks.push('Current object attachment reference blocks disposal; explicit removal then reviewed disposal keeps version tombstone with truthful disposed state')
 const unregisterProject=a.ctx.settings.registerScope({id:'project',list:user=>a.ctx.store.list(user.id,'projects').map(row=>({id:row.id,label:row.name,context:{workspaceId:user.id,projectId:row.id}})),resolve(user,context){const project=a.ctx.store.get(user.id,'projects',context.projectId);if(!project||project.ownerId!==user.id)throw new Error('Own project required');return{realmId:user.id,key:project.id,label:project.name}}});const sharedFiles=[];for(const [id,days]of [['project-a',30],['project-b',60]]){await a.ctx.store.put(buyer.id,'projects',{id,name:id,ownerId:buyer.id});await a.ctx.store.put(buyer.id,'rfqs',{id:'rfq-'+id,ownerId:buyer.id,supplierIds:[supplier.id],projectId:id,status:'draft'});const version=(await a.ctx.attachments.upload(buyer,{kind:'rfq',objectId:'rfq-'+id,filename:'shared-project.txt',buffer:Buffer.from('same retained project artifact')})).attachment;sharedFiles.push(version.fileId);await a.ctx.attachments.remove(buyer,version.id,{confirmed:true,reason:'Test historical project copy'});await a.ctx.retention.configureProject(buyer,{projectId:id,values:{retentionDays:days}})}assert.equal(sharedFiles[0],sharedFiles[1]);let projectFile=(await a.ctx.retention.preview(buyer)).files.find(row=>row.id===sharedFiles[0]);assert.equal(projectFile.effectivePolicy.retentionDays,60);assert.equal(projectFile.projectPolicies.length,2);assert.equal(projectFile.eligible,false);await a.ctx.retention.configureProject(buyer,{projectId:'project-b',values:{retentionDays:0}});projectFile=(await a.ctx.retention.preview(buyer)).files.find(row=>row.id===sharedFiles[0]);assert.equal(projectFile.effectivePolicy.retentionDays,30);assert.equal(projectFile.eligible,false);await assert.rejects(a.ctx.retention.configureProject(other,{projectId:'project-a',values:{retentionDays:0}}),/owned by this party/);checks.push('Actual settings project patches apply strictest age/type/active constraints across a shared file’s own-project references; another party cannot configure or inherit those private patches');unregisterProject();assert.equal((await a.ctx.retention.preview(buyer)).files.find(row=>row.id===sharedFiles[0]).eligible,false);assert((await a.ctx.retention.preview(buyer)).files.find(row=>row.id===sharedFiles[0]).reasons.some(reason=>reason.includes('policy is unavailable')));
 await a.ctx.settings.save(buyer,'file-store',{values:{maxTotalMb:1,maxFileMb:1}});const large=await a.ctx.files.put(buyer,{filename:'large.bin',buffer:Buffer.alloc(600000,1)});await assert.rejects(a.ctx.files.put(buyer,{filename:'too-large.bin',buffer:Buffer.alloc(600000,2)}),/capacity/);writeFileSync(path(large),Buffer.from('tampered'));assert.equal(a.ctx.files.stat(buyer,large.id).storage.state,'corrupt');assert.throws(()=>a.ctx.files.read(buyer,large.id),/differs/);assert.equal((await a.ctx.retention.preview(buyer)).files.find(row=>row.id===large.id).eligible,false);const repaired=await a.ctx.files.put(buyer,{filename:'large.bin',buffer:Buffer.alloc(600000,1)});assert.equal(repaired.restored,true);assert.equal(a.ctx.files.stat(buyer,large.id).storage.state,'available');await a.ctx.files.flush();assert(a.ctx.files.summary(buyer).failures>=2)
 const parallel=await Promise.allSettled([a.ctx.files.put(buyer,{filename:'parallel-a.bin',buffer:Buffer.alloc(300000,3)}),a.ctx.files.put(buyer,{filename:'parallel-b.bin',buffer:Buffer.alloc(300000,4)})]);assert.equal(parallel.filter(row=>row.status==='fulfilled').length,1);assert.match(parallel.find(row=>row.status==='rejected').reason.message,/capacity/);
 checks.push('Concurrent unique-byte capacity enforced, corruption and actual upload/read failures observed, original-byte reupload repairs the existing record without fabricating content')
 const crash=await a.ctx.files.put(buyer,{filename:'interrupted.txt',buffer:Buffer.from('reviewed interrupted data')});await a.ctx.store.put(buyer.id,'files',{...crash,disposition:'disposing',disposalApprovalId:'fixture-reviewed-intent',disposalReason:'Crash fixture after reviewed disposal',disposalRequestedAt:new Date().toISOString()},{event:'files/disposal-requested',actor:'fixture'});unlinkSync(path(crash));const remaining=await a.ctx.files.put(buyer,{filename:'retained-after-crash.txt',buffer:Buffer.from('still present')});await a.ctx.store.put(buyer.id,'files',{...remaining,disposition:'disposing',disposalApprovalId:'fixture-reviewed-intent',disposalReason:'Crash fixture before deletion'},{event:'files/disposal-requested',actor:'fixture'});await a.close();a=await mount(root);assert.equal(a.ctx.files.stat(buyer,crash.id).storage.state,'disposed');assert.equal(a.ctx.files.stat(buyer,remaining.id).disposition,'interrupted');assert.equal(a.ctx.files.read(buyer,remaining.id).toString(),'still present');assert.equal(a.ctx.retention.aggregate(admin).bodyIncluded,false)
 checks.push('Restart resolves interrupted reviewed intent from actual byte presence: absent becomes recorded disposal, existing bytes remain and require a new review; plugin-owned services/guards/routes unload cleanly')
 const report={ok:true,at:new Date().toISOString(),root,checks,passed:checks.length};writeFileSync(join(root,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2))
}finally{await a.close()}
