import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {mkdirSync,writeFileSync} from 'node:fs'
import {resolve,join} from 'node:path'
const require=createRequire(new URL('../../../../host/package.json',import.meta.url)),{chromium}=require('playwright')
const base=(process.env.BASE_URL||'http://127.0.0.1:8644/quotagent/').replace(/\/?$/,'/'),output=resolve(process.env.EVIDENCE_DIR||'tmp/product-evidence/capability-requests/local')
mkdirSync(output,{recursive:true})
const browser=await chromium.launch({headless:true,executablePath:'/opt/hermes/.playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox']})
const report={base,at:new Date().toISOString(),checks:[],screenshots:[],errors:[]},pages=[]
async function login(role){const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();pages.push(page);page.on('pageerror',error=>report.errors.push(error.message));await page.goto(base);await page.getByRole('button',{name:role==='admin'?'Administrator sign in':role==='supplier'?'I’m a supplier':'I’m a contractor'}).click();await page.locator('.ws-navigation').waitFor();await page.waitForTimeout(350);for(const name of ['Not now','Hide walkthrough']){const button=page.getByRole('button',{name,exact:true});if(await button.isVisible())await button.click()}return page}
async function nav(page,label,group='Manage application'){const button=page.locator('.sidebar').getByRole('button',{name:label,exact:true});if(!await button.isVisible())await page.locator('.sidebar').getByRole('button',{name:group,exact:true}).click();await button.click()}
async function shot(page,name){await page.screenshot({path:join(output,name),fullPage:true});report.screenshots.push(name)}
async function request(page,kind,target,reason){const panel=page.locator('.capability-inbox');await panel.getByLabel('What do you need?',{exact:true}).selectOption(kind);await panel.getByLabel('Requested capability',{exact:true}).selectOption(target);await panel.getByLabel('Reason for your request',{exact:true}).fill(reason);await panel.getByRole('button',{name:'Send capability request',exact:true}).click();await panel.locator('.capability-request').filter({hasText:reason}).waitFor()}
const requestCard=(page,label)=>page.locator('.capability-request').filter({has:page.getByRole('heading',{name:label,exact:true})}).first()
try{
 const admin=await login('admin');await nav(admin,'Administration');const userRow=admin.getByRole('row').filter({hasText:'contractor@demo.local'});if(!await userRow.getByLabel('Disable AI assistant',{exact:true}).isChecked()){await userRow.getByLabel('Disable AI assistant',{exact:true}).click();await admin.getByRole('status').filter({hasText:'Account permissions updated.'}).waitFor()}
 const buyer=await login('contractor');await nav(buyer,'Settings');await request(buyer,'permission','assistant:use','Need assistant access for the local quotation check')
 await nav(admin,'Application plugins');let card=requestCard(admin,'Use the AI assistant');await card.getByLabel('Decision note for Use the AI assistant',{exact:true}).fill('Approved quotation assistance for this account');await card.getByRole('button',{name:'Grant requested access',exact:true}).click();await admin.locator('.capability-inbox').getByRole('button',{name:'All outcomes',exact:true}).click();await requestCard(admin,'Use the AI assistant').getByText('resolved',{exact:true}).waitFor();await nav(admin,'Administration');assert.equal(await admin.getByRole('row').filter({hasText:'contractor@demo.local'}).getByLabel('Disable AI assistant',{exact:true}).isChecked(),false)
 await buyer.reload();await buyer.locator('.capability-inbox').getByRole('button',{name:'All outcomes',exact:true}).click();await requestCard(buyer,'Use the AI assistant').getByText('resolved',{exact:true}).waitFor();await shot(buyer,'01-account-access-receipt.png');report.checks.push('Client requests a blocked capability; separate admin reviews and changes actual account permission; both retain the resolved receipt')
 await nav(admin,'Application plugins');const pluginCard=admin.locator('.studio-catalog-plugin').filter({has:admin.getByRole('heading',{name:'Help and getting started',exact:true})});await pluginCard.getByRole('button',{name:'Disable',exact:true}).click();await pluginCard.getByRole('button',{name:'Enable',exact:true}).waitFor();await buyer.reload();await request(buyer,'plugin','user-guide','Restore the help guide for the local check');await admin.reload();card=requestCard(admin,'Help and getting started');await card.getByLabel('Decision note for Help and getting started',{exact:true}).fill('Enable the application help plugin');await card.getByRole('button',{name:'Enable requested plugin',exact:true}).click();await pluginCard.getByRole('button',{name:'Disable',exact:true}).waitFor();await shot(admin,'02-plugin-lifecycle-grant.png');report.checks.push('Administrative request invokes real Cordis lifecycle; disabled Help becomes active again without a source edit')
 await buyer.reload();await request(buyer,'configuration','assistant','Please explain where the assistant preferences are');await admin.reload();card=admin.locator('.capability-request').filter({hasText:'Please explain where the assistant preferences are'});await card.locator('textarea').fill('Open Plugin settings and select Workspace assistant. Preferences are saved for your account.');await card.getByRole('button',{name:'Send guidance',exact:true}).click();await card.getByText('awaiting requester',{exact:true}).waitFor();await buyer.reload();card=buyer.locator('.capability-request').filter({hasText:'Please explain where the assistant preferences are'});await card.getByRole('button',{name:'Confirm this is working',exact:true}).click();await buyer.locator('.capability-inbox').getByRole('button',{name:'All outcomes',exact:true}).click();await buyer.getByText(/The requester confirmed this works on/).waitFor();await shot(buyer,'03-guidance-confirmed.png');report.checks.push('Configuration guidance stays awaiting requester until the client explicitly confirms the observed result')
 const supplier=await login('supplier');await nav(supplier,'Settings');await supplier.locator('.capability-inbox').getByRole('heading',{name:'No open capability requests',exact:true}).waitFor();assert.equal(await supplier.getByText('Need assistant access for the local quotation check',{exact:true}).count(),0);await buyer.setViewportSize({width:390,height:900});await shot(buyer,'04-mobile-requests.png');assert.equal(await buyer.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(report.errors.length,0);report.checks.push('Unrelated supplier sees none of the requester’s explanations; mobile settings has no page overflow or browser errors')
 report.ok=true;report.completedAt=new Date().toISOString();console.log(JSON.stringify(report,null,2))
}catch(error){report.error=error.stack;console.error(JSON.stringify(report,null,2));for(let index=0;index<pages.length;index++)await pages[index].screenshot({path:join(output,`failure-${index}.png`),fullPage:true}).catch(()=>{});process.exitCode=1}
finally{writeFileSync(join(output,'report.json'),JSON.stringify(report,null,2)+'\n');await browser.close()}
