import React,{useEffect,useState} from 'react'
import {registry,useApp,useResource,api,PageHeader,Button,Badge,Empty,ErrorNotice,Loading,Field,date,money} from '../../webui/client/core.jsx'
import './actions.css'
import {useCollection,CollectionControls} from '../../webui/client/collections.jsx'
const pending=new Set(['pending','awaiting-review','granted','executing'])
const statusLabel={pending:'Ready for review','awaiting-review':'Waiting for colleague',granted:'Ready to sign',executing:'Executing',succeeded:'Completed',failed:'Failed',uncertain:'Check delivery',rejected:'Declined',expired:'Expired'}
function ActionCenter(){
 const app=useApp(),view=useCollection('review-actions'),batchResource=useResource('/actions/batches',{batches:[]})
 const resource={...view,data:{actions:view.data.rows,batches:batchResource.data.batches},reload:async()=>{await Promise.all([view.reload(),batchResource.reload()])}}
 const [selected,setSelected]=useState(app.context.actionId||''),[reason,setReason]=useState(''),[reviewerId,setReviewerId]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[checked,setChecked]=useState([]),[batchOperation,setBatchOperation]=useState('approve'),[receipt,setReceipt]=useState(null)
 useEffect(()=>{if(app.context.actionId)setSelected(app.context.actionId)},[app.context.actionId])
 useEffect(()=>{setReason('');setError('');setReviewerId('')},[selected])
 const detail=useResource(selected?'/actions/'+selected:null,{action:null}),selection=useResource(checked.length?'/actions/selection?ids='+encodeURIComponent(checked.join(',')):null,{actions:[]})
 const all=resource.data.actions,action=detail.data.action,Preview=action&&registry.slots.get(`action-preview:${action.kind}`)
 useEffect(()=>setChecked([]),[view.selectionKey])
 const filter=view.query.filters.attention?.equals==='open'?'pending':view.query.filters.decision?.equals==='mine'?'mine':'all'
 const setFilter=value=>{const filters={...view.query.filters};delete filters.attention;delete filters.decision;if(value==='pending')filters.attention={equals:'open'};if(value==='mine')filters.decision={equals:'mine'};view.update({filters})}
 async function selectMatching(){setError('');try{const ids=await view.allKeys();if(ids.length>50)throw new Error('More than 50 actions match. Narrow your filters for one review batch.');setChecked(ids)}catch(e){setError(e.message)}}
 const activeBatches=resource.data.batches.filter(batch=>['running','paused'].includes(batch.status))
 useEffect(()=>{if(!activeBatches.some(batch=>batch.status==='running'))return;const timer=setInterval(()=>resource.reload(),1000);return()=>clearInterval(timer)},[activeBatches.some(batch=>batch.status==='running'),resource.reload])
 useEffect(()=>{if(!receipt)return;const current=resource.data.batches.find(batch=>batch.id===receipt.id);if(current)setReceipt(current)},[resource.data.batches,receipt?.id])
 async function controlBatch(batch,action){setBusy('batch');setError('');try{await api(`/actions/batch/${batch.id}/control`,{method:'POST',body:{action,confirmed:action==='resume',reason}});await resource.reload();app.refresh()}catch(error){setError(error.message)}finally{setBusy('')}}
 const rows=all
 async function decide(verb){
  setBusy(verb);setError('')
  try{const result=await api(`/actions/${action.id}/${verb}`,{method:'POST',body:{confirmed:['approve','grant'].includes(verb),reason,reviewerId}});await resource.reload();app.refresh();if(verb==='retry'){setSelected(result.action.id);setFilter('pending')}else if(verb==='approve'&&result.action.status!=='succeeded')setError(result.action.error||'The action could not complete.');else app.notify(({approve:'Action completed.',grant:'Independent approval recorded. The proposer can now sign.',nominate:'Review assigned.',remind:'Reminder sent.'})[verb]||'Decision saved.')}
  catch(error){setError(error.message)}finally{setBusy('')}
 }
 async function batch(){
  setBusy('batch');setError('')
  try{const result=await api('/actions/batch',{method:'POST',body:{ids:checked,operation:batchOperation,confirmed:true,reason}});setReceipt(result.receipt);await resource.reload();app.refresh();app.notify('Batch started. You can continue other work while each receipt is saved.')}
  catch(error){setError(error.message)}finally{setBusy('')}
 }
 const selectedRows=selection.data.actions
 return <><PageHeader eyebrow="YOU DECIDE WHAT HAPPENS NEXT" title="Review actions">Inspect exact proposals, ask a colleague for independent approval, and sign commitments when they are ready.</PageHeader>
 <ErrorNotice error={resource.error||batchResource.error||detail.error||selection.error||error} retry={()=>{resource.reload();detail.reload();selection.reload()}}/>
 <div className="review-workspace"><section className="card review-list"><div className="filter-tabs">{[['pending','Open'],['mine','My decisions'],['all','All activity']].map(([id,label])=><button key={id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{label}</button>)}</div>
 <CollectionControls view={view} label="actions" selection={<div className="collection-selection"><p>{checked.length} selected across pages · {rows.filter(row=>checked.includes(row.id)).length} on this page</p><Button variant="ghost" disabled={!view.ready||view.loading||!!view.error||view.data.query.matched>50} onClick={selectMatching}>Select all matching actions</Button><Button variant="ghost" disabled={!checked.length} onClick={()=>setChecked([])}>Clear selection</Button>{view.data.query.matched>50&&<p>Narrow to at most 50 matching actions for a review batch.</p>}</div>}/>
 {resource.loading?<Loading/>:rows.length?rows.map(row=><div className="review-choice" key={row.id}><input type="checkbox" aria-label={'Select '+row.title} checked={checked.includes(row.id)} onChange={event=>setChecked(value=>event.target.checked?[...value,row.id]:value.filter(id=>id!==row.id))}/><button className={`review-list-row ${row.id===selected?'selected':''}`} onClick={()=>setSelected(row.id)}><span><strong>{row.title}</strong><small>{row.kindLabel||'Action'} · {date(row.createdAt)}</small>{row.review?.independent&&<small>{row.status==='granted'?`Signer: ${row.proposerName}`:`Reviewer: ${row.reviewerName||'Choose a colleague'}`} · {row.ageMinutes} min</small>}</span><Badge status={row.status==='succeeded'?'success':pending.has(row.status)?'accent':'neutral'}>{statusLabel[row.status]||row.status}</Badge></button></div>):<Empty icon="check" title={resource.error?"Actions unavailable":view.data.query.total?"No actions match these filters":"No actions waiting"}>{resource.error?"Retry to read your actions.":view.data.query.total?"Clear or change the filters to see other actions.":"Agent proposals appear here for your decision."}</Empty>}
 {!!checked.length&&<section className="review-batch"><h3>{checked.length} selected actions</h3><p>Open each action to inspect its exact content. Only selected items will be attempted.</p><Field label="Batch decision"><select value={batchOperation} onChange={event=>setBatchOperation(event.target.value)}><option value="approve">Sign / approve and execute</option><option value="grant">Grant independent approval</option><option value="reject">Decline selected</option><option value="remind">Remind participants</option><option value="retry">Prepare selected attempts again</option></select></Field><details><summary>Review selected action contents</summary>{selectedRows.map(row=><article key={row.id}><strong>{row.title}</strong><pre>{JSON.stringify(row.input,null,2)}</pre></article>)}</details><ErrorNotice error={error}/><Button disabled={!!busy||selection.loading||!!selection.error||checked.length>50} onClick={batch}>Confirm {checked.length} selected decisions</Button></section>}
 {receipt&&<section className="review-batch" role="status"><h3>Batch {receipt.status}</h3><p>{receipt.items.length}/{receipt.ids?.length||receipt.items.length} item receipts saved.</p>{receipt.items.map(item=><p key={item.id}><strong>{all.find(row=>row.id===item.id)?.title||item.id}</strong>: {statusLabel[item.status]||item.status}{item.error&&<span> — {item.error}</span>}</p>)}{receipt.items.some(item=>!item.ok)&&<><p>Successful items stay completed. Inspect other receipts before trying them again.</p><Button variant="secondary" onClick={()=>setChecked(receipt.items.filter(item=>!item.ok).map(item=>item.id))}>Select failed items only</Button></>}</section>}
 {activeBatches.map(batch=><section className="review-batch" key={batch.id}><h3>{batch.status==='running'?'Batch in progress':'Paused batch'}</h3><p>{batch.items.length}/{batch.ids.length} receipts saved. {batch.currentId?'The current action may still finish.':'No action is executing.'}</p>{batch.error&&<p>{batch.error}</p>}<div className="review-batch-controls">{batch.status==='running'?<Button variant="secondary" disabled={!!busy} onClick={()=>controlBatch(batch,'pause')}>Pause after current item</Button>:<Button disabled={!!busy} onClick={()=>controlBatch(batch,'resume')}>Resume unattempted items</Button>}<Button variant="ghost" disabled={!!busy} onClick={()=>controlBatch(batch,'cancel')}>Cancel remaining items</Button></div></section>)}
 {!!resource.data.batches.length&&<details className="review-batch"><summary>Previous batch receipts</summary>{resource.data.batches.slice().reverse().map(batch=><details key={batch.id}><summary>{date(batch.createdAt)} · {batch.items.length} items</summary><pre>{JSON.stringify(batch,null,2)}</pre></details>)}</details>}
 </section><section className="card review-detail">{!action?<Empty icon="check" title="Choose an action to review">See its source, destination and exact content before making a decision.</Empty>:<><div className="section-heading"><div><div className="eyebrow">{action.kindLabel||'Review action'}</div><h2>{action.title}</h2></div><Badge status={action.status==='succeeded'?'success':pending.has(action.status)?'accent':'warning'}>{statusLabel[action.status]||action.status}</Badge></div>{action.summary&&<p>{action.summary}</p>}<ErrorNotice error={error||action.error}/>{action.runId&&<Button variant="ghost" onClick={()=>app.navigate(action.source?.kind==='workflow'?'workroom':'agent',{runId:action.runId})}>Open originating agent task</Button>}
 {action.review?.independent&&<section className="review-authority"><h3>Independent approval</h3><p>Proposer / signer: <strong>{action.proposerName}</strong><br/>Reviewer: <strong>{action.reviewerName||'Not nominated'}</strong></p><p>{money(action.review.amount/100,action.review.currency)} · Authority policy {action.review.policyRevision} · Waiting {action.ageMinutes} minutes</p>{action.dueAt&&<p>Next {action.review.timeoutPolicy} check: {date(action.dueAt)}. Waiting never approves an action.</p>}<details><summary>Authority bands and eligible colleagues</summary><p>{action.authority.reason}</p><ul>{action.authority.bands.map(role=><li key={role.id}>{role.label}: {role.limit===null?'Not configured':role.limit==='unlimited'?'Explicitly unlimited':money(role.limit/100,action.authority.policyCurrency)}{role.within?' · Covers this amount':''}</li>)}</ul><p>Eligible independent reviewers: {action.reviewers.map(person=>person.name).join(', ')||'None. Configure authority and invite a colleague.'}</p></details>{action.authority.policyRevision!==action.review.policyRevision&&<p className="review-warning">Authority changed since this proposal. Decline it and prepare a fresh review.</p>}{action.grant&&<p>Independent grant recorded {date(action.grant.at)}. The proposer must still sign.</p>}{action.delegations?.length>0&&<details><summary>Nomination and delegation history</summary>{action.delegations.map((entry,index)=><p key={index}>{date(entry.at)} · {entry.from||'Unassigned'} → {entry.to} · {entry.reason||'Initial nomination'}</p>)}</details>}{action.ageNotices?.length>0&&<p>{action.ageNotices.at(-1).reason}</p>}<Button variant="ghost" onClick={()=>app.navigate('team',{workspaceId:action.workspaceId})}>Open team authority</Button></section>}
 <p className="muted">Source: {action.source?.plugin||action.kindLabel||action.kind} · {action.source?.kind||'human proposal'}</p><div className="review-exact"><h3>Exact action content</h3>{Preview?<><Preview action={action} input={action.input}/><details><summary>Full request details</summary><pre>{JSON.stringify(action.input,null,2)}</pre></details></>:<pre>{JSON.stringify(action.input,null,2)}</pre>}</div>
 {action.decision&&<p className="muted">{action.decision.choice} · {date(action.decision.at)}{action.decision.reason?` · ${action.decision.reason}`:''}</p>}{action.result&&<details className="review-receipt" open><summary>Execution result</summary><pre>{JSON.stringify(action.result,null,2)}</pre></details>}{action.result?.action?.type==='navigate'&&action.result.action.input?.view&&<Button variant="secondary" icon="arrow" onClick={()=>app.navigate(action.result.action.input.view,action.result.action.input)}>{action.result.action.label||'Open result'}</Button>}{action.status==='uncertain'&&<p className="review-warning">Delivery could not be confirmed. Check the destination before proposing another attempt.</p>}
 {pending.has(action.status)&&action.status!=='executing'&&<><Field label="Decision or delegation reason"><textarea rows={2} value={reason} onChange={event=>setReason(event.target.value)} placeholder="Explain your decision or why another colleague should review…"/></Field>{(action.canNominate||action.canGrant)&&<div className="review-nomination"><Field label="Independent colleague"><select value={reviewerId} onChange={event=>setReviewerId(event.target.value)}><option value="">Choose an eligible colleague</option>{action.reviewers.map(person=><option key={person.accountId} value={person.accountId}>{person.name} · {person.roleLabel}</option>)}</select></Field><Button variant="secondary" disabled={!!busy||!reviewerId} onClick={()=>decide('nominate')}>{action.reviewerId?'Delegate review':'Request independent review'}</Button></div>}<div className="form-actions"><span className="muted">Your decision is recorded as {app.user.name}.</span>{action.canRemind&&<Button variant="ghost" disabled={!!busy} onClick={()=>decide('remind')}>Send reminder</Button>}{action.canReject&&<Button variant="secondary" disabled={!!busy} onClick={()=>decide('reject')}>Decline action</Button>}{action.canGrant&&<Button icon="check" disabled={!!busy} onClick={()=>decide('grant')}>Grant independent approval</Button>}{action.canSign&&<Button icon="check" disabled={!!busy} onClick={()=>decide('approve')}>{action.review?.independent?'Sign & execute':'Approve & execute'}</Button>}</div>{!action.canSign&&!action.canGrant&&!action.canNominate&&<p>Waiting for the named participant. You can continue other work.</p>}</>}
 {['failed','uncertain','rejected','expired'].includes(action.status)&&(!action.proposerId||action.proposerId===app.user.id)&&<Button variant="secondary" busy={busy==='retry'} onClick={()=>decide('retry')}>Propose another attempt</Button>}{action.status==='executing'&&<p role="status">The owning plugin is executing this signed action. Return later to inspect its receipt.</p>}
 </>}</section></div></>
}
registry.page('approvals',{component:ActionCenter,icon:'check',linkKeys:['actionId']})
