import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {mkdirSync,writeFileSync} from 'node:fs'
import {resolve,join} from 'node:path'
const require=createRequire(new URL('../../../../host/package.json',import.meta.url)),{chromium}=require('playwright')
const base=(process.env.BASE_URL||'http://127.0.0.1:8620/quotagent/').replace(/\/?$/,'/'),output=resolve(process.env.EVIDENCE_DIR||'tmp/product-evidence/workspace-experience')
mkdirSync(output,{recursive:true})
const browser=await chromium.launch({headless:true,executablePath:'/opt/hermes/.playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox']})
const report={base,at:new Date().toISOString(),checks:[],screenshots:[],browserErrors:[]},contexts=[]
async function shot(page,name){await page.waitForTimeout(250);await page.screenshot({path:join(output,name),fullPage:true});report.screenshots.push(name)}
async function login(role){const context=await browser.newContext({viewport:{width:1440,height:1000}});contexts.push(context);const page=await context.newPage();page.on('pageerror',error=>report.browserErrors.push(error.message));await page.goto(base);await page.getByRole('button',{name:role==='admin'?'Administrator sign in':role==='contractor'?'I’m a contractor':'I’m a supplier'}).click();await page.locator('.ws-navigation').waitFor();await page.waitForFunction(()=>document.querySelector('.product')?.classList.contains('workspace-presentation'));assert.ok(await page.locator('.sidebar .profile').evaluate(element=>element.getBoundingClientRect().bottom<=innerHeight+1),'Profile remains inside the desktop viewport');return page}
async function dismiss(page){const welcome=page.getByRole('button',{name:'Not now',exact:true});if(await welcome.isVisible())await welcome.click();const hide=page.getByRole('button',{name:'Hide walkthrough',exact:true});if(await hide.isVisible())await hide.click()}
async function nav(page,label,group){const button=page.locator('.sidebar').getByRole('button',{name:label,exact:true});if(!await button.isVisible()&&group)await page.locator('.sidebar').getByRole('button',{name:group,exact:true}).click();await button.click()}
async function style(page,{layout,palette,density}){await nav(page,'Workspace style','Personalize');await page.getByRole('radio',{name:`${layout} layout`,exact:true}).check();await page.getByRole('radio',{name:`${palette} palette`,exact:true}).check();await page.getByRole('radio',{name:`${density} spacing`,exact:true}).check();const save=page.getByRole('button',{name:'Save workspace style',exact:true});if(await save.isEnabled()){await save.click();await page.getByRole('status').filter({hasText:'Workspace style saved.'}).waitFor()}}
async function tour(page,role){await nav(page,'Help & getting started');await page.getByRole('button',{name:'Replay walkthrough',exact:true}).click();const panel=page.getByRole('complementary',{name:'Workspace walkthrough'});await panel.waitFor();assert.match(await panel.innerText(),new RegExp(role==='admin'?'ADMINISTRATOR':role.toUpperCase()));await panel.getByRole('button',{name:'Next step',exact:true}).click();await panel.getByText('Step 2 of 4',{exact:true}).waitFor();await page.reload();await page.getByRole('complementary',{name:'Workspace walkthrough'}).getByText('Step 2 of 4',{exact:true}).waitFor();await shot(page,`${role}-walkthrough.png`);await dismiss(page);await page.getByLabel('Search Help',{exact:true}).fill(role==='admin'?'Manage accounts':role==='supplier'?'Prepare and submit':'Prepare a request');await page.locator('.guide-topic-card').first().click();const article=page.locator('.guide-article');await article.waitFor();const text=await article.innerText();assert.match(text,role==='admin'?/Manage accounts/:role==='supplier'?/Prepare and submit/:/Prepare a request/);await shot(page,`${role}-help.png`);const action=article.getByRole('button',{name:role==='admin'?'Open administration':role==='supplier'?'Open quotations':'Open requests',exact:true});await action.click();await page.waitForURL(new RegExp(`#${role==='admin'?'admin':role==='supplier'?'quotes':'rfqs'}$`));report.checks.push(`${role}: replay, step persistence across reload, role-specific Help search and working destination`)}
try{
 const buyer=await login('contractor');await dismiss(buyer);await shot(buyer,'01-agent-first-workspace.png');await style(buyer,{layout:'Classic',palette:'Ocean',density:'Compact'});await buyer.reload();await buyer.getByRole('radio',{name:'Classic layout',exact:true}).waitFor();assert.ok(await buyer.getByRole('radio',{name:'Classic layout',exact:true}).isChecked());assert.ok(await buyer.getByRole('radio',{name:'Ocean palette',exact:true}).isChecked());assert.ok(await buyer.getByRole('radio',{name:'Compact spacing',exact:true}).isChecked());await buyer.waitForFunction(()=>document.querySelector('.product')?.classList.contains('ws-palette-ocean'));await shot(buyer,'02-persisted-workspace-style.png');report.checks.push('Contractor changed layout, palette and spacing through GUI; saved choices survived reload')
 await buyer.locator('.brand-link').click();await buyer.waitForFunction(()=>document.querySelector('main h1')?.textContent?.includes('Good to see you'));await style(buyer,{layout:'Focus',palette:'Calm',density:'Comfortable'});await buyer.locator('.brand-link').click();await buyer.waitForFunction(()=>!!document.querySelector('.assistant-mode-hidden'));report.checks.push('Home follows Classic records then Focus agent layout without duplicate dock')
 await tour(buyer,'contractor');await nav(buyer,'Workspace style','Personalize');for(const width of [1024,390]){await buyer.setViewportSize({width,height:900});await buyer.waitForTimeout(300);assert.equal(await buyer.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`No horizontal overflow at ${width}`);await shot(buyer,`03-style-${width}.png`)}
 await buyer.setViewportSize({width:1440,height:1000});const vendor=await login('supplier');await dismiss(vendor);await nav(vendor,'Workspace style','Personalize');assert.ok(await vendor.getByRole('radio',{name:'Calm palette',exact:true}).isChecked());await tour(vendor,'supplier');report.checks.push('Supplier retains own default style; contractor choice does not leak')
 const admin=await login('admin');await dismiss(admin);await tour(admin,'admin');assert.equal(await admin.locator('.sidebar').getByRole('button',{name:'Quotation work',exact:true}).count(),0);report.checks.push('Administrator receives management guidance and no quotation-work group')
 assert.equal(report.browserErrors.length,0);report.ok=true;console.log(JSON.stringify(report,null,2))
}catch(error){report.error=error.stack;console.error(JSON.stringify(report,null,2));for(let i=0;i<contexts.length;i++){const page=contexts[i].pages()[0];if(page)await page.screenshot({path:join(output,`failure-${i}.png`),fullPage:true}).catch(()=>{})}process.exitCode=1}
finally{writeFileSync(join(output,'report.json'),JSON.stringify(report,null,2)+'\n');await browser.close()}
