import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {mkdirSync,writeFileSync} from 'node:fs'
import {join,resolve} from 'node:path'
const require=createRequire(new URL('../../../../host/package.json',import.meta.url)),{chromium}=require('playwright'),base=process.env.BASE_URL||'http://127.0.0.1:8620/quotagent/',output=resolve(process.env.EVIDENCE_DIR||'tmp/product-evidence/workspace-experience/lifecycle')
mkdirSync(output,{recursive:true})
const browser=await chromium.launch({headless:true,executablePath:'/opt/hermes/.playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox']})
const report={base,at:new Date().toISOString(),checks:[],browserErrors:[]},disabled=new Set()
async function login(role){const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>report.browserErrors.push(e.message));await page.goto(base);await page.getByRole('button',{name:role==='admin'?'Administrator sign in':'I’m a contractor'}).click();await page.locator('.ws-navigation').waitFor();const dismiss=page.getByRole('button',{name:'Not now',exact:true});if(await dismiss.isVisible())await dismiss.click();return page}
let admin,client
async function toggle(name,enabled){await admin.getByLabel('Search application plugins',{exact:true}).fill(name);const card=admin.locator('.studio-catalog-plugin').filter({has:admin.getByRole('heading',{name,exact:true})});await card.getByRole('button',{name:enabled?'Enable':'Disable',exact:true}).click();await card.getByRole('button',{name:enabled?'Disable':'Enable',exact:true}).waitFor();if(enabled)disabled.delete(name);else disabled.add(name)}
try{
 admin=await login('admin');client=await login('contractor');await admin.getByRole('button',{name:'Manage application',exact:true}).click();await admin.getByRole('button',{name:'Application plugins',exact:true}).click()
 await toggle('Workspace styles',false);await client.reload();await client.locator('.sidebar nav').waitFor();assert.equal(await client.locator('.ws-navigation').count(),0);assert.equal(await client.locator('.workspace-presentation').count(),0);assert.equal(await client.locator('.sidebar').getByRole('button',{name:'Workspace style',exact:true}).count(),0);await client.screenshot({path:join(output,'01-style-effects-unloaded.png'),fullPage:true});report.checks.push('Disabling workspace styles removes grouped navigation, account style page and presentation effect; generic navigation remains')
 await toggle('Workspace styles',true);await client.reload();await client.locator('.ws-navigation').waitFor();await client.waitForFunction(()=>document.querySelector('.product').classList.contains('workspace-presentation'));report.checks.push('Re-enabling workspace styles restores saved account presentation and grouped navigation')
 await client.getByRole('button',{name:'Help & getting started',exact:true}).click();await client.getByRole('button',{name:'Replay walkthrough',exact:true}).click();await client.getByRole('complementary',{name:'Workspace walkthrough'}).waitFor()
 await toggle('Help and getting started',false);await client.reload();await client.locator('.sidebar').waitFor();assert.equal(await client.locator('.guide-floating').count(),0);assert.equal(await client.getByRole('button',{name:'Open Help and getting started',exact:true}).count(),0);assert.equal(await client.locator('.sidebar').getByRole('button',{name:'Help & getting started',exact:true}).count(),0);await client.screenshot({path:join(output,'02-guide-effects-unloaded.png'),fullPage:true});report.checks.push('Disabling user guide removes its active overlay, Help navigation and header control')
 await toggle('Help and getting started',true);await client.reload();await client.getByRole('complementary',{name:'Workspace walkthrough'}).waitFor();await client.getByRole('button',{name:'Hide walkthrough',exact:true}).click();await client.getByRole('button',{name:'Open Help and getting started',exact:true}).waitFor();report.checks.push('Re-enabling user guide restores Help and retained walkthrough progress; user can dismiss it')
 assert.equal(report.browserErrors.length,0);report.ok=true;console.log(JSON.stringify(report,null,2))
}catch(error){report.error=error.stack;console.error(JSON.stringify(report,null,2));process.exitCode=1}
finally{for(const name of disabled){try{await toggle(name,true)}catch(error){report.restoreError=String(error.message);process.exitCode=1}}writeFileSync(join(output,'report.json'),JSON.stringify(report,null,2)+'\n');await browser.close()}
