import assert from 'node:assert/strict'
import {browserHarness} from '../../file-store/tests/browser-helpers.mjs'

const h=await browserHarness('current-help')
const open=async(page,title)=>{
 await h.nav(page,'Help & getting started')
 await page.getByLabel('Search Help',{exact:true}).fill(title)
 await page.locator('.guide-topic-card').filter({has:page.getByText(title,{exact:true})}).click()
 const article=page.locator('.guide-article')
 await article.getByRole('heading',{name:title,exact:true}).waitFor()
 return article
}
const destination=async(page,article,label,view)=>{
 await article.getByRole('button',{name:label,exact:true}).click()
 await page.waitForURL(url=>url.hash===`#${view}`||url.hash.startsWith(`#${view}?`))
 await page.locator('main h1').waitFor()
 assert(!/Page unavailable|This page is not available/.test(await page.locator('main').innerText()))
}
try{
 const buyer=await h.login('contractor@demo.local')
 let article=await open(buyer,'Compare recorded business measures')
 assert.match(await article.innerText(),/equal-length current and earlier baseline windows/)
 assert.match(await article.innerText(),/not proof the agent saved time/)
 await destination(buyer,article,'Open business measures','responses')
 await buyer.getByRole('heading',{name:'Recorded business measures',exact:true}).waitFor()
 await h.shot(buyer,'01-help-opens-business-measures')
 article=await open(buyer,'Keep scope, terms and alternatives explicit')
 assert.match(await article.innerText(),/measurement basis|measurement rules/)
 assert.match(await article.innerText(),/new publication needs these declarations/)
 await destination(buyer,article,'Inspect requests','rfqs')
 article=await open(buyer,'Follow responses, promises and reminders')
 assert.match(await article.innerText(),/stale offers do not count|stale quotations do not count|stale quotes do not count/)
 await destination(buyer,article,'Open responses','responses')
 h.checks.push('Contractor Help explains explicit declarations and current-scope response rules; real links open Requests, Responses and the Business measures tab with its intended context')

 article=await open(buyer,'Attach versions, export evidence and manage retention')
 assert.match(await article.innerText(),/independently trusted public key/)
 assert.match(await article.innerText(),/not the truth of every claim/)
 await destination(buyer,article,'Open evidence','evidence')
 article=await open(buyer,'Deliver a signed exchange by email')
 assert.match(await article.innerText(),/Mail-server acceptance is separate from a signed recipient receipt/)
 await h.shot(buyer,'02-current-signed-email-help')
 await destination(buyer,article,'Open message delivery','exchange')
 article=await open(buyer,'Try a quotation scenario in the sandbox')
 assert.match(await article.innerText(),/separate from live party work/)
 await destination(buyer,article,'Open demo sandbox','sandbox')
 assert.equal(await buyer.getByRole('region',{name:'Active demonstration workspace'}).count(),0)
 h.checks.push('Evidence, signed-email and isolated-demo Help preserves trust/delivery limitations and opens the real pages; visiting sandbox controls does not start or reset a demo')

 const supplier=await h.login('supplier@demo.local')
 article=await open(supplier,'Prepare several quotes for separate review')
 assert.match(await article.innerText(),/Preparation creates an exact review for each eligible quote; it sends nothing/)
 assert.match(await article.innerText(),/a failed item does not resend one that succeeded/)
 await destination(supplier,article,'Select quotation drafts','quotes')
 article=await open(supplier,'Prepare and submit a quotation')
 assert.match(await article.innerText(),/party workspace|supplier party/)
 assert.match(await article.innerText(),/competitors/)
 await h.shot(supplier,'03-supplier-help-private-party-scope')
 h.checks.push('Supplier Help explains separate batch reviews/receipts and private supplier-party scope; quotation destination is reachable')

 const admin=await h.login('admin@demo.local')
 article=await open(admin,'Inspect application operations')
 assert.match(await article.innerText(),/timeline remains your own account/)
 await destination(admin,article,'Open operations','operations')
 article=await open(admin,'Understand your AI usage')
 assert.match(await article.innerText(),/Configured-rate cost estimates/)
 assert.match(await article.innerText(),/not invoices/)
 await destination(admin,article,'Open AI usage','ai-usage')
 await h.nav(admin,'Help & getting started')
 await admin.getByLabel('Search Help',{exact:true}).fill('Try a quotation scenario in the sandbox')
 await admin.getByRole('heading',{name:'No matching Help topics',exact:true}).waitFor()
 await h.shot(admin,'04-admin-no-client-demo-topic')
 h.checks.push('Admin Help links to scoped operations and provider usage, explains estimate/unknown boundaries and omits client-only demo walkthrough')
 await h.finish({release:process.env.RELEASE||null,scope:'Public Help navigation and factual text; no chat/model calls, commercial writes, plugin lifecycle or sandbox mode changes'})
}catch(error){await h.fail(error);throw error}finally{await h.close()}
