import React, {useState,useEffect,useRef} from 'react'
import {registry,useApp,useResource,api,Icon,Button,Badge,Field,PageHeader,Modal,Empty,ErrorNotice,Loading,date,money} from '../../../system/webui/client/core.jsx'
import './ingestion.css'

const accepted = '.eml,.mbox,.msg,.xlsx,.xls,.xlsm,.xlsb,.ods,.csv,.tsv,.docx,.pdf,.txt,.html,.htm,.json,.md'
const number = value => value === '' || value === null || value === undefined ? null : Number(value)
const item = () => ({id:`import-${Date.now()}-${Math.random().toString(16).slice(2,6)}`,description:'',quantity:null,unit:'',unitPrice:null,cost:null})
const b64 = file => new Promise((resolve,reject) => {const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error(`Could not read ${file.name}.`));reader.readAsDataURL(file)})
const engineLabel = (id,engines) => id === 'auto' ? 'Automatic · match the file' : engines.find(engine => engine.id === id)?.name || id

function Ingestion() {
  const app=useApp(), library=useResource('/ingestion',{documents:[],files:[],engines:[],settings:{}})
  const workspace=useResource('/workspace',{rfqs:[],contacts:[]})
  const [selected,setSelected]=useState(app.context.documentId || ''),[document,setDocument]=useState(null),[busy,setBusy]=useState(''),[error,setError]=useState('')
  const [engine,setEngine]=useState('auto'),[errors,setErrors]=useState([]),[settingsOpen,setSettingsOpen]=useState(false),[drag,setDrag]=useState(false)
  const input=useRef(),loaded=useRef(0),configured=useRef(false)
  const data=library.data
  useEffect(()=>{if(!configured.current && data.settings.defaultEngine){setEngine(data.settings.defaultEngine);configured.current=true}},[data.settings.defaultEngine])
  useEffect(()=>{if(app.context.documentId)setSelected(app.context.documentId)},[app.context.documentId])
  useEffect(()=>{
    if(!selected){setDocument(null);return}
    const request=++loaded.current;setBusy('open');setError('')
    api(`/ingestion/${selected}`).then(result=>{if(request===loaded.current)setDocument(result.document)})
      .catch(error=>setError(error.message)).finally(()=>{if(request===loaded.current)setBusy('')})
  },[selected])
  async function upload(fileList) {
    const files=Array.from(fileList || [])
    if(!files.length)return
    setBusy('upload');setErrors([]);setError('')
    try {
      if(files.length>15)throw new Error('Choose up to fifteen files at a time.')
      const documents=[], failures=[]
      // Send each file separately so a group of large documents stays within the request limit.
      for(const [index,file] of files.entries()) {
        setBusy(`upload:${index+1}:${files.length}`)
        const result=await api('/ingestion/upload',{method:'POST',body:{engine,files:[{filename:file.name,mime:file.type || 'application/octet-stream',contentBase64:await b64(file)}]}})
        documents.push(...result.documents);failures.push(...result.errors)
      }
      setErrors(failures)
      await library.reload()
      if(documents.length){setDocument(documents[0]);setSelected(documents[0].id);app.notify(`${documents.length} document${documents.length===1?'':'s'} ready to review.`)}
    } catch(error){setError(error.message)} finally {setBusy('');if(input.current)input.current.value=''}
  }
  const uploadBusy=busy.startsWith('upload')
  const ai=data.engines.find(engine=>engine.id==='ai')
  const readOnly=app.user.permissions?.includes('workspace:read-only')
  return <><PageHeader eyebrow="FROM SOURCE TO STRUCTURE" title="Bring the details into focus." actions={<Button variant="secondary" icon="settings" onClick={()=>setSettingsOpen(true)}>Parser settings</Button>}>Turn email, spreadsheets and documents into reviewed line items. Your originals and drafts stay in your workspace.</PageHeader>
    <ErrorNotice error={error || library.error} retry={library.error ? library.reload : undefined}/>
    <section className={`ingest-upload card ${drag?'is-dragging':''}`} onDragOver={event=>{event.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={event=>{event.preventDefault();setDrag(false);if(!readOnly&&!busy)upload(event.dataTransfer.files)}}>
      <div className="ingest-upload-symbol"><Icon name="file" size={30}/></div><div className="ingest-upload-copy"><h2>Drop your source files here</h2><p>Email exports, Excel, CSV, Word, text PDFs and more. Email attachments are read too.</p><span>EML / MBOX / MSG · XLSX / XLS · CSV / TSV · DOCX / PDF / TXT / HTML / JSON</span></div>
      <div className="ingest-upload-actions"><label className="field"><span>Read with</span><select aria-label="Ingestion engine" value={engine} onChange={event=>setEngine(event.target.value)} disabled={!!busy}><option value="auto">Automatic · match the file</option>{data.engines.map(entry=><option key={entry.id} value={entry.id} disabled={!entry.available}>{entry.name}{!entry.available?' · not connected':''}</option>)}</select></label><Button icon="plus" disabled={!!busy||readOnly} busy={uploadBusy} onClick={()=>input.current.click()}>{uploadBusy?`Reading ${busy.split(':')[1] || ''} of ${busy.split(':')[2] || ''}…`:'Choose files'}</Button><input ref={input} type="file" multiple accept={accepted} aria-label="Upload source files" onChange={event=>upload(event.target.files)} hidden/></div>
    </section>
    <p className="ingest-support-note"><Icon name="check" size={14}/> Traditional parsers work without AI. Scanned PDFs need OCR before upload; legacy Word .doc is not supported.</p>
    {errors.length>0&&<div className="ingest-errors" role="alert">{errors.map((entry,index)=><p key={index}><strong>{entry.filename}:</strong> {entry.error}</p>)}</div>}
    {library.loading&&!data.documents.length?<Loading/>:<div className="ingest-layout"><aside className="card ingest-library"><div className="section-heading"><h2>Your documents</h2><Badge>{data.documents.length}</Badge></div>{data.documents.length?data.documents.map(entry=><button className={`ingest-document-link ${selected===entry.id?'active':''}`} key={entry.id} onClick={()=>setSelected(entry.id)}><span className="ingest-document-icon"><Icon name="file" size={20}/></span><span><strong>{entry.filename}</strong><small>{entry.itemCount} items · {entry.engineName}</small><small>{date(entry.createdAt)}{entry.imported?.length?' · Draft created':''}</small></span><Icon name="chevron" size={15}/></button>):<div className="ingest-library-empty">Your uploaded documents appear here. Choose one to review its source and extracted items.</div>}</aside>
      <section className="ingest-workspace">{busy==='open'?<Loading/>:document?<DocumentReview key={document.id} document={document} setDocument={setDocument} engines={data.engines} ai={ai} refresh={library.reload} workspace={workspace.data}/>:<div className="card"><Empty icon="file" title="From scattered files to a working draft">Upload an actual supplier offer or project brief. Review the source, map columns, edit line items and create a private draft when it is ready.</Empty><div className="ingest-path"><span><b>1</b> Upload & parse</span><Icon name="chevron" size={16}/><span><b>2</b> Review & edit</span><Icon name="chevron" size={16}/><span><b>3</b> Create a draft</span></div></div>}</section>
    </div>}
    {settingsOpen&&<ParserSettings settings={data.settings} engines={data.engines} close={()=>setSettingsOpen(false)} saved={()=>{library.reload();configured.current=false}}/>}
  </>
}

function DocumentReview({document,setDocument,engines,ai,refresh,workspace}) {
  const app=useApp(),supplier=app.user.role==='supplier',readOnly=app.user.permissions?.includes('workspace:read-only')
  const [tab,setTab]=useState('items'),[items,setItems]=useState(document.items),[mapping,setMapping]=useState(document.mapping),[busy,setBusy]=useState(''),[error,setError]=useState('')
  const [title,setTitle]=useState(document.title),[currency,setCurrency]=useState(document.currency),[parseEngine,setParseEngine]=useState(document.engine),[instructions,setInstructions]=useState('')
  const [rfqId,setRfqId]=useState(''),[leadDays,setLeadDays]=useState(14),[terms,setTerms]=useState(''),[notes,setNotes]=useState(''),[deadline,setDeadline]=useState(''),[suppliers,setSuppliers]=useState([])
  const [imported,setImported]=useState(null),[mappingOpen,setMappingOpen]=useState(false)
  const rfqs=(workspace.rfqs || []).filter(rfq=>rfq.status==='published'),rfq=rfqs.find(rfq=>rfq.id===rfqId)
  useEffect(()=>{setItems(document.items);setMapping(document.mapping);setTitle(document.title);setCurrency(document.currency)},[document])
  const missing=items.filter(item=>!item.description.trim()||!(Number(item.quantity)>0)||!item.unit.trim()||(supplier&&item.unitPrice===null)).length
  const replace=next=>{setDocument(next);refresh()}
  async function task(name,fn){setBusy(name);setError('');try{return await fn()}catch(error){setError(error.message)}finally{setBusy('')}}
  const save=()=>task('save',async()=>{const result=await api(`/ingestion/${document.id}`,{method:'PATCH',body:{title,currency,items}});replace(result.document);app.notify('Reviewed extraction saved.')})
  const remap=()=>task('map',async()=>{const result=await api(`/ingestion/${document.id}`,{method:'PATCH',body:{mapping}});replace(result.document);setTab('items');setMappingOpen(false);app.notify('Columns mapped. Review the extracted items.')})
  const extract=()=>task('ai',async()=>{const result=await api(`/ingestion/${document.id}/extract`,{method:'POST',body:{instructions}});replace(result.document);setTab('items');app.notify('AI extraction is ready for review.')})
  const reparse=()=>task('parse',async()=>{const result=await api('/ingestion/parse',{method:'POST',body:{fileId:document.fileId,documentId:document.id,engine:parseEngine}});replace(result.document);setTab('items')})
  const edit=(index,key,value)=>setItems(previous=>previous.map((item,i)=>i===index?{...item,[key]:['quantity','unitPrice','cost'].includes(key)?number(value):value}:item))
  const chooseRfq=value=>{setRfqId(value);const selected=rfqs.find(row=>row.id===value);setItems(previous=>previous.map(item=>({...item,rfqItemId:selected?.items.find(row=>row.description.toLowerCase().trim()===item.description.toLowerCase().trim())?.id || ''})))}
  const makeDraft=()=>task('import',async()=>{
    const result=await api(`/ingestion/${document.id}/import`,{method:'POST',body:{title,currency,items,deadline,supplierIds:suppliers,rfqId,leadDays:Number(leadDays),paymentTerms:terms,notes}})
    setImported(result);refresh();app.refresh();app.notify(supplier?'Private quote draft created.':'Private RFQ draft created.')
  })
  return <><section className="card ingest-review"><div className="section-heading"><div><div className="eyebrow">SOURCE DOCUMENT</div><h2>{document.filename}</h2><p>{document.engineName} · {document.rows.length} source rows · {items.length} editable items</p></div><a className="button button-secondary" href={`/quotagent/api/files/${encodeURIComponent(document.fileId)}/download`} download><Icon name="download" size={16}/> Original</a></div>
    <ErrorNotice error={error}/>
    {document.warnings?.length>0&&<div className="ingest-warnings">{document.warnings.map((warning,index)=><p key={index}>{warning}</p>)}</div>}
    <div className="ingest-reader-controls"><Field label="Parser"><select value={parseEngine} onChange={event=>setParseEngine(event.target.value)}>{engines.filter(engine=>engine.mode!=='extractor').map(engine=><option key={engine.id} value={engine.id}>{engine.name}</option>)}</select></Field><Button variant="secondary" busy={busy==='parse'} disabled={!!busy||readOnly} onClick={reparse}>Read again</Button><Button variant="ghost" icon="spark" onClick={()=>app.ask(`Read my imported document ${document.id} (${document.filename}) using ingestion_read. Explain the actual requirements or offer, unclear fields and useful next actions. Do not invent quantities or terms.`)}>Discuss with AI</Button></div>
    <div className="tabs"><button className={tab==='items'?'active':''} onClick={()=>setTab('items')}>Editable items <span>{items.length}</span></button><button className={tab==='rows'?'active':''} onClick={()=>setTab('rows')}>Source rows <span>{document.rows.length}</span></button><button className={tab==='text'?'active':''} onClick={()=>setTab('text')}>Source text</button>{document.attachments.length>0&&<button className={tab==='attachments'?'active':''} onClick={()=>setTab('attachments')}>Attachments <span>{document.attachments.length}</span></button>}</div>
    {tab==='text'?<pre className="ingest-source-text">{document.text||'No text extracted. Review the warnings above.'}</pre>:tab==='rows'?<><p className="muted">Original column values are preserved here. Automatic mapping recognizes each table’s headings. Applying a mapping below uses your selected columns for every row.</p><Button variant="secondary" onClick={()=>setMappingOpen(!mappingOpen)}>Map columns</Button><SourceRows rows={document.rows} columns={document.columns}/></>:tab==='attachments'?<div className="ingest-attachments">{document.attachments.map(file=><article key={file.id}><Icon name="file"/><div><strong>{file.filename}</strong><small>{file.parsed?`${file.rowCount} rows extracted`:'Saved as an attachment'}</small></div><a href={`/quotagent/api/files/${file.id}/download`} download>Download</a></article>)}</div>:<>
      <div className="ingest-items-heading"><span>{missing?`${missing} item${missing===1?' needs':'s need'} missing details before import.`:'Review each value against the source before creating a draft.'}</span><div>{document.columns.length>0&&<Button variant="ghost" onClick={()=>setMappingOpen(!mappingOpen)}>Map columns</Button>}<Button variant="secondary" icon="plus" disabled={readOnly} onClick={()=>setItems([...items,item()])}>Add item</Button></div></div>
      {items.length?<div className="table-scroll"><table className="ingest-items"><thead><tr><th>Description</th><th>Quantity</th><th>Unit</th><th>Unit price</th>{supplier&&<th>Private cost</th>}<th/></tr></thead><tbody>{items.map((row,index)=><tr key={row.id}><td><input aria-label={`Imported item ${index+1} description`} value={row.description} onChange={event=>edit(index,'description',event.target.value)} disabled={readOnly}/>{row.source?.quote&&<small className="ingest-source-quote">“{row.source.quote}”</small>}{supplier&&rfq&&<label className="ingest-match"><span>Match RFQ item</span><select aria-label={`Match imported item ${index+1}`} value={row.rfqItemId || ''} onChange={event=>edit(index,'rfqItemId',event.target.value)}><option value="">Choose matching scope…</option>{rfq.items.map(target=><option key={target.id} value={target.id}>{target.description} · {target.quantity} {target.unit}</option>)}</select></label>}</td><td><input aria-label={`Imported item ${index+1} quantity`} type="number" min="0" step="any" value={row.quantity??''} placeholder="Missing" onChange={event=>edit(index,'quantity',event.target.value)} disabled={readOnly}/></td><td><input aria-label={`Imported item ${index+1} unit`} value={row.unit} placeholder="Missing" onChange={event=>edit(index,'unit',event.target.value)} disabled={readOnly}/></td><td><input aria-label={`Imported item ${index+1} unit price`} type="number" step="0.01" min="0" value={row.unitPrice??''} placeholder={supplier?'Required':'Optional'} onChange={event=>edit(index,'unitPrice',event.target.value)} disabled={readOnly}/></td>{supplier&&<td><input aria-label={`Imported item ${index+1} private cost`} type="number" step="0.01" min="0" value={row.cost??''} placeholder="Optional" onChange={event=>edit(index,'cost',event.target.value)} disabled={readOnly}/></td>}<td><button className="icon-button" aria-label={`Remove imported item ${index+1}`} disabled={readOnly} onClick={()=>setItems(items.filter((_,i)=>i!==index))}><Icon name="close" size={15}/></button></td></tr>)}</tbody></table></div>:<Empty title="Choose how to extract your items">Use column mapping for tables, AI extraction for prose, or add line items by hand. Missing values remain blank for your review.</Empty>}
      <div className="ingest-save-row"><span>{supplier?'Private cost values are never included in the submitted supplier offer.':'Quoted source prices remain in this extraction; the RFQ draft contains only scope, quantity and unit.'}</span><Button variant="secondary" busy={busy==='save'} disabled={!!busy||readOnly} onClick={save}>Save reviewed extraction</Button></div>
    </>}
    {mappingOpen&&<div className="ingest-mapping"><h3>Map source columns</h3><div className="ingest-mapping-grid">{[['description','Description'],['quantity','Quantity'],['unit','Unit'],['unitPrice','Unit price'],...(supplier?[['cost','Private cost']]:[])].map(([key,label])=><Field key={key} label={label}><select value={mapping[key] || ''} onChange={event=>setMapping({...mapping,[key]:event.target.value})}><option value="">Not present</option>{document.columns.map(column=><option key={column}>{column}</option>)}</select></Field>)}</div><p className="muted">Applying this mapping replaces the editable item list with values from the original rows.</p><Button disabled={!!busy||!mapping.description||readOnly} busy={busy==='map'} onClick={remap}>Apply column mapping</Button></div>}
    </section>
    <section className="card ingest-ai"><div className="ingest-ai-symbol"><Icon name="spark" size={22}/></div><div><h3>Let AI read the details</h3><p>Extract line items from prose and irregular layouts. Source excerpts stay beside the results; you review anything missing.</p><textarea aria-label="AI extraction instructions" rows={2} placeholder="Optional: focus on mechanical equipment; keep all model numbers…" value={instructions} onChange={event=>setInstructions(event.target.value)}/>{document.aiSummary&&<p className="ingest-ai-summary">{document.aiSummary}</p>}</div><Button icon="spark" busy={busy==='ai'} disabled={!!busy||!ai?.available||readOnly} onClick={extract}>{ai?.available?'Extract with AI':'AI not connected'}</Button></section>
    <section className="card ingest-import"><div className="section-heading"><div><div className="eyebrow">NEXT STEP</div><h2>{supplier?'Turn reviewed items into a quote':'Turn reviewed items into a request'}</h2><p>A private draft you can refine before sharing. Nothing is sent on import.</p></div><Badge status="accent">Draft only</Badge></div>
      {supplier?<><Field label="Match an incoming RFQ"><select aria-label="Match an incoming RFQ" value={rfqId} onChange={event=>chooseRfq(event.target.value)}><option value="">Select an open request…</option>{rfqs.map(rfq=><option key={rfq.id} value={rfq.id}>{rfq.title}</option>)}</select></Field>{rfq&&<p className="muted">This RFQ uses {rfq.currency}. Match each row above; quantities, units and currency must agree. If the source uses different units or currency, explicitly review and adjust each price before importing. No conversion is automatic.</p>}<Field label="Reviewed offer currency"><select value={currency} onChange={event=>setCurrency(event.target.value)}><option value="">Review source currency…</option>{['USD','GBP','EUR','AUD','SGD','HKD','CNY','JPY','CAD','NZD','CHF'].map(value=><option key={value}>{value}</option>)}</select></Field><div className="form-grid"><Field label="Lead time (days)"><input type="number" min="0" value={leadDays} onChange={event=>setLeadDays(event.target.value)}/></Field><Field label="Payment terms"><input value={terms} onChange={event=>setTerms(event.target.value)} placeholder="As stated in your offer"/></Field></div><Field label="Public quotation notes"><textarea rows={2} value={notes} onChange={event=>setNotes(event.target.value)}/></Field>{!rfqs.length&&<p className="muted">You need an invitation to an open RFQ before importing a quote. You can still review this document and discuss it with your assistant.</p>}</>:<><Field label="Request title"><input value={title} onChange={event=>setTitle(event.target.value)}/></Field><div className="form-grid"><Field label="Currency"><select value={currency} onChange={event=>setCurrency(event.target.value)}><option value="">Review source currency…</option>{['USD','GBP','EUR','AUD','SGD','HKD','CNY','JPY','CAD','NZD','CHF'].map(value=><option key={value}>{value}</option>)}</select></Field><Field label="Deadline (optional)"><input type="date" value={deadline} onChange={event=>setDeadline(event.target.value)}/></Field></div><details className="ingest-invite"><summary>Choose suppliers now (optional)</summary><div className="ingest-supplier-options">{(workspace.contacts || []).filter(contact=>contact.role==='supplier').map(contact=><label key={contact.id}><input type="checkbox" checked={suppliers.includes(contact.id)} onChange={event=>setSuppliers(event.target.checked?[...suppliers,contact.id]:suppliers.filter(id=>id!==contact.id))}/>{contact.company || contact.name}</label>)}</div></details></>}
      {imported?<div className="ingest-success"><Icon name="check"/><div><strong>Private {supplier?'quote':'RFQ'} draft created</strong><p>The original document and reviewed extraction are linked in your account history.</p></div><Button onClick={()=>{const action=imported.action;app.navigate(action.input.view,action.input)}}>Open draft</Button></div>:<div className="form-actions"><span className="muted">{items.length} items · You review before any commitment</span><Button icon="arrow" busy={busy==='import'} disabled={!!busy||readOnly||!items.length||!!missing||!currency||(supplier&&!rfqId)} onClick={makeDraft}>Create private {supplier?'quote':'RFQ'} draft</Button></div>}
    </section>
  </>
}

function SourceRows({rows,columns}) {return rows.length?<div className="table-scroll ingest-source-rows"><table><thead><tr><th>Source</th>{columns.map(column=><th key={column}>{column}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}><td className="muted">{row._file || row._sheet || index+1}</td>{columns.map(column=><td key={column}>{String(row[column]??'')}</td>)}</tr>)}</tbody></table></div>:<p className="muted">This source contains text rather than a recognized table. Use Source text or AI extraction.</p>}

function ParserSettings({settings,engines,close,saved}) {
  const app=useApp(),[values,setValues]=useState(settings),[busy,setBusy]=useState(false),[error,setError]=useState(''),touched=useRef(new Set())
  const set=(key,value)=>{touched.current.add(key);setValues(previous=>({...previous,[key]:value}))}
  async function submit(event){event.preventDefault();setBusy(true);setError('');try{await api('/settings/ingestion',{method:'PATCH',body:{values:Object.fromEntries([...touched.current].map(key=>[key,values[key]]))}});saved();close();app.notify('Ingestion preferences saved.')}catch(error){setError(error.message)}finally{setBusy(false)}}
  return <Modal title="Document ingestion settings" description="Your choices apply to future uploads and extraction runs." onClose={close}><form onSubmit={submit}><ErrorNotice error={error}/><Field label="Default engine"><select value={values.defaultEngine || 'auto'} onChange={event=>set('defaultEngine',event.target.value)}><option value="auto">Automatic</option>{engines.map(engine=><option key={engine.id} value={engine.id}>{engine.name}</option>)}</select></Field><div className="form-grid"><Field label="Default currency"><select value={values.currency} onChange={event=>set('currency',event.target.value)}>{['USD','GBP','EUR','AUD','SGD','HKD','CNY','JPY','CAD','NZD','CHF'].map(value=><option key={value}>{value}</option>)}</select></Field><Field label="Maximum rows"><input type="number" min="1" max="10000" value={values.maxRows} onChange={event=>set('maxRows',Number(event.target.value))}/></Field></div><Field label="CSV delimiter"><select value={values.delimiter} onChange={event=>set('delimiter',event.target.value)}><option value="auto">Detect automatically</option><option value=",">Comma</option><option value=";">Semicolon</option><option value={'\t'}>Tab</option><option value="|">Pipe</option></select></Field><Field label="AI extraction instructions"><textarea rows={4} value={values.aiInstructions} onChange={event=>set('aiInstructions',event.target.value)}/></Field><div className="form-actions"><Button variant="secondary" onClick={close}>Cancel</Button><Button type="submit" busy={busy}>Save settings</Button></div></form></Modal>
}

registry.page('ingestion',{component:Ingestion,icon:'file'})
