import assert from 'node:assert/strict'
import {mkdirSync,mkdtempSync,writeFileSync} from 'node:fs'
import {resolve,join} from 'node:path'
import {Context} from '../../../../host/node_modules/cordis/lib/index.js'
import * as web from '../../webui/code/product-server.mjs'
import * as store from '../../workspace-store/code/index.mjs'
import * as actions from '../code/index.mjs'
import {payloadHash} from '../code/provenance.mjs'
const ctx=new Context(),fibers=[],users=[{id:'review-owner',role:'contractor',name:'Reviewer'},{id:'other-owner',role:'supplier',name:'Other'}],[user,other]=users,checks=[];mkdirSync('tmp',{recursive:true});const root=mkdtempSync(resolve('tmp/review-provenance-')),mount=async(module,config)=>{const fiber=await ctx.plugin(module,config);assert.equal(fiber.state,2);fibers.push(fiber);return fiber}
try{
 await mount(web,{port:0});await mount(store,{root});await mount({name:'provenance-accounts',apply(inner){inner.provide('accounts',{list:()=>users,get:id=>users.find(row=>row.id===id),can:()=>true,resolve:req=>users.find(row=>row.id===req.headers['x-fixture-user'])})}});let owner=await mount(actions);let executions=0;const register=()=>ctx.actions.register({kind:'fixture.commit',label:'Fixture commitment',execute:async()=>{executions++;return{ok:true}}});register();const address=await ctx.web.listen(),base=`http://127.0.0.1:${address.port}/quotagent/api`,request=async(path,actor=user)=>{const response=await fetch(base+path,{headers:{'x-fixture-user':actor.id}});return{status:response.status,value:await response.json()}}
 await ctx.store.put(user.id,'fixture-records',{id:'original',title:'Frozen basis',revision:1,amount:15},{event:'fixture/source-recorded'});await ctx.store.put(other.id,'fixture-records',{id:'foreign',privateCost:999},{event:'fixture/private-recorded'});const event=ctx.store.events(user.id).at(-1),ref={realm:user.id,seq:event.seq,hash:event.entry_hash},input={amount:15,preview:{sources:[{label:'Frozen source',collection:'fixture-records',recordId:'original',ref,link:{view:'rfqs',rfqId:'original',prompt:'must not enter URL'}}],risks:[{id:'terms',message:'Delivery date remains unconfirmed.',severity:'warning',source:'Owning fixture assessment'}]}}
 const proposal=await ctx.actions.propose(user,{kind:'fixture.commit',title:'Review frozen fixture',input,source:{kind:'human',plugin:'fixture'}});assert.equal(executions,0);const detail=(await request('/actions/'+proposal.id+'/provenance')).value.provenance;assert.equal(detail.payload.recorded,payloadHash(input));assert.equal(detail.payload.matches,true);assert.equal(detail.references[0].ref.hash,ref.hash);assert.equal(detail.references[0].link.prompt,undefined);assert.equal(detail.risks.flags[0].message,input.preview.risks[0].message);assert.equal(detail.proposal.type,'actions/proposed');checks.push('Actual ledger proposal captures the exact source event, declared owner risk and canonical payload hash without executing the action')
 await ctx.store.put(user.id,'fixture-records',{id:'original',title:'Later changed basis',revision:2,amount:800},{event:'fixture/source-changed'});await ctx.store.put(user.id,'review-actions',{...proposal,provenance:{...proposal.provenance,references:[]}},{event:'fixture/altered-derived-provenance'});const opened=await request('/actions/'+proposal.id+'/provenance/0');assert.equal(opened.value.event.body.record.amount,15);assert.equal(opened.value.event.entry_hash,ref.hash);assert.equal((await request('/actions/'+proposal.id+'/provenance/proposal')).value.event.body.record.id,proposal.id);checks.push('Source inspection opens the original exact event after the current business record changes, and the original proposal remains navigable')
 const foreign=ctx.store.events(other.id).at(-1);await assert.rejects(ctx.actions.propose(user,{kind:'fixture.commit',input:{preview:{sources:[{ref:{realm:other.id,seq:foreign.seq,hash:foreign.entry_hash}}]}}}),/outside/);await assert.rejects(ctx.actions.propose(user,{kind:'fixture.commit',input:{preview:{sources:[{recordId:'wrong-record',ref}]}}}),/different record/);await assert.rejects(ctx.actions.propose(user,{kind:'fixture.commit',input:{preview:{sources:[{ref:{...ref,hash:'wrong'}}]}}}),/no longer matches/);assert.equal((await request('/actions/'+proposal.id+'/provenance',other)).status,404);assert.equal((await request('/actions/'+proposal.id+'/provenance/777')).status,404);checks.push('Other-account actions, foreign-realm sources, wrong records, changed hashes and arbitrary source keys refuse before disclosure or execution')
 const missing=await ctx.actions.propose(user,{kind:'fixture.commit',input:{description:'No risk owner'}});assert.equal(ctx.actions.provenance(user,missing.id).risks.state,'not-assessed');assert.equal(ctx.actions.provenance(user,missing.id).references.length,0);const noFlags=await ctx.actions.propose(user,{kind:'fixture.commit',input:{preview:{risks:[]}}});assert.equal(ctx.actions.provenance(user,noFlags.id).risks.state,'supplied');assert.deepEqual(ctx.actions.provenance(user,noFlags.id).risks.flags,[]);const historical={...proposal,id:'historical-action'};delete historical.provenance;await ctx.store.put(user.id,'review-actions',historical,{event:'actions/proposed'});assert.equal(ctx.actions.provenance(user,historical.id).capture,'historical-unmeasured');assert.deepEqual(ctx.actions.provenance(user,historical.id).references,[]);checks.push('Missing risk assessment, explicitly empty owner flags and historical uncaptured references stay distinct; historical input IDs never resolve to newer source records')
 await ctx.store.put(user.id,'review-actions',{...missing,input:{description:'Altered after proposal'}},{event:'fixture/changed-review-input'});assert.equal(ctx.actions.provenance(user,missing.id).payload.matches,false);await owner.dispose();owner=await mount(actions);register();assert.equal(ctx.actions.source(user,proposal.id,'0').event.body.record.amount,15);assert.equal(ctx.actions.provenance(user,proposal.id).payload.matches,true);assert.equal(executions,0);await owner.dispose();assert.equal((await request('/actions/'+proposal.id+'/provenance')).status,404);checks.push('Payload mismatch is explicit; captured source survives native reload; provenance routes dispose and no inspection executes any action')
 const report={ok:true,root,checks};writeFileSync(join(root,'report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2))
}finally{for(const fiber of fibers.reverse())await fiber.dispose()}
