import './settings.css'
import {ConfigurationFiles,ConfigurationDiff} from './configuration.jsx'
import React, { useState, useEffect, useRef } from 'react'
import { registry, useApp, useResource, api, Icon, Button, Badge, Field, PageHeader, Modal, Empty, ErrorNotice, Loading } from '../../webui/client/core.jsx'

export function AvailableSettings() {
  const app=useApp(),resource=useResource('/settings',{settings:[]}),[selected,setSelected]=useState(null)
  return <><div className="studio-settings-intro"><h2>{app.user.role==='admin' ? 'Application and account settings' : 'Settings for your account'}</h2><p>{app.user.role==='admin' ? 'Manage shared defaults and your own account connections. Connection credentials belong only to the signed-in account.' : 'Choose your AI provider, assistant preferences, and other plugin options. Your changes apply only to your account.'}</p></div><ErrorNotice error={resource.error} retry={resource.reload}/>{resource.loading ? <Loading/> : <div className="studio-settings-cards">{resource.data.settings.map(setting=><section className="card" key={setting.id}><div className="section-heading"><span className="extension-icon"><Icon name="settings" size={22}/></span><Badge status={setting.hasOverrides ? 'accent' : 'neutral'}>{setting.hasOverrides ? 'Customized' : 'Using defaults'}</Badge></div><h3>{setting.name || setting.id}</h3><p>{setting.description || 'Configure the way this plugin works for you.'}</p><div className="studio-setting-summary"><span>{setting.fields?.length || 0} settings</span>{setting.configuredSecrets?.length>0 && <span><Icon name="check" size={13}/> Credentials configured</span>}</div><Button variant="secondary" icon="settings" onClick={()=>setSelected({id:setting.id,name:setting.name})}>Configure</Button></section>)}</div>}{!resource.loading && !resource.data.settings.length && <Empty icon="settings" title="No settings available">Your installed plugins will appear here when they expose configurable options.</Empty>}{selected && <PluginSettings key={selected.id} plugin={selected} onClose={()=>setSelected(null)}/>}</>
}

export function PluginSettings({plugin,onClose,context:initialContext,scope:initialScope}) {
  const app=useApp(),[context,setContext]=useState(initialContext||Object.fromEntries(['workspaceId','projectId','sectionId'].filter(key=>app.context[key]).map(key=>[key,app.context[key]]))),[scope,setScope]=useState(initialScope||''),resource=useResource(`/settings/${encodeURIComponent(plugin.id)}?context=${encodeURIComponent(JSON.stringify(context))}&scope=${encodeURIComponent(scope)}`,{fields:[],values:{},configuredSecrets:[]}),[preview,setPreview]=useState(null)
  const ignoredData=useRef(null)
  const [draft,setDraft]=useState(null),[touched,setTouched]=useState(()=>new Set()),[clearSecrets,setClearSecrets]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false)
  useEffect(()=>{if(draft===null && resource.data.id && resource.data!==ignoredData.current && !resource.loading && !resource.error)setDraft({...resource.data.values})},[resource.data,resource.loading,resource.error,draft])
  const data=resource.data
  const set=(key,value)=>{setDraft(v=>({...v,[key]:value}));setTouched(keys=>new Set([...keys,key]));setSaved(false);setPreview(null)}
  async function reset(){setBusy(true);setError('');try{const result=await api(`/settings/${encodeURIComponent(plugin.id)}`,{method:'PATCH',body:{reset:true,scope,context}});setDraft({...result.values});setTouched(new Set());setClearSecrets([]);setSaved(true);app.refresh();app.notify('Default settings restored.')}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function save(event){event.preventDefault();setBusy(true);setError('');try{const values=Object.fromEntries([...touched].map(key=>[key,draft[key]]));for(const field of data.fields)if(field.type==='password' && !values[field.key])delete values[field.key];const result=await api(`/settings/${encodeURIComponent(plugin.id)}`,{method:'PATCH',body:{values,clearSecrets,scope,context,...(preview?{previewId:preview.previewId}:{})}});const next=result.fields ? result : await resource.reload();if(next?.values)setDraft({...next.values});setTouched(new Set());setClearSecrets([]);setSaved(true);setPreview(null);resource.reload();app.refresh();app.notify(result.message || 'Plugin settings saved.')}catch(e){setError(e.message)}finally{setBusy(false)}}
  return <Modal title={`${plugin.name || plugin.id} settings`} description={`Editing ${data.target?.label||'plugin settings'}. Leave credentials blank to keep the saved value.`} wide onClose={onClose}>{data.description && <p className="muted" style={{marginBottom:20}}>{data.description}</p>}<ErrorNotice error={error || resource.error} retry={resource.error ? resource.reload : undefined}/>{draft===null ? resource.loading && <Loading/> : <form onSubmit={save}>{data.availableScopes?.length>1&&<Field label="Configuration scope"><select value={JSON.stringify({scope:data.target?.scope,context:data.target?.context||{}})} onChange={event=>{const next=JSON.parse(event.target.value);ignoredData.current=resource.data;setScope(next.scope);setContext(next.context);setDraft(null);setTouched(new Set());setClearSecrets([]);setSaved(false);setPreview(null)}}>{data.availableScopes.map((item,index)=><option key={index} value={JSON.stringify({scope:item.scope,context:item.context||{}})}>{item.scope} · {item.label}</option>)}</select></Field>}{saved && <div className="studio-saved" role="status"><Icon name="check" size={16}/> Settings saved.</div>}{data.fields?.length ? <div className="studio-settings-fields">{data.fields.map(field=>{
    const value=draft[field.key],configured=data.configuredSecrets?.includes(field.key),cleared=clearSecrets.includes(field.key),origin=data.provenance?.[field.key],originLabel=origin?`${origin.layer}${origin.scopeLabel?' · '+origin.scopeLabel:''} · ${origin.source}`:''
    if(field.type==='boolean')return <label className="studio-boolean-field" key={field.key}><input type="checkbox" checked={!!value} onChange={e=>set(field.key,e.target.checked)}/><span><strong>{field.label}</strong>{field.description && <small>{field.description}</small>}<small>{originLabel}</small></span></label>
    return <div key={field.key}><Field label={field.label} hint={field.description}>{field.type==='select' ? <select value={value ?? ''} onChange={e=>set(field.key,e.target.value)}>{(field.options || []).map(option=>{const optionValue=typeof option==='object' ? option.value : option;return <option key={optionValue} value={optionValue}>{typeof option==='object' ? option.label || option.value : option}</option>})}</select> : field.type==='textarea' ? <textarea rows={5} value={value ?? ''} onChange={e=>set(field.key,e.target.value)}/> : field.type==='color' ? <div className="studio-color-control"><input type="color" aria-label={`${field.label} picker`} value={value || '#ffffff'} onChange={e=>set(field.key,e.target.value)}/><input aria-label={`${field.label} hex value`} value={value || ''} onChange={e=>set(field.key,e.target.value)}/></div> : <input type={field.type==='password' ? 'password' : field.type==='number' ? 'number' : 'text'} min={field.min} max={field.max} step={field.type==='number' ? 'any' : undefined} autoComplete={field.type==='password' ? 'new-password' : undefined} disabled={cleared||field.type==='password'&&!['account','global'].includes(data.target?.scope)} value={value ?? ''} placeholder={field.type==='password' && configured ? 'Configured — leave blank to keep' : field.placeholder || ''} onChange={e=>set(field.key,field.type==='number' && e.target.value!=='' ? Number(e.target.value) : e.target.value)}/>}</Field>{origin&&<details className="setting-origin"><summary>Value source: {originLabel}</summary><p>{origin.reference}{origin.patchId?` · patch ${origin.patchId}`:''}</p>{origin.shadowed?.map((item,index)=>item&&<p key={index}>Earlier: {item.layer} · {item.source} · {item.reference}</p>)}</details>}{field.type==='password' && configured && ['account','global'].includes(data.target?.scope) && <label className="studio-secret-clear"><input type="checkbox" checked={cleared} onChange={e=>{setClearSecrets(v=>e.target.checked ? [...v,field.key] : v.filter(key=>key!==field.key));setSaved(false);setPreview(null)}}/>Clear the saved {field.label.toLowerCase()}</label>}</div>
  })}</div> : <p className="muted">This plugin does not expose configurable settings.</p>}{preview&&<ConfigurationDiff preview={preview}/>}<div className="form-actions">{data.fields?.length>0&&<Button variant="ghost" busy={busy} onClick={async()=>{setBusy(true);setError('');try{const values=Object.fromEntries([...touched].filter(key=>data.fields.find(field=>field.key===key)?.type!=='password'||draft[key]).map(key=>[key,draft[key]]));setPreview(await api('/settings/preview',{method:'POST',body:{changes:[{id:plugin.id,values,clearSecrets,scope,context}]}}))}catch(error){setError(error.message)}finally{setBusy(false)}}}>Preview changes</Button>}{data.hasOverrides && <Button variant="ghost" busy={busy} onClick={reset}>{data.scope==='personal' ? 'Use default settings' : 'Restore defaults'}</Button>}<Button variant="secondary" onClick={onClose}>Close</Button>{data.fields?.length>0 && <Button type="submit" busy={busy} icon="check">Save settings</Button>}</div></form>}</Modal>
}
function SettingsPage(){const app=useApp(),[selected,setSelected]=useState(app.context.schema?{id:app.context.schema}:null);return <><PageHeader eyebrow="YOUR PLUGIN PREFERENCES" title="Plugin settings">Set the options that make your plugins work for you.</PageHeader><ConfigurationFiles/><AvailableSettings/>{selected&&<PluginSettings plugin={selected} context={Object.fromEntries(['workspaceId','projectId','sectionId'].filter(key=>app.context[key]).map(key=>[key,app.context[key]]))} scope={app.context.scope} onClose={()=>{setSelected(null);app.setContext({schema:null})}}/>}</>}
registry.page('plugin-settings',{component:SettingsPage,icon:'settings',linkKeys:['schema','scope','workspaceId','projectId','sectionId']})
