import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {createServer} from 'node:net'
import {once} from 'node:events'
import {mkdirSync,mkdtempSync,writeFileSync} from 'node:fs'
import {resolve,join} from 'node:path'
import * as store from '../../workspace-store/code/index.mjs'
import * as settings from '../../settings/code/index.mjs'
import * as files from '../../file-store/code/index.mjs'
import * as notifications from '../../notifications/code/index.mjs'
import * as actions from '../../action-center/code/index.mjs'
import * as mail from '../code/product.mjs'
import {localServices} from './product-fixtures.mjs'
const require=createRequire(new URL('../../../../host/package.json',import.meta.url)),{Context}=require('cordis'),ctx=new Context(),fibers=[],routes=[],users=[{id:'digest-owner',role:'contractor'},{id:'digest-other',role:'supplier'}],user=users[0],servers=await localServices(),checks=[];let clock=Date.now(),lostMessages=0
const lost=createServer(socket=>{socket.setEncoding('utf8');socket.write('220 Fixture receipt-loss SMTP\r\n');let buffer='',data=false;socket.on('error',()=>{});socket.on('data',chunk=>{buffer+=chunk;let end;while((end=buffer.indexOf('\r\n'))>=0){const line=buffer.slice(0,end);buffer=buffer.slice(end+2);if(data){if(line==='.') {lostMessages++;socket.destroy()}continue}if(/^EHLO|^HELO/.test(line))socket.write('250-fixture.invalid\r\n250 SIZE 1000000\r\n');else if(/^DATA/.test(line)){data=true;socket.write('354 Continue\r\n')}else if(/^QUIT/.test(line)){socket.end('221 Goodbye\r\n')}else socket.write('250 OK\r\n')}})});lost.listen(0,'127.0.0.1');await once(lost,'listening')
mkdirSync('tmp',{recursive:true});const root=mkdtempSync(resolve('tmp/mail-digest-')),mount=async(module,config)=>{const fiber=await ctx.plugin(module,config);assert.equal(fiber.state,2);fibers.push(fiber);return fiber}
try{await mount({name:'digest-fixture',apply(child){child.provide('accounts',{list:()=>users,get:id=>users.find(row=>row.id===id),can:()=>true});child.provide('web',{route:(...args)=>{routes.push(args);return()=>routes.splice(routes.indexOf(args),1)},contribute:()=>()=>{}});child.provide('ingestion',{});child.provide('assistant',{tool:()=>()=>{}})}});await mount(store,{root});await mount(settings);await mount(files);await mount(notifications);await mount(actions);let mailFiber=await mount(mail,{digest:{clock:()=>clock,poll:false}})
 await ctx.settings.save(user,'mail',{values:{enabled:true,fromName:'Fixture',fromAddress:'buyer@fixture.invalid',imapHost:'127.0.0.1',imapPort:servers.imapPort,imapSecurity:'plain',imapUser:'fixture',imapPassword:'private-imap-password',smtpHost:'127.0.0.1',smtpPort:servers.smtpPort,smtpSecurity:'plain',smtpUser:'fixture',smtpPassword:'private-smtp-password'}});assert.equal((await ctx.mail.sync(user)).imported,1);for(let i=0;i<4;i++)await ctx.notifications.push(user,{title:'PRIVATE_COST_928.37',body:'PRIVATE_MESSAGE_DO_NOT_FORWARD',level:i===0?'warning':'info',dedupeKey:'digest-'+i,source:{pluginId:'fixture'}})
 assert.equal(ctx.mailDigest.preview(user).enabled,false);await ctx.mailDigest.poll();assert.equal(servers.smtpMessages.length,0);assert.equal(ctx.mailDigest.preview(users[1]).eligible,0);checks.push('Actual IMAP arrival creates eligible in-app activity; digest defaults off and accounts remain isolated')
 await ctx.settings.save(user,'mail-digest',{values:{enabled:true,recipient:'digest@fixture.invalid',maxItems:2,intervalMinutes:1,workspaceUrl:'https://quotagent.fixture.invalid/'}});const initial=ctx.mailDigest.preview(user);assert.equal(initial.count,2);assert.equal(initial.remaining,3);await assert.rejects(ctx.mailDigest.send(user,{fingerprint:initial.fingerprint}),/confirm/);assert.equal(servers.smtpMessages.length,0);const sent=await Promise.all([ctx.mailDigest.send(user,{confirmed:true,fingerprint:initial.fingerprint}),ctx.mailDigest.send(user,{confirmed:true,fingerprint:initial.fingerprint})]);assert.ok(sent.every(row=>row.ok));assert.equal(servers.smtpMessages.length,1);assert.equal(sent[0].digest.id,sent[1].digest.id);const raw=servers.smtpMessages[0].source.toString();for(const forbidden of ['PRIVATE_COST','PRIVATE_MESSAGE','private-imap-password','private-smtp-password'])assert.ok(!raw.includes(forbidden));assert.match(raw,/2 unread activity/);assert.match(raw,/digest@fixture.invalid/);assert.equal(ctx.mailDigest.preview(user).blocked,'The minimum delivery interval has not elapsed.');checks.push('Exact confirmed preview sends one real SMTP batch, capped at2, carries fixed counts/link only and records recipient/receipt')
 await ctx.mailDigest.poll();assert.equal(servers.smtpMessages.length,1);clock+=60_001;await ctx.settings.save(user,'mail-digest',{values:{automatic:true}});await ctx.mailDigest.poll();assert.equal(servers.smtpMessages.length,2);clock+=60_001;await ctx.mailDigest.poll();assert.equal(servers.smtpMessages.length,3);clock+=60_001;await ctx.mailDigest.poll();assert.equal(servers.smtpMessages.length,3);assert.equal(ctx.mailDigest.preview(user).eligible,0);checks.push('Separate automatic opt-in drains bounded batches with throttle, durable deduplication and no empty send')
 await ctx.notifications.push(user,{title:'New receipt-loss activity',dedupeKey:'receipt-loss',source:{pluginId:'fixture'}});await ctx.settings.save(user,'mail',{values:{smtpPort:lost.address().port,smtpUser:''}});await ctx.mailDigest.poll();assert.equal(lostMessages,1);assert.equal(ctx.mailDigest.history(user)[0].status,'uncertain');clock+=60_001;await ctx.mailDigest.poll();assert.equal(lostMessages,1);await mailFiber.dispose();assert.ok(!routes.some(([,path])=>path.startsWith('/mail-digest')));mailFiber=await mount(mail,{digest:{clock:()=>clock,poll:false}});await ctx.mailDigest.poll();assert.equal(lostMessages,1);assert.equal(ctx.mailDigest.preview(user).eligible,0);checks.push('Actual SMTP DATA accepted then connection lost: delivery becomes uncertain and never automatically retries, including native reload')
 const existing=ctx.mailDigest.history(user)[0];await ctx.store.put(user.id,'mail-digests',{...existing,id:'interrupted',status:'sending',deliveryKeys:['synthetic-interruption:info']},{actor:'fixture',event:'fixture/interrupted-digest'});await mailFiber.dispose();mailFiber=await mount(mail,{digest:{clock:()=>clock,poll:false}});assert.equal(ctx.mailDigest.history(user).find(row=>row.id==='interrupted').status,'uncertain');await mailFiber.dispose();assert.throws(()=>ctx.settings.get(user,'mail-digest'),/registered/);checks.push('Unfinished persisted dispatch recovers as uncertain; child unload removes preferences, routes, timers and transport')
 const report={ok:true,root,smtpAccepted:servers.smtpMessages.length,lostReceiptDispatches:lostMessages,checks};writeFileSync(join(root,'report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2))
}finally{for(const fiber of fibers.reverse())await fiber.dispose();await servers.close();await new Promise(resolve=>lost.close(resolve))}
