import React,{useState,useEffect} from 'react'
import {registry,useApp,useResource,api,Icon,Button,Badge,Field,PageHeader,ErrorNotice,Empty,Loading,Modal} from '../../webui/client/core.jsx'
import {PluginSettings} from '../../settings/client/settings.jsx'
import './mail.css'
const stamp=value=>value?new Date(value).toLocaleString():'Not checked yet'
const labelStatus=value=>({'partially-sent':'Partly accepted',pending:'Awaiting approval',uncertain:'Check delivery',sending:'Sending'}[value]||value)
const fileBase64=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('Could not read attachment.'));reader.readAsDataURL(file)})
function Mail(){
  const app=useApp(),resource=useResource('/mail',{status:{},messages:[],files:[]}),[folder,setFolder]=useState('inbox'),[selected,setSelected]=useState(app.context.messageId||''),[search,setSearch]=useState('')
  const [settingsOpen,setSettingsOpen]=useState(false),[compose,setCompose]=useState(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[test,setTest]=useState(null)
  const {status,messages,files}=resource.data,readOnly=app.user.permissions?.includes('workspace:read-only')
  const current=messages.find(message=>message.id===selected)
  useEffect(()=>{if(app.context.messageId)setSelected(app.context.messageId)},[app.context.messageId])
  const filtered=messages.filter(message=>folder==='drafts'?['draft','pending','failed','sending','uncertain'].includes(message.status):folder==='sent'?['sent','partially-sent'].includes(message.status):message.direction==='inbound')
    .filter(message=>`${message.subject} ${message.from} ${message.to?.join(' ')} ${message.body}`.toLowerCase().includes(search.toLowerCase()))
  const task=async(name,fn)=>{setBusy(name);setError('');try{return await fn()}catch(error){setError(error.message)}finally{setBusy('')}}
  const synchronize=()=>task('sync',async()=>{const result=await api('/mail/sync',{method:'POST',body:{}});await resource.reload();app.refresh();app.notify(`${result.imported} email${result.imported===1?'':'s'} imported.`)})
  const connect=()=>task('test',async()=>{const result=await api('/mail/test',{method:'POST',body:{kind:'both'}});setTest(result.result);await resource.reload()})
  const select=message=>{setSelected(message.id);if(!message.read&&message.direction==='inbound'&&!readOnly)api(`/mail/${message.id}/read`,{method:'POST',body:{}}).then(resource.reload).catch(()=>{})}
  const ingest=(message,fileId)=>task(`ingest:${fileId||message.id}`,async()=>{const result=await api(`/mail/${message.id}/ingest`,{method:'POST',body:{fileId}});app.navigate('ingestion',result.action.input)})
  const reply=message=>setCompose({replyToId:message.id,to:(message.replyTo?.length?message.replyTo:message.fromAddresses||[]).join(', '),subject:`Re: ${message.subject.replace(/^Re:\s*/i,'')}`,body:'',attachmentIds:[]})
  return <><PageHeader eyebrow="YOUR CONNECTED INBOX" title="Keep the conversation moving." actions={<><Button variant="secondary" icon="settings" onClick={()=>setSettingsOpen(true)}>Email settings</Button><Button icon="plus" disabled={readOnly} onClick={()=>setCompose({to:'',subject:'',body:'',attachmentIds:[]})}>Compose email</Button></>}>Read live email, turn attachments into useful line items, and prepare replies with your AI teammate.</PageHeader>
    <ErrorNotice error={error||resource.error} retry={resource.error?resource.reload:undefined}/>
    <section className="card mail-connection"><div><span className={`mail-connection-dot ${status.enabled?'on':''}`}/><strong>{status.enabled?status.fromAddress||'Email connection enabled':'Connect your own email'}</strong><p>{status.enabled?`Last inbox check: ${stamp(status.lastSyncAt)}${status.autoSync?' · Automatic checks on':''}`:'Set your IMAP and SMTP details. This account’s mailbox and credentials stay separate from other accounts.'}</p>{status.lastError&&<p className="mail-warning">{status.lastError}</p>}</div><div className="mail-connection-actions"><Button variant="secondary" disabled={!status.enabled||!!busy||readOnly} busy={busy==='test'} onClick={connect}>Test connection</Button><Button icon="refresh" disabled={!status.enabled||!!busy||readOnly} busy={busy==='sync'||status.syncing} onClick={synchronize}>Sync email</Button></div></section>
    {test&&<div className="mail-test-result" role="status">{Object.entries(test).map(([kind,result])=><p key={kind}><strong>{kind.toUpperCase()}:</strong> {result.ok?'Connected and authenticated. No email was sent.':result.error}{result.mailboxes?.length>0&&<span> Folders: {result.mailboxes.map(folder=>folder.path).join(', ')}</span>}</p>)}</div>}
    {status.warnings?.length>0&&<div className="mail-warnings">{status.warnings.map((warning,i)=><p key={i}>{warning}</p>)}</div>}
    <div className="mail-layout"><section className="card mail-list"><div className="tabs"><button className={folder==='inbox'?'active':''} onClick={()=>setFolder('inbox')}>Inbox</button><button className={folder==='drafts'?'active':''} onClick={()=>setFolder('drafts')}>Drafts</button><button className={folder==='sent'?'active':''} onClick={()=>setFolder('sent')}>Sent</button></div><input className="mail-search" aria-label="Search email" placeholder="Search this mailbox…" value={search} onChange={event=>setSearch(event.target.value)}/>{resource.loading?<Loading/>:filtered.length?filtered.map(message=><button className={`mail-list-item ${selected===message.id?'selected':''}`} key={message.id} onClick={()=>select(message)}><span><strong>{message.direction==='inbound'?message.from:message.to?.join(', ')||'No recipient'}</strong><small>{stamp(message.receivedAt||message.createdAt)}</small></span><b>{message.subject||'(No subject)'}</b><p>{message.body.slice(0,120)}</p><span><Badge status={message.status==='pending'?'accent':'neutral'}>{labelStatus(message.status)}</Badge>{message.attachments?.length>0&&<small>{message.attachments.length} attachment(s)</small>}</span></button>):<Empty icon="mail" title={status.enabled?'No messages here yet':'Your inbox starts here'}>{status.enabled?'Sync your mailbox, or compose a private draft.':'Open Email settings, configure your provider, then test and sync.'}</Empty>}</section>
      <section className="card mail-reader">{current?<><div className="mail-reader-heading"><div><Badge>{labelStatus(current.status)}</Badge><h2>{current.subject||'(No subject)'}</h2><p><b>From:</b> {current.from||status.fromAddress||'Your configured sender'}</p><p><b>To:</b> {current.to?.join(', ')||'No recipient'}</p>{current.cc?.length>0&&<p><b>Cc:</b> {current.cc.join(', ')}</p>}<p className="muted">{stamp(current.receivedAt||current.createdAt)}</p></div></div>
        <div className="mail-reader-actions">{current.direction==='inbound'&&<Button variant="secondary" disabled={readOnly} onClick={()=>reply(current)}>Reply</Button>}{['draft','pending','failed'].includes(current.status)&&<Button variant="secondary" disabled={readOnly} onClick={()=>setCompose({...current,to:current.to.join(', '),cc:current.cc?.join(', ')||'',bcc:current.bcc?.join(', ')||'',attachmentIds:current.attachments.map(file=>file.id)})}>Edit draft</Button>}{current.actionId&&<Button variant="secondary" onClick={()=>app.navigate('approvals',{actionId:current.actionId})}>Open send review</Button>}<Button variant="ghost" icon="spark" onClick={()=>app.ask(`Read my email ${current.id} using mail_read. ${current.direction==='inbound'?'Summarize the request and prepare an editable reply draft using mail_draft.':'Help improve this draft.'} Never send it without my review.`)}>Draft with AI</Button>{current.originalFileId&&<Button variant="ghost" icon="file" disabled={!!busy||readOnly} onClick={()=>ingest(current)}>Extract line items</Button>}</div>
        {current.lastError&&<ErrorNotice error={current.lastError}/>}<pre className="mail-body">{current.body||'This email has no plain-text body.'}</pre>
        {current.warnings?.length>0&&<div className="mail-warnings">{current.warnings.map((warning,i)=><p key={i}>{warning}</p>)}</div>}
        {current.attachments?.length>0&&<div className="mail-attachments"><h3>Attachments</h3>{current.attachments.map(file=><article key={file.id}><Icon name="file"/><div><strong>{file.filename}</strong><small>{Math.ceil(file.size/1024)} KB</small></div><a href={`/quotagent/api/files/${file.id}/download`} download>Download</a><Button variant="ghost" disabled={!!busy||readOnly} busy={busy===`ingest:${file.id}`} onClick={()=>ingest(current,file.id)}>Extract items</Button></article>)}</div>}
        {current.receipt&&<p className="mail-receipt">SMTP receipt: {current.receipt.accepted?.length||0} recipient(s) accepted{current.receipt.rejected?.length?` · Rejected: ${current.receipt.rejected.join(', ')}`:''}. {current.receipt.response}</p>}
      </>:<Empty icon="mail" title="Choose a conversation">Read the source, review its attachments, then decide what happens next.</Empty>}</section>
    </div>
    {settingsOpen&&<PluginSettings plugin={{id:'mail',name:'Email connection'}} onClose={()=>{setSettingsOpen(false);resource.reload()}}/>}
    {compose&&<MailComposer initial={compose} files={files} close={()=>setCompose(null)} saved={async message=>{setSelected(message.id);setFolder('drafts');await resource.reload()}}/>}
  </>
}
function MailComposer({initial,files,close,saved}){
  const app=useApp(),[draft,setDraft]=useState(initial),[available,setAvailable]=useState(files),[busy,setBusy]=useState(''),[error,setError]=useState('')
  const set=(key,value)=>setDraft(previous=>({...previous,[key]:value}))
  async function save(review=false){setBusy(review?'review':'save');setError('');try{const result=await api('/mail/draft',{method:'POST',body:{...draft}});setDraft(previous=>({...previous,id:result.message.id}));await saved(result.message);if(review){const proposal=await api(`/mail/${result.message.id}/review`,{method:'POST',body:{}});close();app.navigate('approvals',proposal.action.input)}else{app.notify('Private email draft saved.');close()}}catch(error){setError(error.message)}finally{setBusy('')}}
  async function upload(list){setBusy('upload');setError('');try{for(const file of Array.from(list)){const result=await api('/files',{method:'POST',body:{filename:file.name,mime:file.type,contentBase64:await fileBase64(file)}});setAvailable(previous=>[result.file,...previous.filter(item=>item.id!==result.file.id)]);setDraft(previous=>({...previous,attachmentIds:[...new Set([...(previous.attachmentIds||[]),result.file.id])]}))}}catch(error){setError(error.message)}finally{setBusy('')}}
  return <Modal title={initial.replyToId?'Reply by email':'Compose email'} description="Save privately, then review the exact recipients, content and attachments before sending." wide onClose={close}><ErrorNotice error={error}/><form onSubmit={event=>{event.preventDefault();save(false)}}><Field label="To"><input aria-label="Email recipients" value={draft.to||''} onChange={event=>set('to',event.target.value)} placeholder="person@example.com, team@example.com"/></Field><div className="form-grid"><Field label="Cc"><input value={draft.cc||''} onChange={event=>set('cc',event.target.value)}/></Field><Field label="Bcc"><input value={draft.bcc||''} onChange={event=>set('bcc',event.target.value)}/></Field></div><Field label="Subject"><input aria-label="Email subject" value={draft.subject||''} onChange={event=>set('subject',event.target.value)}/></Field><Field label="Message"><textarea aria-label="Email message" rows={10} value={draft.body||''} onChange={event=>set('body',event.target.value)}/></Field><details className="mail-compose-files"><summary>Attachments · {draft.attachmentIds?.length||0} selected</summary><label className="field"><span>Upload attachments</span><input aria-label="Upload email attachments" type="file" multiple onChange={event=>upload(event.target.files)} disabled={!!busy}/></label><div>{available.map(file=><label key={file.id}><input type="checkbox" checked={draft.attachmentIds?.includes(file.id)||false} onChange={event=>set('attachmentIds',event.target.checked?[...(draft.attachmentIds||[]),file.id]:(draft.attachmentIds||[]).filter(id=>id!==file.id))}/><span>{file.filename}</span></label>)}</div></details><div className="form-actions"><Button variant="secondary" onClick={close}>Cancel</Button><Button variant="secondary" type="submit" busy={busy==='save'} disabled={!!busy}>Save draft</Button><Button icon="send" busy={busy==='review'} disabled={!!busy} onClick={()=>save(true)}>Review send</Button></div></form></Modal>
}
registry.page('mail',{component:Mail,icon:'mail'})
function MailActionPreview({input}){
  return <section className="mail-action-preview"><div className="mail-preview-addresses"><p><span>From</span><strong>{input.from?.name?`${input.from.name} <${input.from.address}>`:input.from?.address}</strong></p><p><span>To</span><strong>{input.to?.join(', ')}</strong></p>{input.cc?.length>0&&<p><span>Cc</span><strong>{input.cc.join(', ')}</strong></p>}{input.bcc?.length>0&&<p><span>Bcc</span><strong>{input.bcc.join(', ')}</strong></p>}<p><span>Subject</span><strong>{input.subject}</strong></p></div><pre className="mail-body">{input.body}</pre>{input.attachments?.length>0&&<div className="mail-attachments"><h3>Files included in this email</h3>{input.attachments.map(file=><article key={file.id}><Icon name="file"/><div><strong>{file.filename}</strong><small>{Math.ceil(file.size/1024)} KB</small></div><a href={`/quotagent/api/files/${file.id}/download`} download>Review file</a></article>)}</div>}<p className="mail-preview-note">Approval sends this exact email through your configured SMTP connection. To change it, decline this action and edit the draft.</p></section>
}
registry.slot('action-preview:mail.send',MailActionPreview)
