import {fillDeclaredScope} from '../../../domain/procurement/tests/declared-scope-fixture.mjs'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {browserHarness} from '../../file-store/tests/browser-helpers.mjs'
const h=await browserHarness('attachments'),{login,nav,post,click,shot,download,checks}=h,title=`[File evidence] Request ${Date.now()}`,filename=`scope-${Date.now()}.txt`,first='Source drawing notes\n<script>This remains literal text</script>\n原始',second='Reviewed scope version 2'
const row=(page,version)=>page.locator('.artifact-row').filter({has:page.getByText(filename,{exact:true})}).filter({hasText:`Version ${version} ·`})
function pdf(){const content='BT /F1 16 Tf 30 80 Td (Reviewed fixture PDF) Tj ET',objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 120] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${content.length} >>\nstream\n${content}\nendstream`];let value='%PDF-1.4\n',offsets=[0];for(const [index,object]of objects.entries()){offsets.push(Buffer.byteLength(value));value+=`${index+1} 0 obj\n${object}\nendobj\n`}const start=Buffer.byteLength(value);value+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(offset=>String(offset).padStart(10,'0')+' 00000 n ').join('\n')}\ntrailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${start}\n%%EOF\n`;return Buffer.from(value)}
async function select(page,id){await nav(page,'Object attachments');await page.getByLabel('Attachment business object').selectOption(`rfq:${id}`);await page.getByRole('heading',{name:'Object attachments',exact:true}).last().waitFor()}
async function upload(page,buffer,name=filename,mime='text/plain'){return post(page,'attachments',()=>page.getByLabel('Upload object attachment').setInputFiles({name,mimeType:mime,buffer:Buffer.from(buffer)}))}
async function deliver(page,version,id){await row(page,version).getByRole('button',{name:'Deliver version',exact:true}).click();await page.getByLabel('Attachment recipient').selectOption('supplier-demo');await page.getByRole('checkbox',{name:'I reviewed this file and recipient.',exact:true}).check();return click(page,`attachments/${id}/deliver`,'Confirm file delivery')}
try{
 const buyer=await login('contractor@demo.local'),supplier=await login('supplier@demo.local'),other=await login('supplier2@demo.local');await nav(buyer,'Requests');await buyer.getByRole('button',{name:'New request',exact:true}).click();await buyer.getByLabel('Request title',{exact:true}).fill(title);await buyer.getByLabel('Project brief',{exact:true}).fill('Local attachment product verification; no external commitment.');await buyer.getByLabel('Item 1 description',{exact:true}).fill('Test scope panel');await buyer.locator('.supplier-options label').filter({hasText:'supplier@demo.local'}).getByRole('checkbox').check();await buyer.locator('.supplier-options label').filter({hasText:'supplier2@demo.local'}).getByRole('checkbox').check();await fillDeclaredScope(buyer);const created=await click(buyer,'workspace/create-rfq','Save request draft'),rfqId=created.rfq.id;await buyer.getByRole('button',{name:'Publish request',exact:true}).click();await click(buyer,'workspace/publish-rfq','Confirm & continue');await buyer.getByLabel('Upload object attachment').waitFor({state:'attached'})
 await select(buyer,rfqId);const one=await upload(buyer,first);await row(buyer,1).getByRole('button',{name:'Preview',exact:true}).click();assert.equal(await buyer.locator('.artifact-text').innerText(),first);await shot(buyer,'01-literal-private-preview');await buyer.getByRole('button',{name:'Close dialog',exact:true}).click();await select(supplier,rfqId);await supplier.getByRole('heading',{name:'No files on this object',exact:true}).waitFor();const sent=await deliver(buyer,1,one.attachment.id);assert.equal(sent.transfer.status,'delivered');await supplier.reload();await row(supplier,1).waitFor();const saved=await download(supplier,row(supplier,1).getByRole('link',{name:'Download version',exact:true}),'received-v1.txt');assert.equal(readFileSync(saved,'utf8'),first);await select(other,rfqId);await other.getByRole('heading',{name:'No files on this object',exact:true}).waitFor();checks.push('RFQ created and published through GUI; attachment initially private, exact recipient review delivers via real QEP, intended supplier downloads identical bytes while the other invited supplier sees no file')
 const two=await upload(buyer,second);assert.equal(two.attachment.version,2);assert.equal(two.attachment.supersedes,one.attachment.id);await deliver(buyer,2,two.attachment.id);await buyer.getByRole('checkbox',{name:'Show all versions and removal history',exact:true}).check();const old=await download(buyer,row(buyer,1).getByRole('link',{name:'Download version',exact:true}),'original-v1.txt');assert.equal(readFileSync(old,'utf8'),first);await row(buyer,2).getByRole('button',{name:'Remove version',exact:true}).click();await buyer.getByLabel('Attachment removal reason').fill('Version withdrawn after fixture review; preserve history.');await click(buyer,`attachments/${two.attachment.id}/remove`,'Confirm version removal');await supplier.reload();await row(supplier,2).getByText('removed',{exact:true}).waitFor();await supplier.getByRole('checkbox',{name:'Show all versions and removal history',exact:true}).check();assert.equal(await supplier.locator('.artifact-row').count(),2);assert.equal(readFileSync(await download(supplier,row(supplier,2).getByRole('link',{name:'Download version',exact:true}),'removed-v2.txt'),'utf8'),second);await shot(supplier,'02-received-version-history');checks.push('Same filename creates immutable superseding version, prior bytes still download, delivered removal becomes visible tombstone and counterparty history remains accessible')
 const image=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jfS8AAAAASUVORK5CYII=','base64');await upload(buyer,image,'pixel.png','image/png');let media=buyer.locator('.artifact-row').filter({has:buyer.getByText('pixel.png',{exact:true})});await media.getByRole('button',{name:'Preview',exact:true}).click();await buyer.locator('.artifact-image').waitFor();await buyer.waitForFunction(()=>document.querySelector('.artifact-image')?.naturalWidth===1);await buyer.getByRole('button',{name:'Close dialog',exact:true}).click();const pdfBytes=pdf(),pdfUpload=await upload(buyer,pdfBytes,'reviewed.pdf','application/pdf');media=buyer.locator('.artifact-row').filter({has:buyer.getByText('reviewed.pdf',{exact:true})});const rendered=buyer.waitForResponse(response=>response.url().includes(`/attachments/${pdfUpload.attachment.id}/download?inline=true`));await media.getByRole('button',{name:'Preview',exact:true}).click();const pdfResponse=await rendered;assert.equal(pdfResponse.status(),200);assert.equal(pdfResponse.headers()['content-type'],'application/pdf');assert(pdfResponse.headers()['content-disposition'].startsWith('inline;'));await buyer.locator('.artifact-pdf-canvas[data-rendered=true]').waitFor();assert(await buyer.locator('.artifact-pdf-canvas').evaluate(canvas=>{const data=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data;let dark=0;for(let i=0;i<data.length;i+=4)if(data[i]<150&&data[i+1]<150&&data[i+2]<150&&data[i+3]>0)dark++;return dark>20}));await shot(buyer,'03-pdf-browser-preview');await buyer.getByRole('button',{name:'Close dialog',exact:true}).click();await upload(buyer,Buffer.alloc(300000,97),'long-text.txt');media=buyer.locator('.artifact-row').filter({has:buyer.getByText('long-text.txt',{exact:true})});await media.getByRole('button',{name:'Preview',exact:true}).click();await buyer.getByText('Preview shows the first 262,144 of 300,000 bytes. Download the original for the complete file.',{exact:true}).waitFor();await buyer.getByRole('button',{name:'Close dialog',exact:true}).click();await upload(buyer,'Unsupported binary fixture','drawing.bin','application/octet-stream');media=buyer.locator('.artifact-row').filter({has:buyer.getByText('drawing.bin',{exact:true})});await media.getByRole('button',{name:'Preview',exact:true}).click();await buyer.getByText('This file type has no inline preview. Download the original to use a suitable viewer.',{exact:true}).waitFor();await shot(buyer,'03-unsupported-download');await buyer.getByRole('button',{name:'Close dialog',exact:true}).click();checks.push('Real PNG renders, valid PDF rendered to a bounded canvas with actual nonblank page pixels and explicit download fallback, escaped text retains literal markup, bounded text preview discloses exact truncation, unsupported media offers its original download')
 await buyer.setViewportSize({width:390,height:844});await shot(buyer,'04-mobile-versions');assert.equal(await buyer.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);await buyer.reload();await row(buyer,2).getByText('removed',{exact:true}).waitFor();checks.push('Attachment versions and removal state survive reload; narrow mobile layout has no horizontal page overflow')
 await h.finish({rfqId,title,filename,attachmentIds:[one.attachment.id,two.attachment.id]})
}catch(error){await h.fail(error);throw error}finally{await h.close()}
