import assert from 'node:assert/strict'
import {mkdirSync,mkdtempSync,writeFileSync} from 'node:fs'
import {resolve,join} from 'node:path'
import {createServer} from 'node:http'
import {mount,sourceObjects,buyer,supplier,other} from '../../file-store/tests/native-harness.mjs'
mkdirSync('tmp',{recursive:true});const root=mkdtempSync(resolve('tmp/attachments-native-')),checks=[];let a=await mount(join(root,'left')),b=await mount(join(root,'right')),server
const channel='artifact-fixture',secret='private-fixture-key',input={kind:'rfq',objectId:'rfq-fixture',filename:'scope.txt',mime:'text/plain'},file=Buffer.from('Original specification\n<script>literal text only</script>\n原始')
async function sendPackage(delivery){const value=await a.ctx.store.package(buyer.id,delivery.msgId);return value.package}
try{
 await sourceObjects(a.ctx);await sourceObjects(b.ctx);await a.ctx.store.configurePeer(buyer.id,supplier.id,channel,secret);await b.ctx.store.configurePeer(supplier.id,buyer.id,channel,secret)
 const transport=a.ctx.store.exchangeTransport({id:'manual-artifact-fixture',select:()=>({mode:'manual',channel})})
 const first=(await a.ctx.attachments.upload(buyer,{...input,buffer:file})).attachment,same=await a.ctx.attachments.upload(buyer,{...input,buffer:file});assert.equal(same.duplicate,true);assert.equal(same.attachment.id,first.id);assert.equal(a.ctx.attachments.list(buyer,input).versions.length,1);assert.equal(b.ctx.attachments.list(supplier,input).versions.length,0);assert.throws(()=>a.ctx.attachments.download(other,first.id),/not found/);assert.equal(a.ctx.attachments.preview(buyer,first.id).text,file.toString());assert.equal((await a.ctx.files.eligibility(buyer,first.fileId)).allowed,false)
 await assert.rejects(a.ctx.attachments.deliver(buyer,first.id,{recipientId:supplier.id}),/Review/);await assert.rejects(a.ctx.attachments.deliver(buyer,first.id,{recipientId:other.id,confirmed:true}),/counterparty/)
 const sent=await a.ctx.attachments.deliver(buyer,first.id,{recipientId:supplier.id,confirmed:true});assert.equal(sent.transfer.status,'queued');const original=await sendPackage(sent.transfer);assert.equal(original.resources.length,1);assert.equal(original.envelope.body.record.artifacts[0].sha256,first.sha256);assert(!JSON.stringify(a.ctx.store.events(buyer.id)).includes('contentBase64'))
 const corrupted=structuredClone(original);corrupted.resources[0].contentBase64=Buffer.from('different bytes').toString('base64');const pending=await b.ctx.store.receivePackage(supplier.id,corrupted);assert.equal(pending.resourceState,'missing');assert.equal(b.ctx.attachments.list(supplier,input).versions.length,0);assert.equal(b.ctx.files.list(supplier).length,0)
 const applied=await b.ctx.store.receivePackage(supplier.id,original);assert.equal(applied.status,'applied',JSON.stringify(applied));await a.ctx.store.receivePackage(buyer.id,applied.receipt);const incoming=b.ctx.attachments.list(supplier,input).versions[0];assert.equal(incoming.visibility,'received');assert.equal(b.ctx.attachments.download(supplier,first.id).buffer.toString(),file.toString());assert(!JSON.stringify(b.ctx.store.events(supplier.id)).includes('contentBase64'));await b.ctx.store.receivePackage(supplier.id,original);assert.equal(b.ctx.attachments.list(supplier,input).versions.length,1)
 checks.push('Private version and identical-upload retry; explicit recipient review; real two-root HMAC QEP manifest+bytes+signed receipt; tampered resource remains non-effective; no file bytes enter ledger')
 const second=(await a.ctx.attachments.upload(buyer,{...input,buffer:Buffer.from('Scope revision 2')})).attachment;assert.equal(second.version,2);assert.equal(second.supersedes,first.id);assert.equal(a.ctx.attachments.download(buyer,first.id).buffer.toString(),file.toString());const secondDelivery=await a.ctx.attachments.deliver(buyer,second.id,{recipientId:supplier.id,confirmed:true});const third=(await a.ctx.attachments.upload(buyer,{...input,buffer:Buffer.from('Scope revision 3')})).attachment,thirdDelivery=await a.ctx.attachments.deliver(buyer,third.id,{recipientId:supplier.id,confirmed:true}),thirdPackage=await sendPackage(thirdDelivery.transfer);const held=await b.ctx.store.receivePackage(supplier.id,thirdPackage);assert.equal(held.status,'held');assert.equal(b.ctx.attachments.list(supplier,input).versions.length,1)
 await b.close();b=await mount(join(root,'right'));await b.ctx.store.configurePeer(supplier.id,buyer.id,channel,secret);const preceding=await b.ctx.store.receivePackage(supplier.id,await sendPackage(secondDelivery.transfer));assert.equal(preceding.status,'applied');const released=preceding.released.find(row=>row.id===thirdDelivery.transfer.msgId);assert.equal(released.resourceState,'missing');assert.equal(b.ctx.attachments.list(supplier,input).versions.length,2);const repaired=await b.ctx.store.receivePackage(supplier.id,thirdPackage);assert.equal(repaired.status,'applied');for(const row of [preceding,repaired])await a.ctx.store.receivePackage(buyer.id,row.receipt);assert.equal(b.ctx.attachments.download(supplier,third.id).buffer.toString(),'Scope revision 3')
 checks.push('Immutable filename version chain and older downloads; out-of-order artifact manifest stays held across restart, then explicitly waits for reimported bytes before becoming an attachment')
 const removed=await a.ctx.attachments.remove(buyer,third.id,{confirmed:true,reason:'Replaced by approved drawing'});assert(removed.attachment.removedAt);const removal=await b.ctx.store.receivePackage(supplier.id,await sendPackage(removed.transfers[0]));assert.equal(removal.status,'applied');await a.ctx.store.receivePackage(buyer.id,removal.receipt);assert(b.ctx.attachments.list(supplier,input).versions.find(row=>row.id===third.id).removedAt);assert.equal(b.ctx.attachments.download(supplier,third.id).buffer.toString(),'Scope revision 3');assert.equal((await b.ctx.files.eligibility(supplier,b.ctx.attachments.list(supplier,input).versions.find(row=>row.id===third.id).fileId)).allowed,true)
 const long=(await a.ctx.attachments.upload(buyer,{...input,filename:'long.txt',buffer:Buffer.alloc(300000,97)})).attachment,preview=a.ctx.attachments.preview(buyer,long.id);assert.equal(preview.truncated,true);assert.equal(preview.shownBytes,262144);const unsupported=(await a.ctx.attachments.upload(buyer,{...input,filename:'drawing.unknown',mime:'application/octet-stream',buffer:Buffer.from('Unknown drawing')})).attachment;assert.equal(a.ctx.attachments.preview(buyer,unsupported.id).kind,'unsupported')
 checks.push('Delivered removal is a signed tombstone, preserved old file still downloads, active received reference releases only after removal; text preview exact truncation and unsupported download explanation')
 transport();server=createServer(async(req,res)=>{let text='';for await(const part of req)text+=part;try{const value=await b.ctx.store.receivePackage(supplier.id,JSON.parse(text));res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify(value))}catch(error){res.writeHead(400);res.end(JSON.stringify({error:error.message}))}});await new Promise(done=>server.listen(0,'127.0.0.1',done));const http=a.ctx.store.exchangeTransport({id:'http-artifact-fixture',select:()=>({mode:'http',channel}),handles:row=>row.channel===channel,async deliver({package:packageValue,signal}){const response=await fetch(`http://127.0.0.1:${server.address().port}/receive`,{method:'POST',body:JSON.stringify(packageValue),signal});return response.json()}});const httpFile=(await a.ctx.attachments.upload(buyer,{...input,filename:'http.txt',buffer:Buffer.from('Actual HTTP artifact')})).attachment,httpDelivery=await a.ctx.attachments.deliver(buyer,httpFile.id,{recipientId:supplier.id,confirmed:true});assert.equal(httpDelivery.transfer.status,'delivered');assert.equal(b.ctx.attachments.download(supplier,httpFile.id).buffer.toString(),'Actual HTTP artifact');http();a.ctx.store.exchangeTransport({id:'manual-artifact-remainder',select:()=>({mode:'manual',channel})})
 checks.push('Actual independent loopback HTTP transfer includes artifact bytes and verifies a signed delivery receipt; every native route/navigation/policy/guard disposes on unmount')
 for(const [kind,collection]of [['quote','quotes'],['order','orders'],['change','changes']]){const object={id:`${kind}-fixture`,rfqId:'rfq-fixture',ownerId:buyer.id,supplierId:supplier.id,status:kind==='quote'?'submitted':'active',title:`Fixture ${kind}`};for(const target of [a,b])for(const user of [buyer,supplier])await target.ctx.store.put(user.id,collection,object,{event:'fixture/readable-object',actor:'fixture'});const attached=(await a.ctx.attachments.upload(buyer,{kind,objectId:object.id,filename:`${kind}.txt`,buffer:Buffer.from(`File for ${kind}`)})).attachment;const outgoing=await a.ctx.attachments.deliver(buyer,attached.id,{recipientId:supplier.id,confirmed:true});const incoming=await b.ctx.store.receivePackage(supplier.id,await sendPackage(outgoing.transfer));assert.equal(incoming.status,'applied');await a.ctx.store.receivePackage(buyer.id,incoming.receipt);assert.equal(b.ctx.attachments.download(supplier,attached.id).buffer.toString(),`File for ${kind}`)}checks.push('Real manifest/resource transfers authorize readable quotation, order and change objects as well as RFQs, without modifying business money or commitments')
 const simultaneous=await Promise.all([a.ctx.attachments.upload(buyer,{...input,filename:'simultaneous.txt',buffer:Buffer.from('first parallel version')}),a.ctx.attachments.upload(buyer,{...input,filename:'simultaneous.txt',buffer:Buffer.from('second parallel version')})]);assert.deepEqual(simultaneous.map(row=>row.attachment.version),[1,2]);assert.equal(simultaneous[1].attachment.supersedes,simultaneous[0].attachment.id);checks.push('Simultaneous uploads of the same object filename serialize into distinct ordered immutable versions')
 const report={ok:true,at:new Date().toISOString(),root,checks,passed:checks.length};writeFileSync(join(root,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2))
}finally{if(server?.listening)await new Promise(done=>server.close(done));await a.close();await b.close()}
