import {generateKeyPairSync,randomUUID} from 'node:crypto'
import {mkdirSync,existsSync,readFileSync,writeFileSync,renameSync} from 'node:fs'
import {join} from 'node:path'
import {bridge,canonical,sha256,fingerprint,signBundle,verifyBundle} from './bundle.mjs'
export const name='product-evidence'
export const inject=['store','accounts','files','web','notifications']
export const provides=['evidence']
const now=()=>new Date().toISOString(),copy=value=>structuredClone(value),fail=(message,status=400)=>{throw Object.assign(new Error(message),{status})}
export function apply(ctx,config={}){
 const children=new Set(),keys=new Map(),directory=join(ctx.store.root,'evidence-keys');mkdirSync(directory,{recursive:true,mode:0o700})
 const party=user=>user.role==='admin'?user.id:ctx.get('procurement')?.realm(user)||ctx.get('teams')?.resolveUser(user,'snapshot').id||user.id
 const scoped=user=>({...ctx.accounts.get(party(user)),actorId:user.id,permissions:user.permissions||[]})
 const rows=user=>ctx.store.events(party(user))
 const key=realm=>{if(!keys.has(realm)){const path=join(directory,sha256(realm)+'.json');let pair;if(existsSync(path))pair=JSON.parse(readFileSync(path,'utf8'));else{if(ctx.store.list(realm,'evidence-exports').length)fail('The original audit signing key is missing. Restore its private backup to preserve exporter identity; prior packages can still be downloaded and independently verified.',503);const generated=generateKeyPairSync('ed25519');pair={privateKey:generated.privateKey.export({format:'pem',type:'pkcs8'}),publicKey:generated.publicKey.export({format:'pem',type:'spki'}),createdAt:now()};const temporary=path+'.tmp';writeFileSync(temporary,JSON.stringify(pair),{mode:0o600});renameSync(temporary,path)}keys.set(realm,pair)}return keys.get(realm)}
 const identity=user=>{const realm=party(user),pair=key(realm);return{realm,publicKey:pair.publicKey,fingerprint:fingerprint(pair.publicKey),algorithm:'ed25519',createdAt:pair.createdAt}}
 const statistics=events=>{const types=new Map(),correlations=new Set();let references=0;for(const row of events){types.set(row.type,(types.get(row.type)||0)+1);if(row.correlation_id)correlations.add(row.correlation_id);if(row.refs&&Object.keys(row.refs).length)references++}const times=events.map(row=>row.ts).filter(Boolean).sort();return{events:events.length,byType:[...types].sort(([a],[b])=>a.localeCompare(b)).map(([type,count])=>({type,count})),correlations:correlations.size,withReferences:references,firstAt:times[0]||null,lastAt:times.at(-1)||null,bodyIncluded:false}}
 const objectRanges=user=>{const procurement=ctx.get('procurement');if(!procurement||user.role==='admin')return[];const snapshot=procurement.snapshot(user),events=rows(user),has=(value,id)=>value===id||Array.isArray(value)&&value.some(row=>has(row,id))||value&&typeof value==='object'&&Object.values(value).some(row=>has(row,id));return Object.entries({rfq:'rfqs',quote:'quotes',order:'orders',change:'changes'}).flatMap(([kind,key])=>(snapshot[key]||[]).map(record=>{const matches=events.filter(event=>has(event.refs,record.id)||has(event.body,record.id));return{kind,id:record.id,title:record.title||record.supplierName||record.id,matchedEvents:matches.length,fromSeq:matches[0]?.seq||null,toSeq:matches.at(-1)?.seq||null}}))}
 const publicIdentity=user=>{try{return{identity:identity(user),identityError:null}}catch(error){return{identity:null,identityError:error.message}}}
 const list=user=>({realm:party(user),summary:statistics(rows(user)),...publicIdentity(user),objects:objectRanges(user),exports:ctx.store.list(party(user),'evidence-exports').slice(-100).reverse().map(record=>({...record,storage:ctx.files.stat(scoped(user),record.fileId).storage})),verifications:ctx.store.list(user.id,'evidence-verifications').slice(-100).reverse(),rebuilds:ctx.store.list(user.id,'evidence-rebuilds').slice(-100).reverse(),calls:ctx.store.events(user.id).filter(event=>event.type==='agent/model-requested').slice(-100).reverse().map(event=>({callId:event.body.callId,purpose:event.body.purpose,model:event.body.request?.model,at:event.ts,seq:event.seq,runId:event.body.runId,serialization:event.body.serialization||null})),limits:{list:100},scopeNote:'The audit range belongs to the selected party. Model request checks belong to your own account.'})
 const exportPack=async(user,input={})=>{
  const realm=party(user),events=rows(user);if(!events.length)fail('This workspace has no events to export.')
  const fromSeq=Number(input.fromSeq||1),toSeq=Number(input.toSeq||events.at(-1).seq)
  if(!Number.isInteger(fromSeq)||!Number.isInteger(toSeq))fail('Choose whole sequence numbers.')
  const generatedAt=now(),payload=await bridge({op:'export',path:join(ctx.store.root,'ledgers',realm+'.jsonl'),realm,fromSeq,toSeq,generatedAt,scope:`private-party:${realm}`,proofSeqs:input.proofSeqs},{children,python:config.python}),bundle=signBundle(payload,{...key(realm),realm,exportedBy:user.id,generatedAt}),buffer=Buffer.from(JSON.stringify(bundle,null,2)+'\n')
  const id=`audit-${randomUUID()}`,file=await ctx.files.put(scoped(user),{filename:`${id}.audit.json`,mime:'application/json',buffer,kind:'audit-export',actor:user.id,provenance:{kind:'ledger-slice',fromSeq,toSeq,realm}}),record={id,fileId:file.id,ownerId:realm,fromSeq,toSeq,count:bundle.count,merkleRoot:bundle.merkleRoot,payloadSha256:bundle.payloadSha256,signerFingerprint:bundle.exporter.fingerprint,createdAt:generatedAt,exportedBy:user.id,size:buffer.length,scope:bundle.scope}
  await ctx.store.put(realm,'evidence-exports',record,{event:'evidence/native-exported',actor:`human:${user.id}`});return{ok:true,export:record}
 }
 const download=(user,id)=>{const record=ctx.store.get(party(user),'evidence-exports',id);if(!record)fail('Audit export not found in this party workspace.',404);return{record,buffer:ctx.files.read(scoped(user),record.fileId,{includeDeleted:true})}}
 const verify=async(user,input={})=>{
  let bundle=input.bundle;try{if(typeof bundle==='string')bundle=JSON.parse(bundle)}catch{fail('Choose a valid JSON audit bundle.')}
  if(!bundle||typeof bundle!=='object')fail('Upload an audit bundle to verify.')
  if(input.trustedPublicKey&&!String(input.trustedPublicKey).trim().startsWith('-----BEGIN PUBLIC KEY-----'))fail('Supply an independently obtained public key in PEM format. Do not upload a private key.')
  const report=await verifyBundle(bundle,{trustedPublicKey:input.trustedPublicKey||'',children,python:config.python}),record={id:`verification-${randomUUID()}`,createdAt:now(),ownerId:user.id,packageSha256:sha256(canonical(bundle)),...report}
  await ctx.store.put(user.id,'evidence-verifications',record,{event:'evidence/native-verified',actor:`human:${user.id}`});return{ok:true,verification:record}
 }
 const requestEvent=(user,callId)=>{const matches=ctx.store.events(user.id).filter(row=>row.type==='agent/model-requested'&&row.body.callId===callId);if(matches.length!==1)fail(matches.length?'Multiple recorded requests use this call ID.':'The original model request is missing from this account.',409);return matches[0]}
 const rebuild=async(user,callId)=>{
  const checks=[],add=(name,ok,detail)=>checks.push({name,ok:!!ok,detail});let event,request=null,requestSha256=null,coverage='unmeasured',boundary='unmeasured'
  try{
   event=requestEvent(user,callId);await bridge({op:'export',path:join(ctx.store.root,'ledgers',user.id+'.jsonl'),realm:user.id,fromSeq:event.seq,toSeq:event.seq,generatedAt:now()},{children,python:config.python});add('Containing ledger integrity',true,'The unchanged kernel helper verified the containing ledger and the original request event.');request=event.body.request;add('Complete request shape',!!request?.model&&Array.isArray(request.messages)&&request.messages.every(message=>message&&typeof message.role==='string'),'Messages, model and tool definitions are rebuilt from the recorded request event.')
   const wire=event.body.serialization==='json-key-sorted/v1'?canonical(request):JSON.stringify(request);requestSha256=sha256(wire)
   const dispatched=ctx.store.events(user.id).filter(row=>row.type==='agent/model-dispatched'&&row.body.callId===callId)
   if(dispatched.length){boundary='measured';for(const attempt of dispatched){const matching=attempt.body.serialization==='json-key-sorted/v1'?canonical(request):JSON.stringify(request);add(`Provider boundary attempt ${attempt.body.attempt}`,sha256(matching)===attempt.body.requestSha256&&Buffer.byteLength(matching)===attempt.body.requestBytes,`Compared to exact serialized request digest and byte count recorded at dispatch (sequence ${attempt.seq}).`)}}
   const receipt=event.body.contextReceipt
   if(receipt?.selectedSourceHash){const parts=[];for(const [index,message]of(request.messages||[]).entries()){const match=message.role==='user'&&typeof message.content==='string'?/^SOURCE_DATA[^:]*:\s*([\s\S]*)$/.exec(message.content):null;if(match)parts.push([`message${index}`,JSON.parse(match[1])])}const candidates=[Object.fromEntries(parts),...(parts.length===1?[parts[0][1]]:[])];coverage=candidates.some(source=>sha256(canonical(source))===receipt.selectedSourceHash)?'matched':'mismatch';add('Recorded source coverage digest',coverage==='matched','Recomputed from the SOURCE_DATA actually present in the request; omitted facts remain disclosed by the assembly receipt.')}
  }catch(error){add('Original recorded model input',false,error.message)}
  const report={id:`rebuild-${randomUUID()}`,ownerId:user.id,callId,createdAt:now(),ok:checks.length>0&&checks.every(check=>check.ok),checks,boundary,coverage,requestSha256,sourceRef:event?{realm:user.id,seq:event.seq,hash:event.entry_hash}:null,model:request?.model||null,messageCount:request?.messages?.length??null,limitations:['A dispatch digest measures the application provider boundary, not an independent network witness.',...(boundary==='unmeasured'?['This historical call has no dispatch-byte receipt; only its recorded request can be reconstructed.']:[]),...(coverage==='unmeasured'?['No source-assembly digest was recorded for this call.']:[])]}
  await ctx.store.put(user.id,'evidence-rebuilds',report,{event:'evidence/model-input-rebuilt',actor:`human:${user.id}`})
  if(!report.ok)try{await ctx.notifications.push(user,{type:'warning',level:'warning',source:{pluginId:'evidence'},title:'Model input reconstruction failed',body:checks.find(check=>!check.ok)?.detail||'Inspect the recorded input and source coverage.',link:{view:'evidence',callId},sourceId:report.id,dedupeKey:`rebuild-failed:${callId}:${requestSha256}`})}catch(error){await ctx.store.append(user.id,'evidence/notification-failed',{reportId:report.id,error:error.message},{actor:'system:evidence'})}
  return{ok:true,rebuild:report}
 }
 const aggregate=user=>{if(user.role!=='admin')fail('Administrator access is required.',403);const summaries=[],unavailable=[];for(const account of ctx.accounts.list()){try{summaries.push(statistics(ctx.store.events(account.id)))}catch(error){unavailable.push({realm:account.id,code:error.code||'unavailable'})}}return{accounts:summaries.length,unavailable,events:summaries.reduce((sum,row)=>sum+row.events,0),correlations:summaries.reduce((sum,row)=>sum+row.correlations,0),withReferences:summaries.reduce((sum,row)=>sum+row.withReferences,0),bodyIncluded:false}}
 ctx.effect(()=>()=>{for(const child of children)child.kill();children.clear();keys.clear()})
 ctx.provide('evidence',{list,identity,export:exportPack,download,verify,rebuild,aggregate,request:(user,id)=>copy(requestEvent(user,id).body.request)})
 const route=(method,path,handler,options={})=>ctx.effect(()=>ctx.web.route(method,path,handler,options))
 route('GET','/evidence',({user})=>list(user));route('GET','/evidence/aggregate',({user})=>aggregate(user),{admin:true})
 route('GET','/evidence/key',({user,res})=>{const current=identity(user);res.setHeader('content-type','application/x-pem-file');res.setHeader('content-disposition',`attachment; filename="${current.realm}.public.pem"`);res.end(current.publicKey)})
 route('POST','/evidence/export',({user,body})=>exportPack(user,body),{capability:'workspace:write'})
 route('GET','/evidence/exports/:id/download',({user,params,res})=>{const value=download(user,params.id);res.setHeader('content-type','application/json');res.setHeader('content-disposition',`attachment; filename="${value.record.id}.audit.json"`);res.end(value.buffer)})
 route('POST','/evidence/verify',({user,body})=>verify(user,body),{capability:'workspace:write'})
 route('POST','/evidence/calls/:id/rebuild',({user,params})=>rebuild(user,params.id),{capability:'workspace:write'})
 route('GET','/evidence/calls/:id/request',({user,params,res})=>{const value=requestEvent(user,params.id);res.setHeader('content-type','application/json');res.setHeader('content-disposition','attachment; filename="recorded-model-request.json"');res.end(JSON.stringify(value.body.request,null,2)+'\n')})
 ctx.effect(()=>ctx.web.contribute({id:'evidence',label:'Evidence & verification',icon:'shield',roles:['contractor','supplier','admin'],order:47}))
 ctx.inject(['assistant'],inner=>inner.effect(()=>inner.assistant.tool({name:'evidence_status',description:'Read account audit counts and model input reconstruction outcomes; no private bundle is sent externally.',effect:'read',roles:['contractor','supplier'],parameters:{type:'object',properties:{}},execute:user=>{const value={realm:party(user),summary:statistics(rows(user)),rebuilds:ctx.store.list(user.id,'evidence-rebuilds').slice(-100)};return{realm:value.realm,summary:value.summary,rebuilds:value.rebuilds,action:{type:'navigate',input:{view:'evidence'},label:'Open evidence & verification'}}}})))
}
