import {createHash} from 'node:crypto'
export const name='exchange-mail'
export const inject=['store','accounts','settings','web','files','mail','exchange']
export const provides=['qepMail']
const fail=(message,status=400)=>{throw Object.assign(new Error(message),{status})}
const now=()=>new Date().toISOString(),hash=bytes=>createHash('sha256').update(bytes).digest('hex')
const packages=value=>{const result=Array.isArray(value)?value:[value];if(!result.length||result.length>128||result.some(item=>item?.schema!=='quotagent/qep-package/v1'||!item.envelope))fail('Choose a signed QEP package or a bounded array of original packages.');return result}
const summary=items=>items.map(item=>{const env=item.envelope;return {msgId:env.msg_id,seq:env.seq,type:env.type,eventClass:env.class,bodyHash:env.body_hash,channel:item.channel,from:env.sender?.realm,to:env.recipients?.[0]?.match(/^account:([^:]+):to:/)?.[1]||'',title:env.body?.record?.title||env.body?.record?.supplierName||env.body?.record?.id||env.type,recordId:env.body?.record?.id||null,approvals:env.approvals?.length||0}})
export function apply(ctx){
 ctx.effect(()=>ctx.settings.define({id:'qep-mail',name:'QEP email delivery',scope:'account',description:'Bound the signed package attachment before it becomes a reviewed email. SMTP acceptance remains separate from QEP acceptance.',fields:[{key:'maxPackageMb',label:'Maximum package attachment (MB)',type:'number',min:1,max:12}],defaults:{maxPackageMb:8}}))
 ctx.effect(()=>ctx.mail.extension({id:'qep-mail'}));ctx.effect(()=>ctx.exchange.extension({id:'qep-mail'}))
 const guard=user=>{if(!user?.id||!['contractor','supplier'].includes(user.role))fail('Use a signed-in business account.',403);if(user.permissions?.includes('workspace:read-only'))fail('This workspace has read-only access.',403)}
 const limit=(user,bytes)=>{const max=Number(ctx.settings.get(user,'qep-mail').maxPackageMb)*1024*1024;if(bytes.length>max)fail(`This QEP attachment exceeds your ${max/1024/1024} MB email-package limit. Use a portable file or HTTP delivery, or change the explicit package setting.`,413)}
 const save=(user,record,event)=>ctx.store.put(user.id,'exchange-mail',{...record,ownerId:user.id,updatedAt:now()},{event:`exchange-mail/${event}`,actor:`human:${user.id}`})
 const source=(user,messageId,fileId)=>{const message=ctx.mail.get(user,messageId);if(!message.attachments.some(file=>file.id===fileId))fail('Choose a saved attachment of this account-owned email.',403);const file=ctx.files.get(user,fileId),bytes=ctx.files.read(user,fileId);limit(user,bytes);let value;try{value=JSON.parse(bytes.toString('utf8'))}catch{fail('This attachment is not readable UTF-8 QEP JSON. Keep the original and ask the sender for the exported package.')}return{message,file,bytes,items:packages(value)}}
 const preview=async(user,input)=>{guard(user);const original=source(user,input.messageId,input.fileId),realm=ctx.exchange.workspace(user);for(const item of original.items)await ctx.exchange.preview(user,item);const facts=summary(original.items);await ctx.store.append(user.id,'exchange-mail/previewed',{messageId:original.message.id,fileId:original.file.id,fileSha256:hash(original.bytes),workspaceId:realm,packages:facts},{actor:`human:${user.id}`});return {ok:true,messageId:original.message.id,fileId:original.file.id,filename:original.file.filename,fileSha256:hash(original.bytes),workspaceId:realm,verified:true,packages:facts,note:'Pairing, recipient and signatures verified. Import still applies domain, sequence and conflict validation.'}}
 const makeDraft=async(user,items,{to,replyToId,origin})=>{guard(user);items=packages(items);const encoded=Buffer.from(JSON.stringify(items.length===1?items[0]:items,null,2)+'\n','utf8');limit(user,encoded);const facts=summary(items);if(facts.some(item=>item.from!==ctx.exchange.workspace(user)))fail('Only this selected workspace’s original outbound packages can be emailed.',403);const filename=items.length===1?`${facts[0].msgId}.qep.json`:`qep-recovery-${hash(encoded).slice(0,16)}.qep.json`,file=await ctx.files.put(user,{filename,mime:'application/json',buffer:encoded,kind:'generated',provenance:{plugin:'exchange-mail',workspaceId:ctx.exchange.workspace(user),messageIds:facts.map(item=>item.msgId)}})
  const body=['Original signed QEP exchange package attached.',...facts.map(item=>`${item.title}: ${item.type}; sequence ${item.seq}; message ${item.msgId}; body hash ${item.bodyHash}.`),'Import this original attachment in Deliveries & exchange or use the signed-exchange action beside the email attachment.','This email carries existing signed content. SMTP acceptance is not a QEP acceptance or a new commercial approval.'].join('\n\n')
  const message=await ctx.mail.draft(user,{to,replyToId,subject:items.length===1?`QEP exchange: ${facts[0].title}`:`QEP recovery: ${facts.length} original messages`,body,attachmentIds:[file.id]})
  const record={id:`mail-${message.id}`,direction:'outbound',workspaceId:ctx.exchange.workspace(user),mailId:message.id,fileId:file.id,fileSha256:hash(encoded),packages:facts,origin,createdAt:now()};await save(user,record,'drafted');return {ok:true,message,record,action:{type:'navigate',label:'Review email draft',input:{view:'mail',messageId:message.id}}}
 }
 const draftDelivery=async(user,id,input={})=>{guard(user);const receipt=input.direction==='inbox',original=await ctx.exchange.exportPackage(user,id,{receipt});return makeDraft(user,[original.package],{to:input.to,origin:{type:receipt?'receipt':'delivery',id,direction:receipt?'inbox':'outbox'}})}
 const importAttachment=async(user,input)=>{guard(user);if(input.confirmed!==true)fail('Confirm import of the verified signed attachment.');const checked=await preview(user,input),original=source(user,input.messageId,input.fileId);if(input.fileSha256!==checked.fileSha256)fail('The attachment changed after preview. Review its original bytes again.',409);const results=[];for(const item of original.items)results.push(await ctx.exchange.receive(checked.workspaceId,item,{user}));const replies=[...new Map(results.flatMap(result=>[...(result.receipts||[]),...(result.replays||[])]).map(item=>[item.envelope.msg_id,item])).values()].sort((a,b)=>a.envelope.seq-b.envelope.seq);const record={id:`import-${original.message.id}-${original.file.id}`,direction:'inbound',workspaceId:checked.workspaceId,mailId:original.message.id,fileId:original.file.id,fileSha256:checked.fileSha256,packages:checked.packages,results:results.map(result=>({id:result.id||result.delivery?.id,status:result.status,control:!!result.control,released:(result.released||[]).map(row=>({id:row.id,status:row.status}))})),replyIds:replies.map(item=>item.envelope.msg_id),createdAt:now()};await save(user,record,'imported');return {ok:true,record,replyAvailable:record.replyIds.length>0,action:{type:'navigate',label:'Inspect delivery results',input:{view:'exchange'}}}}
 const reply=async(user,id,input={})=>{guard(user);const record=ctx.store.get(user.id,'exchange-mail',id);if(!record||record.direction!=='inbound'||record.workspaceId!==ctx.exchange.workspace(user))fail('Open the original importing workspace to prepare its receipt or recovery reply.',403);const sourceMail=ctx.mail.get(user,record.mailId),items=[];for(const messageId of record.replyIds||[])items.push((await ctx.store.package(record.workspaceId,messageId)).package);if(!items.length)fail('This import has no signed receipt or requested original to reply with.');return makeDraft(user,items,{to:input.to||sourceMail.replyTo?.length&&sourceMail.replyTo||sourceMail.fromAddresses,replyToId:sourceMail.id,origin:{type:'import-reply',id:record.id}})}
 const state=user=>{const workspaceId=ctx.exchange.workspace(user),messages=ctx.mail.list(user),reports=messages.filter(message=>message.deliveryReport?.originalMessageId);return {records:ctx.store.list(user.id,'exchange-mail').map(record=>{const message=messages.find(item=>item.id===record.mailId),recipients=[...(message?.to||[]),...(message?.cc||[]),...(message?.bcc||[])].map(value=>value.toLowerCase());const deliveryReports=message?.messageId?reports.filter(item=>item.deliveryReport.originalMessageId===message.messageId).map(item=>({messageId:item.id,sourceFileId:item.originalFileId,reports:item.deliveryReport.reports.filter(report=>recipients.includes(report.recipient.split(';').at(-1).trim().toLowerCase()))})).filter(item=>item.reports.length):[];const failed=deliveryReports.some(item=>item.reports.some(report=>report.action==='failed'));return {...record,mailStatus:failed?'reported-failure':message?.status||'mail-unavailable',mailMessageId:message?.messageId||null,deliveryReports,qep:record.packages.map(item=>({msgId:item.msgId,status:record.workspaceId===workspaceId?ctx.store.get(record.workspaceId,record.direction==='outbound'?'exchange-outbox':'exchange-inbox',item.msgId)?.status||'not-recorded':'select-original-workspace'}))}})}}
 ctx.provide('qepMail',{preview,draftDelivery,importAttachment,reply,state})
 const route=(method,path,handler)=>ctx.effect(()=>ctx.web.route(method,path,handler,method==='GET'?{}:{capability:'workspace:write'}))
 route('GET','/exchange/mail/state',({user})=>state(user));route('POST','/exchange/mail/preview',({user,body})=>preview(user,body));route('POST','/exchange/mail/import',({user,body})=>importAttachment(user,body));route('POST','/exchange/mail/:id/reply',({user,params,body})=>reply(user,params.id,body));route('POST','/exchange/:id/mail-draft',({user,params,body})=>draftDelivery(user,params.id,body))
 ctx.inject(['assistant'],inner=>{inner.effect(()=>inner.assistant.tool({name:'email_exchange_package',description:'Prepare a PRIVATE editable email containing an already signed outbound QEP package or receipt. Never sends; the account owner must review the exact mail through normal send approval.',roles:['contractor','supplier'],effect:'draft',parameters:{type:'object',properties:{id:{type:'string'},to:{type:'array',items:{type:'string'}},direction:{type:'string',enum:['outbox','inbox']}},required:['id','to']},execute:(user,args)=>draftDelivery(user,args.id,args)}))})
}
