import React,{useEffect,useState} from 'react'
import {registry,useApp,useResource,api,Icon,Button,Badge,PageHeader,ErrorNotice,Loading} from '../../webui/client/core.jsx'
import {defaults,layouts,palettes,presentation} from '../code/presets.mjs'
import {groupNavigation} from '../code/navigation.mjs'
import './styles.css'

function StyleEffect(){
 const app=useApp(),resource=useResource('/workspace-style',{preferences:defaults})
 const preferences=resource.data.preferences||defaults
 useEffect(()=>app.registerPresentation?.('workspace-styles',presentation(preferences,app.user.role)),[app.registerPresentation,app.user.id,app.user.role,preferences.layout,preferences.palette,preferences.density])
 return null
}
function LayoutPreview({layout}){return <div className={`ws-preview ws-preview-${layout}`} aria-hidden="true"><div className="ws-preview-nav"><i/><i/><i/></div><div className="ws-preview-main">{layout==='classic'?<><div className="ws-preview-bars"><i/><i/><i/></div><b/><b/></>:<><span className="ws-preview-star">✦</span><b/><b/><div className="ws-preview-compose"/></>}</div>{layout!=='focus'&&<div className="ws-preview-assistant"><i/><i/><i/><b/></div>}</div>}
function Styles(){
 const app=useApp(),resource=useResource('/workspace-style',{preferences:defaults}),[draft,setDraft]=useState(null),[touched,setTouched]=useState(()=>new Set()),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{if(draft===null&&!resource.loading)setDraft({...resource.data.preferences})},[resource.loading,resource.data,draft])
 const preferences=draft||resource.data.preferences||defaults
 const extensions=app.bootstrap?.extensions?.plugins||app.bootstrap?.extensions||[],theme=Array.isArray(extensions)&&[...extensions].reverse().find(item=>item.enabled&&item.kind==='theme')
 const set=(key,value)=>{setDraft({...preferences,[key]:value});setTouched(old=>new Set([...old,key]))}
 async function save(){setBusy(true);setError('');try{await api('/settings/workspace-styles',{method:'PATCH',body:{values:Object.fromEntries([...touched].map(key=>[key,preferences[key]]))}});setTouched(new Set());await resource.reload();app.refresh();app.notify('Workspace style saved.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <><PageHeader eyebrow="MAKE ROOM FOR YOUR WAY OF WORKING" title="Workspace style" actions={<Button icon="check" busy={busy} disabled={!touched.size} onClick={save}>Save workspace style</Button>}>Choose how your workspace feels. These choices stay with your account.</PageHeader><ErrorNotice error={error||resource.error} retry={resource.error?resource.reload:undefined}/>{resource.loading?<Loading/>:<div className="ws-settings"><section className="card"><div className="section-heading"><div><h2>Your layout</h2><p>Each layout keeps the same tools and work. Change how you reach them.</p></div><Badge>Only your account</Badge></div><div className="ws-layouts" role="radiogroup" aria-label="Workspace layout">{layouts.map(layout=><label key={layout.id} className={`ws-option ${preferences.layout===layout.id?'selected':''}`}><input type="radio" name="workspace-layout" checked={preferences.layout===layout.id} onChange={()=>set('layout',layout.id)} aria-label={`${layout.name} layout`}/><LayoutPreview layout={layout.id}/><span className="ws-option-heading"><strong>{layout.name}</strong>{preferences.layout===layout.id&&<Icon name="check" size={17}/>}</span><span>{layout.description}</span></label>)}</div></section><section className="card"><div className="section-heading"><div><h2>Your colors</h2><p>Three light palettes with clear, familiar surfaces.</p></div></div>{theme&&<div className="ws-theme-note"><Icon name="puzzle" size={18}/><p>Your active custom theme, <strong>{theme.name}</strong>, supplies the colors. These palette choices will apply when that theme is disabled in Plugin studio.</p></div>}<div className="ws-palettes" role="radiogroup" aria-label="Color palette">{palettes.map(palette=><label key={palette.id} className={`ws-palette ${preferences.palette===palette.id?'selected':''}`}><input type="radio" name="workspace-palette" checked={preferences.palette===palette.id} onChange={()=>set('palette',palette.id)} aria-label={`${palette.name} palette`}/><span className="ws-swatches">{palette.colors.map(color=><i key={color} style={{background:color}}/>)}</span><span><strong>{palette.name}</strong><small>{palette.description}</small></span>{preferences.palette===palette.id&&<Icon name="check" size={17}/>}</label>)}</div></section><section className="card ws-spacing"><div><h2>Your spacing</h2><p>Comfortable gives each control room. Compact fits more detail on a wide screen.</p></div><div className="ws-density" role="radiogroup" aria-label="Workspace spacing">{['comfortable','compact'].map(value=><label key={value}><input type="radio" name="workspace-density" checked={preferences.density===value} onChange={()=>set('density',value)} aria-label={`${value[0].toUpperCase()+value.slice(1)} spacing`}/><span>{value[0].toUpperCase()+value.slice(1)}</span></label>)}</div></section><p className="ws-save-note">{touched.size?'Your choices are ready. Save to apply them across your workspace.':'Your saved choices apply on your next visit, too.'}</p></div>}</>
}
function GroupedNavigation({items,currentId,navigate}){
 const {primary,sections,utilities}=groupNavigation(items),[opened,setOpened]=useState({})
 useEffect(()=>{const active=sections.find(group=>group.items.some(item=>item.id===currentId));if(active)setOpened(old=>({...old,[active.id]:true}))},[currentId,items.map(item=>item.id).join('|')])
 const itemButton=item=><button key={item.id} className={`nav-item ${currentId===item.id?'active':''}`} aria-current={currentId===item.id?'page':undefined} onClick={()=>navigate(item.id)}><Icon name={registry.pages.get(item.id)?.icon||item.icon}/><span>{item.label}</span>{currentId===item.id&&<span className="nav-active-dot"/>}</button>
 return <nav className="ws-navigation" aria-label="Main navigation"><div className="ws-primary">{primary.map(itemButton)}</div><div className="ws-nav-groups">{sections.map(group=><section className="ws-nav-group" key={group.id}><button className={`ws-group-toggle ${group.items.some(item=>item.id===currentId)?'has-current':''}`} aria-expanded={!!opened[group.id]} aria-controls={`nav-group-${group.id}`} onClick={()=>setOpened(old=>({...old,[group.id]:!old[group.id]}))}><Icon name={group.icon} size={17}/><span>{group.label}</span><Icon name="chevron" size={14}/></button><div id={`nav-group-${group.id}`} hidden={!opened[group.id]} className="ws-group-items">{group.items.map(itemButton)}</div></section>)}</div><div className="ws-nav-utilities">{utilities.map(itemButton)}</div></nav>
}
function AppearanceCard(){const app=useApp();return <section className="card section-space"><div className="section-heading"><div><h2>Make the workspace yours</h2><p>Choose a layout, color palette and spacing that suit your work.</p></div><Icon name="sun"/></div><Button variant="secondary" icon="sun" onClick={()=>app.navigate('workspace-style')}>Choose workspace style</Button></section>}
registry.page('workspace-style',{component:Styles,icon:'sun'})
registry.slot('shell:navigation',GroupedNavigation,{navigation:'workspace-style'})
registry.slot('shell:effect:styles',StyleEffect,{navigation:'workspace-style'})
registry.slot('account:workspace-style',AppearanceCard,{navigation:'workspace-style'})
