import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {mkdirSync,mkdtempSync,writeFileSync,readFileSync} from 'node:fs'
import {resolve,join} from 'node:path'
import {spawn} from 'node:child_process'
const require=createRequire(new URL('../../../../host/package.json',import.meta.url)),{chromium}=require('playwright'),root=mkdtempSync(resolve('tmp/operations-gui-')),out=resolve(process.env.EVIDENCE_DIR||root),checks=[],report={at:new Date().toISOString(),root,checks,errors:[],screenshots:[]};let browser,host,page
mkdirSync(out,{recursive:true})
async function navigate(page){const button=page.getByRole('navigation',{name:'Main navigation'}).getByRole('button',{name:'Operations & timeline',exact:true,includeHidden:true});await button.waitFor({state:'attached'});if(!await button.isVisible())await button.locator('xpath=ancestor::section[contains(@class,"ws-nav-group")]').getByRole('button').first().click();await button.click();await page.getByRole('heading',{name:'Operations & timeline',exact:true}).waitFor()}
try{
 let base=process.env.BASE_URL
 if(!base){host=spawn('node',['host/product.mjs'],{env:{...process.env,QUOTAGENT_WEBUI_PORT:'0',QUOTAGENT_PRODUCT_DATA:root,QUOTAGENT_WEBUI_ASSETS:resolve('tmp/agent-experience/operations-build')},stdio:['ignore','pipe','pipe']});let errors='';host.stderr.on('data',data=>errors+=data);const ready=await new Promise((resolve,reject)=>{let output='';host.stdout.on('data',data=>{output+=data;for(const line of output.split('\n'))try{const row=JSON.parse(line);if(row.ready)resolve(row)}catch{}});host.once('exit',code=>reject(new Error('Host exited '+code+' '+errors)))});base=ready.url}
 report.base=base;browser=await chromium.launch({headless:true,executablePath:'/opt/hermes/.playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox']})
 for(const role of ['admin','contractor','supplier']){
  const context=await browser.newContext({viewport:{width:1440,height:1100}});page=await context.newPage();page.setDefaultTimeout(20000);page.on('pageerror',error=>report.errors.push(error.message));await page.goto(base);await page.getByRole('button',{name:role==='admin'?'Administrator sign in':role==='contractor'?'I’m a contractor':'I’m a supplier',exact:role==='admin'}).click();await page.locator('.ws-navigation').waitFor();if(role!=='admin')await page.getByRole('button',{name:'Not now',exact:true}).click();await navigate(page);await page.getByLabel('Search events',{exact:true}).waitFor();await page.locator('.collection-controls').waitFor()
  if(role==='admin'){
   await page.getByRole('heading',{name:'Application summary',exact:true}).waitFor();await page.getByText('Complete account coverage',{exact:true}).waitFor();const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download operations snapshot',exact:true}).click();const download=await pending;await download.saveAs(join(out,'operations-summary.json'));const snapshot=JSON.parse(readFileSync(join(out,'operations-summary.json'),'utf8'));assert(snapshot.coverage.totalAccounts>=4);assert(snapshot.plugins.some(row=>row.id==='observability'&&row.status==='active'));assert.equal(snapshot.sources.provider,'agent-runtime');assert.equal(typeof snapshot.totals.requests,'number');assert.equal(typeof snapshot.generatedAt,'string');checks.push('Separate admin GUI displays actual native plugin/provider metadata and downloads a timestamped source-labelled JSON snapshot')
   await page.getByRole('button',{name:'Snapshot settings',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Snapshot interval (seconds)',{exact:true}).fill('45');await dialog.getByRole('button',{name:'Preview changes',exact:true}).click();await dialog.locator('.settings-diff').getByText('45',{exact:true}).waitFor();await dialog.getByRole('button',{name:'Save settings',exact:true}).click();await dialog.getByText('Settings saved.',{exact:true}).waitFor();await dialog.getByRole('button',{name:'Close',exact:true}).click();await page.reload();await page.getByRole('button',{name:'Snapshot settings',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[role="dialog"] input[type="number"]')?.value==='45');await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();checks.push('Administrator previews and applies periodic snapshot settings in GUI; explicit value survives reload')
  }else{assert.equal(await page.getByRole('button',{name:'Download operations snapshot',exact:true}).count(),0);assert.equal(await page.getByRole('heading',{name:'Application summary',exact:true}).count(),0);await page.getByLabel('Search events',{exact:true}).fill('procurement/');await page.getByText('Filters, saved view & export columns',{exact:true}).click();await page.getByLabel('Sort by',{exact:true}).selectOption('sequence');await page.getByLabel('Sort direction',{exact:true}).selectOption('desc');await page.getByRole('button',{name:'Save view',exact:true}).click();await page.getByText('View saved to your account.',{exact:true}).waitFor();await page.reload();await page.waitForFunction(()=>document.querySelector('[aria-label="Search events"]')?.value==='procurement/');assert.equal(await page.getByRole('alert').count(),0);checks.push(role+' GUI offers only its authorized timeline; real collection query and explicit personal preferences survive reload')}
  await page.setViewportSize({width:390,height:1000});await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const screenshot=role+'-mobile.png';await page.screenshot({path:join(out,screenshot),fullPage:true});report.screenshots.push(screenshot);await context.close();page=null
 }
 assert.deepEqual(report.errors,[]);checks.push('All three account views fit a 390px viewport with no JavaScript errors');report.ok=true
}catch(error){report.error=error.stack;process.exitCode=1;if(page)await page.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>{})}finally{if(browser)await browser.close();if(host){host.kill('SIGTERM');await new Promise(resolve=>host.once('exit',resolve))}writeFileSync(join(out,'report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2))}
