import {createProtocolAccount} from '../../exchange-workbench/tests/gui-account.mjs'
import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {mkdirSync,mkdtempSync,writeFileSync,readFileSync} from 'node:fs'
import {resolve,join} from 'node:path'
import {spawn} from 'node:child_process'
const require=createRequire(new URL('../../../../host/package.json',import.meta.url)),{chromium}=require('playwright'),{expect}=require('playwright/test'),root=mkdtempSync(resolve('tmp/operations-gui-')),out=resolve(process.env.EVIDENCE_DIR||root),checks=[],report={at:new Date().toISOString(),root,checks,errors:[],screenshots:[]};let browser,host,page,pendingRestore
mkdirSync(out,{recursive:true})
async function navigate(page){const button=page.getByRole('navigation',{name:'Main navigation'}).getByRole('button',{name:'Operations & timeline',exact:true,includeHidden:true});await button.waitFor({state:'attached'});if(!await button.isVisible())await button.locator('xpath=ancestor::section[contains(@class,"ws-nav-group")]').getByRole('button').first().click();await button.click();await page.getByRole('heading',{name:'Operations & timeline',exact:true}).waitFor()}
async function restoreSetting(){if(!pendingRestore)return;const {page,value}=pendingRestore;await page.setViewportSize({width:1440,height:1100});const open=page.getByRole('dialog');if(await open.count())await open.last().getByRole('button',{name:'Close',exact:true}).click();await navigate(page);await page.getByRole('button',{name:'Snapshot settings',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Snapshot interval (seconds)',{exact:true}).fill(value);await dialog.getByRole('button',{name:'Save settings',exact:true}).click();await dialog.getByText('Settings saved.',{exact:true}).waitFor();await dialog.getByRole('button',{name:'Close',exact:true}).click();await page.reload();await page.getByRole('button',{name:'Snapshot settings',exact:true}).click();await page.waitForFunction(saved=>document.querySelector('[role="dialog"] input[type="number"]')?.value===saved,value);await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();report.snapshotSetting.restored=value;pendingRestore=null;checks.push('Original shared admin snapshot interval restored through GUI and verified after reload')}
try{
 let base=process.env.BASE_URL
 if(!base){host=spawn('node',['host/product.mjs'],{env:{...process.env,QUOTAGENT_WEBUI_PORT:'0',QUOTAGENT_PRODUCT_DATA:root,QUOTAGENT_WEBUI_ASSETS:resolve('tmp/agent-experience/operations-build')},stdio:['ignore','pipe','pipe']});let errors='';host.stderr.on('data',data=>errors+=data);const ready=await new Promise((resolve,reject)=>{let output='';host.stdout.on('data',data=>{output+=data;for(const line of output.split('\n'))try{const row=JSON.parse(line);if(row.ready)resolve(row)}catch{}});host.once('exit',code=>reject(new Error('Host exited '+code+' '+errors)))});base=ready.url}
 report.base=base;browser=await chromium.launch({headless:true,executablePath:'/opt/hermes/.playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox']})
 for(const role of ['admin','contractor','supplier']){
  const context=await browser.newContext({viewport:{width:1440,height:1100}});page=await context.newPage();page.setDefaultTimeout(20000);page.on('pageerror',error=>report.errors.push(error.message));if(process.env.BASE_URL&&role!=='admin'){const user=await createProtocolAccount(page,base,{prefix:'operations',role});(report.accounts||=[]).push({id:user.id,role})}else{await page.goto(base);await page.getByRole('button',{name:role==='admin'?'Administrator sign in':role==='contractor'?'I’m a contractor':'I’m a supplier',exact:role==='admin'}).click();await page.locator('.ws-navigation').waitFor();if(role!=='admin')await page.getByRole('button',{name:'Not now',exact:true}).click({timeout:1500}).catch(()=>{})}await navigate(page);await page.getByLabel('Search events',{exact:true}).waitFor();await page.locator('.collection-controls').waitFor()
  if(role==='admin'){
   await page.getByRole('heading',{name:'Application summary',exact:true}).waitFor();await page.getByText('Complete account coverage',{exact:true}).waitFor();const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download operations snapshot',exact:true}).click();const download=await pending;await download.saveAs(join(out,'operations-summary.json'));const snapshot=JSON.parse(readFileSync(join(out,'operations-summary.json'),'utf8'));assert(snapshot.coverage.totalAccounts>=4);assert(snapshot.plugins.some(row=>row.id==='observability'&&row.status==='active'));assert.equal(snapshot.sources.provider,'agent-runtime');assert.equal(typeof snapshot.totals.requests,'number');assert.equal(typeof snapshot.generatedAt,'string');checks.push('Separate admin GUI displays actual native plugin/provider metadata and downloads a timestamped source-labelled JSON snapshot')
   await page.getByRole('button',{name:'Snapshot settings',exact:true}).click();const dialog=page.getByRole('dialog'),interval=dialog.getByLabel('Snapshot interval (seconds)',{exact:true});await interval.waitFor();const original=await interval.inputValue(),candidate=original==='45'?'46':'45';await interval.fill(candidate);await dialog.getByRole('button',{name:'Preview changes',exact:true}).click();await dialog.locator('.settings-diff').getByText(candidate,{exact:true}).waitFor()
   if(process.env.BASE_URL){pendingRestore={page,value:original};report.snapshotSetting={before:original,applied:candidate}}
   await dialog.getByRole('button',{name:'Save settings',exact:true}).click();await dialog.getByText('Settings saved.',{exact:true}).waitFor();await dialog.getByRole('button',{name:'Close',exact:true}).click();await page.reload();await page.getByRole('button',{name:'Snapshot settings',exact:true}).click();await page.waitForFunction(value=>document.querySelector('[role="dialog"] input[type="number"]')?.value===value,candidate);await page.screenshot({path:join(out,'admin-snapshot-setting-persisted.png'),fullPage:true});report.screenshots.push('admin-snapshot-setting-persisted.png');await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();checks.push('Administrator previews and applies periodic snapshot settings in GUI; explicit value survives reload')
  }else{assert.equal(await page.getByRole('button',{name:'Download operations snapshot',exact:true}).count(),0);assert.equal(await page.getByRole('heading',{name:'Application summary',exact:true}).count(),0);await page.getByLabel('Search events',{exact:true}).fill('procurement/');await page.getByText('Filters, saved view & export columns',{exact:true}).click();await page.getByLabel('Sort by',{exact:true}).selectOption('sequence');await page.getByLabel('Sort direction',{exact:true}).selectOption('desc');await page.getByRole('button',{name:'Save view',exact:true}).click();await page.getByText('View saved to your account.',{exact:true}).waitFor();await page.reload();await expect(page.getByLabel('Search events',{exact:true})).toHaveValue('procurement/',{timeout:20000});await page.getByText('Filters, saved view & export columns',{exact:true}).click();await expect(page.getByLabel('Sort by',{exact:true})).toHaveValue('sequence');await expect(page.getByLabel('Sort direction',{exact:true})).toHaveValue('desc');await page.getByText('Filters, saved view & export columns',{exact:true}).click();assert.equal(await page.getByRole('alert').count(),0);checks.push(role+' GUI offers only its authorized timeline; real collection query and explicit personal preferences survive reload')}
  await page.setViewportSize({width:390,height:1000});await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const screenshot=role+'-mobile.png';await page.screenshot({path:join(out,screenshot),fullPage:true});report.screenshots.push(screenshot);if(pendingRestore)await restoreSetting();await context.close();page=null
 }
 assert.deepEqual(report.errors,[]);checks.push('All three account views fit a 390px viewport with no JavaScript errors');report.ok=true
}catch(error){report.error=error.stack;process.exitCode=1;if(page)await page.screenshot({path:join(out,'failure.png'),fullPage:true}).catch(()=>{})}finally{if(pendingRestore)try{await restoreSetting()}catch(error){report.restoreError=error.stack;process.exitCode=1}if(browser)await browser.close();if(host){host.kill('SIGTERM');await new Promise(resolve=>host.once('exit',resolve))}writeFileSync(join(out,'report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2))}
