import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {mkdirSync,mkdtempSync,readFileSync,existsSync,writeFileSync} from 'node:fs'
import {resolve,join} from 'node:path'
import * as web from '../../webui/code/product-server.mjs'
import * as store from '../../workspace-store/code/index.mjs'
import * as settings from '../../settings/code/index.mjs'
import * as teams from '../../teams/code/index.mjs'
import * as operations from '../code/product.mjs'
const require=createRequire(new URL('../../../../host/package.json',import.meta.url)),{Context}=require('cordis'),ctx=new Context(),fibers=[],checks=[],users=[{id:'ops-admin',role:'admin',email:'admin@test.local'},{id:'ops-buyer',role:'contractor',email:'buyer@test.local'},{id:'ops-colleague',role:'contractor',email:'colleague@test.local'},{id:'ops-vendor',role:'supplier',email:'vendor@test.local'},{id:'ops-unavailable',role:'contractor',email:'bad@test.local'}],root=mkdtempSync(resolve('tmp/operations-')),secret='Private cost model 183737 and confidential mail words'
mkdirSync(join(root,'ledgers'),{recursive:true});writeFileSync(join(root,'ledgers/ops-unavailable.jsonl'),'broken test ledger\n')
const mount=async(module,config)=>{const fiber=await ctx.plugin(module,config);assert.equal(fiber.state,2);fibers.push(fiber);return fiber}
try{
 await mount(web);await mount(store,{root});await mount({name:'ops-accounts-fixture',apply(child){child.provide('accounts',{get:id=>users.find(user=>user.id===id),list:()=>users,can:()=>true})}});await mount(settings);await mount(teams)
 await ctx.store.append(users[1].id,'procurement/private-cost',{text:secret});await ctx.store.put(users[1].id,'review-actions',{id:'pending-review',status:'awaiting-review',body:secret},{event:'actions/proposed'});await ctx.store.put(users[1].id,'studio-proposals',{id:'proposal',status:'proposed',body:secret},{event:'studio/proposal-recorded'});await ctx.store.put('system','studio-canaries',{id:'canary',status:'rolled-back',secret},{event:'studio/canary-restored'});await ctx.store.append(users[3].id,'mail/message-received',{body:secret})
 const invitation=await ctx.teams.invite(users[1],{email:users[2].email,roleId:'lead'});await ctx.teams.answerInvite(users[2],invitation.id,true)
 const fiber=await mount(operations,{pollMs:20}),sample=ctx.operations.sample(users[0]);assert.equal(sample.coverage.totalAccounts,5);assert.equal(sample.coverage.availableAccounts,4);assert.equal(sample.coverage.unavailableAccounts,1);assert.equal(sample.coverage.complete,false);assert.equal(sample.totals.requests,null);assert.equal(sample.sources.provider,'unavailable');assert.equal(sample.collections['review-actions'].states['awaiting-review'],1);assert.equal(sample.sharedRuntime.trials,1);assert.equal(JSON.stringify(sample).includes(secret),false);assert.equal(JSON.stringify(sample).includes('pending-review'),false);checks.push('Real ledger operational counts exclude body/cost canaries and record IDs; quarantined realm explicitly reduces coverage; unavailable provider metrics are null; system canary counts use their actual source')
 assert.throws(()=>ctx.operations.sample(users[1]),error=>error.status===403);assert(ctx.operations.timeline(users[2]).some(row=>row.realm===users[1].id));assert(!ctx.operations.timeline(users[3]).some(row=>row.realm===users[1].id));assert(!ctx.operations.timeline(users[0]).some(row=>row.realm===users[1].id));assert(!JSON.stringify(ctx.operations.timeline(users[2])).includes(secret));assert.throws(()=>ctx.teams.list(users[4]),error=>error.status===503);checks.push('Separate admin gets aggregate metadata only; accepted teammate sees owner event metadata; unrelated supplier and admin timeline do not receive another party events; an unrelated quarantined account cannot break workspace discovery, while own unavailable workspace fails explicitly')
 const before=ctx.store.events(users[1].id).length;await new Promise(resolve=>setTimeout(resolve,50));const file=join(root,'operations/summary.json');assert(existsSync(file));assert(!readFileSync(file,'utf8').includes(secret));assert.equal(ctx.store.events(users[1].id).length,before);checks.push('Actual periodic atomic snapshot is readable JSON, contains only metadata and appends no account events')
 await fiber.dispose();assert.equal(existsSync(file),false);assert(!ctx.get('operations'));assert(!ctx.web.routes().some(row=>row.path==='/operations'));checks.push('Disposal removes routes, service, interval and derived snapshot while preserving ledger facts')
 const report={ok:true,root,at:new Date().toISOString(),checks};writeFileSync(join(root,'report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2))
}finally{for(const fiber of fibers.reverse())if(fiber.state!==0)await fiber.dispose()}
