import './studio.css'
import React, { useState, useEffect } from 'react'
import { ApplicationPlugins } from '../../plugin-manager/client/manager.jsx'
import { AvailableSettings } from '../../settings/client/settings.jsx'
import { EvolutionPanel } from './evolution.jsx'
import { GeneratedTool } from './generated-tool.jsx'
import { registry, useApp, useResource, api, Icon, Button, Badge, Field, PageHeader, Modal, Empty, ErrorNotice, Loading } from '../../webui/client/core.jsx'

const kindLabel = kind => ({theme:'Workspace theme',widget:'Personal widget',skill:'Workflow skill',calculator:'Personal tool'})[kind] || 'Extension'
const iconFor = kind => ({theme:'sun',skill:'spark',calculator:'grid',widget:'puzzle'})[kind] || 'puzzle'
const copy = value => JSON.parse(JSON.stringify(value))
const display = value => typeof value === 'object' ? JSON.stringify(value) : String(value ?? '')
const managedBy = (plugin,user) => plugin.canManage ?? (user.role === 'admin' || plugin.ownerId === user.id && !plugin.global)

function Studio() {
  const app = useApp(), admin = app.user.role === 'admin'
  const resource = useResource('/studio',{plugins:[],market:[],skills:[]}), evolutionSummary=useResource('/studio/evolution/summary',{counts:{}})
  const [tab,setTab] = useState(admin ? 'application' : 'mine'), [prompt,setPrompt] = useState('')
  const [busy,setBusy] = useState(''), [error,setError] = useState(''), [inspect,setInspect] = useState(null), [calculator,setCalculator] = useState(null), [configure,setConfigure] = useState(null), [evolution,setEvolution] = useState(null)
  const data = resource.data, mine = data.plugins || [], skills = mine.filter(p => p.kind === 'skill')
  const rows = tab === 'market' ? data.market || [] : tab === 'skills' ? skills : mine
  useEffect(()=>{if(app.context.pluginId){const target=mine.flatMap(row=>[row,...(row.instances||[])]).find(row=>row.id===app.context.pluginId);if(target&&managedBy(target,app.user)){setEvolution(target);app.setContext({...app.context,pluginId:undefined})}}},[app.context.pluginId,data])
  async function generate(event) {
    event.preventDefault(); if(!prompt.trim()) return
    setBusy('generate'); setError('')
    try {const response=await api('/studio/generate',{method:'POST',body:{prompt}});setPrompt('');app.refresh();app.notify(`${response.plugin?.name || 'Your extension'} is ready to use.`);setTab('mine')}
    catch(e){setError(e.message)} finally {setBusy('')}
  }
  async function act(plugin,action) {
    setBusy(plugin.id);setError('')
    try {
      const result=await api(`/studio/${encodeURIComponent(plugin.id)}/${action}`,{method:'POST',body:{}})
      app.refresh();app.notify({load:'Extension enabled in your workspace.',unload:'Extension disabled. Your workspace has been restored.',publish:'Your extension is now in the marketplace.',install:'Extension installed in your workspace.',promote:'Extension promoted to a global default.',delete:'Extension deleted.',run:'Workflow completed. Open your assistant to review the result.'}[action])
      if(action==='run')app.setAssistantOpen(true)
      return result
    }catch(e){setError(e.message);return null}finally{setBusy('')}
  }
  function installedCopy(plugin) {
    return mine.find(item=>item.id===plugin.installedId) || (plugin.installationScope==='owner' ? mine.find(item=>item.id===plugin.id) : null)
  }
  function manageMarket(plugin) {
    const local=installedCopy(plugin)
    if(local && managedBy(local,app.user)) setConfigure(local)
    else {setTab('mine');app.notify(plugin.installationScope==='global' ? 'This extension is managed by your administrator.' : 'Your installed extension is in My extensions.')}
  }
  const examples=['Give my workspace a warm sand and forest green theme.','Create a widget with a pre-submission quotation checklist.','Create a reusable skill to review deadlines and draft supplier follow-ups.']
  return <><PageHeader eyebrow={admin ? 'APPLICATION & PERSONAL EXTENSIONS' : 'BUILT AROUND YOU'} title={admin ? 'Manage every plugin.' : 'Your workspace. Your way.'} actions={<Badge status="accent"><Icon name="spark" size={12}/> Powered by your agent</Badge>}>{admin ? 'See what runs this application, configure its behavior, and manage shared extensions.' : 'Create useful extensions, adjust them to fit, and share your best ideas.'}</PageHeader>
    <div className="studio-evolution-summary" aria-label="Evolution activity">{[['proposals','proposals'],['shadowPasses','paired reviews passed'],['activeTrials','active trials'],['rollbacks','verified rollbacks']].map(([key,label])=><span key={key}><strong>{evolutionSummary.data.counts[key]||0}</strong> {label}</span>)}</div>
    <div className="tabs studio-tabs">
      {admin && <button className={tab==='application' ? 'active' : ''} onClick={()=>setTab('application')}>Application plugins</button>}
      <button className={tab==='mine' ? 'active' : ''} onClick={()=>setTab('mine')}>{admin ? 'Personal & global extensions' : 'My extensions'} <span>{mine.length}</span></button>
      <button className={tab==='market' ? 'active' : ''} onClick={()=>setTab('market')}>Marketplace <span>{data.market?.length || 0}</span></button>
      <button className={tab==='skills' ? 'active' : ''} onClick={()=>setTab('skills')}>Saved skills <span>{skills.length}</span></button>
      <button className={tab==='settings' ? 'active' : ''} onClick={()=>setTab('settings')}>Plugin settings</button>
    </div>
    {tab==='application' && admin ? <ApplicationPlugins/> : tab==='settings' ? <AvailableSettings/> : <>
      {tab!=='market' && <section className="studio-create card"><div className="studio-create-heading"><span className="extension-icon"><Icon name="puzzle" size={24}/></span><div><h2>What would make your work easier?</h2><p>A different look, a useful tool, or a repeatable workflow. Start with an idea.</p></div></div><form onSubmit={generate}><textarea aria-label="Describe an extension" rows={3} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="For example: create a calm ocean theme for my workspace…"/><div className="studio-create-footer"><span><Icon name="check" size={14}/> Built for your account · Configurable · Reversible</span><Button type="submit" icon="spark" busy={busy==='generate'} disabled={!prompt.trim()}>{busy==='generate' ? 'Building your extension…' : 'Create with AI'}</Button></div></form><div className="prompt-examples">{examples.map((example,i)=><button key={example} onClick={()=>setPrompt(example)}><Icon name={['sun','grid','spark'][i]} size={14}/>{['A personal theme','A useful widget','A workflow skill'][i]}</button>)}</div></section>}
      <ErrorNotice error={error || resource.error} retry={resource.error ? resource.reload : undefined}/>
      <div className="studio-list-heading"><p>{tab==='market' ? 'Shared extensions you can add to your workspace.' : tab==='skills' ? 'Run a saved process whenever you need a fresh result.' : 'Your installed extensions and the defaults available to your account.'}</p><span aria-live="polite">{resource.refreshing && !resource.loading ? 'Updating…' : `${rows.length} ${rows.length===1 ? 'extension' : 'extensions'}`}</span></div>
      {resource.loading ? <Loading/> : rows.length ? <div className="extensions-grid">{rows.map(plugin=>{
        const manage=managedBy(plugin,app.user), installed=plugin.installed===true, local=installedCopy(plugin)
        const active=tab==='market' ? (plugin.installedEnabled ?? local?.enabled ?? (installed && plugin.enabled)) : plugin.enabled
        return <article className="card plugin-card" key={plugin.id} data-plugin-id={plugin.id}><div className="plugin-card-heading"><span className={`extension-icon extension-${plugin.kind}`}><Icon name={iconFor(plugin.kind)} size={23}/></span><div className="plugin-badges">{plugin.global && <Badge status="blue">Global default</Badge>}{tab==='market' ? installed && <Badge status="success">Installed</Badge> : <Badge status={plugin.enabled ? 'success' : 'neutral'}>{plugin.enabled ? 'Enabled' : 'Disabled'}</Badge>}</div></div><div className="eyebrow">{kindLabel(plugin.kind).toUpperCase()}</div><h3>{plugin.name}</h3><p>{plugin.description}</p><ExtensionPreview plugin={plugin}/>
          <div className="plugin-actions">{tab==='market' ? installed ? <>{(local && managedBy(local,app.user)) || plugin.installationScope==='owner' ? <Button variant="secondary" icon="settings" onClick={()=>manageMarket(plugin)}>Manage</Button> : <span className="plugin-managed-note">{plugin.installationScope==='global' ? 'Managed by administrator' : 'Already available in your workspace'}</span>}{plugin.installationScope==='global' && !admin && <Button variant="secondary" icon="plus" busy={busy===plugin.id} onClick={()=>act(plugin,'install')}>Customize a copy</Button>}{local && !active && managedBy(local,app.user) && <Button busy={busy===local.id} onClick={()=>act(local,'load')}>Enable</Button>}</> : <Button icon="plus" busy={busy===plugin.id} onClick={()=>act(plugin,'install')}>Install in my workspace</Button> : <>
            {manage ? <><Button variant={plugin.enabled ? 'secondary' : 'primary'} busy={busy===plugin.id} onClick={()=>act(plugin,plugin.enabled ? 'unload' : 'load')}>{plugin.enabled ? 'Disable' : 'Enable'}</Button><Button variant="secondary" icon="settings" onClick={()=>setConfigure(plugin)}>Configure</Button><Button variant="secondary" onClick={()=>setEvolution(plugin)}>Improve & history</Button></> : <><span className="plugin-managed-note">Managed by administrator</span>{plugin.global && <Button variant="secondary" icon="plus" busy={busy===plugin.id} onClick={()=>act(plugin,'install')}>Customize a copy</Button>}</>}
            {plugin.kind==='skill' && <Button icon="spark" disabled={!plugin.enabled} busy={busy===plugin.id} onClick={()=>act(plugin,'run')}>Run skill</Button>}{plugin.kind==='calculator' && <Button icon="grid" disabled={!plugin.enabled} onClick={()=>setCalculator(plugin)}>Open tool</Button>}
          </>}<button className="text-button" onClick={()=>setInspect(plugin)}>View details <Icon name="chevron" size={13}/></button></div>
          <div className="plugin-sharing"><span>{admin && plugin.scopeLabels?.length ? plugin.scopeLabels.join(' · ') : plugin.global ? 'Organization default' : plugin.published ? 'Shared with the community' : plugin.ownerId===app.user.id ? 'Only in your workspace' : 'Available in your workspace'}</span>{!plugin.published && plugin.ownerId===app.user.id && manage && <button disabled={busy===plugin.id} onClick={()=>act(plugin,'publish')}>Publish to market</button>}{admin && !plugin.global && <button disabled={busy===plugin.id} onClick={()=>act(plugin,'promote')}>Promote globally</button>}</div></article>
      })}</div> : <section className="card"><Empty icon={tab==='skills' ? 'spark' : 'puzzle'} title={tab==='market' ? 'Good ideas are worth sharing' : tab==='skills' ? 'Make repeatable work easier' : 'Your next useful tool starts with an idea'}>{tab==='market' ? 'Publish an extension to make it available to others. They can install and configure their own copy.' : tab==='skills' ? 'Ask your agent to turn a process into a saved skill, then run it whenever you need a fresh result.' : 'Create a theme, widget, or automation skill tailored to your work.'}</Empty></section>}
    </>}
    {evolution && <EvolutionPanel plugin={evolution} onClose={()=>setEvolution(null)}/>}
    {calculator && <GeneratedTool plugin={calculator} onClose={()=>setCalculator(null)}/>}
    {configure && <ExtensionSettings key={configure.id} plugin={configure} onClose={()=>setConfigure(null)} onSaved={plugin=>{setConfigure(plugin);app.refresh()}}/>}
    {inspect && <Modal title={inspect.name} description={inspect.description} wide onClose={()=>setInspect(null)}><div className="extension-details">{inspect.instances?.length>1 && <Field label="Extension instance" hint="Each account installation and global default keeps its own configuration."><select aria-label="Extension instance" value={inspect.id} onChange={event=>{const selected=inspect.instances.find(item=>item.id===event.target.value);if(selected)setInspect({...selected,instances:inspect.instances,scopeLabels:inspect.scopeLabels})}}>{inspect.instances.map(instance=><option key={instance.id} value={instance.id}>{instance.global ? 'Global default' : `Personal · ${instance.ownerName || instance.ownerId}`}{instance.enabled ? ' · Enabled' : ' · Disabled'}</option>)}</select></Field>}<Badge>{kindLabel(inspect.kind)}</Badge><Badge status={inspect.enabled ? 'success' : 'neutral'}>{inspect.enabled ? 'Enabled' : 'Disabled'}</Badge><p>{inspect.global ? 'Available across the organization. Global settings are managed by an administrator.' : 'This extension can be configured or disabled without changing your business records.'}</p><h3>What it does</h3><ExtensionPreview plugin={inspect}/>{inspect.kind==='skill' && <p className="studio-preserve-lines">{inspect.spec?.prompt}</p>}{inspect.kind==='calculator' && <p>Inputs: {(inspect.spec?.fields || []).map(field=>field.label).join(', ')}</p>}<details><summary>Review extension configuration</summary><pre>{JSON.stringify(inspect.spec,null,2)}</pre></details>{inspect.source && <details><summary>Review generated plugin source</summary><pre>{inspect.source}</pre></details>}</div><div className="form-actions">{managedBy(inspect,app.user) && <><Button variant={inspect.enabled ? "secondary" : "primary"} busy={busy===inspect.id} onClick={async()=>{const result=await act(inspect,inspect.enabled ? 'unload' : 'load');if(result)setInspect({...inspect,enabled:!inspect.enabled})}}>{inspect.enabled ? 'Disable' : 'Enable'}</Button><Button variant="danger" busy={busy===inspect.id} onClick={async()=>{if(await act(inspect,'delete'))setInspect(null)}}>Delete extension</Button><Button variant="secondary" icon="settings" onClick={()=>{setConfigure(inspect);setInspect(null)}}>Configure</Button></>}<Button variant="secondary" onClick={()=>setInspect(null)}>Close</Button></div></Modal>}
  </>
}
function ExtensionPreview({plugin}) {
  if(plugin.kind==='theme') return <div className="theme-preview" style={{background:plugin.spec?.background || '#f4f7f9'}}><div className="theme-preview-sidebar" style={{background:plugin.spec?.accent || '#178679'}}/><div className="theme-preview-content"><div style={{background:plugin.spec?.text || '#18333a'}}/><div style={{background:plugin.spec?.surface || 'white'}}/><span style={{background:plugin.spec?.accent || '#178679'}}/></div></div>
  if(plugin.kind==='skill' && plugin.spec?.steps?.length) return <ol className="skill-steps">{plugin.spec.steps.slice(0,3).map((step,i)=><li key={i}>{typeof step==='string' ? step : step.description || step.title || display(step)}</li>)}</ol>
  if(plugin.kind==='widget') return <div className="widget-preview"><strong>{plugin.spec?.title || plugin.name}</strong><p>{plugin.spec?.body}</p>{plugin.spec?.items?.length>0 && <ul>{plugin.spec.items.slice(0,4).map((item,i)=><li key={i}>{display(item)}</li>)}</ul>}</div>
  return null
}

function ExtensionSettings({plugin,onClose,onSaved}) {
  const app=useApp(), [draft,setDraft]=useState(()=>copy({name:plugin.name,description:plugin.description,spec:plugin.spec || {}}))
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false)
  const set=(key,value)=>{setDraft(v=>({...v,[key]:value}));setSaved(false)}
  const spec=(key,value)=>{setDraft(v=>({...v,spec:{...v.spec,[key]:value}}));setSaved(false)}
  async function save(event){event.preventDefault();setBusy(true);setError('');try{const result=await api(`/studio/${encodeURIComponent(plugin.id)}/configure`,{method:'POST',body:{...draft,expectedRevisionId:plugin.revisionId}});const updated=result.plugin || {...plugin,...draft};setDraft(copy({name:updated.name,description:updated.description,spec:updated.spec}));onSaved(updated);setSaved(true);app.notify('Extension configuration saved.')}catch(e){setError(e.message)}finally{setBusy(false)}}
  const lines=(value)=>Array.isArray(value) ? value.map(display).join('\n') : ''
  return <Modal title={`Configure ${plugin.name}`} description={plugin.global ? 'These settings apply to the global default. Personal copies keep their own settings.' : 'Tune your own copy. Other people’s installations keep their settings.'} wide onClose={onClose}><form onSubmit={save}><ErrorNotice error={error}/>{saved && <div className="studio-saved" role="status"><Icon name="check" size={16}/> Configuration saved.</div>}<div className="form-grid"><Field label="Extension name"><input required value={draft.name} onChange={e=>set('name',e.target.value)}/></Field><Field label="Description"><input value={draft.description} onChange={e=>set('description',e.target.value)}/></Field></div>
    {plugin.kind==='theme' && <><div className="studio-color-grid">{[['accent','Accent color'],['background','Page background'],['surface','Card background'],['text','Text color']].map(([key,label])=><Field key={key} label={label}><div className="studio-color-control"><input type="color" aria-label={`${label} picker`} value={draft.spec[key] || '#ffffff'} onChange={e=>spec(key,e.target.value)}/><input aria-label={`${label} hex value`} pattern="#[0-9a-fA-F]{6}" required value={draft.spec[key] || ''} onChange={e=>spec(key,e.target.value)} spellCheck={false}/></div></Field>)}</div><Field label="Corner radius (pixels)"><input type="number" min="0" max="40" value={parseInt(draft.spec.radius,10) || 0} onChange={e=>spec('radius',`${e.target.value}px`)}/></Field><div className="studio-theme-live-preview" style={{background:draft.spec.background,color:draft.spec.text,borderRadius:draft.spec.radius}}><div style={{background:draft.spec.surface,borderRadius:draft.spec.radius}}><strong>Preview your workspace</strong><p>Clear information, in your own style.</p><span style={{background:draft.spec.accent,borderRadius:draft.spec.radius}}>Primary action</span></div></div></>}
    {plugin.kind==='widget' && <><Field label="Widget title"><input value={draft.spec.title || ''} onChange={e=>spec('title',e.target.value)}/></Field><Field label="Widget content"><textarea rows={5} value={draft.spec.body || ''} onChange={e=>spec('body',e.target.value)}/></Field><Field label="Checklist or reference items" hint="One item per line."><textarea rows={5} value={lines(draft.spec.items)} onChange={e=>spec('items',e.target.value.split('\n'))}/></Field></>}
    {plugin.kind==='skill' && <><Field label="Workflow instructions"><textarea required rows={6} value={draft.spec.prompt || ''} onChange={e=>spec('prompt',e.target.value)}/></Field><Field label="Workflow steps" hint="One step per line. Your agent follows these when you run the skill."><textarea rows={6} value={lines(draft.spec.steps)} onChange={e=>spec('steps',e.target.value.split('\n'))}/></Field></>}
    {plugin.kind==='calculator' && <><Field label="Tool title"><input value={draft.spec.title || ''} onChange={e=>spec('title',e.target.value)}/></Field><h3 className="studio-config-subheading">Input defaults</h3><div className="form-grid">{(draft.spec.fields || []).map((field,index)=><Field key={field.name} label={field.label || field.name}><input type={field.type==='number' ? 'number' : 'text'} step={field.type==='number' ? 'any' : undefined} value={field.default ?? ''} onChange={e=>spec('fields',draft.spec.fields.map((row,i)=>i===index ? {...row,default:field.type==='number' ? Number(e.target.value) : e.target.value} : row))}/></Field>)}</div><details className="studio-code-editor"><summary>Edit generated calculation code</summary><Field label="JavaScript implementation" hint="A pure function of input and workspace. Changes are checked before replacing the active tool."><textarea spellCheck={false} rows={14} value={draft.spec.code || ''} onChange={e=>spec('code',e.target.value)}/></Field></details></>}
    <div className="form-actions"><Button variant="secondary" onClick={onClose}>Close</Button><Button type="submit" busy={busy} icon="check">Save configuration</Button></div></form></Modal>
}

registry.page('extensions',{component:Studio,icon:'puzzle'})
