import assert from 'node:assert/strict'
import { mkdirSync, mkdtempSync } from 'node:fs'
import { resolve } from 'node:path'
import { Context } from '../../../../host/node_modules/cordis/lib/index.js'
import * as storePlugin from '../../../system/workspace-store/code/index.mjs'
import * as procurementPlugin from '../code/index.mjs'
import * as actionsPlugin from '../../../system/action-center/code/index.mjs'
import * as teamsPlugin from '../../../system/teams/code/index.mjs'
const buyer={id:'buyer',name:'Buyer',role:'contractor',email:'buyer@test.local',permissions:[]}, reviewer={id:'reviewer',name:'Reviewer',role:'contractor',email:'reviewer@test.local',permissions:[]}, supplier={id:'supplier',name:'Supplier',role:'supplier',email:'supplier@test.local',permissions:[]}, outsider={id:'outsider',name:'Other',role:'contractor',email:'other@test.local',permissions:[]}
const users=[buyer,reviewer,supplier,outsider],routes=[];mkdirSync('tmp',{recursive:true});const root=mkdtempSync(resolve('tmp/procurement-fulfillment-'));const checks=[]
async function mount(){const ctx=new Context(),fibers=[];fibers.push(await ctx.plugin({name:'fixture-foundation',apply(inner){inner.provide('accounts',{list:()=>structuredClone(users),get:id=>structuredClone(users.find(row=>row.id===id)),can:user=>!user.permissions?.includes('workspace:read-only')});inner.provide('web',{route:(...args)=>{routes.push(args);return()=>routes.splice(routes.indexOf(args),1)},contribute:()=>()=>{}})}}));fibers.push(await ctx.plugin(storePlugin,{root}));fibers.push(await ctx.plugin(teamsPlugin));fibers.push(await ctx.plugin(actionsPlugin));fibers.push(await ctx.plugin(procurementPlugin));return{ctx,dispose:async()=>{for(const fiber of fibers.reverse())await fiber.dispose()}}}
let mounted=await mount(),ctx=mounted.ctx
try{
 const run=(user,action,input,options)=>ctx.procurement.execute(user,action,input,options), data=user=>ctx.procurement.snapshot(user)
 const invitation=await ctx.teams.invite(buyer,{email:reviewer.email,roleId:'lead'});await ctx.teams.answerInvite(reviewer,invitation.id,true);await ctx.teams.select(reviewer,buyer.id)
 const policy=ctx.teams.state(buyer).workspace.policy;policy.currency='USD';policy.roles=policy.roles.map(role=>({...role,limit:role.id==='lead'?100000:role.id==='director'?0:0}));const policyProposal=await ctx.teams.proposePolicy(buyer,{policy,reviewerId:reviewer.id,reason:'Reviewer has sufficient USD authority; proposer limit is deliberately lower.'});await ctx.teams.decidePolicy(reviewer,policyProposal.id,{approved:true});await ctx.teams.applyPolicy(buyer,policyProposal.id)
 const review=async(action,input)=>routes.find(row=>row[0]==='POST'&&row[1]==='/workspace/review/:action')[2]({user:buyer,params:{action},body:input})
 const authorize=async(action,input)=>{const {proposal}=await review(action,input);await assert.rejects(ctx.actions.approve(buyer,proposal.id,{confirmed:true}),/different nominated/);await ctx.actions.nominate(buyer,proposal.id,{reviewerId:reviewer.id});await ctx.actions.grant(reviewer,proposal.id,{confirmed:true,reason:'Checked exact source, terms and amount'});const result=await ctx.actions.approve(buyer,proposal.id,{confirmed:true});assert.equal(result.status,'succeeded',result.error);return result}
 const rfq=(await run(buyer,'create-rfq',{title:'Bilateral fulfillment check',items:[{id:'panel',description:'LED panel',quantity:10,unit:'each'}],supplierIds:[supplier.id],currency:'USD'})).rfq;const edited=await run(reviewer,'create-rfq',{id:rfq.id,expectedRevision:rfq.revision,description:'Current shared draft'});const draftEvents=ctx.store.events(buyer.id).length;await assert.rejects(run(buyer,'create-rfq',{id:rfq.id,expectedRevision:rfq.revision,description:'Stale overwrite'}),error=>error.code==='REVISION_CONFLICT'&&error.details.currentRevision===edited.rfq.revision);assert.equal(ctx.store.events(buyer.id).length,draftEvents);assert(ctx.store.events(buyer.id).some(event=>event.type==='procurement/rfq-drafted'&&event.actor==='human:reviewer'));await run(buyer,'publish-rfq',{id:rfq.id,confirmed:true})
 const quote=(await run(supplier,'save-quote',{rfqId:rfq.id,items:[{id:'panel',unitPrice:20,cost:12}],leadDays:7,paymentTerms:'Net30',commercial:{taxMode:'exclusive',taxRate:20,freight:25,validityUntil:'2028-01-01'}})).quote;await run(supplier,'save-quote',{...quote,id:quote.id,expectedRevision:quote.revision,leadDays:8});await assert.rejects(run(supplier,'save-quote',{...quote,id:quote.id,expectedRevision:quote.revision,leadDays:20}),error=>error.code==='REVISION_CONFLICT');await run(supplier,'submit-quote',{id:quote.id,confirmed:true});const received=ctx.store.get(buyer.id,'quotes',quote.id);await assert.rejects(ctx.store.exchange(supplier.id,buyer.id,'quotes',{...received,items:received.items.map(row=>({...row,cost:9}))}),/private/i);await assert.rejects(ctx.store.exchange(supplier.id,buyer.id,'quotes',{...received,total:1}),/No recorded human decision/)
 await assert.rejects(run(buyer,'award',{quoteId:quote.id,confirmed:true}),/supplier confirmation/)
 await assert.rejects(run(buyer,'propose-award',{quoteId:quote.id,reason:'Full scope',confirmed:true},{agent:true}),/cannot commit/)
 let intent=(await run(buyer,'propose-award',{quoteId:quote.id,reason:'Complete scope with delivered price and suitable lead time',confirmed:true})).awardIntent
 assert.equal(data(supplier).awardIntents[0].quote.items[0].cost,undefined);assert.equal(data(buyer).orders.length,0)
 await assert.rejects(run(buyer,'sign-order',{id:intent.id,confirmed:true}),/supplier must confirm/)
 await run(supplier,'decline-award',{id:intent.id,reason:'Revise capacity date',confirmed:true});await assert.rejects(run(buyer,'sign-order',{id:intent.id,confirmed:true}),/supplier must confirm/)
 intent=(await run(buyer,'propose-award',{quoteId:quote.id,reason:'Reconfirmed capacity',confirmed:true})).awardIntent;await run(supplier,'confirm-award',{id:intent.id,confirmed:true})
 const approvalBefore=ctx.store.events(buyer.id).filter(row=>row.type==='procurement/human-approved').length
 await assert.rejects(run(buyer,'sign-order',{id:intent.id,confirmed:true}),/Prepare this commitment/)
 assert.equal(ctx.store.events(buyer.id).filter(row=>row.type==='procurement/human-approved').length,approvalBefore,'No approval event before independent authorization')
 const signed=await authorize('sign-order',{id:intent.id}),order=signed.result.order
 assert.equal(order.total,265);assert.equal(order.reviewActionId,signed.id);assert.equal(order.supplierConfirmedBy,supplier.id);assert.equal(order.signedBy,buyer.id)
 assert.equal((await run(buyer,'sign-order',{id:intent.id,confirmed:true})).order.id,order.id);assert.equal(data(buyer).orders.length,1);assert.equal(data(supplier).orders[0].total,265)
 assert.equal(signed.grant.actorId,reviewer.id);assert.equal(signed.review.amount,26500);assert.equal(signed.review.object.id,intent.id)
 assert.equal(ctx.store.events(buyer.id).find(row=>row.type==='procurement/human-approved'&&row.body.action==='sign-order').body.authority.reviewerId,reviewer.id)
 checks.push('Atomic compare-and-save rejects stale RFQ/quote edits without appending; team business owner and actual editor retained; public QEP policy rejects private cost and unreviewed changed money')
 checks.push('Real team authority + reviewer grant + proposer signature; supplier confirmation prerequisite; no premature PO/approval; exact tax/freight total; duplicate signature one order; private costs excluded')
 await run(supplier,'acknowledge-order',{id:order.id,confirmed:true})
 await assert.rejects(run(buyer,'propose-change',{orderId:order.id,title:'Unquoted',lines:[{itemId:'new-scope',deltaQuantity:1}],confirmed:true}),/original quoted/)
 await assert.rejects(run(buyer,'propose-change',{orderId:order.id,title:'Unstated rate',lines:[{itemId:'panel',deltaQuantity:0,newUnitPrice:22}],confirmed:true}),/Reason/)
 const change=(await run(buyer,'propose-change',{orderId:order.id,expectedOrderRevision:1,title:'Two more panels and approved coating',description:'Scope increases; revised coating rate',lines:[{itemId:'panel',deltaQuantity:2,newUnitPrice:22,rateReason:'Additional coating accepted at new rate'}],confirmed:true})).change
 assert.equal(change.lines[0].originalUnitPrice,20);assert.equal(change.proposedAmounts.total,341.8);assert.equal(change.amount,76.8)
 await assert.rejects(run(buyer,'confirm-change',{id:change.id,confirmed:true}),/other party/);await assert.rejects(run(buyer,'approve-change',{id:change.id,confirmed:true}),/other party/)
 const stale=(await run(supplier,'propose-change',{orderId:order.id,expectedOrderRevision:1,title:'Competing old base',lines:[{itemId:'panel',deltaQuantity:1}],confirmed:true})).change
 await run(supplier,'confirm-change',{id:change.id,confirmed:true});assert.equal(data(buyer).orders[0].total,265)
 const applied=await authorize('approve-change',{id:change.id});assert.equal(applied.review.amount,7680);assert.equal(applied.result.order.total,341.8);assert.equal(applied.result.order.items[0].quantity,12);assert.equal(applied.result.order.orderRevision,2)
 assert.equal(data(supplier).orders[0].items[0].unitPrice,22);assert.equal((await run(buyer,'approve-change',{id:change.id,confirmed:true})).order.total,341.8)
 await run(buyer,'settle-change',{id:change.id,confirmed:true});await run(supplier,'settle-change',{id:change.id,confirmed:true});assert.equal(data(buyer).changes[0].status,'settled')
 await assert.rejects(run(buyer,'confirm-change',{id:stale.id,confirmed:true}),/order changed/)
 await assert.rejects(run(buyer,'propose-change',{orderId:order.id,expectedOrderRevision:1,title:'Stale order',lines:[{itemId:'panel',deltaQuantity:1}],confirmed:true}),/order changed/)
 checks.push('Structured original quote/rate basis; explicit changed-rate reason + counterparty confirmation; independent absolute delta authority; precise applied scope; duplicate application and two-party closure')
 const receipt=(await run(buyer,'record-acceptance',{orderId:order.id,reference:'DEL-1',acceptedAt:'2026-09-26',lines:[{itemId:'panel',quantity:5}],deficiencies:'One carton scuffed; units inspected and accepted.',confirmed:true})).acceptance
 await assert.rejects(run(buyer,'record-acceptance',{orderId:order.id,reference:'DEL-1',lines:[{itemId:'panel',quantity:5}],confirmed:true}),/already recorded/)
 await assert.rejects(run(buyer,'record-acceptance',{orderId:order.id,reference:'OVER',lines:[{itemId:'panel',quantity:8}],confirmed:true}),/exceeds/)
 await assert.rejects(run(buyer,'propose-change',{orderId:order.id,title:'Too much removed',lines:[{itemId:'panel',deltaQuantity:-8}],confirmed:true}),/below recorded/)
 const invoice=async(number,qty,price=22,extra={})=>(await run(supplier,'record-invoice',{orderId:order.id,invoiceNumber:number,invoiceDate:'2026-09-26',currency:'USD',lines:[{itemId:'panel',quantity:qty,unitPrice:price}],taxAmount:Math.round(qty*price*20)/100,freightAmount:0,statedTotal:Math.round(qty*price*120)/100,...extra,confirmed:true})).invoice
 const bad=await invoice('BAD-1',6,23,{currency:'EUR',taxAmount:0,freightAmount:30,statedTotal:100})
 let checked=await run(buyer,'reconcile-invoice',{id:bad.id,confirmed:true});for(const code of ['arithmetic','currency','unit-price','accepted-quantity','tax','freight'])assert(checked.match.differences.some(row=>row.kind===code),code)
 const first=await invoice('INV-1',5,22,{freightAmount:25,statedTotal:157});checked=await run(buyer,'reconcile-invoice',{id:first.id,confirmed:true});assert.equal(checked.match.status,'matched')
 const second=await invoice('INV-2',6);checked=await run(buyer,'reconcile-invoice',{id:second.id,confirmed:true});assert.equal(checked.match.status,'mismatch');assert(checked.match.differences.some(row=>row.kind==='accepted-quantity'))
 await run(buyer,'record-acceptance',{orderId:order.id,reference:'DEL-2',acceptedAt:'2026-09-27',lines:[{itemId:'panel',quantity:7}],confirmed:true});checked=await run(buyer,'reconcile-invoice',{id:second.id,confirmed:true});assert.equal(checked.match.status,'matched');assert.equal(checked.match.acceptanceIds.length,2)
 const excess=await invoice('INV-EXCESS',2);checked=await run(buyer,'reconcile-invoice',{id:excess.id,confirmed:true});assert(checked.match.differences.some(row=>row.kind==='ordered-quantity'))
 const last=await invoice('INV-3',1);assert.equal((await run(buyer,'reconcile-invoice',{id:last.id,confirmed:true})).match.status,'matched')
 assert.equal(data(buyer).invoices.filter(row=>row.status==='matched').reduce((sum,row)=>sum+Math.round(row.total*100),0),34180)
 assert.equal(data(supplier).acceptances.length,2);assert.equal(data(supplier).invoiceMatches.length,data(buyer).invoiceMatches.length)
 assert.equal(data(buyer).invoiceMatches.filter(row=>row.invoiceId===second.id).length,2)
 await assert.rejects(run(buyer,'record-invoice',{orderId:order.id,invoiceNumber:'INV-1',confirmed:true}),/already recorded/)
 checks.push('Reviewed acceptance increment limits and unique sources; no reduction below accepted scope; invoice arithmetic/currency/rate/tax/freight/quantity differences; cumulative matching excludes prior billed units; new delivery resolves mismatch with history retained')
 const extraOffer=async(title)=>{const request=(await run(buyer,'create-rfq',{title,items:[{id:'x',description:'Fixture unit',quantity:1,unit:'each'}],supplierIds:[supplier.id]})).rfq;await run(buyer,'publish-rfq',{id:request.id,confirmed:true});const offer=(await run(supplier,'save-quote',{rfqId:request.id,items:[{id:'x',unitPrice:50}],commercial:{taxMode:'inclusive',freight:0}})).quote;await run(supplier,'submit-quote',{id:offer.id,confirmed:true});const intent=(await run(buyer,'propose-award',{quoteId:offer.id,reason:'Known reviewed fixture scope',confirmed:true})).awardIntent;return {request,offer,intent}}
 const withdrawn=await extraOffer('Withdrawn source check');await run(supplier,'withdraw-quote',{id:withdrawn.offer.id,reason:'Unable to meet the requirement',confirmed:true});await assert.rejects(run(supplier,'confirm-award',{id:withdrawn.intent.id,confirmed:true}),/quotation changed/);await run(buyer,'withdraw-award',{id:withdrawn.intent.id,reason:'Source offer withdrawn',confirmed:true});await run(buyer,'close-rfq',{id:withdrawn.request.id,reason:'No current offer',confirmed:true});assert.equal(data(supplier).rfqs.find(row=>row.id===withdrawn.request.id).closedReason,'No current offer')
 const deferred=await extraOffer('Durable queued signature check');await run(supplier,'confirm-award',{id:deferred.intent.id,confirmed:true});const stopHandoff=ctx.store.exchangeTransport({id:'fixture-manual-handoff',select:({collection})=>collection==='orders'?{channel:'local',mode:'manual'}:null});const queued=await authorize('sign-order',{id:deferred.intent.id});assert.equal(queued.result.deliveryPending,true);assert.equal(data(supplier).orders.some(row=>row.id===queued.result.order.id),false);const packet=queued.result.deliveries.find(row=>row.collection==='orders');assert.equal(packet.status,'queued');stopHandoff();const delivered=await ctx.store.retryDelivery(buyer.id,packet.msgId);assert.equal(delivered.received,true);assert.equal(data(supplier).orders.find(row=>row.id===queued.result.order.id).total,50);assert.equal(data(buyer).orders.filter(row=>row.awardId===deferred.intent.id).length,1)
 checks.push('Withdrawal prevents confirmation and closes source transparently; actual signed queued PO reports pending, reuses the original packet and completes delivery without a duplicate commitment')
 const humanEvents=ctx.store.events(buyer.id).filter(event=>event.type==='procurement/human-approved');assert(humanEvents.some(event=>event.body.scope.id===receipt.id));assert.equal(data(outsider).orders.length,0)
 await mounted.dispose();mounted=await mount();ctx=mounted.ctx
 assert.equal(data(buyer).orders.find(row=>row.id===order.id).total,341.8);assert.equal(data(supplier).awardIntents.find(row=>row.id===intent.id).status,'committed');assert.equal(data(buyer).invoiceMatches.filter(row=>row.invoiceId===second.id).length,2)
 assert.equal(ctx.actions.get(buyer,signed.id).grant.actorId,reviewer.id)
 checks.push('Actual durable ledger replay preserves bilateral award, independent grant, approved scope and invoice matching history in both realms')
 console.log(JSON.stringify({ok:true,root,checks,ids:{rfq:rfq.id,quote:quote.id,intent:intent.id,order:order.id,change:change.id,receipt:receipt.id,invoice:first.id,action:signed.id},events:ctx.store.events(buyer.id).length},null,2))
}finally{await mounted.dispose()}
