// Product acceptance: every business write is initiated by an ordinary visible GUI control.
import assert from 'node:assert/strict'
import {chromium} from '../../../../host/node_modules/playwright/index.mjs'
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs'
const base=process.env.BASE_URL||'http://127.0.0.1:8640/quotagent/',output=process.env.EVIDENCE_DIR||'tmp/product-evidence/fulfillment/local';mkdirSync(output,{recursive:true})
const old=process.env.FULFILLMENT_RECHECK_REPORT?JSON.parse(readFileSync(process.env.FULFILLMENT_RECHECK_REPORT,'utf8')):null
const stamp=Date.now(),title=old?.title||`[Fulfillment check] Lighting ${stamp}`,email=old?.reviewer?.email||`fulfillment-reviewer-${stamp}@local.test`,reviewerName=old?.reviewer?.name||`Fulfillment reviewer ${stamp}`,pages=[],responses=[],checks=[],errors=[],report={base,title,reviewer:{email,name:reviewerName},screenshots:[]}
const browser=await chromium.launch({headless:true,executablePath:'/opt/hermes/.playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox']})
const field=(page,label)=>page.locator('label.field').filter({has:page.getByText(label,{exact:true})}).locator('input,textarea,select').first()
async function ready(page){await page.getByRole('navigation',{name:'Main navigation'}).waitFor();for(const label of ['Not now','Hide walkthrough'])await page.getByRole('button',{name:label,exact:true}).click({timeout:1000}).catch(()=>{})}
async function fresh(email,password='demo1234'){const page=await browser.newPage({viewport:{width:1480,height:1100}});pages.push(page);page.setDefaultTimeout(18000);page.on('pageerror',e=>errors.push(e.message));page.on('response',async response=>{if(response.url().includes('/api/')&&response.request().method()!=='GET')responses.push({url:response.url(),status:response.status(),body:await response.json().catch(()=>null)})});await page.goto(base);if(email){await page.getByLabel('Email address',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await ready(page)}return page}
async function nav(page,label){
 const nav=page.getByRole('navigation',{name:'Main navigation'}),button=nav.getByRole('button',{name:label,exact:true})
 for(let attempt=0;attempt<5;attempt++){
  if(!await button.isVisible())await nav.locator('.ws-nav-group').filter({has:page.getByRole('button',{name:label,exact:true,includeHidden:true})}).locator('.ws-group-toggle').click()
  try{await button.click({timeout:2500});return}catch(error){if(attempt===4)throw error}
 }
}
async function capture(page,path,trigger){const pending=page.waitForResponse(response=>response.url().endsWith('/api/'+path)&&response.request().method()==='POST');await trigger();const response=await pending,body=await response.json();assert.equal(response.status(),200,JSON.stringify(body));return body}
const mutation=(page,action,trigger)=>capture(page,'workspace/'+action,trigger)
async function confirm(page,action){return mutation(page,action,()=>page.getByRole('button',{name:'Confirm & continue',exact:true}).click())}
async function shot(page,name){await page.screenshot({path:`${output}/${name}.png`,fullPage:true,animations:'disabled'});report.screenshots.push(name+'.png')}
async function request(page){await nav(page,'Requests');await page.getByLabel('Search requests').fill(title);await page.getByRole('button').filter({has:page.getByRole('heading',{name:title,exact:true})}).click();await page.getByRole('heading',{name:title,exact:true}).waitFor()}
async function orders(page){await nav(page,'Orders');const card=page.locator('.fulfillment-order').filter({has:page.getByRole('heading',{name:title,exact:true})});await card.waitFor();return card}
async function reviewed(buyer,reviewer,proposal){await buyer.getByLabel('Independent colleague',{exact:true}).selectOption({label:`${reviewerName} · Team lead`});await buyer.getByRole('button',{name:'Request independent review',exact:true}).click();await reviewer.reload();await nav(reviewer,'Review actions');await reviewer.locator('.review-list-row').filter({hasText:proposal.title}).click();await shot(reviewer,`review-${report.screenshots.length}`);await capture(reviewer,`actions/${proposal.id}/grant`,()=>reviewer.getByRole('button',{name:'Grant independent approval',exact:true}).click());await buyer.reload();await buyer.locator('.review-list-row').filter({hasText:proposal.title}).click();await buyer.getByRole('button',{name:'Sign & execute',exact:true}).waitFor();const signed=await capture(buyer,`actions/${proposal.id}/approve`,()=>buyer.getByRole('button',{name:'Sign & execute',exact:true}).click());assert.equal(signed.action.status,'succeeded',signed.action.error);return signed.action.result}
try{
 const buyer=await fresh('contractor@demo.local'),supplier=await fresh('supplier@demo.local')
 if(old){const buyerOrder=await orders(buyer);await buyerOrder.getByRole('button',{name:/^Invoices/}).click();await buyerOrder.getByText('Matches approved scope and acceptance',{exact:true}).waitFor();await shot(buyer,'restart-matching-history');const supplierOrder=await orders(supplier);await supplierOrder.getByRole('button',{name:/^Delivery/}).click();await supplierOrder.getByRole('heading',{name:`DEL-2-${old.stamp}`,exact:true}).waitFor();await shot(supplier,'restart-counterparty-receipts');checks.push('Process replay preserves approved order scope, invoice matching history and both supplier delivery receipts');report.ids=old.ids;report.stamp=old.stamp}
 else{
 const reviewer=await fresh();await reviewer.getByRole('button',{name:'Create an account',exact:true}).click();await reviewer.getByLabel('Your name',{exact:true}).fill(reviewerName);await reviewer.getByLabel('Company',{exact:true}).fill('Review colleague');await reviewer.getByLabel('Email address',{exact:true}).fill(email);await reviewer.getByLabel('Password',{exact:true}).fill('fulfillment-local-pass');await reviewer.getByRole('button',{name:'Create workspace',exact:true}).click();await ready(reviewer)
 await nav(buyer,'My day & team');await buyer.getByRole('button',{name:'Colleagues',exact:true}).click();await buyer.getByRole('button',{name:'Invite colleague',exact:true}).click();let dialog=buyer.getByRole('dialog');await dialog.getByLabel('Colleague email',{exact:true}).fill(email);await dialog.getByLabel('Team role',{exact:true}).selectOption('lead');await dialog.getByRole('button',{name:'Send invitation',exact:true}).click();await dialog.waitFor({state:'hidden'});await nav(reviewer,'My day & team');await reviewer.getByRole('button',{name:'Accept invitation',exact:true}).click();await capture(reviewer,'teams/select',()=>reviewer.getByLabel('Active party workspace',{exact:true}).selectOption({label:'Northstar Construction'}));await reviewer.waitForFunction(()=>!document.querySelector('[aria-label="Active party workspace"]').disabled);await nav(reviewer,'My day & team')
 await buyer.getByRole('button',{name:/^Authority/}).click();await buyer.getByRole('button',{name:'Propose authority changes',exact:true}).click();dialog=buyer.getByRole('dialog');await dialog.getByLabel('Limit type for Director',{exact:true}).selectOption('amount');await dialog.getByLabel('Amount in USD for Director',{exact:true}).fill('0');await dialog.getByLabel('Limit type for Team lead',{exact:true}).selectOption('amount');await dialog.getByLabel('Amount in USD for Team lead',{exact:true}).fill('10000');await dialog.getByLabel('Independent reviewer',{exact:true}).selectOption({label:`${reviewerName} · Team lead`});await dialog.getByLabel('Reason for change',{exact:true}).fill('Independent reviewer covers the commitment; proposer must still sign separately.');await dialog.getByRole('button',{name:'Request policy review',exact:true}).click();await dialog.waitFor({state:'hidden'});await reviewer.reload();await nav(reviewer,'My day & team');await reviewer.getByRole('button',{name:/^Authority/}).click();await reviewer.locator('.team-policy-proposal').filter({has:reviewer.getByRole('button',{name:'Approve policy',exact:true})}).first().getByRole('button',{name:'Approve policy',exact:true}).click();await buyer.reload();await buyer.getByRole('button',{name:/^Authority/}).click();await buyer.locator('.team-policy-proposal').first().getByRole('button',{name:'Apply approved policy',exact:true}).click();await buyer.locator('.team-policy-proposal').first().getByText('applied',{exact:true}).waitFor();checks.push('New colleague explicitly invited and accepted; different human approves exact authority policy; reviewer limit covers order while proposer limit is zero')
 await nav(buyer,'Requests');await buyer.getByRole('button',{name:'New request',exact:true}).click();await field(buyer,'Request title').fill(title);await field(buyer,'Project brief').fill('Ten panels, delivered with declared tax and freight. Use a bilateral award and retain receipts.');await buyer.getByLabel('Item 1 description',{exact:true}).fill('LED panel');await buyer.getByLabel('Item 1 quantity',{exact:true}).fill('10');await buyer.locator('.supplier-options label').filter({hasText:'supplier@demo.local'}).getByRole('checkbox').check();const created=await mutation(buyer,'create-rfq',()=>buyer.getByRole('button',{name:'Save request draft',exact:true}).click());await buyer.getByRole('button',{name:'Publish request',exact:true}).click();await confirm(buyer,'publish-rfq')
 await request(supplier);await supplier.getByRole('button',{name:'Prepare quote',exact:true}).click();await supplier.getByLabel('Unit price for LED panel',{exact:true}).fill('20');await supplier.getByLabel('Private cost for LED panel',{exact:true}).fill('12');const drafted=await mutation(supplier,'save-quote',()=>supplier.getByRole('button',{name:'Save quotation draft',exact:true}).click());await nav(supplier,'Commercial workbench');await supplier.getByLabel('Workbench request',{exact:true}).selectOption(created.rfq.id);await supplier.getByRole('tab',{name:'Commercial terms',exact:true}).click();await supplier.getByLabel('Tax treatment',{exact:true}).selectOption('exclusive');await supplier.getByLabel('Tax rate (%)',{exact:true}).fill('20');await supplier.getByLabel('Freight charge',{exact:true}).fill('25');await supplier.getByLabel('Quote valid until',{exact:true}).fill('2028-01-01');await capture(supplier,'commercial/save-terms',()=>supplier.getByRole('button',{name:'Save commercial terms to draft',exact:true}).click());await request(supplier);await supplier.getByRole('button',{name:'My quotes',exact:true}).click();await supplier.getByRole('button',{name:'Review & submit',exact:true}).click();await confirm(supplier,'submit-quote')
 await request(buyer);await buyer.getByRole('button',{name:'Compare offers',exact:true}).click();await buyer.getByRole('button',{name:'Propose award',exact:true}).click();await field(buyer,'Selection reason').fill('Complete declared scope and suitable delivery; total includes 20% tax and 25 freight.');await shot(buyer,'01-nonbinding-intent-review');const proposed=await mutation(buyer,'propose-award',()=>buyer.getByRole('button',{name:'Send nonbinding award intent',exact:true}).click());assert.equal(proposed.awardIntent.total,265);assert.equal(await buyer.locator('.fulfillment-order').filter({has:buyer.getByRole('heading',{name:title,exact:true})}).count(),0);await nav(supplier,'Orders');const intent=supplier.locator('.fulfillment-intents .fulfillment-record').filter({has: supplier.getByRole('heading',{name:title,exact:true})});await intent.getByRole('button',{name:'Confirm award intent',exact:true}).click();await shot(supplier,'02-supplier-confirms-offer');await confirm(supplier,'confirm-award');await buyer.reload();const buyerIntent=buyer.locator('.fulfillment-intents .fulfillment-record').filter({has:buyer.getByRole('heading',{name:title,exact:true})});const signProposal=await mutation(buyer,'review/sign-order',()=>buyerIntent.getByRole('button',{name:'Prepare order for review',exact:true}).click());const signed=await reviewed(buyer,reviewer,signProposal.proposal);assert.equal(signed.order.total,265);await shot(buyer,'03-independent-signature-receipt');checks.push('GUI RFQ and private quote; declared tax/freight; nonbinding intent creates no PO; supplier confirms exact offer; independent colleague grants and proposer signs one265USD order')
 let order=await orders(supplier);await order.getByRole('button',{name:'Acknowledge order',exact:true}).click();await confirm(supplier,'acknowledge-order');order=await orders(buyer);await order.getByRole('button',{name:'Propose change',exact:true}).click();dialog=buyer.getByRole('dialog');await dialog.getByLabel('Change title',{exact:true}).fill('Additional panels and coating');await dialog.getByLabel('What changed, and why?',{exact:true}).fill('Two additional panels with agreed coating upgrade.');await dialog.locator('.fulfillment-line-edit').getByRole('checkbox').check();await dialog.getByLabel('Quantity change for LED panel',{exact:true}).fill('2');await dialog.getByLabel('New unit price for LED panel',{exact:true}).fill('22');await dialog.getByLabel('Rate change reason for LED panel',{exact:true}).fill('Agreed additional coating at2 per unit');await dialog.getByRole('button',{name:'Review line changes',exact:true}).click();await dialog.getByRole('heading',{name:'Review the exact change',exact:true}).waitFor();await shot(buyer,'04-sourced-change-review');const change=await mutation(buyer,'propose-change',()=>dialog.getByRole('button',{name:'Confirm & send change proposal',exact:true}).click());assert.equal(change.change.amount,76.8);order=await orders(supplier);await order.getByRole('button',{name:/^Changes/}).click();await order.getByRole('button',{name:'Confirm change',exact:true}).click();await confirm(supplier,'confirm-change');order=await orders(buyer);await order.getByRole('button',{name:/^Changes/}).click();const changeReview=await mutation(buyer,'review/approve-change',()=>order.getByRole('button',{name:'Prepare change for review',exact:true}).click());const revised=await reviewed(buyer,reviewer,changeReview.proposal);assert.equal(revised.order.total,341.8);assert.equal(revised.order.items[0].quantity,12);await shot(buyer,'05-approved-change-receipt');checks.push('GUI change traces original20USD rate, quantity10→12 and rate20→22 with reason; counterparty confirms, independent approval applies76.80USD once')
 async function delivery(reference,quantity){const card=await orders(buyer);await card.getByRole('button',{name:/^Delivery/}).click();await card.getByRole('button',{name:'Record delivery',exact:true}).click();const modal=buyer.getByRole('dialog');await modal.getByLabel('Delivery reference',{exact:true}).fill(reference);await modal.getByLabel('Delivery date',{exact:true}).fill('2026-09-26');await modal.getByLabel('Accepted quantity for LED panel',{exact:true}).fill(String(quantity));await modal.getByRole('checkbox').check();return mutation(buyer,'record-acceptance',()=>modal.getByRole('button',{name:'Confirm delivery acceptance',exact:true}).click())}
 await delivery(`DEL-1-${stamp}`,5);order=await orders(supplier);await order.getByRole('button',{name:/^Invoices/}).click();await order.getByText('PURCHASE ORDER · REVISION 2',{exact:true}).waitFor();await order.getByRole('button',{name:'Record source invoice',exact:true}).click();dialog=supplier.getByRole('dialog');await dialog.getByLabel('Invoice reference',{exact:true}).fill(`INV-${stamp}`);await dialog.getByLabel('Invoice date',{exact:true}).fill('2026-09-26');await dialog.getByLabel('Invoice quantity for LED panel',{exact:true}).fill('12');await dialog.getByLabel('Invoice unit price for LED panel',{exact:true}).fill('22');await dialog.getByLabel('Added tax on invoice',{exact:true}).fill('52.80');await dialog.getByLabel('Invoice freight',{exact:true}).fill('25');await dialog.getByLabel('Stated invoice total',{exact:true}).fill('341.80');await dialog.getByRole('checkbox').check();const invoice=await mutation(supplier,'record-invoice',()=>dialog.getByRole('button',{name:'Confirm invoice record',exact:true}).click());order=await orders(buyer);await order.getByRole('button',{name:/^Invoices/}).click();await order.getByRole('button',{name:'Reconcile invoice',exact:true}).click();const mismatch=await confirm(buyer,'reconcile-invoice');assert.equal(mismatch.match.status,'mismatch');await shot(buyer,'06-invoice-missing-acceptance');await delivery(`DEL-2-${stamp}`,7);order=await orders(buyer);await order.getByRole('button',{name:/^Invoices/}).click();await order.getByRole('button',{name:'Recheck invoice',exact:true}).click();const matched=await confirm(buyer,'reconcile-invoice');assert.equal(matched.match.status,'matched');await order.getByText('Matches approved scope and acceptance',{exact:true}).waitFor();await order.getByText('Matching history (2)',{exact:true}).click();await shot(buyer,'07-invoice-reconciliation-history');checks.push('Partial delivery5 causes invoice12 mismatch; reviewed further delivery7 permits a fresh match; prior mismatch remains visible with source receipts and order revision')
 order=await orders(supplier);await order.getByRole('button',{name:/^Delivery/}).click();await order.getByRole('heading',{name:`DEL-2-${stamp}`,exact:true}).waitFor();await shot(supplier,'08-counterparty-delivery-proof');await buyer.setViewportSize({width:390,height:900});await shot(buyer,'09-mobile-matching');assert.equal(await buyer.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);checks.push('Supplier sees shared receipt sources; mobile invoice history stays within viewport');report.ids={rfq:created.rfq.id,quote:drafted.quote.id,intent:proposed.awardIntent.id,order:signed.order.id,change:change.change.id,invoice:invoice.invoice.id,signature:signProposal.proposal.id};report.stamp=stamp
 }
 assert.deepEqual(errors,[]);Object.assign(report,{ok:true,checks,errors,completedAt:new Date().toISOString()});console.log(JSON.stringify(report,null,2))
}catch(error){report.error=error.stack;report.checks=checks;report.errors=errors;for(const [i,page] of pages.entries()){await shot(page,`failure-${i}`).catch(()=>{});writeFileSync(`${output}/failure-${i}.txt`,await page.locator('body').innerText().catch(()=>''))}console.error(JSON.stringify(report,null,2));process.exitCode=1}
finally{writeFileSync(`${output}/report.json`,JSON.stringify(report,null,2)+'\n');writeFileSync(`${output}/responses.json`,JSON.stringify(responses,null,2)+'\n');await browser.close()}
