// Public GUI-only cancellation regression; the provider creates the plan and begins real workers.
import {chromium} from '../../../../host/node_modules/playwright/index.mjs'
import {mkdirSync,readFileSync,writeFileSync} from 'node:fs'
const base=(process.env.BASE_URL||'https://novara.remoteblossom.com/quotagent').replace(/\/$/,'')+'/'
const out=process.env.EVIDENCE_DIR||'tmp/product-evidence/workroom/cancellation/public';mkdirSync(out,{recursive:true})
const report={base,startedAt:new Date().toISOString(),checks:[],pageErrors:[]},persist=()=>writeFileSync(out+'/report.json',JSON.stringify(report,null,2)+'\n')
const browser=await chromium.launch({headless:true,executablePath:'/opt/hermes/.playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox']})
let page,state
const check=(condition,message)=>{if(!condition)throw new Error(message);report.checks.push(message);persist();console.log('PASS '+message)}
const waitState=async predicate=>{for(let n=0;n<180;n++){if(state&&predicate(state))return state;await page.waitForTimeout(500)}throw new Error('Expected workflow state did not arrive: '+JSON.stringify(state&&{status:state.status,steps:state.steps.map(step=>step.status)}))}
try{
 page=await browser.newPage({viewport:{width:1512,height:1000}});page.setDefaultTimeout(30000);page.on('pageerror',error=>report.pageErrors.push(error.message));page.on('response',async response=>{if(response.request().method()==='GET'&&/\/api\/workflows\/[^/]+$/.test(response.url()))try{state=(await response.json()).run}catch{}})
 await page.goto(base);await page.getByLabel('Email address').fill('supplier2@demo.local');await page.getByLabel('Password',{exact:true}).fill('demo1234');await page.getByRole('button',{name:'Sign in',exact:true}).click();const nav=page.getByRole('navigation',{name:'Main navigation'});await nav.getByRole('button',{name:'Agent workroom',exact:true}).click()
 const previous=JSON.parse(readFileSync('tmp/product-evidence/workroom/recovery/report.json'))
 await page.locator('.workroom-run-card').filter({hasText:previous.objective}).click();await waitState(run=>run.id===previous.runId)
 check(state.status==='cancelled'&&state.steps.every(step=>['completed','cancelled'].includes(step.status)),'Historical cancelled run is reconciled with no task showing Working')
 check(state.traces.some(trace=>trace.event==='cancellation-reconciled'),'Reconciliation is an appended visible event preserving prior history');report.reconciledRun=state;await page.screenshot({path:out+'/01-reconciled-existing-run.png',fullPage:true})
 await page.getByRole('button',{name:'New agent run',exact:true}).click();report.objective=`[Cancellation recheck ${Date.now()}] Inspect my current opportunities with four independent specialists: scope, commercial, delivery, and source-integrity. Plan exactly four bounded tasks. Read the actual RFQ and private offer records and prepare evidence-backed reports. Do not ask questions, create drafts or make external commitments.`
 await page.getByLabel('Agent team objective',{exact:true}).fill(report.objective);await page.getByRole('dialog').locator('input[type=checkbox]').check();await page.getByRole('button',{name:'Create agent plan',exact:true}).click();await waitState(run=>run.id!==previous.runId&&run.status==='awaiting-plan');report.runId=state.id;check(state.steps.length===4,'Real provider produced four independent specialist tasks for the cancellation boundary')
 await page.getByRole('button',{name:'Approve plan & start agents',exact:true}).click();await waitState(run=>run.status==='running'&&run.traces.some(trace=>trace.event==='agent-started'));report.beforeCancellation=state;await page.screenshot({path:out+'/02-specialists-running.png',fullPage:true})
 await page.getByRole('button',{name:'Cancel run',exact:true}).click();await page.locator('.workroom-run-summary').getByText('Cancelled',{exact:true}).waitFor();await page.waitForTimeout(11000)
 const [response]=await Promise.all([page.waitForResponse(response=>response.request().method()==='GET'&&response.url().endsWith('/api/workflows/'+report.runId)),page.getByRole('button',{name:'Refresh status',exact:true}).click()]);state=(await response.json()).run
 check(state.status==='cancelled'&&state.steps.every(step=>['completed','cancelled'].includes(step.status)),'Cancellation remains terminal for every unfinished specialist after delayed refresh')
 const cancelledAt=state.traces.findIndex(trace=>trace.event==='cancelled');check(cancelledAt>=0&&!state.traces.slice(cancelledAt+1).some(trace=>trace.event==='agent-started'),'Activity contains no specialist start after human cancellation');report.afterCancellation=state
 await page.reload();await nav.getByRole('button',{name:'Agent workroom',exact:true}).click();await page.locator('.workroom-run-card').filter({hasText:report.objective}).click();await page.locator('.workroom-run-summary').getByText('Cancelled',{exact:true}).waitFor();await waitState(run=>run.id===report.runId&&run.status==='cancelled');check(state.steps.every(step=>['completed','cancelled'].includes(step.status)),'Terminal task states survive full page reload');await page.screenshot({path:out+'/03-cancelled-after-reload.png',fullPage:true});check(report.pageErrors.length===0,'Public cancellation journey has no browser JavaScript errors');report.ok=true
}catch(error){report.ok=false;report.failure=error.message;console.error(error);if(page)await page.screenshot({path:out+'/failure.png',fullPage:true}).catch(()=>{});process.exitCode=1}finally{report.finishedAt=new Date().toISOString();persist();console.log(JSON.stringify({ok:report.ok,checks:report.checks.length,runId:report.runId,failure:report.failure}));await browser.close()}
