import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {mkdirSync,mkdtempSync,writeFileSync} from 'node:fs'
import {resolve,join} from 'node:path'
import * as store from '../../workspace-store/code/index.mjs'
import * as settings from '../../settings/code/index.mjs'
import * as workflows from '../code/index.mjs'
const require=createRequire(new URL('../../../../host/package.json',import.meta.url)),{Context}=require('cordis'),ctx=new Context(),fibers=[],calls=[],tools=[],registered=new Map(),users=[{id:'workflow-scope-user',role:'contractor'}];let selected='team-a'
mkdirSync('tmp',{recursive:true});const root=mkdtempSync(resolve('tmp/workflow-scope-')),user=users[0],wait=async(fn)=>{for(let i=0;i<400;i++){if(fn())return;await new Promise(resolve=>setTimeout(resolve,10))}throw new Error('Native workflow did not settle')}
const mount=async(module,config)=>{const fiber=await ctx.plugin(module,config);assert.equal(fiber.state,2);fibers.push(fiber)}
const plan={title:'Scoped fixture plan',summary:'Two independent scope checks',steps:['one','two'].map(id=>({id,title:id,role:'Scope reader',task:'Read source only',dependsOn:[]}))}
try{
 await mount({name:'workflow-scope-fixture',apply(child){child.provide('accounts',{get:id=>users.find(row=>row.id===id),list:()=>users,can:()=>true});child.provide('web',{route:()=>()=>{},contribute:()=>()=>{}});child.provide('teams',{scope:who=>({team:{id:who.workspaceOwnerId||selected,name:'Fixture team'},member:{roleId:'owner'}})});child.provide('actions',{register:()=>()=>{},propose:async()=>{throw new Error('This read-only fixture must not propose commitments')}});child.provide('assistant',{tool:item=>{registered.set(item.name,item);return()=>registered.delete(item.name)},definitions:()=>[{type:'function',function:{name:'procurement_workspace',parameters:{type:'object',properties:{}}}}],invoke:async(who,request)=>{tools.push({role:who.role,workspaceOwnerId:who.workspaceOwnerId,runId:request.context.runId});return{rfqs:[],fixture:true}}});child.provide('ai',{complete:async(who,request)=>{calls.push({role:who.role,workspaceOwnerId:who.workspaceOwnerId,runId:request.runId});if(request.purpose.endsWith(':planner'))return{role:'assistant',content:JSON.stringify(plan)};if(request.purpose.endsWith(':synthesis'))return{role:'assistant',content:'Recorded fixture synthesis'};if(!request.messages.some(row=>row.role==='tool'))return{role:'assistant',tool_calls:[{id:'read-source',type:'function',function:{name:'procurement_workspace',arguments:'{}'}}]};return{role:'assistant',content:'Recorded fixture source result'}}})}})
 await mount(store,{root:join(root,'data')});await mount(settings);await mount(workflows)
 const run=await ctx.workflows.start(user,{objective:'Read team A',checkpoint:true});await wait(()=>ctx.workflows.get(user,run.id).status==='awaiting-plan');selected='team-b';await ctx.workflows.control(user,run.id,{action:'resume'});await wait(()=>ctx.workflows.get(user,run.id).status==='completed');assert.ok(calls.filter(row=>row.runId===run.id).every(row=>row.workspaceOwnerId==='team-a'));assert.ok(tools.filter(row=>row.runId===run.id).every(row=>row.workspaceOwnerId==='team-a'));assert.equal(ctx.workflows.get(user,run.id).accountRole,'contractor')
 const paused=await ctx.workflows.start(user,{objective:'Buyer perspective must remain fixed',checkpoint:true});await wait(()=>ctx.workflows.get(user,paused.id).status==='awaiting-plan');const before=calls.length;user.role='supplier';await assert.rejects(ctx.workflows.control(user,paused.id,{action:'resume'}),error=>error.code==='account-role-changed');assert.equal(calls.length,before);await ctx.workflows.control(user,paused.id,{action:'cancel'});const next=await ctx.workflows.start(user,{objective:'New supplier perspective',checkpoint:false});await wait(()=>ctx.workflows.get(user,next.id).status==='completed');assert.ok(calls.filter(row=>row.runId===next.id).every(row=>row.role==='supplier'&&row.workspaceOwnerId==='team-b'));assert.ok(tools.filter(row=>row.runId===next.id).every(row=>row.role==='supplier'))
 const report={ok:true,root,checks:['Native Cordis workflow pins all model/tool calls to original team across selected-workspace change','Changing account business perspective rejects resume without dispatch; cancel and a new correctly scoped run remain available'],modelCalls:calls.length,toolCalls:tools.length};writeFileSync(join(root,'report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2))
}finally{for(const fiber of fibers.reverse())await fiber.dispose()}
