import {randomUUID} from 'node:crypto'
export const name='artifact-retention'
export const inject=['store','web','accounts','files','settings','actions']
export const provides=['retention']
const now=()=>new Date().toISOString(),fail=(message,status=400)=>{throw Object.assign(new Error(message),{status})}
export async function apply(ctx){
 const realm=user=>user.role==='admin'?user.id:ctx.get('procurement')?.realm(user)||user.id,scope=(user,id=realm(user))=>({...ctx.accounts.get(id),actorId:user.id,permissions:user.permissions||[]})
 const manage=user=>{const id=realm(user);if(user.id!==id||!ctx.accounts.can(user,'workspace:write'))fail('Only this party workspace owner can change retention or dispose its files.',403);return id}
 ctx.effect(()=>ctx.settings.define({id:'retention',name:'File retention',scope:'account',defaults:{retentionDays:30,kinds:'upload,attachment,received-attachment,audit-export',includeActive:false},fields:[{key:'retentionDays',label:'Minimum age in days',type:'number',min:0,max:36500},{key:'kinds',label:'File kinds eligible for review',type:'text',description:'Comma-separated upload, attachment, received-attachment, audit-export. Unknown kinds remain retained.'},{key:'includeActive',label:'Also review unarchived library files',type:'boolean',description:'Current object references and named holds still prevent disposal. Nothing is automatically deleted.'}]}))
 ctx.effect(()=>ctx.settings.define({id:'retention-project',name:'Project file retention constraints',scope:'user',scopes:['project'],defaults:{retentionDays:0,kinds:'upload,attachment,received-attachment,audit-export',includeActive:true},description:'Additional constraints for files attached to this party’s own projects. The strictest applicable project and account policies apply; another party’s project never grants settings access.',fields:[{key:'retentionDays',label:'Additional minimum age in days',type:'number',min:0,max:36500},{key:'kinds',label:'Permitted file kinds',type:'text'},{key:'includeActive',label:'Permit review of unarchived files',type:'boolean'}]}))
 const projectChoices=user=>ctx.store.list(realm(user),'projects').filter(project=>project.ownerId===realm(user)).map(project=>{try{return{id:project.id,name:project.name,policy:ctx.settings.get(scope(user),'retention-project',{workspaceId:realm(user),projectId:project.id})}}catch(error){return{id:project.id,name:project.name,policy:null,error:error.message,unavailable:true}}})
 const fileProjects=(user,file)=>{const party=realm(user),references=ctx.store.list(party,'object-attachments').filter(row=>row.fileId===file.id),resources=ctx.store.list(party,'attachment-resources').filter(row=>row.fileId===file.id),incoming=ctx.store.list(party,'attachment-deliveries').filter(row=>resources.some(resource=>resource.id===row.attachmentId)),ids=new Set();for(const reference of [...references,...incoming]){const source=ctx.store.get(party,{rfq:'rfqs',quote:'quotes',order:'orders',change:'changes'}[reference.kind],reference.objectId),rfq=reference.kind==='rfq'?source:ctx.store.get(party,'rfqs',source?.rfqId);if(rfq?.projectId&&ctx.store.get(party,'projects',rfq.projectId)?.ownerId===party)ids.add(rfq.projectId)}return projectChoices(user).filter(project=>ids.has(project.id))}
 const holds=user=>ctx.store.list(realm(user),'retention-holds')
 ctx.effect(()=>ctx.files.guard({id:'retention-holds',check(user,file){const current=ctx.store.list(user.id,'retention-holds').find(row=>!row.releasedAt&&(row.all||row.fileIds.includes(file.id)));return{allowed:!current,reason:current?`Retained by hold “${current.name}”: ${current.reason}`:null}}}))
 const preview=async user=>{const owner=scope(user),policy=ctx.settings.get(owner,'retention'),rows=[];for(const file of ctx.files.all(owner)){const projects=fileProjects(user,file),policies=[policy,...projects.map(project=>project.policy).filter(Boolean)],effective={retentionDays:Math.max(...policies.map(value=>value.retentionDays)),includeActive:policies.every(value=>value.includeActive)},allowedKinds=policies.map(value=>new Set(String(value.kinds).split(',').map(kind=>kind.trim()).filter(Boolean))),eligible=await ctx.files.eligibility(owner,file.id),ageDays=Math.max(0,(Date.now()-Date.parse(file.createdAt))/86400000),reasons=[...eligible.reasons];if(projects.some(project=>project.unavailable))reasons.push('A project retention policy is unavailable. Keep this copy until its owning scope plugin is restored.');if(!ctx.get('attachments')&&(ctx.store.list(owner.id,'object-attachments').some(row=>row.fileId===file.id)||ctx.store.list(owner.id,'attachment-resources').some(row=>row.fileId===file.id)))reasons.push('Enable Object attachments to check current object references before disposal.');if(file.disposedAt)reasons.push('This file record was already disposed.');if(!Number.isFinite(ageDays)||ageDays<effective.retentionDays)reasons.push(`Keep until the minimum age of ${effective.retentionDays} days${projects.length?' under account/project policies':''}.`);if(!allowedKinds.every(kinds=>kinds.has(file.kind||'upload')))reasons.push('This file kind is not included in the retention policy.');if(!effective.includeActive&&!file.archivedAt&&!file.deletedAt)reasons.push('Archive this library copy first, or explicitly allow active library files in the policy.');if(!['available','missing','disposed'].includes(eligible.storage.state))reasons.push('Inspect the unavailable or corrupt content before preparing disposal.');rows.push({...file,projectPolicies:projects.map(project=>({projectId:project.id,name:project.name,...project.policy})),effectivePolicy:effective,ageDays:Number.isFinite(ageDays)?Math.floor(ageDays):null,storage:eligible.storage,eligible:eligible.allowed&&!reasons.length,reasons})}return{realm:owner.id,canManage:user.id===owner.id,policy,projects:projectChoices(user),summary:ctx.files.summary(owner),files:rows.sort((a,b)=>b.createdAt.localeCompare(a.createdAt)),holds:holds(user),reports:ctx.store.list(owner.id,'retention-reports').slice(-100).reverse(),notice:'Only reviewed local file copies can be disposed. The append-only ledger, exported packages and counterparty copies remain unchanged.'}}
 const configure=async(user,input)=>{manage(user);return ctx.settings.save(scope(user),'retention',{values:input.values})}
 const configureProject=async(user,input)=>{const party=manage(user),project=ctx.store.get(party,'projects',input.projectId);if(!project||project.ownerId!==party)fail('Choose a project owned by this party workspace.',403);return ctx.settings.save(scope(user),'retention-project',{scope:'project',context:{workspaceId:party,projectId:project.id},values:input.values})}
 const hold=async(user,input)=>{const id=manage(user),name=String(input.name||'').trim(),reason=String(input.reason||'').trim(),fileIds=[...new Set(input.fileIds||[])];if(!name||!reason||!input.all&&!fileIds.length)fail('Name the hold, give a reason and choose files or all copies.');for(const fileId of fileIds)ctx.files.get(scope(user),fileId,{includeDeleted:true,includeDisposed:true});const record={id:`hold-${randomUUID()}`,name:name.slice(0,160),reason:reason.slice(0,2000),all:!!input.all,fileIds,createdAt:now(),createdBy:user.id,releasedAt:null};await ctx.store.put(id,'retention-holds',record,{event:'retention/hold-applied',actor:`human:${user.id}`});return{ok:true,hold:record}}
 const release=async(user,id,input)=>{const party=manage(user),old=ctx.store.get(party,'retention-holds',id);if(!old)fail('Hold not found.',404);if(!input.confirmed||!String(input.reason||'').trim())fail('Confirm releasing this hold and record the reason.');if(old.releasedAt)return{ok:true,hold:old,duplicate:true};const record={...old,releasedAt:now(),releasedBy:user.id,releaseReason:String(input.reason).trim().slice(0,2000)};await ctx.store.put(party,'retention-holds',record,{event:'retention/hold-released',actor:`human:${user.id}`});return{ok:true,hold:record}}
 const propose=async(user,input)=>{const party=manage(user),data=await preview(user),ids=[...new Set(input.fileIds||[])],reason=String(input.reason||'').trim();if(!ids.length||!reason)fail('Choose eligible files and record the disposal reason.');const files=ids.map(id=>data.files.find(row=>row.id===id));if(files.some(row=>!row?.eligible))fail('A selected file is no longer eligible. Refresh the preview and inspect its reasons.',409);const frozen={workspaceId:party,reason,files:files.map(row=>({id:row.id,filename:row.filename,sha256:row.sha256,size:row.size,kind:row.kind||'upload'})),preparedAt:now()};const action=await ctx.actions.propose(user,{kind:'retention.dispose',title:`Dispose ${files.length} reviewed file ${files.length===1?'copy':'copies'}`,summary:`Remove eligible local bytes for: ${reason}. The ledger and counterparty copies remain.`,input:frozen,source:{kind:'human',view:'retention'},idempotencyKey:input.idempotencyKey});return{ok:true,proposal:action,action:{type:'navigate',input:{view:'approvals',actionId:action.id},label:'Review exact disposal'}}}
 ctx.effect(()=>ctx.actions.register({kind:'retention.dispose',label:'Dispose reviewed file copies',async execute(user,input,action,{signal}){const pinned={...user,workspaceOwnerId:input.workspaceId};if(manage(pinned)!==input.workspaceId)fail('This review belongs to a different party workspace.',403);const data=await preview(pinned),results=[];for(const file of input.files){const current=data.files.find(row=>row.id===file.id);if(!current||current.sha256!==file.sha256||!current.eligible)fail(`The reviewed file “${file.filename}” is no longer eligible. Prepare a fresh review.`,409)}const id=`disposal-${action.id}`,prior=ctx.store.get(input.workspaceId,'retention-reports',id);if(prior?.status==='complete')return{ok:true,report:prior,duplicate:true,action:{type:'navigate',input:{view:'retention',reportId:id},label:'Open disposal result'}};await ctx.store.put(input.workspaceId,'retention-reports',{id,status:'executing',approvalId:action.id,reason:input.reason,files:input.files,results:[],startedAt:now()},{event:'retention/disposal-started',actor:`human:${user.id}`});for(const file of input.files){if(signal?.aborted){results.push({id:file.id,filename:file.filename,status:'not-attempted',error:'Execution stopped before this file.'});continue}try{const value=await ctx.files.dispose(scope(pinned),file.id,{expectedSha256:file.sha256,reason:input.reason,actor:user.id,approvalId:action.id});results.push({id:file.id,filename:file.filename,status:'disposed',bytesRemoved:value.bytesRemoved||0,sharedContentRetained:!!value.sharedContentRetained})}catch(error){results.push({id:file.id,filename:file.filename,status:'failed',error:error.message})}}const report={id,approvalId:action.id,reason:input.reason,files:input.files,results,status:results.every(row=>row.status==='disposed')?'complete':'partial',finishedAt:now()};await ctx.store.put(input.workspaceId,'retention-reports',report,{event:'retention/disposal-completed',actor:`human:${user.id}`});return{ok:true,outcome:report.status,report,action:{type:'navigate',input:{view:'retention',reportId:id},label:'Open disposal result'}}}}))
 const archive=async(user,id,input={})=>{manage(user);return{ok:true,file:await ctx.files.archive(scope(user),id,{reason:input.reason||'Archived for retention review',actor:user.id})}}
 const aggregate=user=>{if(user.role!=='admin')fail('Administrator access is required.',403);const rows=[],unavailable=[];for(const account of ctx.accounts.list()){try{rows.push({realm:account.id,...ctx.files.summary(account)})}catch(error){unavailable.push({realm:account.id,message:error.message,code:error.code})}}return{rows,unavailable,totals:rows.reduce((sum,row)=>Object.fromEntries(Object.entries(sum).map(([key,value])=>[key,value+(row[key]||0)])),{records:0,bytes:0,missing:0,corrupt:0,failures:0,disposed:0}),bodyIncluded:false}}
 for(const user of ctx.accounts.list()){try{await ctx.files.recover(user);for(const row of ctx.store.list(user.id,'retention-reports').filter(row=>row.status==='executing'))await ctx.store.put(user.id,'retention-reports',{...row,status:'interrupted',recoveredAt:now(),results:row.files.map(file=>{const current=ctx.files.stat(user,file.id);return{id:file.id,filename:file.filename,status:current.disposedAt?'disposed':'not-confirmed',storage:current.storage.state}}),message:'The process stopped during disposal. Completed records are retained; remaining copies need a fresh review.'},{event:'retention/disposal-recovered',actor:'system:retention'})}catch(error){if(error.status!==503)throw error}}
 ctx.provide('retention',{preview,configure,configureProject,hold,release,propose,archive,aggregate})
 const route=(method,path,handler,options={})=>ctx.effect(()=>ctx.web.route(method,path,handler,options))
 route('GET','/retention',({user})=>preview(user));route('GET','/retention/aggregate',({user})=>aggregate(user),{admin:true});route('POST','/retention/policy',({user,body})=>configure(user,body),{capability:'workspace:write'});route('POST','/retention/project-policy',({user,body})=>configureProject(user,body),{capability:'workspace:write'});route('POST','/retention/holds',({user,body})=>hold(user,body),{capability:'workspace:write'});route('POST','/retention/holds/:id/release',({user,params,body})=>release(user,params.id,body),{capability:'workspace:write'});route('POST','/retention/propose',({user,body})=>propose(user,body),{capability:'workspace:write'});route('POST','/retention/files/:id/archive',({user,params,body})=>archive(user,params.id,body),{capability:'workspace:write'})
 route('GET','/retention/files/:id/preview',({user,params})=>ctx.files.preview(scope(user),params.id));route('GET','/retention/files/:id/download',({user,params,query,res})=>{const owner=scope(user),file=ctx.files.get(owner,params.id,{includeDeleted:true}),inline=query.get('inline')==='true'&&['image','pdf'].includes(ctx.files.preview(owner,file.id).kind);res.setHeader('content-type',file.mime);res.setHeader('content-disposition',`${inline?'inline':'attachment'}; filename*=UTF-8''${encodeURIComponent(file.filename)}`);res.end(ctx.files.read(owner,file.id,{includeDeleted:true}))})
 ctx.effect(()=>ctx.web.contribute({id:'retention',label:'Files & retention',icon:'archive',roles:['contractor','supplier','admin'],order:48}))
}
