import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {mkdirSync,writeFileSync} from 'node:fs'
import {resolve,join} from 'node:path'
const require=createRequire(new URL('../../../../host/package.json',import.meta.url)),{chromium}=require('playwright')
const base=(process.env.BASE_URL||'http://127.0.0.1:8643/quotagent/').replace(/\/?$/,'/'),output=resolve(process.env.EVIDENCE_DIR||'tmp/product-evidence/teams/local')
mkdirSync(output,{recursive:true})
const browser=await chromium.launch({headless:true,executablePath:'/opt/hermes/.playwright/chromium_headless_shell-1243/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox']})
const stamp=Date.now(),email=`reviewer-${stamp}@local.test`,name=`Colleague ${stamp}`,report={base,at:new Date().toISOString(),checks:[],screenshots:[],errors:[],reviewer:{email,name}},pages=[]
async function page(){const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();pages.push(page);page.on('pageerror',error=>report.errors.push(error.message));await page.goto(base);return page}
async function ready(page){await page.locator('.ws-navigation').waitFor();await page.waitForTimeout(450);for(const name of ['Not now','Hide walkthrough']){const button=page.getByRole('button',{name,exact:true});if(await button.isVisible())await button.click()}}
async function nav(page,label,group='Quotation work'){const button=page.locator('.sidebar').getByRole('button',{name:label,exact:true});if(!await button.isVisible())await page.locator('.sidebar').getByRole('button',{name:group,exact:true}).click();await button.click();await page.getByRole('heading',{name:'My day & team',exact:true}).waitFor()}
async function shot(page,name){await page.screenshot({path:join(output,name),fullPage:true});report.screenshots.push(name)}
try{
 const buyer=await page();await buyer.getByRole('button',{name:'I’m a contractor'}).click();await ready(buyer)
 const reviewer=await page();await reviewer.getByRole('button',{name:'Create an account',exact:true}).click();await reviewer.getByLabel('Your name',{exact:true}).fill(name);await reviewer.getByLabel('Company',{exact:true}).fill('Independent review team');await reviewer.getByLabel('Email address',{exact:true}).fill(email);await reviewer.getByLabel('Password',{exact:true}).fill('local-review-pass');await reviewer.getByRole('button',{name:'Create workspace',exact:true}).click();await ready(reviewer);await nav(reviewer,'My day & team');await reviewer.getByRole('button',{name:'Project conversations',exact:true}).click();await reviewer.getByRole('heading',{name:'Create some work first',exact:true}).waitFor();report.checks.push('A newly registered same-side colleague starts with an isolated business workspace')
 await nav(buyer,'My day & team');await buyer.getByRole('button',{name:'Colleagues',exact:true}).click();await buyer.getByRole('button',{name:'Invite colleague',exact:true}).click();const invite=buyer.getByRole('dialog');await invite.getByLabel('Colleague email',{exact:true}).fill(email);await invite.getByLabel('Team role',{exact:true}).selectOption('lead');await invite.getByRole('button',{name:'Send invitation',exact:true}).click();await invite.waitFor({state:'hidden'});await reviewer.reload();await reviewer.getByRole('button',{name:'Accept invitation',exact:true}).click();const picker=reviewer.getByLabel('Active party workspace',{exact:true});await picker.waitFor();await picker.selectOption({label:'Northstar Construction'});await nav(reviewer,'My day & team');await reviewer.getByRole('button',{name:'Project conversations',exact:true}).click();await reviewer.getByLabel('Project record',{exact:true}).waitFor();assert.ok(await reviewer.getByLabel('Project record',{exact:true}).locator('option').count()>0);await shot(reviewer,'01-accepted-team.png');report.checks.push('Owner invitation, explicit colleague acceptance and header selection expose the shared party business records')
 await buyer.getByRole('button',{name:/^Authority/}).click();await buyer.getByRole('button',{name:'Propose authority changes',exact:true}).click();const policy=buyer.getByRole('dialog');await policy.getByLabel('Limit type for Director',{exact:true}).selectOption('amount');await policy.getByLabel('Amount in USD for Director',{exact:true}).fill('100000');await policy.getByLabel('Limit type for Team lead',{exact:true}).selectOption('amount');await policy.getByLabel('Amount in USD for Team lead',{exact:true}).fill('50000');await policy.getByLabel('New role name',{exact:true}).fill('Project coordinator '+stamp);await policy.getByRole('button',{name:'Add authority role',exact:true}).click();await policy.getByLabel('Limit type for Project coordinator '+stamp,{exact:true}).selectOption('amount');await policy.getByLabel('Amount in USD for Project coordinator '+stamp,{exact:true}).fill('2000');await policy.getByLabel('Independent reviewer',{exact:true}).selectOption({label:`${name} · Team lead`});await policy.getByLabel('Reason for change',{exact:true}).fill('Two-person decisions with explicit monetary limits');await policy.getByRole('button',{name:'Request policy review',exact:true}).click();await policy.waitFor({state:'hidden'});assert.equal(await buyer.getByRole('button',{name:'Approve policy',exact:true}).count(),0)
 await reviewer.reload();await reviewer.getByRole('button',{name:/^Authority/}).click();const proposal=reviewer.locator('.team-policy-proposal').filter({has:reviewer.getByRole('button',{name:'Approve policy',exact:true})}).first();await proposal.getByRole('button',{name:'Approve policy',exact:true}).click();await reviewer.locator('.team-policy-proposal').first().getByText('granted',{exact:true}).waitFor();await buyer.reload();await buyer.getByRole('button',{name:/^Authority/}).click();await buyer.locator('.team-policy-proposal').first().getByRole('button',{name:'Apply approved policy',exact:true}).click();await buyer.locator('.team-policy-proposal').first().getByText('applied',{exact:true}).waitFor();await buyer.getByRole('cell',{name:'Project coordinator '+stamp,exact:true}).first().waitFor();await shot(buyer,'02-reviewed-authority.png');report.checks.push('Exact authority policy and added custom role reviewed by a different colleague and applied separately; proposer has no self-approve control')
 await buyer.getByRole('button',{name:'Project conversations',exact:true}).click();const record=buyer.getByLabel('Project record',{exact:true});await record.waitFor();report.objectKey=await record.inputValue();await buyer.getByLabel('Assign to',{exact:true}).selectOption({label:`${name} · Team lead`});await buyer.getByLabel('Assignment or transfer reason',{exact:true}).fill('Check delivery scope before the decision');await buyer.getByRole('button',{name:'Assign work',exact:true}).click();await buyer.getByRole('status').filter({hasText:'Work assigned.'}).waitFor();await buyer.getByRole('button',{name:`Mention ${name}`,exact:true}).click();const comment=buyer.getByLabel('Team comment',{exact:true});await comment.fill((await comment.inputValue())+'Please check the requested delivery and @unknown@local.test.');await buyer.getByRole('button',{name:'Add comment',exact:true}).click();await buyer.getByText('No notification sent for: @unknown@local.test',{exact:true}).waitFor();await shot(buyer,'03-assignment-conversation.png');await buyer.getByRole('button',{name:'My day',exact:true}).click();await buyer.getByRole('button',{name:'Assigned by me',exact:true}).click();await buyer.getByText('Check delivery scope before the decision',{exact:true}).waitFor();await buyer.getByRole('heading',{name:'Request deadlines',exact:true}).waitFor()
 await reviewer.reload();await reviewer.getByRole('button',{name:'My day',exact:true}).click();await reviewer.getByRole('button',{name:'Mark done',exact:true}).waitFor();await reviewer.locator('.team-mention').filter({hasText:'Please check the requested delivery'}).click();await reviewer.getByRole('button',{name:'Follow updates',exact:true}).click();await reviewer.getByRole('button',{name:'Unfollow',exact:true}).waitFor();await reviewer.getByRole('button',{name:'My day',exact:true}).click();await reviewer.getByRole('button',{name:'Following',exact:true}).click();await reviewer.getByRole('heading',{name:'Following',exact:true}).waitFor();await reviewer.getByRole('button',{name:'Open work',exact:true}).waitFor();await reviewer.getByRole('button',{name:'My work',exact:true}).click();await shot(reviewer,'04-personal-day.png');await reviewer.getByRole('button',{name:'Mark done',exact:true}).click();await reviewer.getByRole('heading',{name:'Nothing assigned to you',exact:true}).waitFor();report.checks.push('Assignment, assigned-by-me/following filters, mention, unknown-name disclosure, request deadlines and completion produce actionable daily work')
 await reviewer.reload();assert.equal(await reviewer.getByLabel('Active party workspace',{exact:true}).inputValue(),'contractor-demo');await reviewer.getByRole('button',{name:'Project conversations',exact:true}).click();assert.equal(await reviewer.getByRole('button',{name:'Unfollow',exact:true}).count(),1);await reviewer.setViewportSize({width:390,height:900});await shot(reviewer,'05-mobile-team.png');assert.equal(await reviewer.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);report.checks.push('Selected workspace, following and comments survive browser reload; mobile team conversation has no page overflow')
 assert.equal(report.errors.length,0);report.ok=true;report.completedAt=new Date().toISOString();console.log(JSON.stringify(report,null,2))
}catch(error){report.error=error.stack;console.error(JSON.stringify(report,null,2));for(let index=0;index<pages.length;index++)await pages[index].screenshot({path:join(output,`failure-${index}.png`),fullPage:true}).catch(()=>{});process.exitCode=1}
finally{writeFileSync(join(output,'report.json'),JSON.stringify(report,null,2)+'\n');await browser.close()}
